### ISSUE TITLE
Postgres 9.4.4: ECONNREFUSED when running knex migrations

### ISSUE THREAD

**Issue by demisx** [tgriesser/knex#1002]
```bash
$ sql -V
psql (PostgreSQL) 9.4.4
$ knex -V
Knex CLI version:  0.8.6
Local Knex version:  0.8.6
```

I cannot run `knex` on one of our servers, though I have no problem connecting to the database via `psql`.

This works:
```bash
$ su - app
$ psql -d data-api-stg
psql (9.4.4)
Type "help" for help.

data-api-stg=>
```

But runing `knex` migrations throws ECONNREFUSED error:
```bash
$ DEBUG=pool2 knex --env staging --knexfile config/db/knexfile.js migrate:latest
Working directory changed to ~/data-api/config/db
Using environment: staging
  pool2 New ResourceRequest (id=0, timeout=Infinity) +0ms
  pool2 Attempting to acquire minimum resources (cur=0, min=2) +9ms
  pool2 Attempting to acquire resource (cur=0, ac=0) +1ms
  pool2 Attempting to acquire resource (cur=0, ac=1) +8ms
  pool2 Not growing pool: pending=1, to be available=2 +2ms
  pool2 Couldn't allocate new resource: connect ECONNREFUSED +6ms
  pool2 Destroying pool: unable to aquire a resource within 0s +0ms
  pool2 ResourceRequest: reject (id=0) +1ms
  pool2 ResourceRequest: fulfilling with error: Pool was destroyed (id=0) +1ms
Knex:warning - Pool2 - Error: Pool was destroyed
  pool2 ResourceRequest: clearing timeout (id=0) +1ms
Knex:Error Pool2 - Error: connect ECONNREFUSED
  pool2 Couldn't allocate new resource: connect ECONNREFUSED +1ms
  pool2 Destroying pool: unable to aquire a resource within 0s +0ms
Knex:Error Pool2 - Error: connect ECONNREFUSED
Error: Pool was destroyed
    at Pool._destroyPool (/home/app/data-api/node_modules/knex/node_modules/pool2/lib/pool.js:536:20)
    at Pool.<anonymous> (/home/app/data-api/node_modules/knex/node_modules/pool2/lib/pool.js:458:18)
    at Pool.<anonymous> (/home/app/data-api/node_modules/knex/node_modules/pool2/lib/pool.js:493:17)
    at tryCatcher (/home/app/data-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.errorAdapter (/home/app/data-api/node_modules/bluebird/js/main/nodeify.js:36:34)
    at Promise._settlePromiseAt (/home/app/data-api/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/home/app/data-api/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/app/data-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/app/data-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/app/data-api/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

```js
// in knexfile.js
staging: {
    client: 'postgresql',
    connection: {
      database: 'data-api-stg',
      user:     'app',
      password: ''
    },
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'knex_migrations'
    }
  }
```

Using peer authentication. Can you please give me some clues what may be wrong here? Thank you.

**Comment by demisx** [comment]
Turns out that Postgres on Ubuntu 14.04 runs on port 5433 instead of 5432. So, changing config fixed it (see below). Also, had to create a dummy password `password`for the the database user, otherwise it would fail authentication.

```bash
// in knexfile.js
staging: {
    client: 'pg',
    connection: {
      database: 'data-api-stg',
      port: 5433,
      user:     '',
      password: 'password'
    },
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'knex_migrations'
    }
  }
```
