### ISSUE TITLE
Breaks with latest version of bluebird

### ISSUE THREAD

**Issue by brycehamrick** [tgriesser/knex#1035]
When using bluebird 3.0.1:

```
module.js:338
throw err;
      ^
Error: Cannot find module 'bluebird/js/main/promise'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/brycehamrick/src/appname/node_modules/knex/lib/promise.js:3:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Resolved by downgrading to bluebird@2.9.24.

**Comment by chrisbroome** [comment]
I had this issue as well and went nuclear by deleting my `node_modules` folder and doing a fresh `npm install`. You may be able to work around it by doing an `npm upgrade`, though.

**Comment by jamesdixon** [comment]
I can confirm that @chrisbroome's solution works!

**Comment by chrisbroome** [comment]
Awesome! Glad it worked. :smile:

**Comment by rhys-vdw** [comment]
Interesting. I wonder why `Promise` can't be included directly [here](https://github.com/tgriesser/knex/blob/521a6f9e97f6df553febeeed1f3e65a4761074f3/src/promise.js#L2) by `require('bluebird')`...

**Comment by chrisbroome** [comment]
The latest version of bluebird, 3.0.2, has `promise.js` located at `bluebird/js/release/promise.js`.

Version 2.10.2 has `promise.js` located at `bluebird/js/main/promise.js`.

I'm thinking somehow npm is getting confused an trying to load `node_modules/bluebird` instead of `node_modules/knex/node_modules/bluebird`.

**Comment by wubzz** [comment]
Closing old stale issue. If still an issue in latest knex, please reopen. _(Cannot reproduce)_
