### ISSUE TITLE
Error: Connection lost: The server closed the connection.

### ISSUE THREAD

**Issue by danielgindi** [tgriesser/knex#1072]
I thought that the pool is supposed to handle closed connections?.. But an app crashes periodically because of this.

And of course it is not reasonable to query for all of the open connections in the pool, and periodically send a keep alive...

```

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/yehuda/app/node_modules/mysql/lib/protocol/Protocol.js:103:13)
    at Socket.<anonymous> (/home/yehuda/app/node_modules/mysql/lib/Connection.js:102:28)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
    --------------------
    at Protocol._enqueue (/home/yehuda/app/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Connection.query (/home/yehuda/app/node_modules/mysql/lib/Connection.js:201:25)
    at /home/yehuda/app/node_modules/knex/lib/dialects/mysql/index.js:80:18
    at tryCatcher (/home/yehuda/app/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/home/yehuda/app/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/home/yehuda/app/node_modules/bluebird/js/main/promise.js:70:37)
    at Client._stream (/home/yehuda/app/node_modules/knex/lib/dialects/mysql/index.js:77:12)
    at Client.stream (/home/yehuda/app/node_modules/knex/lib/client.js:137:25)
    at /home/yehuda/app/node_modules/knex/lib/runner.js:94:28
    at tryCatcher (/home/yehuda/app/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/yehuda/app/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/yehuda/app/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/home/yehuda/app/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/yehuda/app/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/yehuda/app/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:448:13)

```

**Comment by danielgindi** [comment]
@tgriesser any ideas?

**Comment by viniciusbo** [comment]
I'm also experiencing this issue. Can't find a way to get over it.

**Comment by atiertant** [comment]
if you have a look at [function connectionErrorHandler](https://github.com/tgriesser/knex/blob/master/src/dialects/mysql/index.js#L127) called on connection error or end, the connection is removed from pool but the promise returned by _query is never resolved or rejected...

**Comment by tmeinders** [comment]
Has anyone determined workarounds for this issue? Should the recovery be done outside of knex?

**Comment by wubzz** [comment]
I believe this is similar to #1198 which is still not completely resolved, but some investigation is in there for those interested.

You can try supplying a `ping` function on your pool config, which will check whether or not to dispose of the current connection and acquire a new one. See [Pool2](https://github.com/myndzi/pool2) for syntax.

Obviously this should be handled by knex internally, but since we're yet to find a complete solution *(primarily transactions are the issue atm)*, this is all I can provide for now.

**Comment by mercmobily** [comment]
This is a duplicate of #3447 - MySQL connections being closed by the server after idle timeout and Knex not validating them before use.

The fix is to configure your pool settings:

```js
pool: {
  min: 0,
  max: 10,
  idleTimeoutMillis: 300000 // 5 minutes
}
```

Setting `min: 0` is essential so idle connections get discarded before MySQL closes them.

This is being tracked in the connection pooling meta issue #6241.

Closing as duplicate of #3447.

**Comment by mercmobily** [comment]
Closing as duplicate of #3447
