### ISSUE TITLE
Reading then updating throws an Error

### ISSUE THREAD

**Issue by flawyte** [tgriesser/knex#1102]
I'm trying to chain read and update operations. First I read (fetch) data from the database based on its **id**, then I change it and want to update the data in the database as well but I get a `Unhandled rejection Error: There is no pool defined on the current client` error.

**index.js**

    var id = args.id;
    var proj = new Project(id);
    
    proj.read(knex).then(function(rows) {
      proj.set(args);
      proj.update(knex).then(console.log); // <== ERROR THROWN HERE
    });

**Project.js** (only related functions)

    read(knex) {
      var self = this;
    
      return knex('projects').where('id', this.id).then(function(rows) {
        if (rows.length == 0)
          throw '[panda] Read project: no project with id = ' + self.id;
        self.set(rows[0]);
    
        return self;
      });
    }
    
    update(knex) {
      console.log(knex('projects').where('id', this.id).update(this).toString());
    
      return knex('projects').where('id', this.id).update(this);
    }

**Command**

    $ node index.js projects update --id=5 --name=Test-update
    update "projects" set "completion" = 0, "currentIteration" = NULL, "id" = 5, "name" = 'Test-update' where "id" = 5
    Unhandled rejection Error: There is no pool defined on the current client
        at /home/flawyte/development/projects/js/panda/node_modules/knex/lib/client.js:202:25
        at tryCatcher (/home/flawyte/development/projects/js/panda/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._resolveFromResolver (/home/flawyte/development/projects/js/panda/node_modules/bluebird/js/main/promise.js:480:31)
        at new Promise (/home/flawyte/development/projects/js/panda/node_modules/bluebird/js/main/promise.js:70:37)
        at Client.acquireConnection (/home/flawyte/development/projects/js/panda/node_modules/knex/lib/client.js:200:12)
        at /home/flawyte/development/projects/js/panda/node_modules/knex/lib/runner.js:136:49
        at tryCatcher (/home/flawyte/development/projects/js/panda/node_modules/bluebird/js/main/util.js:26:23)
        at Function.Promise.attempt.Promise.try (/home/flawyte/development/projects/js/panda/node_modules/bluebird/js/main/method.js:31:24)
        at Runner.ensureConnection (/home/flawyte/development/projects/js/panda/node_modules/knex/lib/runner.js:135:26)
        at Runner.run (/home/flawyte/development/projects/js/panda/node_modules/knex/lib/runner.js:30:31)
        at QueryBuilder.Target.then (/home/flawyte/development/projects/js/panda/node_modules/knex/lib/interface.js:27:43)
        at /home/flawyte/development/projects/js/panda/index.js:80:31
        at tryCatcher (/home/flawyte/development/projects/js/panda/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/home/flawyte/development/projects/js/panda/node_modules/bluebird/js/main/promise.js:507:31)
        at Promise._settlePromiseAt (/home/flawyte/development/projects/js/panda/node_modules/bluebird/js/main/promise.js:581:18)
        at Promise._settlePromises (/home/flawyte/development/projects/js/panda/node_modules/bluebird/js/main/promise.js:697:14)

If I remove the `then(console.log)` in **index.js** no error is thrown but data in database remains unchanged after script ending. Why ?

**Comment by bruun** [comment]
Disclaimer: I'm not that familiar with the Knex codebase.

I see the following code in Knex's `client.js`:

```
  acquireConnection: function() {
    var client = this
    return new Promise(function(resolver, rejecter) {
      if (!client.pool) {
        return rejecter(new Error('There is no pool defined on the current client'))
      }
    })
  },
```
You can tap into that function and see what `this` is set to.
If `this` is not a `Client` object, then it's been bound incorrectly somwhere. 
If `this is a `Client` object, it looks like `Client`'s `destroy` has been called, setting the pool to undefined. Why that happens I don't know, but it's a place to start looking :-)

**Comment by blah238** [comment]
> If I remove the then(console.log) in index.js no error is thrown but data in database remains unchanged after script ending. Why ?

Because the query is only issued to the database upon `.then()` (or one of [Bluebird](http://bluebirdjs.com/docs/api-reference.html)'s other promise runners) being called. No `.then()`, no database interaction.

Also to avoid the **unhandled** rejection part, you should always `return` your promises and [`catch`](http://bluebirdjs.com/docs/api/catch.html) (or provide a rejection handler function to the second argument of `.then()`) them at some point. If an error occurs within the promise chain and no handler is provided it results in an unhandled rejection.

I am not sure why you're getting the error you're getting. Can you produce an [SSCCE](http://sscce.org/) that reproduces it? Also what DB, OS, versions, etc. are you using?

**Comment by flawyte** [comment]
Problem solved !

I had a line `knex.destroy();` at the very end of my script and as knex is asynchronous, the line was being executed **after** the read instruction (due to quick execution) but **before** update, causing the error above. I noticed the error while writing the SSCCE :)

Thanks for your help.
