### ISSUE TITLE
Error: Pool is destroyed

### ISSUE THREAD

**Issue by jurgen7777** [tgriesser/knex#1146]
Hello all,
Using knex + express + newrelic on Heroku environment, got such error recently:
```
 error: [Error: Pool is destroyed] 'Error: Pool is destroyed
  at Pool.acquire (/app/node_modules/knex/node_modules/pool2/lib/pool.js:163:12)
  at /app/node_modules/knex/lib/client.js:204:19
  at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._resolveFromResolver (/app/node_modules/bluebird/js/main/promise.js:480:31)
  at new Promise (/app/node_modules/bluebird/js/main/promise.js:70:37)
  at Client.acquireConnection (/app/node_modules/knex/lib/client.js:200:12)
  at /app/node_modules/knex/lib/runner.js:138:49
  at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)
  at Function.Promise.attempt.Promise.try (/app/node_modules/bluebird/js/main/method.js:31:24)
  at Runner.ensureConnection (/app/node_modules/knex/lib/runner.js:137:26)
  at Runner.run (/app/node_modules/knex/lib/runner.js:30:31)
  at QueryBuilder.Target.then (/app/node_modules/knex/lib/interface.js:27:43)
  at Object.module.exports.mobile_version (/app/lib/middleware/check_version.js:17:14)
  at Object.eval [as handle] (<anonymous>:10:19)
  at next (/app/node_modules/connect/lib/proto.js:174:15)
  at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
  at Object.app.get.res.json.ZIK_SERVER_URL (/app/apiserver.js:86:12)
  at Object.eval [as handle] (<anonymous>:10:19)
  at next (/app/node_modules/connect/lib/proto.js:174:15)
  at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
  at Object.serveStatic (/app/node_modules/connect/node_modules/serve-static/index.js:74:16)
  at Object.serveStatic [as handle] (<anonymous>:10:19)
  at next (/app/node_modules/connect/lib/proto.js:174:15)
  at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
  at Object.expressInit (/app/node_modules/express/lib/middleware.js:30:5)
  at Object.expressInit [as handle] (<anonymous>:10:19)
  at next (/app/node_modules/connect/lib/proto.js:174:15)
  at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
  at Object.query (/app/node_modules/connect/lib/middleware/query.js:43:5)
  at Object.query [as handle] (<anonymous>:10:19)
  at next (/app/node_modules/connect/lib/proto.js:174:15)
  at Function.app.handle (/app/node_modules/connect/lib/proto.js:182:3)
  at Server.app (/app/node_modules/connect/lib/connect.js:67:37)
  at Server.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
  at Server.wrappedHandler (/app/node_modules/newrelic/lib/instrumentation/core/http.js:124:51)
  at Server.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
  at Server.wrapTransactionInvocation (/app/node_modules/newrelic/lib/transaction/tracer/index.js:79:65)
  at Server.emit (events.js:98:17)
  at HTTPParser.parser.onIncoming (http.js:2111:12)
  at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
  at Socket.socket.ondata (http.js:1969:22)
  at TCP.onread (net.js:528:27)
'
```

What could be the source of the problem? Could be a Newrelic plugin?
Thanks.

**Comment by elhigu** [comment]
@jurgen7777 some test code how to reproduce problem would be really valuable

**Comment by asafyish** [comment]
This happens to us when the connection to the database is spotty. When it happens, other tools also have trouble connecting.

**Comment by jurgen7777** [comment]
Yes, sorry for the delay, the problem was that the Heroku Postgres server had refused a connection temporary. After that there became  pool destroyed error.
Thanks.

**Comment by davidfurlong** [comment]
This fixed this bug for me:
http://stackoverflow.com/questions/13573204/psql-could-not-connect-to-server-no-such-file-or-directory-mac-os-x
