### ISSUE TITLE
MSSQL transactions failing rollback

### ISSUE THREAD

**Issue by AiNoKame** [tgriesser/knex#1192]
I'm using MSSQL as the dialect and testing the rollback functionality of a transaction by forcing a transaction to fail. When trx.rollback() is invoked, I'm consistently seeing:

`Unhandled rejection TypeError: Cannot read property 'rollback' of null
    at Transaction_MSSQL.rollback (/Users/rod/Documents/GitHub/ripple-connect2/node_modules/knex/lib/dialects/mssql/transaction.js:49:20)
    at Function.transactor.rollback (/Users/rod/Documents/GitHub/ripple-connect2/node_modules/knex/lib/transaction.js:192:18)
    at /Users/rod/Documents/GitHub/ripple-connect2/node_modules/knex/lib/transaction.js:47:22
    at tryCatcher (/Users/rod/Documents/GitHub/ripple-connect2/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/rod/Documents/GitHub/ripple-connect2/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/rod/Documents/GitHub/ripple-connect2/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/rod/Documents/GitHub/ripple-connect2/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/rod/Documents/GitHub/ripple-connect2/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/rod/Documents/GitHub/ripple-connect2/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/rod/Documents/GitHub/ripple-connect2/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

Has rollback functionality been tested with MSSQL?

**Comment by rhys-vdw** [comment]
There is a [test](https://github.com/tgriesser/knex/blob/4244bb1ec266783e4a9d5f1acabfbd24d0c2b491/test/integration/builder/transaction.js#L53-L83). MSSQL is pretty new so there may be problems.

**Comment by AiNoKame** [comment]
Interesting, trying to just remove `trx.commit` and `trx.rollback` at the end of my Promise chain within `knex.transaction` makes the benign error message go away, since `commit()` and `rollback()` in `/node_modules/knex/lib/dialects/mssql/transaction.js` are automatically invoked in a transaction :smile_cat:
