### ISSUE TITLE
Latest release 0.10.0 contains broken build

### ISSUE THREAD

**Issue by tuhoojabotti** [tgriesser/knex#1211]
I tried to update from 0.9.0 to 0.10.0 and migrations fail with the following error:

```
Knex:warning - migrations failed with error: Cannot read property 'format' of undefined
TypeError: Cannot read property 'format' of undefined
    at Raw.Target._formatQuery (/home/tuhis/projektit/booster/node_modules/knex/lib/interface.js:21:33)
    at Raw.<anonymous> (/home/tuhis/projektit/booster/node_modules/knex/lib/interface.js:12:19)
    at /home/tuhis/projektit/booster/node_modules/knex/node_modules/lodash/index.js:2874:23
    at arrayMap (/home/tuhis/projektit/booster/node_modules/knex/node_modules/lodash/index.js:1406:25)
    at Function.map (/home/tuhis/projektit/booster/node_modules/knex/node_modules/lodash/index.js:6710:14)
    at Raw.Target.toQuery (/home/tuhis/projektit/booster/node_modules/knex/lib/interface.js:11:14)
    at ColumnCompiler.defaultTo (/home/tuhis/projektit/booster/node_modules/knex/lib/schema/columncompiler.js:122:19)
    at ColumnCompiler.getModifiers (/home/tuhis/projektit/booster/node_modules/knex/lib/schema/columncompiler.js:66:34)
    at ColumnCompiler.compileColumn (/home/tuhis/projektit/booster/node_modules/knex/lib/schema/columncompiler.js:41:88)
    at ColumnCompiler.toSQL (/home/tuhis/projektit/booster/node_modules/knex/lib/schema/columncompiler.js:32:23)
    at TableCompiler.getColumns (/home/tuhis/projektit/booster/node_modules/knex/lib/schema/tablecompiler.js:127:79)
    at TableCompiler.create (/home/tuhis/projektit/booster/node_modules/knex/lib/schema/tablecompiler.js:42:22)
    at TableCompiler.toSQL (/home/tuhis/projektit/booster/node_modules/knex/lib/schema/tablecompiler.js:28:20)
    at TableBuilder.toSQL (/home/tuhis/projektit/booster/node_modules/knex/lib/schema/tablebuilder.js:37:42)
    at SchemaCompiler.createTable (/home/tuhis/projektit/booster/node_modules/knex/lib/schema/compiler.js:59:19)
    at SchemaCompiler.toSQL (/home/tuhis/projektit/booster/node_modules/knex/lib/schema/compiler.js:46:26)
```

So it seems that the change to use client.SqlString is not working because the dialects don't have it for some reason.

https://github.com/tgriesser/knex/commit/4b2c0efff1da258e48f4bd6c399e06152909e2a2#diff-c550bd19c632c81d7c28cc22ec416510L37

**Comment by tuhoojabotti** [comment]
Problem was a migration requiring knex without config to use `knex.raw('now()')` in `defaultTo`.
