### ISSUE TITLE
Mismatched migration timecode.

### ISSUE THREAD

**Issue by MrJadaml** [tgriesser/knex#1215]
I generated a new (first and only so far) migration for my app:
```
$ knex migrate:make create_albums
=> Using environment: development
=> Created Migration: ../migrations/20160221100019_create_albums.js
```

built up the migration and then ran it:

```
$ knex migrate:latest
=> Using environment: development
=> Error: The migration directory is corrupt, the following files are missing: 20151221141800_create_albums.js
    at validateMigrationList (../node_modules/knex/lib/migrate/index.js:429:11)
    at Object.tapHandler (../node_modules/bluebird/js/main/finally.js:64:23)
    at Object.tryCatcher (../node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (../node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (../node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (../node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (../node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (../node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (../node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:384:17)
```

it looks like the timecode that was generated is not the same as what knex thinks it should be looking for in the migration directory?

If I drop into the postgres shell and pull up the knex migrations I get the following:

```
album_demo=# select * from knex_migrations;
 id |              name               | batch |       migration_time
----+---------------------------------+-------+----------------------------
  1 | 20151221141800_create_albums.js |     1 | 2015-12-21 14:23:19.111-08
(1 row)
```

note the date is off.
Thinking it might be a postgres issue I run the following:

```
jadam=# select current_timestamp;
              now
-------------------------------
 2016-02-21 12:11:59.462537-08
(1 row)
```

so timestamps from postgres look like they are working fine. I suppose I can rename the file to match the old date, but that feels icky to me.

**Comment by elhigu** [comment]
Could you send us commands which I can use to reproduce the problem. I'm pretty sure that there has been an user error. 

One possible scenario how this could have happened would be following:

You are using the same DB that you used in last december. Around 21st of December 2015 you were trying out knex and created migration with name "create_albums" and did run it to your DB.

Now 21st of February 2016 you are testing out again and created new project and other migration file with name "create_albums", but you are still using the same DB from December, which already has migrations ran from December.

So because filename in your migration directory and information about ran migration files in migrations DB table doesn't match there will be an error (migration which has already been ran is not found).

**Comment by MrJadaml** [comment]
@elhigu You were right. Looking back through my .zsh_history I had created a db with the same name back in December. Good call.
