### ISSUE TITLE
Can't use knex.schema.table to alter an existing table?

### ISSUE THREAD

**Issue by anyong** [tgriesser/knex#1221]
Getting this error when I try to run a migration file. Below is my latest migration file contents, the others are all using `knex.schema.createTable` which works just fine.

```js
exports.up = function(knex, Promise) {
    return knex.schema.table('orders').then(function(t) {
        t.string('test_col');
    });
};

exports.down = function(knex, Promise) {
    return knex.schema.table('orders').then(function (t) {
        t.dropColumns('test_col');
    });
};

/*
$ ../node_modules/.bin/knex migrate:latest
Knex:warning - migrations failed with error: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at TableBuilder.toSQL (C:\project\node_modules\knex\lib\schema\tablebuilder.js:36:11)
    at SchemaCompiler.alterTable (C:\project\node_modules\knex\lib\schema\compiler.js:59:19)
    at SchemaCompiler.toSQL (C:\project\node_modules\knex\lib\schema\compiler.js:46:26)
    at SchemaBuilder.toSQL (C:\project\node_modules\knex\lib\schema\builder.js:43:43)
    at C:\project\node_modules\knex\lib\runner.js:34:32
    at C:\project\node_modules\bluebird\js\main\using.js:176:30
    at tryCatcher (C:\project\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\project\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\project\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\project\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\project\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\project\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\project\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

$ ../node_modules/.bin/knex version
Knex CLI version:  0.10.0
Local Knex version:  0.10.0
*/
```

**Comment by wubzz** [comment]
@anyong I believe this is the correct syntax
```javascript
   return knex.schema.table('orders', function(t) {
        t.string('test_col');
    }).then(...);
```

From what I can tell from the stack, knex is trying to call the table function which is undefined, since you run `.then()` it's trying to run the querybuilder instance as an SQL to the database.
https://github.com/tgriesser/knex/blob/master/src/schema/tablebuilder.js#L15
https://github.com/tgriesser/knex/blob/master/src/schema/tablebuilder.js#L34

**Comment by anyong** [comment]
Just realized that. Sorry / thanks!
