### ISSUE TITLE
Not able to run migrations!

### ISSUE THREAD

**Issue by pavanvamsi3** [tgriesser/knex#1229]
My migration file. 

```
exports.up = function(knex, Promise) {
  return knex.schema.createTable('users', function (table) {
    table.increments();
    table.string('username');
    table.timestamps();
  });
};

exports.down = function(knex, Promise) {

};
```

Whenever I run this, I get this error. Using Node 4.3.

> Using environment: development
> TypeError: expecting an array, a promise or a thenable

```
See http://goo.gl/s8MMhc

at PromiseArray.init [as _init] (/home/vagrant/www/ray-watch/node_modules/bluebird/js/main/promise_array.js:42:27)
at Promise._settlePromiseAt (/home/vagrant/www/ray-watch/node_modules/bluebird/js/main/promise.js:579:21)
at Promise._settlePromises (/home/vagrant/www/ray-watch/node_modules/bluebird/js/main/promise.js:697:14)
at Async._drainQueue (/home/vagrant/www/ray-watch/node_modules/bluebird/js/main/async.js:123:16)
at Async._drainQueues (/home/vagrant/www/ray-watch/node_modules/bluebird/js/main/async.js:133:10)
at Immediate.Async.drainQueues [as _onImmediate] (/home/vagrant/www/ray-watch/node_modules/bluebird/js/main/async.js:15:14)
at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by pavanvamsi3** [comment]
Note: This issue happens in version 0.10. I went crazy. :-1:

**Comment by sombriks** [comment]
you need to return something on migrate down. my projects do need them, try to return the knex.schema.dropTable("users")

**Comment by pavanvamsi3** [comment]
I had that in down function. That doesn't seem to solve the problem.
I downgraded to 0.9.0 and it worked like a charm.

**Comment by elhigu** [comment]
@pavanvamsi3 what command are you running when you get the error?

**Comment by kibertoad** [comment]
@elhigu I suggest closing this due to age.
