### ISSUE TITLE
Cannot read property 'client' of undefined in `config.client`

### ISSUE THREAD

**Issue by kuanb** [tgriesser/knex#1302]
Having trouble debugging this. `config` is undefined (see below error log). Unclear where to go from here. I am on a AWS vm. Works fine with same versions of all tools on Mac locally.

I've gotten roped into what I assume are red herrings, incl. removing node_modules, reinstalling, using different versions of `npm`, etc. 

```
$ npm start

> ch-courtsms@ start /home/ubuntu/ch-courtsms
> nodemon server/app.js --ignore node_modules/

[nodemon] 1.9.1
[nodemon] starting `node server/app.js`

/home/ubuntu/ch-courtsms/node_modules/knex/lib/index.js:17
  if (arguments.length === 0 || !config.client && !config.dialect) {
                                       ^

TypeError: Cannot read property 'client' of undefined
    at Knex (/home/ubuntu/ch-courtsms/node_modules/knex/lib/index.js:17:40)
    at Object.<anonymous> (/home/ubuntu/ch-courtsms/server/db.js:4:27)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/ubuntu/ch-courtsms/server/app.js:8:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by kuanb** [comment]
Issue was not related to `knex`

**Comment by niksubramanian** [comment]
hi @kuanb - I'm facing the same issue with an amazon vm - could you let me know how you debugged this issue?

Thanks in advance!

**Comment by niksubramanian** [comment]
**For posterity:**

Actually found the issue - this issue rises up when knex doesn't find an environment in which it needs to run. Usually, you require knex this way:
```
const knex = require('knex')('production')
```
The error @kuanb and I ran into is due to requiring knex without an environment.

My case: I was using a node environment variable instead of a string to define 'production'. To run my instance on EC2, I was using forever.js, which doesn't run node with environment variables. As such, made knex generate this error! Hope this solves your issues!

**Comment by tahapirzada65** [comment]
Hey Guys,

I'm having some trouble fixing a similar issue with `mocha` : 
C:\Jenkins\workspace\management-console-backend>mocha tests\unit --reporter mocha-junit-reporter
c:\users\sys_aimsengr\AppData\Roaming\npm\node_modules\knex\lib\index.js:17
  if (arguments.length === 0 || !config.client && !config.dialect) {
                                       ^

TypeError: Cannot read property 'client' of undefined
    at Knex (c:\users\sys_aimsengr\AppData\Roaming\npm\node_modules\knex\lib\ind
ex.js:17:40)
    at Object.<anonymous> (C:\Jenkins\workspace\management-console-backend\tests
\unit\database-migration.js:51:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\Users\sys_aimsengr\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js
:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\sys_aimsengr\AppData\Roaming\npm\node_modules\m
ocha\lib\mocha.js:217:14)
    at Mocha.run (C:\Users\sys_aimsengr\AppData\Roaming\npm\node_modules\mocha\l
ib\mocha.js:469:10)
    at Object.<anonymous> (C:\Users\sys_aimsengr\AppData\Roaming\npm\node_module
s\mocha\bin\_mocha:404:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

Mv knex has been required in this fashion : 
 var knex = require('knex')({
  client: 'mysql',
  debug: false,
  connection: process.env.MYSQL_URI || appEnv.getServiceCreds(process.env.MYSQL_SERVICE_NAME || config.mySqlServiceName).uri || config.db || ''
}); 

Please let me know your if you guys have a solution for this.
Thanks

**Comment by jurko-gospodnetic** [comment]
Sorry, but I really don't understand the question here.

1. the stack trace tells you that the `config` variable used in line 17 of `c:\users\sys_aimsengr\AppData\Roaming\npm\node_modules\knex\lib\index.js` is undefined
1. taking a look at that file shows you that the config variable is a parameter to the `Knex` function (constructor for the main knex object I assume), so this function is getting called with no or an `undefined` parameter
1. taking another look at the stack trace again, this function is being called from `C:\Jenkins\workspace\management-console-backend\tests\unit\database-migration.js`, line 51

Now that code is yours and you should take a look in there to see what it is you are passing in when constructing the knex object in question.

If I had to guess, my gut feeling is that you are messing up code that runs at application startup with code that runs just before each test and ending up calling the knex function at startup and passing it in a variable that only gets set before each test.
