### ISSUE TITLE
knex cli fails with node 6.0.0

### ISSUE THREAD

**Issue by bonesoul** [tgriesser/knex#1369]
```
λ knex init
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.basename (path.js:801:5)
    at Liftoff.buildEnvironment (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\knex\node_modules\liftoff\index.js:113:52)
    at Liftoff.<anonymous> (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\knex\node_modules\liftoff\index.js:181:32)
    at module.exports (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\knex\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\knex\node_modules\liftoff\index.js:174:9)
    at C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\knex\node_modules\liftoff\index.js:148:9
    at C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\knex\node_modules\v8flags\index.js:108:14
    at C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\knex\node_modules\v8flags\index.js:36:12
    at C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\knex\node_modules\v8flags\index.js:47:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)
    at node.js:444:3

```

**Comment by LinusU** [comment]
@raistlinthewiz Which version of liftoff is installed in `C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\knex\node_modules\liftoff`?

**Comment by jrowny** [comment]
also seeing this

**Comment by jrowny** [comment]
downgrading to 4.4.3 solved the problem for me.

**Comment by majimboo** [comment]
having the exact same problem on Ubuntu 16.04... I don't wish to downgrade anything.

**Comment by rhys-vdw** [comment]
So what's the solution here? Should we update Liftoff?

It looks like we need some test coverage for CLI - a number of issues have cropped up recently.

**Comment by terribleplan** [comment]
@rhys-vdw: Under 6.1.0 I only get this error when trying to use knex locally vs. globally (I don't much like installing things with -g, it makes thing messy when working on things that require outdated versions). I manually installed liftoff 2.2.1 for knex and that worked, so it seems that updating liftoff is the solution.

**Comment by kibertoad** [comment]
Knex seems to support Node 6 just fine these days, so I'm resolving this issue.
