### ISSUE TITLE
ReferenceError: d is not defined

### ISSUE THREAD

**Issue by nixgadget** [tgriesser/knex#1385]
When calling ``knex migrate`` I seem to be running into this issue. Im using ``sqlite`` for now.

Using, node v4.4.3

Running command ``node_modules/.bin/knex migrate:make test``

```
Using environment: development
Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
ReferenceError: d is not defined
    at eval (lodash.templateSources[0]:10:6)
    at Migrator._writeNewMigration (/Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/lib/migrate/index.js:326:89)
    at /Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/lib/migrate/index.js:124:23
    at tryCatcher (/Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/node_modules/bluebird/js/release/promise.js:628:18)
    at /Volumes/STORAGE/Projects/Node_Packages/my_project/node_modules/knex/node_modules/bluebird/js/release/nodeback.js:42:21
```

Any idea what is causing this ?

**Comment by rhys-vdw** [comment]
The error is coming from [here](https://github.com/tgriesser/knex/blob/master/src/migrate/index.js#L260-L262).

Apparently Lodash 4 no longer accepts a `null` second argument.

**Comment by nixgadget** [comment]
I realised it after posting this. Thanks.

**Comment by rhys-vdw** [comment]
@nixgadget I've just released 0.11.1 that includes a fix.

**Comment by nixgadget** [comment]
@rhys-vdw Does this bug also affect seeding ? If so im happy to create a PR for it.

**Comment by rhys-vdw** [comment]
Not sure. Could you check?

**Comment by nixgadget** [comment]
Raised PR #1389
