### ISSUE TITLE
Not able to rename a table

### ISSUE THREAD

**Issue by rvarbanov** [tgriesser/knex#1403]
My migration scripts are breaking when trying to rename a table

```js
'use strict';

exports.up = (knex, Promise) => {
	return knex.schema.withSchema('core').renameTable('organization_id_type', 'organization_code_type');
};

exports.down = (knex, Promise) => {
	return knex.schema.withSchema('core').renameTable('organization_code_type', 'organization_id_type');
};
```

and here is the warning that I get

```bash
Knex:warning - migrations failed with error: alter table "core"."organization_id_type" rename to "core"."organization_code_type" - syntax error at or near "."
Unhandled rejection error: alter table "core"."organization_id_type" rename to "core"."organization_code_type" - syntax error at or near "."
    at Connection.parseE (/opt/app/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/opt/app/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/opt/app/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
```

**Comment by rhys-vdw** [comment]
Got the solution from [StackOverflow](http://stackoverflow.com/a/27787841/317135).

The "schema" part should not be specified in the `TO` name.
