### ISSUE TITLE
TypeError: (0 , _lodash.mapKeys) is not a function

### ISSUE THREAD

**Issue by olalonde** [tgriesser/knex#1404]
I'm getting this when calling `somemodel.toJSON()`:

```
TypeError: (0 , _lodash.mapKeys) is not a function
    at HashItem.ModelBase.serialize (/path.../node_modules/bookshelf/lib/base/model.js:290:47)
    at HashItem.ModelBase.toJSON (/path.../node_modules/bookshelf/lib/base/model.js:312:15)
    at HashItem.hashItem.save.then (hash-items.js:20:28)
    at HashItem.tryCatcher (path.../node_modules/bookshelf/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/path.../node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:507:31)
```

I noticed the version of lodash npm installed is `lodash@3.7.0` whereas lodash docs state that `mapKeys` was introduced in `lodash@3.8.0`.

Perhaps change 

https://github.com/tgriesser/bookshelf/blob/master/package.json#L36

to `"lodash": "^3.8.0"` ?

**Comment by wubzz** [comment]
@olalonde Correct me if I'm wrong but are you not in the wrong repo for this?

**Comment by olalonde** [comment]
Oops yeah, was meant for bookshelf.

**Comment by olalonde** [comment]
Moved to https://github.com/tgriesser/bookshelf/issues/1245
