### ISSUE TITLE
MariaDB/MySQL client defined, but Knex tries to connect with SQLite client

### ISSUE THREAD

**Issue by jepster** [tgriesser/knex#1421]
I have defined my database connection:

```
var knex = require('knex')({
  client: 'mariasql',
  debug: true,
  connection: {
    host     : '127.0.0.1',
    user     : 'root',
    password : 'password',
    database : 'database',
    charset  : 'utf8',
  }
});

module.exports = require('bookshelf')(knex);

knex.raw('select 1+1 as result').then(function () {
  console.log('valid connection..');
});
```

I initialize it that way in my models:
`var bookshelf = require('../lib/bookshelf_init.js');`

The console.log() function at the bottom returns "valid connection". But after I query the database in my program, I'm getting "SQLITE" errors:

`SQLITE_ERROR: no such table: ...`

Do I have made any mistake in the initialization of knex or bookshelf? Why do I get SQLite errors? I'm using bookshelf in version 0.9.5 and knex in version 0.11.3.

**Comment by elhigu** [comment]
Can you make this happen with plain knex without bookshelf?

**Comment by IrregularShed** [comment]
I think this may be related to what I'm experiencing. Despite setting up knex to use mysql (using code I copied from an earlier project), I get this output:
```
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module 'sqlite3'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Client._driver (d:\dev\rs\rs-dsa\utilities\node_modules\knex\lib\dialects\sqlite3\index.js:65:12)
at Client.initializeDriver (d:\dev\rs\rs-dsa\utilities\node_modules\knex\lib\client.js:211:26)
at Client (d:\dev\rs\rs-dsa\utilities\node_modules\knex\lib\client.js:92:10)
at Client_SQLite3 (d:\dev\rs\rs-dsa\utilities\node_modules\knex\lib\dialects\sqlite3\index.js:51:23)
at new Client (d:\dev\rs\rs-dsa\utilities\node_modules\knex\lib\util\make-client.js:24:18)
at new Knex (d:\dev\rs\rs-dsa\utilities\node_modules\knex\lib\index.js:57:36)
at Object.Knex (d:\dev\rs\rs-dsa\utilities\node_modules\knex\lib\index.js:43:12)
at createTechhub (d:\dev\rs\rs-dsa\utilities\index.js:42:17)
at createTechhubs (d:\dev\rs\rs-dsa\utilities\index.js:23:13)
at Object.<anonymous> (d:\dev\rs\rs-dsa\utilities\index.js:63:1)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
```

The code being run is:
```javascript
    knex({
        client: 'mysql',
        connection: {
            host: settings.host,
            user: settings.user,
            password: settings.password,
            database: settings.database,
            charset: 'UTF8_GENERAL_CI'
        }
    });
```
and later on:
```javascript
    return data.knex('nodes')
        .insert({
    ...
```

The code is identical to what I wrote previously, but the NPM package versions are different. My old code is using knex 0.11.1 and bluebird 3.3.5; the new code has got knex 0.11.5 and bluebird 3.4.0.

I hope those details can help. I think that whatever code is creating the client is getting the client type wrong for some reason, but that's merely a (partially) educated guess. (In the log `\util\make-client.js` is followed immediately by SQLite3, after all.)

**Comment by IrregularShed** [comment]
I've just changed the versions of the libraries to what was working in my other project, but it's not made any difference. Apologies if version numbers are a red herring!

**Comment by IrregularShed** [comment]
_[Deleted comments that could've caused a wild goose chase after spotting an error in my setup]_

**Comment by wubzz** [comment]
Closing old issue with no response.
