### ISSUE TITLE
Password authentication failed when running a migration on Node v6.2

### ISSUE THREAD

**Issue by santiagovazquez** [tgriesser/knex#1466]
Running a migration cause auth failen on node versions > 6.0 (tested on 6.0 and 6.2)

```
NODE_ENV=production knex migrate:latest
Knex:warning - Pool2 - Error: Pool was destroyed
Knex:Error Pool2 - error: password authentication failed for user "------"
Error: Pool was destroyed
    at Pool._destroyPool (/home/deploy/alentame-api-deploy-master-branch/e5d48e6b613f404daade1971e0b518ede830705c/node_modules/pool2/lib/pool.js:548:20)
    at Pool.<anonymous> (/home/deploy/alentame-api-deploy-master-branch/e5d48e6b613f404daade1971e0b518ede830705c/node_modules/pool2/lib/pool.js:465:18)
    at Pool.<anonymous> (/home/deploy/alentame-api-deploy-master-branch/e5d48e6b613f404daade1971e0b518ede830705c/node_modules/pool2/lib/pool.js:505:17)
    at tryCatcher (/home/deploy/alentame-api-deploy-master-branch/e5d48e6b613f404daade1971e0b518ede830705c/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.errorAdapter (/home/deploy/alentame-api-deploy-master-branch/e5d48e6b613f404daade1971e0b518ede830705c/node_modules/knex/node_modules/bluebird/js/main/nodeify.js:36:34)
    at Promise._settlePromiseAt (/home/deploy/alentame-api-deploy-master-branch/e5d48e6b613f404daade1971e0b518ede830705c/node_modules/knex/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/home/deploy/alentame-api-deploy-master-branch/e5d48e6b613f404daade1971e0b518ede830705c/node_modules/knex/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/deploy/alentame-api-deploy-master-branch/e5d48e6b613f404daade1971e0b518ede830705c/node_modules/knex/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/deploy/alentame-api-deploy-master-branch/e5d48e6b613f404daade1971e0b518ede830705c/node_modules/knex/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/deploy/alentame-api-deploy-master-branch/e5d48e6b613f404daade1971e0b518ede830705c/node_modules/knex/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

When using 5.9, it's working:

```
~/alentame-api-deploy-master-branch/current$ nvm install v5.9.0
~/alentame-api-deploy-master-branch/current$ nvm use v5.9
NODE_ENV=production knex migrate:latest
/home/deploy/alentame-api-deploy-master-branch/e5d48e6b613f404daade1971e0b518ede830705c/migrations/20160527105544_suspensions.js
/home/deploy/alentame-api-deploy-master-branch/e5d48e6b613f404daade1971e0b518ede830705c/migrations/20160527111204_add_mvps_to_matches.js
```

Environment: Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-36-generic x86_64)
On my mac seems to work just fine.

**Comment by santiagovazquez** [comment]
Sorry, my bad. The problem was with an old version of pg package. I weren't able to delete this issue.
