### ISSUE TITLE
ECONNRESET when idle

### ISSUE THREAD

**Issue by goowikns** [tgriesser/knex#1500]
Hi,

I can't seem to reproduce this error whenever, but following error is usually thrown after a few hours:
fyi these are the package versions:

- **node:** v4.4.3
- **knex:** v0.10.0
- **mysql:** v2.10.2

```
Unhandled rejection Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:552:26)
    --------------------
    at Protocol._enqueue (C:\Users\User\PhpstormProjects\projectname\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at Connection.query (C:\Users\User\PhpstormProjects\projectname\node_modules\mysql\lib\Connection.js:201:25)
    at C:\Users\User\PhpstormProjects\projectname\node_modules\knex\lib\dialects\mysql\index.js:92:18
    at tryCatcher (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\promise.js:480:31)
    at new Promise (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\promise.js:70:37)
    at Client._query (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\lib\dialects\mysql\index.js:88:12)
    at Client.query (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\lib\client.js:136:24)
    at Runner.<anonymous> (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\lib\runner.js:115:24)
    at Runner.tryCatcher (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\util.js:26:23)
    at Runner.query (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\method.js:15:34)
    at C:\Users\User\PhpstormProjects\projectname\node_modules\knex\lib\runner.js:43:21
    at C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\using.js:176:30
    at tryCatcher (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

And not sure whether this is related but after a simple page refresh I received following error:

```
Unhandled rejection Error: Knex: Timeout acquiring a connection. The pool is probably full. Are yo
u missing a .transacting(trx) call?
    at C:\Users\User\PhpstormProjects\projectname\node_modules\knex\lib\runner.js:138:30
    at tryCatcher (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\util.js:26:23)
    at CatchFilter.doFilter (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\catch_filter.js:40:36)
    at CatchFilter.tryCatcher (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\User\PhpstormProjects\projectname\node_modules\knex\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Here is my basic connection to the database:

```
var knex = require('knex')({
  client: 'mysql',
  connection: {
    host: 'xx.xx.xx.xx',  // your host
    user: 'userhere', // your database user
    password: 'password', // your database password
    database: 'database',
    charset: 'UTF8_GENERAL_CI'
  }
});

var DB = require('bookshelf')(knex);
DB.plugin( 'registry' );

module.exports.DB = DB;
```

fyi the database is accessed from the outside (not localhost). It gets populated succesfully so connection wise, is fine.

**Comment by elhigu** [comment]
Try latest knex if it works better, IIRC there was some fixes done to how pool discards broken connections.

Also try to create single file test case where you can reproduce the problem, otherwise there are pretty close to zero changes to help with this.

**Comment by tgriesser** [comment]
I think this should be cleaned up a bit in version 0.12, please open another ticket if you're still seeing this.
