### ISSUE TITLE
Error: Pool is destroyed

### ISSUE THREAD

**Issue by olalonde** [tgriesser/knex#1591]
I keep seeing this error randomly pop up in my logs:

```javascript
Error: Pool is destroyed 
    at Pool.acquire (/app/node_modules/pool2/lib/pool.js:166:12) 
    at /app/node_modules/knex/lib/client.js:220:19 
    at tryCatcher (/app/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23) 
    at Promise._resolveFromResolver (/app/node_modules/knex/node_modules/bluebird/js/main/promise.js:480:31) 
    at new Promise (/app/node_modules/knex/node_modules/bluebird/js/main/promise.js:70:37) 
    at Client.acquireConnection (/app/node_modules/knex/lib/client.js:216:12) 
    at /app/node_modules/knex/lib/runner.js:137:23 
    at tryCatcher (/app/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23) 
    at Promise._resolveFromResolver (/app/node_modules/knex/node_modules/bluebird/js/main/promise.js:480:31) 
    at new Promise (/app/node_modules/knex/node_modules/bluebird/js/main/promise.js:70:37) 
    at /app/node_modules/knex/lib/runner.js:136:35 
    at tryCatcher (/app/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23) 
    at Function.Promise.attempt.Promise.try (/app/node_modules/knex/node_modules/bluebird/js/main/method.js:31:24) 
    at Runner.ensureConnection (/app/node_modules/knex/lib/runner.js:135:26) 
    at Runner.run (/app/node_modules/knex/lib/runner.js:29:31) 
    at QueryBuilder.Target.then (/app/node_modules/knex/lib/interface.js:26:43) 
    at QueryBuilder.tryCatcher (/app/node_modules/bookshelf/node_modules/bluebird/js/main/util.js:26:23)  
    at doThenable (/app/node_modules/bookshelf/node_modules/bluebird/js/main/thenables.js:52:38) 
    at tryConvertToPromise (/app/node_modules/bookshelf/node_modules/bluebird/js/main/thenables.js:30:20) 
    at Promise._resolveCallback (/app/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:442:24) 
    at Promise._settlePromiseFromHandler (/app/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:515:17) 
    at Promise._settlePromiseAt (/app/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:581:18) 
    at Async._drainQueue (/app/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:128:12) 
    at Async._drainQueues (/app/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:133:10) 
    at Immediate.Async.drainQueues (/app/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:15:14) 
    at runCallback (timers.js:570:20) 
    at tryOnImmediate (timers.js:550:5) 
    at processImmediate [as _immediateCallback] (timers.js:529:5) 
Error: Pool is destroyed 
    at Pool.acquire (/app/node_modules/pool2/lib/pool.js:166:12) 
    at /app/node_modules/knex/lib/client.js:220:19 
    at tryCatcher (/app/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23) 
    at Promise._resolveFromResolver (/app/node_modules/knex/node_modules/bluebird/js/main/promise.js:480:31) 
    at new Promise (/app/node_modules/knex/node_modules/bluebird/js/main/promise.js:70:37) 
    at Client.acquireConnection (/app/node_modules/knex/lib/client.js:216:12) 
    at /app/node_modules/knex/lib/runner.js:137:23 
    at tryCatcher (/app/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23) 
    at Promise._resolveFromResolver (/app/node_modules/knex/node_modules/bluebird/js/main/promise.js:480:31) 
    at new Promise (/app/node_modules/knex/node_modules/bluebird/js/main/promise.js:70:37) 
    at /app/node_modules/knex/lib/runner.js:136:35 
    at tryCatcher (/app/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23) 
    at Function.Promise.attempt.Promise.try (/app/node_modules/knex/node_modules/bluebird/js/main/method.js:31:24) 
    at Runner.ensureConnection (/app/node_modules/knex/lib/runner.js:135:26) 
    at Runner.run (/app/node_modules/knex/lib/runner.js:29:31) 
    at QueryBuilder.Target.then (/app/node_modules/knex/lib/interface.js:26:43) 
    at QueryBuilder.tryCatcher (/app/node_modules/bookshelf/node_modules/bluebird/js/main/util.js:26:23)  
    at doThenable (/app/node_modules/bookshelf/node_modules/bluebird/js/main/thenables.js:52:38) 
    at tryConvertToPromise (/app/node_modules/bookshelf/node_modules/bluebird/js/main/thenables.js:30:20) 
    at Promise._resolveCallback (/app/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:442:24) 
    at Promise._settlePromiseFromHandler (/app/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:515:17) 
    at Promise._settlePromiseAt (/app/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:581:18) 
    at Async._drainQueue (/app/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:128:12) 
    at Async._drainQueues (/app/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:133:10) 
    at Immediate.Async.drainQueues (/app/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:15:14) 
    at runCallback (timers.js:570:20) 
    at tryOnImmediate (timers.js:550:5) 
    at processImmediate [as _immediateCallback] (timers.js:529:5) 
```

It's hard to reproduce the bug, it seems to happen pretty randomly. It could be an issue with having a too high connection count the database.

**Comment by elhigu** [comment]
There is pretty much nothing we can do if it cannot be reproduced? Are you using mysql?

**Comment by olalonde** [comment]
PostgreSQL

**Comment by olalonde** [comment]
Maybe a bug with https://github.com/myndzi/pool2?

**Comment by tgriesser** [comment]
This is perhaps the most common issue with knex without a good solution, I'm going to take a look at the causes/potential solutions tomorrow.

**Comment by myndzi** [comment]
@tgriesser Hit me up on IRC when you have a look. If there's anything I can do to surface more useful error information I feel like that would be helpful. In general, it seems to be unclear when there is a normal "connection issue", partly because pool2 winds up being the source of some error messages, but since it accepts callbacks to manage the resources, it's never actually in control of the connection process and we get stuff like this that is deceptive about the source of the problem.

**Comment by myndzi** [comment]
@olalonde Is it possible that this error could be happening after a restart of your application? This specific state should only happen under pretty specific circumstances, not after the application has been successfully running.

**Comment by olalonde** [comment]
Maybe replacing pool2 with https://github.com/coopernurse/node-pool could be an option? would be helpful if we could have a test that reproduces the issue. but I can't seem to pinpoint how to reproduce reliably

**Comment by atiertant** [comment]
> Maybe replacing pool2 with https://github.com/coopernurse/node-pool which seems more actively maintained could be an option? would be helpful if we could have a test that reproduces the issue. but I can't seem to pinpoint how to reproduce it reliably

i used node-pool in other project and it work perfectly, replacing pool2 could solve the problem...

**Comment by olalonde** [comment]
It's also what https://github.com/brianc/node-postgres uses

**Comment by tgriesser** [comment]
I ended up moving back to node-pool for now, but am planning on re-configuring the connection api to make pooling swappable, so you can specify pool2 or another pooling option, or no pool at all in the future. Try 0.12 and see if things are working any better

**Comment by krstripe** [comment]
I hope this change solves peoples' intermittent problems. It looks like this code addresses the issues with generic-pool that pool2 was originally written to solve (it tracks checked out resources and validates returned resources). In fact, they look awful similar under the hood.

Given that the 'pool is destroyed' error only has one pretty specific source (failure with never a success in the first place), my suspicion remains that this type of error arises at the intersection of knex and pool2. I hope the problem goes away in the process of swapping things over. If it doesn't and you want to attack this further, you know how to get ahold of me :) I don't believe I've been inactive as a maintainer, I simply haven't had anything to act on.

**Comment by myndzi** [comment]
I hope this change solves peoples' intermittent problems. It looks like this code addresses the issues with generic-pool that pool2 was originally written to solve (it tracks checked out resources and validates returned resources). In fact, they look awful similar under the hood.

Given that the 'pool is destroyed' error only has one pretty specific source (failure with never a success in the first place), my suspicion remains that this type of error arises at the intersection of knex and pool2. I hope the problem goes away in the process of swapping things over. If it doesn't and you want to attack this further, you know how to get ahold of me :) I don't believe I've been inactive as a maintainer, I simply haven't had anything to act on.

**Comment by niczak** [comment]
@myndzi I know this is an old post but I am having this issue w/ 0.10.0 - did moving to 0.12 fix the issue?
