### ISSUE TITLE
MSSQL Migration Error

### ISSUE THREAD

**Issue by mgarf** [tgriesser/knex#1627]
when i run knex migrate:latest and get the following error with debug enabled: 

```
[ { sql: 'select object_id from sys.tables where object_id = object_id(?)',
    output: [Function: output],
    bindings: [ '[knex_migrations]' ] } ]
[ { sql: 'select object_id from sys.tables where object_id = object_id(?)',
    output: [Function: output],
    bindings: [ '[knex_migrations_lock]' ] } ]
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '878ef3da-71b8-4674-b0b9-98e6dc3c1b2d',
  sql: 'select * from [knex_migrations_lock]' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '337a89c1-582a-4966-975c-f4db8ee7345c',
  sql: 'select [name] from [knex_migrations] order by [id] asc' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '712a23f0-3da4-43cb-9e19-9111273852cd',
  sql: 'select * from [knex_migrations_lock] with (READCOMMITTEDLOCK)' }
{ method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '66cda343-bdf5-495f-8005-60f8b00930cc',
  sql: 'update [knex_migrations_lock] set [is_locked] = ?;select @@rowcount',
  returning: '@@rowcount' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '45a5e130-e12a-46f9-99f6-d9bc53d0bad3',
  sql: 'select max([batch]) as [max_batch] from [knex_migrations]' }
[ { sql: 'CREATE TABLE [company] ([companyId] int identity(1,1) not null primary
 key, [name] nvarchar(255), [dueNet] int(10), [timeDue] time, [created_at] datet
ime, [updated_at] datetime)',
    bindings: [] } ]
[ { sql: 'CREATE TABLE [companyExceptions] ([companyExceptionsId] int identity(1
,1) not null primary key, [company] int(11), [forWeek] date, [dueNet] int(10), [
timeDue] time, [created_at] datetime, [updated_at] datetime, CONSTRAINT [company
exceptions_company_foreign] FOREIGN KEY ([company]) REFERENCES [company] ([compa
nyId]))',
    bindings: [] } ]
[ { sql: 'CREATE TABLE [project] ([projectId] int identity(1,1) not null primary
 key, [name] nvarchar(255), [created_at] datetime, [updated_at] datetime, [start
] datetime, [end] datetime)',
    bindings: [] } ]
[ { sql: 'CREATE TABLE [projectAssignments] ([assignmentId] int identity(1,1) no
t null primary key, [user] int(11), [project] int(11), [created_at] datetime, [u
pdated_at] datetime, CONSTRAINT [projectassignments_user_foreign] FOREIGN KEY ([
user]) REFERENCES [users] ([userId]), CONSTRAINT [projectassignments_project_for
eign] FOREIGN KEY ([project]) REFERENCES [project] ([projectId]))',
    bindings: [] } ]
[ { sql: 'CREATE TABLE [timecard] ([timecardId] int identity(1,1) not null prima
ry key, [forWeek] date, [user] int(11), [status] nvarchar(255), [created_at] dat
etime, [updated_at] datetime, CONSTRAINT [timecard_user_foreign] FOREIGN KEY ([u
ser]) REFERENCES [users] ([userId]))',
    bindings: [] } ]
[ { sql: 'CREATE TABLE [timecardEntries] ([timecardEntriesId] int identity(1,1)
not null primary key, [timecard] int(11), [Monday] nvarchar(255), [Tuesday] nvar
char(255), [Wednesday] nvarchar(255), [Thursday] nvarchar(255), [Friday] nvarcha
r(255), [Saturday] nvarchar(255), [Sunday] nvarchar(255), [project] int(11), [cr
eated_at] datetime, [updated_at] datetime, CONSTRAINT [timecardentries_timecard_
foreign] FOREIGN KEY ([timecard]) REFERENCES [timecard] ([timecardId]), CONSTRAI
NT [timecardentries_project_foreign] FOREIGN KEY ([project]) REFERENCES [project
] ([projectId]))',
    bindings: [] } ]
[ { sql: 'CREATE TABLE [approvals] ([approvalId] int identity(1,1) not null prim
ary key, [Comment] nvarchar(255), [user] int(11), [manager] int(11), [timecard]
int(11), [status] nvarchar(255), [created_at] datetime, [updated_at] datetime, C
ONSTRAINT [approvals_user_foreign] FOREIGN KEY ([user]) REFERENCES [users] ([use
rId]), CONSTRAINT [approvals_manager_foreign] FOREIGN KEY ([manager]) REFERENCES
 [users] ([userId]), CONSTRAINT [approvals_timecard_foreign] FOREIGN KEY ([timec
ard]) REFERENCES [timecard] ([timecardId]))',
    bindings: [] } ]
[ { sql: 'CREATE TABLE [configuration] ([configurationId] int identity(1,1) not
null primary key, [escalation] text null, [pendingApprovals] text null, [confirm
ation] text null, [reminder] text null, [newuser] text null, [reset] text null,
[reject] text null, [financeUser] int(11), [created_at] datetime, [updated_at] d
atetime, CONSTRAINT [configuration_financeuser_foreign] FOREIGN KEY ([financeUse
r]) REFERENCES [users] ([userId]))',
    bindings: [] } ]
Unhandled rejection TransactionError: Can't rollback transaction. There is a req
uest in progress.
    at Transaction._rollback (C:\Program Files\iisnode\www\timecard\node_modules
\mssql\lib\main.js:1061:18)
    at C:\Program Files\iisnode\www\timecard\node_modules\mssql\lib\main.js:1041
:24
    at Transaction.rollback (C:\Program Files\iisnode\www\timecard\node_modules\
mssql\lib\main.js:1039:14)
    at Transaction_MSSQL.rollback (C:\Program Files\iisnode\www\timecard\node_mo
dules\knex\lib\dialects\mssql\transaction.js:63:21)
    at Function.transactor.rollback (C:\Program Files\iisnode\www\timecard\node_
modules\knex\lib\transaction.js:208:18)
    at C:\Program Files\iisnode\www\timecard\node_modules\knex\lib\transaction.j
s:72:29
    at tryCatcher (C:\Program Files\iisnode\www\timecard\node_modules\knex\node_
modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\iisnode\www\timecard\
node_modules\knex\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Program Files\iisnode\www\timecard\node_module
s\knex\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Program Files\iisnode\www\timecard\node_modul
es\knex\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Program Files\iisnode\www\timecard\node_modul
es\knex\node_modules\bluebird\js\release\promise.js:681:18)
    at Async._drainQueue (C:\Program Files\iisnode\www\timecard\node_modules\kne
x\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Program Files\iisnode\www\timecard\node_modules\kn
ex\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (C:\Program Files\iisnode\www\timecard\node_m
odules\knex\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

**Comment by mgarf** [comment]
my knexfile.js:

```
var dotenv = require('dotenv');

dotenv.load();

module.exports = {
  client: 'mssql',
  connection: {
    host: process.env.DB_HOST,
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      database: process.env.DB_NAME
  },
  debug: true,
  migrations: {
    tableName: 'migrations'
  }
};
```

**Comment by mgarf** [comment]
My Migration file:

```
exports.up = function(knex, Promise) {
  return Promise.all([

    knex.schema.createTable('company', function(table) {
      table.increments('companyId').primary();
      table.string('name');
      table.integer('dueNet',10);
      table.time('timeDue');
      table.timestamps();
    }),

    knex.schema.createTable('users', function(table) {
      table.increments('userId').primary();
      table.string('firstName');
      table.string('lastName');
      table.string('email').unique();
      table.integer('company',11).unsigned().references('companyId').inTable('company');
      table.string('password');
      table.string('passwordResetToken');
      table.dateTime('passwordResetExpires');
      table.string('picture');
      table.integer('manager',11).unsigned().references('userId');
      table.integer('backup',11).unsigned().references('userId');
      table.string('role');
      table.string('status');
      table.timestamps();
    }),

    knex.schema.createTable('companyExceptions', function(table) {
      table.increments('companyExceptionsId').primary();
      table.integer('company',11).unsigned().references('companyId').inTable('company');
      table.date('forWeek');
      table.integer('dueNet',10);
      table.time('timeDue');
      table.timestamps();
    }),

    knex.schema.createTable('project', function(table) {
      table.increments('projectId').primary();
      table.string('name');
      table.timestamps();
      table.dateTime('start');
      table.dateTime('end');
    }),

    knex.schema.createTable('projectAssignments', function(table) {
      table.increments('assignmentId').primary();
      table.integer('user',11).unsigned().references('userId').inTable('users');
      table.integer('project',11).unsigned().references('projectId').inTable('project');
      table.timestamps();
    }),

    knex.schema.createTable('timecard', function(table) {
      table.increments('timecardId').primary();
      table.date('forWeek');
      table.integer('user',11).unsigned().references('userId').inTable('users');
      table.string('status');
      table.timestamps();
    }),

    knex.schema.createTable('timecardEntries', function(table) {
      table.increments('timecardEntriesId').primary();
      table.integer('timecard',11).unsigned().references('timecardId').inTable('timecard');
      table.string('Monday');
      table.string('Tuesday');
      table.string('Wednesday');
      table.string('Thursday');
      table.string('Friday');
      table.string('Saturday');
      table.string('Sunday');
      table.integer('project',11).unsigned().references('projectId').inTable('project');
      table.timestamps();
    }),

    knex.schema.createTable('approvals', function(table) {
      table.increments('approvalId').primary();
      table.string('Comment');
      table.integer('user',11).unsigned().references('userId').inTable('users');
      table.integer('manager',11).unsigned().references('userId').inTable('users');
      table.integer('timecard',11).unsigned().references('timecardId').inTable('timecard');
      table.string('status');
      table.timestamps();
    }),

    knex.schema.createTable('configuration', function(table) {
      table.increments('configurationId').primary();
      table.json('escalation').nullable();
      table.json('pendingApprovals').nullable();
      table.json('confirmation').nullable();
      table.json('reminder').nullable();
      table.json('newuser').nullable();
      table.json('reset').nullable();
      table.json('reject').nullable();
      table.integer('financeUser',11).unsigned().references('userId').inTable('users');
      table.timestamps();
    })
  ]);

};

exports.down = function(knex, Promise) {
  return Promise.all([
    knex.schema.dropTable('users'),
    knex.schema.dropTable('timecard'),
    knex.schema.dropTable('approvals'),
    knex.schema.dropTable('company'),
    knex.schema.dropTable('companyExceptions'),
    knex.schema.dropTable('project'),
    knex.schema.dropTable('projectAssignments'),
    knex.schema.dropTable('configuration')
  ])
};

```

**Comment by mgarf** [comment]
Narrowed it down to two things. One is the numbers on integer which I removed. The second being the .references to its own table. in table users.

**Comment by mgarf** [comment]
Solved by moving field references of the same table to a separate migration and dropping the numbers on the integers
