### ISSUE TITLE
Some oracledb tests failing (currently disabled to be able to enable oracledb tests on CI)

### ISSUE THREAD

**Issue by elhigu** [tgriesser/knex#1689]
```
 1) oracle | oracledb Schema renameColumn #933 - .renameColumn should not drop null or default value:
     AssertionError: expected 'undefined' to include '1'
      at test/integration/schema/index.js:452:66
  From previous event:
      at test/integration/schema/index.js:451:14
      at lib/transaction.js:9:4206
  From previous event:
      at lib/transaction.js:9:3996
  From previous event:
      at Oracle_Transaction.Transaction (lib/transaction.js:9:3385)
      at new Oracle_Transaction (lib/dialects/oracledb/transaction.js:9:1750)
      at Client_Oracledb.transaction (lib/dialects/oracledb/index.js:9:3860)
      at Function.transaction (lib/util/make-knex.js:9:4505)
      at Context.<anonymous> (test/integration/schema/index.js:443:21)
```

```
  1) oracle | oracledb Inserts should handle simple inserts:
     insert into "accounts" ("about", "created_at", "email", "first_name", "last_name", "logins", "updated_at") values (:1, :2, :3, :4, :5, :6, :7) returning "id" into :8 - ORA-04098: trigger 'TRAVIS.test_table_one_id_trg' is invalid and failed re-validation
  Error: ORA-04098: trigger 'TRAVIS.test_table_one_id_trg' is invalid and failed re-validation

      at Error (native)
  From previous event:
      at Connection.connection.executeAsync (lib/dialects/oracledb/index.js:9:11129)
      at lib/dialects/oracledb/index.js:9:15642
  From previous event:
      at Client_Oracledb._query (lib/dialects/oracledb/index.js:9:14988)
      at Client_Oracledb.query (lib/client.js:9:11138)
      at Runner.<anonymous> (lib/runner.js:9:6823)
  From previous event:
      at lib/runner.js:9:3513
  From previous event:
      at Runner.run (lib/runner.js:9:2625)
      at Builder.Target.then (lib/interface.js:9:1687)
```

```
  1) oracle | oracledb Inserts should handle multi inserts:
     begin execute immediate 'insert into "accounts" ("about", "created_at", "email", "first_name", "last_name", "logins", "updated_at") values (:1, :2, :3, :4, :5, :6, :7) returning "id" into :8' using :1, :2, :3, :4, :5, :6, :7, out :8; execute immediate 'insert into "accounts" ("about", "created_at", "email", "first_name", "last_name", "logins", "updated_at") values (:1, :2, :3, :4, :5, :6, :7) returning "id" into :8' using :9, :10, :11, :12, :13, :14, :15, out :16;end; - ORA-04098: trigger 'TRAVIS.test_table_one_id_trg' is invalid and failed re-validation
ORA-06512: at line 1
  Error: ORA-04098: trigger 'TRAVIS.test_table_one_id_trg' is invalid and failed re-validation
  ORA-06512: at line 1

      at Error (native)
  From previous event:
      at Connection.connection.executeAsync (lib/dialects/oracledb/index.js:9:11129)
      at lib/dialects/oracledb/index.js:9:15642
  From previous event:
      at Client_Oracledb._query (lib/dialects/oracledb/index.js:9:14988)
      at Client_Oracledb.query (lib/client.js:9:11138)
      at Runner.<anonymous> (lib/runner.js:9:6823)
  From previous event:
      at lib/runner.js:9:3513
  From previous event:
      at Runner.run (lib/runner.js:9:2625)
      at Builder.Target.then (lib/interface.js:9:1687)
```

```
  1) oracle | oracledb Inserts should take hashes passed into insert and keep them in the correct order:
     begin execute immediate 'insert into "accounts" ("about", "created_at", "email", "first_name", "last_name", "logins", "updated_at") values (:1, :2, :3, :4, :5, :6, :7) returning "id" into :8' using :1, :2, :3, :4, :5, :6, :7, out :8; execute immediate 'insert into "accounts" ("about", "created_at", "email", "first_name", "last_name", "logins", "updated_at") values (:1, :2, :3, :4, :5, :6, :7) returning "id" into :8' using :9, :10, :11, :12, :13, :14, :15, out :16;end; - ORA-04098: trigger 'TRAVIS.test_table_one_id_trg' is invalid and failed re-validation
ORA-06512: at line 1
  Error: ORA-04098: trigger 'TRAVIS.test_table_one_id_trg' is invalid and failed re-validation
  ORA-06512: at line 1

      at Error (native)
  From previous event:
      at Connection.connection.executeAsync (lib/dialects/oracledb/index.js:9:11129)
      at lib/dialects/oracledb/index.js:9:15642
  From previous event:
      at Client_Oracledb._query (lib/dialects/oracledb/index.js:9:14988)
      at Client_Oracledb.query (lib/client.js:9:11138)
      at Runner.<anonymous> (lib/runner.js:9:6823)
  From previous event:
      at lib/runner.js:9:3513
  From previous event:
      at Runner.run (lib/runner.js:9:2625)
      at Builder.Target.then (lib/interface.js:9:1687)
```

```
 1) oracle | oracledb Inserts should drop any where clause bindings:
     insert into "accounts" ("about", "created_at", "email", "first_name", "last_name", "logins", "updated_at") values (:1, :2, :3, :4, :5, :6, :7) returning "id" into :8 - ORA-04098: trigger 'TRAVIS.test_table_one_id_trg' is invalid and failed re-validation
  Error: ORA-04098: trigger 'TRAVIS.test_table_one_id_trg' is invalid and failed re-validation

      at Error (native)
  From previous event:
      at Connection.connection.executeAsync (lib/dialects/oracledb/index.js:9:11129)
      at lib/dialects/oracledb/index.js:9:15642
  From previous event:
      at Client_Oracledb._query (lib/dialects/oracledb/index.js:9:14988)
      at Client_Oracledb.query (lib/client.js:9:11138)
      at Runner.<anonymous> (lib/runner.js:9:6823)
  From previous event:
      at lib/runner.js:9:3513
  From previous event:
      at Runner.run (lib/runner.js:9:2625)
      at Builder.Target.then (lib/interface.js:9:1687)
```

```
1) oracle | oracledb Inserts should replace undefined keys in multi insert with DEFAULT:
     begin execute immediate 'insert into "accounts" ("about", "created_at", "email", "last_name", "logins", "updated_at") values (:1, :2, :3, :4, DEFAULT, :5)' using :1, :2, :3, :4, :5; execute immediate 'insert into "accounts" ("about", "created_at", "email", "last_name", "logins", "updated_at") values (DEFAULT, :1, :2, :3, :4, :5)' using :6, :7, :8, :9, :10;end; - ORA-04098: trigger 'TRAVIS.test_table_one_id_trg' is invalid and failed re-validation
ORA-06512: at line 1
  Error: ORA-04098: trigger 'TRAVIS.test_table_one_id_trg' is invalid and failed re-validation
  ORA-06512: at line 1

      at Error (native)
  From previous event:
      at Connection.connection.executeAsync (lib/dialects/oracledb/index.js:9:11129)
      at lib/dialects/oracledb/index.js:9:15642
  From previous event:
      at Client_Oracledb._query (lib/dialects/oracledb/index.js:9:14988)
      at Client_Oracledb.query (lib/client.js:9:11138)
      at Runner.<anonymous> (lib/runner.js:9:6823)
  From previous event:
      at lib/runner.js:9:3513
  From previous event:
      at Runner.run (lib/runner.js:9:2625)
      at Builder.Target.then (lib/interface.js:9:1687)
      at Context.<anonymous> (test/integration/builder/inserts.js:757:10)
```

```
  1) oracle | oracledb Inserts #1423 should replace undefined keys in single insert with DEFAULT also in transacting query:
     insert into "accounts" ("about", "created_at", "email", "last_name", "logins", "updated_at") values (:1, :2, :3, :4, :5, :6) - ORA-04098: trigger 'TRAVIS.test_table_one_id_trg' is invalid and failed re-validation
  Error: ORA-04098: trigger 'TRAVIS.test_table_one_id_trg' is invalid and failed re-validation

      at Error (native)
  From previous event:
      at Connection.connection.executeAsync (lib/dialects/oracledb/index.js:9:11129)
      at lib/dialects/oracledb/index.js:9:15642
  From previous event:
      at Client_Oracledb._query (lib/dialects/oracledb/index.js:9:14988)
      at Client_Oracledb.query (lib/client.js:9:11138)
      at lib/transaction.js:9:15241
  From previous event:
      at Client_Oracledb.trxClient.query (lib/transaction.js:9:14673)
      at Runner.<anonymous> (lib/runner.js:9:6823)
  From previous event:
      at lib/runner.js:9:3513
  From previous event:
      at Runner.run (lib/runner.js:9:2625)
      at Builder.Target.then (lib/interface.js:9:1687)
      at test/integration/builder/inserts.js:789:12
      at lib/transaction.js:9:4206
  From previous event:
      at lib/transaction.js:9:3996
  From previous event:
      at Oracle_Transaction.Transaction (lib/transaction.js:9:3385)
      at new Oracle_Transaction (lib/dialects/oracledb/transaction.js:9:1750)
      at Client_Oracledb.transaction (lib/dialects/oracledb/index.js:9:3860)
      at Function.transaction (lib/util/make-knex.js:9:4505)
      at Context.<anonymous> (test/integration/builder/inserts.js:779:19)
```

```
  1) oracle | oracledb Selects allows you to stream:
     TypeError: connection.reader is not a function
      at new OracleQueryStream (lib/dialects/oracle/stream.js:9:1078)
      at lib/dialects/oracle/index.js:9:10202
      at Client_Oracledb._stream (lib/dialects/oracle/index.js:9:9598)
      at Client_Oracledb.stream (lib/client.js:9:12205)
      at lib/runner.js:9:5914
  From previous event:
      at Runner.stream (lib/runner.js:9:5089)
      at Builder.Target.stream (lib/interface.js:9:3760)
      at Context.<anonymous> (test/integration/builder/selects.js:163:31)
```

```
Unhandled rejection TypeError: connection.reader is not a function
    at new OracleQueryStream (/home/travis/build/tgriesser/knex/lib/dialects/oracle/stream.js:9:1078)
    at /home/travis/build/tgriesser/knex/lib/dialects/oracle/index.js:9:10202
    at Client_Oracledb._stream (/home/travis/build/tgriesser/knex/lib/dialects/oracle/index.js:9:9598)
    at Client_Oracledb.stream (/home/travis/build/tgriesser/knex/lib/client.js:9:12205)
    at /home/travis/build/tgriesser/knex/lib/runner.js:9:5914
From previous event:
    at Runner.stream (/home/travis/build/tgriesser/knex/lib/runner.js:9:5089)
    at Builder.Target.stream (/home/travis/build/tgriesser/knex/lib/interface.js:9:3760)
    at Context.<anonymous> (/home/travis/build/tgriesser/knex/test/integration/builder/selects.js:178:37)
    at callFnAsync (/home/travis/build/tgriesser/knex/node_modules/mocha/lib/runnable.js:349:8)
    at Test.Runnable.run (/home/travis/build/tgriesser/knex/node_modules/mocha/lib/runnable.js:301:7)
    at Runner.runTest (/home/travis/build/tgriesser/knex/node_modules/mocha/lib/runner.js:422:10)
    at /home/travis/build/tgriesser/knex/node_modules/mocha/lib/runner.js:528:12
    at next (/home/travis/build/tgriesser/knex/node_modules/mocha/lib/runner.js:342:14)
    at /home/travis/build/tgriesser/knex/node_modules/mocha/lib/runner.js:352:7
    at next (/home/travis/build/tgriesser/knex/node_modules/mocha/lib/runner.js:284:14)
    at Immediate.<anonymous> (/home/travis/build/tgriesser/knex/node_modules/mocha/lib/runner.js:320:5)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
  1) returns a stream if not passed a function
```

```
1) oracle | oracledb Updates should increment a value:
     AssertionError: expected [] to equal 1
      at test/integration/builder/updates.js:70:35
  From previous event:
      at Builder.Target.then (lib/interface.js:9:1751)
      at Context.<anonymous> (test/integration/builder/updates.js:68:63)
```

and much more...

**Comment by elhigu** [comment]
Test was disabled by https://github.com/tgriesser/knex/pull/1685 pull request

**Comment by atiertant** [comment]
@elhigu should be closed?
