### ISSUE TITLE
request.abort is not a function

### ISSUE THREAD

**Issue by e10jc** [tgriesser/knex#1709]
I occasionally see errors like this:

```
TypeError: request.abort is not a function
    at Object.abort (/usr/src/app/node_modules/knex/lib/client.js:285:17)
    at /usr/src/app/node_modules/knex/lib/runner.js:215:29
    at tryCatcher (/usr/src/app/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at /usr/src/app/node_modules/knex/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/usr/src/app/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/knex/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/src/app/node_modules/knex/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/src/app/node_modules/knex/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/src/app/node_modules/knex/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/usr/src/app/node_modules/knex/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/src/app/node_modules/knex/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/usr/src/app/node_modules/knex/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

I notice that the generic-pool library doesn't have an abort function, but the pool2 library did.

**Comment by tgriesser** [comment]
Should be fixed in 0.12.3
