### ISSUE TITLE
Issue Inserting JSON object into JSON type MySQL column

### ISSUE THREAD

**Issue by MarkHerhold** [tgriesser/knex#1727]
How do I go about inserting JSON data into a JSON-type field using MySQL? If I try adding a JSON object called `meta`, I get an error back. :disappointed: Is there a way to tell knex that this is a JSON object?

I am a new user to knex so I apologize if I am doing something dumb.

## Code
```js
const knex = require('knex')({
    client: 'mysql2',
    connection: {
        host: '127.0.0.1',
        user: 'root',
        database: 'test'
    }
});

const Account = knex('account');

Account.insert({
    id: 'account1',
    name: 'Account 1',
    meta: { created: '2016-10-08T20:32:02.983Z' }
}).then(function(data) {
    console.log(data);
}).error(function(err) {
    console.error(err.stack);
});
```

## Error Stack
```
Unhandled rejection Error: insert into `account` (`id`, `meta`, `name`) values ('account1', {"created":"2016-10-08T20:32:02.983Z"}, 'Account 1') - Unknown column 'created' in 'field list'
    at Packet.asError (/Users/Mark/projects/mysql-test/node_modules/mysql2/lib/packets/packet.js:666:13)
    at Query.Command.execute (/Users/Mark/projects/mysql-test/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/Users/Mark/projects/mysql-test/node_modules/mysql2/lib/connection.js:360:28)
    at PacketParser.onPacket (/Users/Mark/projects/mysql-test/node_modules/mysql2/lib/connection.js:87:66)
    at PacketParser.executeStart (/Users/Mark/projects/mysql-test/node_modules/mysql2/lib/packet_parser.js:45:12)
    at Socket.<anonymous> (/Users/Mark/projects/mysql-test/node_modules/mysql2/lib/connection.js:94:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

**Comment by niksubramanian** [comment]
Hi Mark,

Have you tried this?

> Note that when setting an array (or a value that could be an array) as the value of a json or jsonb column, you should use JSON.stringify() to convert your value to a string prior to passing it to the query builder, e.g.

```
knex.table('users')
.where({id: 1})
.update({json_data: JSON.stringify(mightBeAnArray)});
```

**Comment by ricardogama** [comment]
@MarkHerhold give [bookshelf-json-columns](https://github.com/seegno/bookshelf-json-columns) a try!

**Comment by MarkHerhold** [comment]
@ricardogama Cool! Will take a look! Is there any reason why this wouldn't be integrated into bookshelf itself? MySQL/Postgres are coming out with a lot of JSON features and we are in Node.js, so you would think JSON support would be integrated, no? 

@niksubramanian I actually just tried stringify, the problem is that I have to babysit all of the calls in and out of bookshelf, which is a major PITA. Going to look into @ricardogama's suggestion.

**Comment by felixmosh** [comment]
@MarkHerhold this will help you :]

```javascript
const db = require('knex')({
    client: 'mysql',
    connection: {
        host: 'localhost',
        user: 'mysql',
        password: 'mysql',
        database: 'mysql',
        typeCast: function(field, next) {
            if (field.type == 'TINY' && field.length == 1) {
                return (field.string() == '1'); // 1 = true, 0 = false
            } 
            return next();
        }
    }
});
```
