### ISSUE TITLE
Issue Selecting and Inserting Concurrently

### ISSUE THREAD

**Issue by MarkHerhold** [tgriesser/knex#1728]
I am running into an issue where MySQL reports that a document _is a duplicate_ if I attempt to insert the document while selecting all documents in the table. I find this to be very odd.

Because of the async nature of Node.js, I would think that I would be able to execute an insert and query at the same time. E.g. Two REST requests come in at the same time, one performing a select and the other performing an insert using a shared instance of knex.

I am a new user to knex so I apologize if I am doing something dumb.

## Code

```js
var knex = require('knex')({
    client: 'mysql2',
    connection: { host: '127.0.0.1', user: 'root', database: 'test' }
});

const Account = knex('account');

const num = 7; // <-- pick whatever number you want, the result is the same

// insert a new doc
const insert = Account.insert({
    id: 'account' + num,
    name: 'Account ' + num,
    meta: '{}'
});

// select everything
const select = Account.select();

// do both at the same time
Promise.all([insert, select]).then(function(data) {
    let [insertRes, selectRes] = data;
    console.log(insertRes);
    console.log(selectRes); 
}).catch(function(err) {
    console.error(err.stack);
});
```

## Error Stack

```
Error: insert into `account` (`id`, `meta`, `name`) values ('account7', '{}', 'Account 9') - Duplicate entry 'account7' for key 'PRIMARY'
    at Packet.asError (/Users/Mark/projects/mysql-test/node_modules/mysql2/lib/packets/packet.js:666:13)
    at Query.Command.execute (/Users/Mark/projects/mysql-test/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/Users/Mark/projects/mysql-test/node_modules/mysql2/lib/connection.js:360:28)
    at PacketParser.onPacket (/Users/Mark/projects/mysql-test/node_modules/mysql2/lib/connection.js:87:66)
    at PacketParser.executeStart (/Users/Mark/projects/mysql-test/node_modules/mysql2/lib/packet_parser.js:45:12)
    at Socket.<anonymous> (/Users/Mark/projects/mysql-test/node_modules/mysql2/lib/connection.js:94:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

**Comment by wubzz** [comment]
@MarkHerhold This is because you're using the same query builder for two very different queries. Basically you have one querybuilder assigned to both insert and select, which won't work, since the builder itself will consider both variables `insert` and `select` to be an insert query, ergo the duplicate key.

Instead, you should use two query builders since they are two different queries:
```javascript
const num = 7; // <-- pick whatever number you want, the result is the same

// insert a new doc
const insert = knex('account').insert({
    id: 'account' + num,
    name: 'Account ' + num,
    meta: '{}'
});

// select everything
const select = knex('account').select();
```

If I'm not making any sense to you right now, try adding `console.log` on `select.toString()` and `insert.toString()` after their declaration, as that should print what I'm trying to explain.

**Comment by MarkHerhold** [comment]
@wubzz Ok, that does make sense. How do I get a new instance of a query builder? I'm not seeing anything specific in the docs.

I tried this but still get the same result.
```js
const Account = function Account() {
    // return a new instance of the knex query builder
    return knex('account');
};

// insert a new doc
const insert = Account().insert({
    id: 'acc' + num,
    name: 'Account ' + num,
    meta: '{}'
});

// select everything
const select = Account().select();
```
