### ISSUE TITLE
Destroy connection does not work from Knex Version 0.12.3

### ISSUE THREAD

**Issue by kirrg001** [tgriesser/knex#1752]
Hey!👋

When destroying a connection, the node process does not shutdown.

```
var Promise = require('bluebird');
var knex = require('knex');
var connection = knex({
    "client": "mysql",
    "connection": {
        "host": "127.0.0.1",
        "user": "root",
        "password": "your-password",
        "database": "your_database"
    }
});

connection.raw('DROP DATABASE test;')
    .catch(function (err) {
        // CASE: database exists
        if (err.errno === 1049) {
            return Promise.resolve();
        }

        return Promise.reject(err);
    })
    .finally(function () {
        console.log('Dropping connection');
        return new Promise(function (resolve, reject) {
            connection.destroy(function (err, res) {
                if (err) {
                    return reject(err);
                }

                resolve();
            });
        });
    });
```

**Database: mysql**

**Works on `0.12.2`
Does not work from `0.12.3`.**

**Comment by elhigu** [comment]
How about latest knex? Does it work currently?

**Comment by kirrg001** [comment]
@elhigu does not work from `0.12.3`

**Comment by JulesAU** [comment]
I'm on `"0.13.0"` using Postgres and still it appears that destroy() does not reliable close the entire connection pool.

**Comment by elhigu** [comment]
@JulesAU `knex.destroy()` does graceful destroy, so it waits until running queries are ended and empties pool. Open new issue if you have an example where it doesn't work right with knex >= 0.14.2.

**Comment by elhigu** [comment]
I also tried the code from original post with 0.12.3 and 0.14.2 and with both knex versions process did exit immediately after error was thrown about non existing database.

knex 0.14.2:
```
Mikaels-MacBook-Pro-2:objection.js mikaelle$ time node test-destroy.js 
Dropping connection
Unhandled rejection Error: ER_DB_DROP_EXISTS: Can't drop database 'test'; database doesn't exist
    at Query.Sequence._packetToError (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
    --------------------
    at Protocol._enqueue (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/Connection.js:201:25)
    at /Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/lib/dialects/mysql/index.js:156:18
    at Promise._execute (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/lib/dialects/mysql/index.js:150:12)
    at Client_MySQL.query (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/lib/client.js:211:17)
    at Runner.<anonymous> (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/lib/runner.js:149:36)
    at Runner.tryCatcher (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/lib/runner.js:61:21
    at tryCatcher (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/node_modules/bluebird/js/release/promise_array.js:144:14)


real	0m0.402s
user	0m0.363s
sys	0m0.046s
Mikaels-MacBook-Pro-2:objection.js mikaelle$ 
```
