### ISSUE TITLE
Debugger message is way too long when the sql request crashes

### ISSUE THREAD

**Issue by radjivC** [tgriesser/knex#1765]
Hi,

I use Knex with Postgres and every time the sql request throw an error. I receive this huge message. I have increased the buffer of my terminal but it's still not very user friendly.
😭 

Cheers,

**Comment by elhigu** [comment]
Any example which debugger message are you talking about?

**Comment by radjivC** [comment]
``` [TypeError: Cannot read property 'created_at' of undefined]
error: unhandledRejection reason=Cannot read property 'created_at' of undefined, _bitField=136970240, _fulfillmentHandler0=undefined, _rejectionHandler0=undefined, _progressHandler0=undefined, _promise0=undefined, _receiver0=undefined, , Formatter=function Formatter_PG() {
  this.client = client;
  this.paramCount = 0;
  Formatter.apply(this, arguments);
}, Raw=function Raw_PG() {
  this.client = client;
  Raw.apply(this, arguments);
}, Transaction=function Transaction_PG() {
  this.client = client;
  Transaction.apply(this, arguments);
}, QueryBuilder=function QueryBuilder_PG() {
  this.client = client;
  QueryBuilder.apply(this, arguments);
  if (client.defaultReturning) {
    this._single.returning = client.defaultReturning;
  }
}, QueryCompiler=function QueryCompiler_PG() {
  this.formatter = new client.Formatter();
  QueryCompiler.apply(this, arguments);
}, tableName=knex_migrations, directory=db/migrations, directory=db/seeds, Runner=function Runner_PG() {
  this.client = client;
  Runner.apply(this, arguments);
}, host=localhost, user=dev, password=lol, database=progressclaim_development, Pool=function Pool_PG() {
  this.client = client;
  Pool.apply(this, arguments);
}, databaseName=progressclaim_development, $ref=$["promise"]["_boundTo"]["client"], min=2, max=10, create=function (callback) {
      pool.client.acquireRawConnection()
        .tap(function(connection) {
          connection.__cid = _.uniqueId('__cid');
          if (pool.config.afterCreate) {```
and a 1000 lines more 

the sql request can be a select, update, insert...
Every sql crash with knex do that debugger message

**Comment by elhigu** [comment]
I have never seen that, looks like you might be using winston to log errors and accidentally you are printing out some objects containing bunch of functions or something like that. Please add some steps to reproduce.

simple test prints reasonable amount of data:

```js
let knex = require('knex')({client: 'pg', connection: 'postgres:///knex_test'});
knex('foo').catch(e => console.dir(e));

{ error: select * from "foo" - relation "foo" does not exist
    at Connection.parseE (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
  name: 'error',
  length: 95,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '15',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1156',
  routine: 'parserOpenTable' }
```

**Comment by wubzz** [comment]
No activity in 1.5 years, closing.
