### ISSUE TITLE
Unhandled Exception in `connection.end()` for MySQL Dialect

### ISSUE THREAD

**Issue by I00000** [tgriesser/knex#1798]
Unfortunately, the fix for https://github.com/tgriesser/knex/issues/1691 does not work because the connection.end continues to crash my node. In my context, I use a pool of connections and I get a timeout from MySQL server due to network problems or server problems (e.g. DB restart). All of these events are considered fatal errors.

In my code, I have tried to catch them like that:
```javascript
pool: {
    min: 2,
    max: 7,
    afterCreate: function (connection, callback) {
        connection.on('error', function (err) {
            console.log('>>>>>>>>>>>>>>>>>>>>>>> err', err);
        });
        callback(null, connection);
    }
}
```
Unfortunately, my handler is never called due to the removeAllListeners call in destroyRawConnection:
```javascript
destroyRawConnection(connection) {
    connection.removeAllListeners()
    connection.end(() => {
        if (err) connection.__knex__disposed = err
    });
}
```
I tried the 2 different patches in destroyRawConnection:
```javascript
destroyRawConnection(connection) {
    connection.end(() => {
       connection.removeAllListeners()
        if (err) connection.__knex__disposed = err
    });
}
```
Unfortunately, this is one does not work but the following work well
```javascript
destroyRawConnection(connection) {
    connection.end(() => {
        if (err) connection.__knex__disposed = err
    });
}
```
For this one, I have changed a lit bit my handler
```javascript
pool: {
    min: 2,
    max: 7,
    afterCreate: function (connection, callback) {
        connection.on('error', function (err) {
           this.removeAllListeners();
            console.log('>>>>>>>>>>>>>>>>>>>>>>> err', err);
        });
        callback(null, connection);
    }
}
```
After some tests, everything seems OK.

**Comment by elhigu** [comment]
Hi, if you provide some kind of test code e.g. against `knex_test` database so I could try to reproduce the problem. @wubzz also knows a lot (more than me) about knex connection issues.

Maybe in that test you could emulate DB restart by killing all connections for example like this http://stackoverflow.com/questions/1903838/how-do-i-kill-all-the-processes-in-mysql-show-processlist

**Comment by I00000** [comment]
This code allows to reproduce the issue:

server.js
```javascript
'use strict';

var express = require('express');
var knex = require('knex');
var port = 7000;
// configuration ===============================================================
var db = knex({
    client: 'mysql2',
    connection: {
        debug: false,
        host: 'localhost',
        port: 3306,
        database: 'app',
        user: 'root',
        password: 'password'
    },
    pool: {
        min: 2,
        max: 7,
        idleTimeoutMillis: 3000,
        afterCreate: function (connection, callback) {
            console.log(' >>>>>>>>>>>>>>>>>>>>>>> afterCreate', connection.__knexUid);
            connection.on('error', function (err) {
                // the handler on one connection is sometime called several times
                // this.removeAllListeners();
                // https://github.com/tgriesser/knex/issues/1691
                console.log(' >>>>>>>>>>>>>>>>>>>>>>> err', this.__knexUid);
            });
            callback(null, connection);
        }
    },
    acquireConnectionTimeout: 3000
});
var table = 'users';

// launch ======================================================================
var webApp = express();
webApp.use(express.static('./'));
var server = webApp.listen(port, function () {
    console.log('App listening on port ' + server.address().port);
});

function accessDb() {
    setTimeout(function () {
        db(table).then(rows => {
            console.log(table + ' length:', rows.length);
        });
        accessDb();
    }, 5000);
}

accessDb();
```
package.json
```javascript
{
  "name": "bug",
  "description": "Bug knex",
  "version": "0.0.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/I00000/BUG/bug.git"
  },
  "license": "Apache-2.0",
  "dependencies": {
    "express": "4.14.0",
    "knex": "0.12.6",
    "mysql2": "1.1.2"
  }
}
```
when you restart mysql, you get the following errors:
```
users length: 0
 >>>>>>>>>>>>>>>>>>>>>>> afterCreate __knexUid5
 >>>>>>>>>>>>>>>>>>>>>>> afterCreate __knexUid6
Unhandled rejection Error: select * from `users` - Server shutdown in progress
    at Packet.asError (c:\Dev\BUG\node_modules\mysql2\lib\packets\packet.js:667:13)
    at Query.Command.execute (c:\Dev\BUG\node_modules\mysql2\lib\commands\command.js:29:22)
    at Connection.handlePacket (c:\Dev\BUG\node_modules\mysql2\lib\connection.js:417:28)
    at PacketParser.onPacket (c:\Dev\BUG\node_modules\mysql2\lib\connection.js:93:16)
    at PacketParser.executeStart (c:\Dev\BUG\node_modules\mysql2\lib\packet_parser.js:73:14)
    at Socket.<anonymous> (c:\Dev\BUG\node_modules\mysql2\lib\connection.js:101:29)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
 >>>>>>>>>>>>>>>>>>>>>>> err __knexUid6
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:284:12)
    at Connection.write (c:\Dev\BUG\node_modules\mysql2\lib\connection.js:224:15)
    at Connection.writePacket (c:\Dev\BUG\node_modules\mysql2\lib\connection.js:265:10)
    at Quit.start (c:\Dev\BUG\node_modules\mysql2\lib\commands\quit.js:21:14)
    at Quit.Command.execute (c:\Dev\BUG\node_modules\mysql2\lib\commands\command.js:39:20)
    at Connection.handlePacket (c:\Dev\BUG\node_modules\mysql2\lib\connection.js:417:28)
    at Connection.addCommand (c:\Dev\BUG\node_modules\mysql2\lib\connection.js:440:10)
    at Connection.end (c:\Dev\BUG\node_modules\mysql2\lib\connection.js:804:22)
    at Client_MySQL2.destroyRawConnection (c:\Dev\BUG\node_modules\knex\lib\dialects\mysql\index.js:121:16)
    at Object.destroy (c:\Dev\BUG\node_modules\knex\lib\client.js:244:18)
    at Pool.destroy (c:\Dev\BUG\node_modules\knex\node_modules\generic-pool\lib\generic-pool.js:193:17)
    at Array.forEach (native)
    at Pool.removeIdle [as _removeIdle] (c:\Dev\BUG\node_modules\knex\node_modules\generic-pool\lib\generic-pool.js:224:12)
    at null._onTimeout (c:\Dev\BUG\node_modules\knex\node_modules\generic-pool\lib\generic-pool.js:249:12)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by elhigu** [comment]
I just kill my local mysql and get following errors in the end:
```
 >>>>>>>>>>>>>>>>>>>>>>> afterCreate __knexUid8
 >>>>>>>>>>>>>>>>>>>>>>> afterCreate __knexUid9
 >>>>>>>>>>>>>>>>>>>>>>> err __knexUid8
 >>>>>>>>>>>>>>>>>>>>>>> err __knexUid9
Knex:warning - Connection Error: Error: Connection lost: The server closed the connection.
```

but yeah, node crashes with `Error: This socket has been ended by the other party`. Those socket errors are usually pretty hard to catch... maybe mysql driver has some event handler for that... sorry for not being able to look into this more right now.

**Comment by I00000** [comment]
```javascript
destroyRawConnection(connection) {
    connection.removeAllListeners() // You cannot catch it because of that removeAllListeners. I did some tests by removing this line and everything seems OK
    connection.end(() => {
        if (err) connection.__knex__disposed = err
    });
}
```

**Comment by novemberborn** [comment]
I think the problem is that `mysql2` transitions connections to a broken state, and the dialect in Knex does not recognize this. #2175 seems to fix it for me.

**Comment by mercmobily** [comment]
Thank you for reporting this issue about unhandled errors when MySQL restarts whilst using the mysql2 driver.

When MySQL server restarted or connections were forcibly closed, applications would crash with:
```
Error: This socket has been ended by the other party
```

This happened because `destroyRawConnection()` was calling `connection.removeAllListeners()` BEFORE `connection.end()`, preventing error handlers from catching socket errors during cleanup.

**The Fix**

This issue was **fixed in 2019** (commit 03ecbeef1) by deferring the `removeAllListeners()` call:

```javascript
// Current implementation (fixed)
async destroyRawConnection(connection) {
  try {
    const end = promisify((cb) => connection.end(cb));
    return await end();
  } catch (err) {
    connection.__knex__disposed = err;
  } finally {
    // removeAllListeners is now deferred until after end() completes
    defer(() => connection.removeAllListeners());
  }
}
```

The `defer()` (from lodash) ensures listeners remain active during the connection.end() process, allowing proper error handling. (Yes, we will need to eradicate lodash at some point...)

**PR #2175 - A Different Issue**

PR #2175 attempted to address a related but different problem: improving `validateConnection()` to better detect broken connections before use. It proposed checking `connection._fatalError` to identify connections that had encountered fatal errors. This PR was closed without merging because:

1. The contributor couldn't continue the work
2. It relied on private mysql2 APIs (`_fatalError`)
3. The mysql2 maintainer never provided a public API for this

**Current State**

**The crash bug is FIXED**: Applications no longer crash when MySQL connections fail during cleanup.

**What remains**: Knex still uses private mysql2 properties for connection validation:
```javascript
validateConnection(connection) {
  return (
    connection &&
    !connection._fatalError &&      // Private API
    !connection._protocolError &&   // Private API
    !connection._closing &&         // Private API
    !connection.stream.destroyed
  );
}
```

This is suboptimal but not critical - it means:
- Connection validation might miss some edge cases
- The implementation could break if mysql2 changes internals
- But it doesn't cause crashes - just potentially reuses bad connections

**Why This Matters Less Now**

Modern connection pooling and error handling improvements mean:
- Bad connections are generally detected and replaced
- Retry logic handles transient failures
- The pool validates connections before use (when configured)

**Recommendations**

For users still concerned about connection reliability:
1. Enable connection validation: `pool: { validateOnBorrow: true }`
2. Implement application-level retry logic
3. Consider using the original `mysql` driver if stability is more important than performance

The critical crash bug has been resolved. The remaining issue about using private APIs for validation is a technical debt issue rather than a functional problem.

**Related issues:**
- #3483 - PR that fixed the removeAllListeners issue
- #2175 - Attempted PR for better connection validation
- #1691 - Original connection error handling issues
- #2589 - Connection lifecycle management improvements
