### ISSUE TITLE
SchemaBuilder requiring a connection when one is not set, specifically when inside mocha unit tests

### ISSUE THREAD

**Issue by Verikon** [tgriesser/knex#1803]
consider:

```
import { assert } from 'chai';
import knex from 'knex';
import pg from 'pg';

var Knex = knex({ client: 'pg' });

describe( 'Tests knex schemabuilder', () => {

  it( 'produces a create table string using callback method', function( done ) {

      Knex.schema.createTable( 'test_table', function( d ){
        console.log( d.toString() );
        done();
      })
  })

  it( 'produces a create table string using promise method', function( done ) {

      Knex.schema.createTable( 'test_table' )
        .then( ( d ) => {
          console.log( d.toString() );
          done();
        });
  })

});
```

- in the first test, the callback is never fired
- in the second test, the promise resolves with a connection error;
```
Unhandled rejection Error: Unable to acquire a connection
    at E:\enterra\projects\auth-service\node_modules\knex\lib\client.js:274:25
```

Knex is configured to operate in a connectionless mode.

> You can even use knex without a connection, just for its query building features. Just pass in an empty object when initializing the library. Specify a client if you are interested in a particular flavour of SQL.
- http://knexjs.org/#Installation-client

**Comment by wubzz** [comment]
@Verikon In the first example the callback is never fired because it is not followed by a `.then` / `.asCallback` / `.toString()` / `.toSQL()` call. That code basically just tells the builder that you're "eventually going to use this callback in compilation".

In the second example, you trigger a compilation and run of the builder by calling `.then`. Calling `.then` will trigger an attempt of acquiring a connection as Knex sees this as a query that should be run. If all you dont want the query to actually be run, then you should use `.toString()` / `.toSQL()`.

Does this clear anything up?

**Comment by calebeaires** [comment]
I had the same problem when event if I am using ``.toString()`` / ``.toSQL()``. Here is my example:

**Using Angular 2**;

1. Import it
``import * as Knex from 'knex';``

2. Set it
``knex = Knex({});``

3. Trie to make an SQL string
```
this.knex.schema.createTable(this.database, function (table) {
      table.increments();
      data.forEach(function (value, key) {
        table.specificType(value.name, value.column_type)
      });
    }).toString();
```

4. Get this error
```
error_handler.js:53 TypeError: Cannot read property 'length' of undefined
    at ColumnCompiler.getModifiers (http://localhost:4200/main.bundle.js:65879:39)
    at ColumnCompiler.compileColumn (http://localhost:4200/main.bundle.js:65857:88)
    at ColumnCompiler.toSQL (http://localhost:4200/main.bundle.js:65848:23)
    at http://localhost:4200/main.bundle.js:66213:65
    at Array.map (native)
    at TableCompiler.getColumns (http://localhost:4200/main.bundle.js:66212:18)
    at TableCompiler.create (http://localhost:4200/main.bundle.js:66126:22)
    at TableCompiler.toSQL (http://localhost:4200/main.bundle.js:66112:20)
    at TableBuilder.toSQL (http://localhost:4200/main.bundle.js:98448:42)
    at SchemaCompiler.createTable (http://localhost:4200/main.bundle.js:66024:23)
    at SchemaCompiler.toSQL (http://localhost:4200/main.bundle.js:66013:26)
    at SchemaBuilder.toSQL (http://localhost:4200/main.bundle.js:98256:43)
    at SchemaBuilder.Target.toQuery (http://localhost:4200/main.bundle.js:42016:21)
    at SchemaBuilder.toString (http://localhost:4200/main.bundle.js:98252:15)
```

**Comment by wubzz** [comment]
@calebeaires That's because you don't provide a dialect. Yes you can use Knex for its query building purposes only - But! It still needs to know if you're trying to compile for postgres, mysql, oracle, etc. Provide a `client` and it shall work.

**Comment by elhigu** [comment]
@Verikon you shouldn't try to resolve promises because then knex will try to send queries to DB, you just need to tell to query builder to give you either single string, where bindings are already interpolated or to request templated SQL and bindings separately.

```js
knex = require('knex')({client: 'pg'});

> knex.schema.createTable('users', function (table) { 
    table.increments(); 
    console.log("Foo"); 
    table.string('name'); 
  }).toString();
Foo
'create table "users" ("id" serial primary key, "name" varchar(255))'

> knex.schema.createTable('users', function (table) { 
    table.increments(); 
    console.log("Foo"); 
    table.string('name'); 
  }).toSQL();
Foo
[ { sql: 'create table "users" ("id" serial primary key, "name" varchar(255))',
    bindings: [] } ]
```

**Comment by calebeaires** [comment]
Using:
- Angular 2
- Angular CLI
- [@types/knex](https://www.npmjs.com/package/@types/knex)

If have tried this both approach:



```node
var Knex = require('knex')({client: 'mysql'});
//...

```
and/or
```typescript
import * as Knex from 'knex';
//...
this.client = 'mysql'
this.knex = Knex({ client: this.client });
```

```jconsole
index.js:55Uncaught Error: Cannot find module "./dialects"(…)webpackMissingModule
@ index.js:55Knex @ index.js:55(anonymous function) 
@ table-build.component.ts:4__webpack_require__ 
@ bootstrap 147eba1…:52(anonymous function) 
@ split.module.ts:16__webpack_require__ 
@ bootstrap 147eba1…:52(anonymous function) 
@ app.module.ts:37__webpack_require__ 
@ bootstrap 147eba1…:52(anonymous function) 
@ main.bundle.js:140183__webpack_require__
@ bootstrap 147eba1…:52(anonymous function) 
@ main.bundle.js:140168__webpack_require__ 
@ bootstrap 147eba1…:52webpackJsonpCallback 
@ bootstrap 147eba1…:23(anonymous function) 
@ main.bundle.js:1
```

**Comment by Verikon** [comment]
@elhigu , @wubzz ; that works, thank you very much :) 

Great library and thank you for your time and effort.

@calebeaires : Looks more like a webpack issue than a knex issue? One thing i can see there is that Knex exports a sing function so;

`import * as Knex from 'knex';`

is more succinctly expressed with

`import Knex from 'knex';`

**Comment by calebeaires** [comment]
@Verikon I have tried it (``import Knex from 'knex';``), but I head no success. 

**Error**
``@types/knex/index"' has no default export``

**Comment by Verikon** [comment]
@calebeaires , how are you installing this?

`npm install knex` ?

**Comment by Verikon** [comment]
I notice that package.json indicated ./knex.js as main. That file requires './lib/index' which does not exist in source. Do you have ./lib in your installation?

**Comment by calebeaires** [comment]
Yes, it is located on 

```
-node_modules
 -knex
  -knex.js
  -lib
   -index.js
   -dialects
(....)
```

**Comment by calebeaires** [comment]
I have opened the discussion here so Angular 2 community may go along with it. Maybe you could subscribe to it!

👍  Thanks folks!
