### ISSUE TITLE
TypeError: _this.client._formatQuery is not a function

### ISSUE THREAD

**Issue by batwood001** [tgriesser/knex#1808]
```
TypeError: _this.client._formatQuery is not a function
    at /Users/path-to-project/node_modules/knex/lib/interface.js:31:27
    at arrayMap (/Users/path-to-project/node_modules/knex/node_modules/lodash/_arrayMap.js:16:21)
    at map (/Users/path-to-project/node_modules/knex/node_modules/lodash/map.js:50:10)
    at Raw.Target.toQuery (/Users/path-to-project/node_modules/knex/lib/interface.js:28:30)
    at ColumnCompiler_PG.ColumnCompiler.defaultTo (/Users/path-to-project/node_modules/knex/lib/schema/columncompiler.js:155:19)
    at ColumnCompiler_PG.ColumnCompiler.getModifiers (/Users/path-to-project/node_modules/knex/lib/schema/columncompiler.js:99:34)
    at ColumnCompiler_PG.ColumnCompiler.compileColumn (/Users/path-to-project/node_modules/knex/lib/schema/columncompiler.js:74:88)
    at ColumnCompiler_PG.ColumnCompiler.toSQL (/Users/path-to-project/node_modules/knex/lib/schema/columncompiler.js:65:23)
    at /Users/path-to-project/node_modules/knex/lib/schema/tablecompiler.js:170:65
    at Array.map (native)
    at TableCompiler_PG.TableCompiler.getColumns (/Users/path-to-project/node_modules/knex/lib/schema/tablecompiler.js:169:18)
    at TableCompiler_PG.TableCompiler.create (/Users/path-to-project/node_modules/knex/lib/schema/tablecompiler.js:83:22)
    at TableCompiler_PG.TableCompiler.toSQL (/Users/path-to-project/node_modules/knex/lib/schema/tablecompiler.js:69:20)
    at TableBuilder.toSQL (/Users/path-to-project/node_modules/knex/lib/schema/tablebuilder.js:72:42)
    at SchemaCompiler_PG.createTable (/Users/path-to-project/node_modules/knex/lib/schema/compiler.js:62:23)
    at SchemaCompiler_PG.toSQL (/Users/path-to-project/node_modules/knex/lib/schema/compiler.js:51:26)
```

getting this error in 0.12.6 when running `migrate:latest`. Any suggestions?

**Comment by wubzz** [comment]
If this is still an issue then please reopen with code sample to reproduce the issue.
