### ISSUE TITLE
Syntax error when attempting `knex migrate:latest'

### ISSUE THREAD

**Issue by Circlepuller** [tgriesser/knex#1823]
So I get this error when attempting the command specified in the title. It happens even if the migration file is unmodified from when it was created. In this case I tried creating a table named 'posts' with just timestamp fields. Here's all the information I could get that would likely be useful:

```
➜  server-ts cat knexfile.js 
// Update with your config settings.

module.exports = {

  development: {
    client: 'sqlite3',
    connection: {
      filename: './dev.sqlite3'
    }
  },

  staging: {
    client: 'postgresql',
    connection: {
      database: 'my_db',
      user:     'username',
      password: 'password'
    },
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'knex_migrations'
    }
  },

  production: {
    client: 'postgresql',
    connection: {
      database: 'my_db',
      user:     'username',
      password: 'password'
    },
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'knex_migrations'
    }
  }

};
➜  server-ts ls migrations && cat migrations/20161208001928_setup.js 
20161208001928_setup.js
module.exports = {
  up: function(knex, Promise) {
    return Promise.all([
      knex.schema.createTableIfNotExists('posts', function(table) {
        table.timestamps();
      });
    ]);
  },
  down: function(knex, Promise) {
    return Promise.all([
      knex.schema.dropTable('posts');
    ]);
  }
};
➜  server-ts knex migrate:latest                                    
Using environment: development
Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
Knex:warning - migrations failed with error: Unexpected token ;
SyntaxError: Unexpected token ;
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Migrator._validateMigrationStructure (/home/circlepuller/Node/fusen/server-ts/node_modules/knex/lib/migrate/index.js:275:21)
    at wrapper (/home/circlepuller/Node/fusen/server-ts/node_modules/lodash/lodash.js:4994:19)
    at arrayMap (/home/circlepuller/Node/fusen/server-ts/node_modules/lodash/lodash.js:660:23)
    at Function.map (/home/circlepuller/Node/fusen/server-ts/node_modules/lodash/lodash.js:9556:14)
    at /home/circlepuller/Node/fusen/server-ts/node_modules/knex/lib/migrate/index.js:242:47
    at tryCatcher (/home/circlepuller/Node/fusen/server-ts/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/circlepuller/Node/fusen/server-ts/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/circlepuller/Node/fusen/server-ts/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/circlepuller/Node/fusen/server-ts/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/circlepuller/Node/fusen/server-ts/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/circlepuller/Node/fusen/server-ts/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/circlepuller/Node/fusen/server-ts/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/circlepuller/Node/fusen/server-ts/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by elhigu** [comment]
Do you have any other files in migration directory which could cause require to fail to syntax error?

**Comment by luismasserral** [comment]
This is happening to me too, and answering the @elhigu question, I have no other files in the migrations folder. I have tried same code as @Circlepuller and my own code, and even other tutorials code, and everytime I run the migrate command I get the same error:

```
$ knex migrate:latest --env=development
Using environment: development
Knex:warning - migrations failed with error: Unexpected token ;
SyntaxError: Unexpected token ;
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Migrator._validateMigrationStructure (C:\Users\extmali\Code\Testing\treinny\server\node_modules\knex\lib\migrate\index.js:339:21)
    at wrapper (C:\Users\extmali\Code\Testing\treinny\server\node_modules\lodash\_createBaseWrapper.js:24:15)
    at arrayMap (C:\Users\extmali\Code\Testing\treinny\server\node_modules\lodash\_arrayMap.js:16:21)
    at map (C:\Users\extmali\Code\Testing\treinny\server\node_modules\lodash\map.js:51:10)
    at C:\Users\extmali\Code\Testing\treinny\server\node_modules\knex\lib\migrate\index.js:305:55
    at tryCatcher (C:\Users\extmali\Code\Testing\treinny\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\extmali\Code\Testing\treinny\server\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\extmali\Code\Testing\treinny\server\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\extmali\Code\Testing\treinny\server\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\extmali\Code\Testing\treinny\server\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\extmali\Code\Testing\treinny\server\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\extmali\Code\Testing\treinny\server\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\extmali\Code\Testing\treinny\server\node_modules\bluebird\js\release\async.js:17:14)
```

This is my migration file `20161223101840_v1.0.0.js`

```
exports.up = function (knex, Promise) {
    return Promise.all([
        knex.schema.createTable('users', function (table) {
            table.increments('id').primary();
            table.string('email').unique();
            table.string('username').unique();
            table.string('password');
            table.string('first_name');
            table.string('last_name');
            table.string('gender');
            table.timestamps();
        });
    ]);
};

exports.down = function (knex, Promise) {
    return Promise.all([
        knex.schema.dropTable('users');
    ]);
};
```

I'm running Windows 10 with this versions of node & npm:

```
$ node -v
v4.6.1
$ npm -v
3.10.9
```

**Comment by luismasserral** [comment]
Found the solution, and it's really weird!

If I remove the `;` character in the `knex` statement, it works! I can't find out why it fails when you end that line with a `;`, but it's working. This is my working code:

```
exports.up = function (knex, Promise) {
    return Promise.all([
        knex.schema.createTable('users', function (table) {
            table.increments('id').primary();
            table.string('email').unique();
            table.string('username').unique();
            table.string('password');
            table.string('first_name');
            table.string('last_name');
            table.string('gender');
            table.timestamps();
        })
    ]);
};

exports.down = function (knex, Promise) {
    return Promise.all([
        knex.schema.dropTable('users')
    ]);
};
```

**Comment by luismasserral** [comment]
Ok, now I know what's going on here... OMG I can't believe I didn't see before... u_U

@Circlepuller you and I are making the same mistake, when we use the `Promise.all` function, we pass an array as a parameter, and this array only has one item, the `knex.schema.createTable` statement. So, we don't have to use any `;` character, it's an array hehe! 👍

**Comment by Circlepuller** [comment]
Sorry for the late response. Yeah, it was a simple syntax error on our part. Running the node executable by itself on the file pinpoints the issue and I wish knex would do that itself, haha.
