### ISSUE TITLE
mysql Unhandled 'error' event on Unknown column 'xx' in 'field list'

### ISSUE THREAD

**Issue by id0Sch** [tgriesser/knex#1852]
Hi,
when a bad query is ran when using streams I could not catch the error and the program crashes
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Unknown column 'datea' in 'field list'
```
``` javascript
const query = db.query(parsedQuery);
logger.trace(query.toString());

const stream = query
    .stream()
    .pipe(CsvParser.transform(format === 'csv'))
     .on('error', (err) => {
           console.log(err);
     })

if (debug === 'true') {
    console.log('debug');
    this.set('x-query', query.toString());
}
this.body = stream;
```

please assist :(

**Comment by elhigu** [comment]
Please add single file test case to reproduce your error.

**Comment by id0Sch** [comment]
``` javascript
const Knex = require('knex');
let knex = Knex({
    client: 'mysql',
    connection: {
        user: 'root',
        password: 'root',
        database: 'database',
        host: 'localhost'
    },
});
const INVALID_COLUMN_NAME = 'date'
const TABLE_NAME='table'
let stream = knex(TABLE_NAME).select(INVALID_COLUMN_NAME).limit(5).stream();

stream
    .on('error', function (err) {
        console.log(err); // never called
    })
    .on('data', function (data) {
        console.log(data);
    })
```

is that what you meant?

**Comment by elhigu** [comment]
Thanks, I was able to reproduce this one.

```sh
Mikaels-MacBook-Pro-2: mikaelle$ node test
/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/protocol/Parser.js:77
        throw err; // Rethrow non-MySQL errors
        ^

Error: ER_NO_SUCH_TABLE: Table 'knex_test.table' doesn't exist
    at Query.Sequence._packetToError (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
    --------------------
    at Protocol._enqueue (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/mysql/lib/Connection.js:201:25)
    at /Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/lib/dialects/mysql/index.js:137:18
    at Promise._execute (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/bluebird/js/release/promise.js:77:14)
    at Client_MySQL._stream (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/lib/dialects/mysql/index.js:134:12)
    at Client_MySQL.stream (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/lib/client.js:201:17)
    at /Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/knex/lib/runner.js:110:28
    at tryCatcher (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/mikaelle/Projects/Vincit/yessql/objection.js/node_modules/bluebird/js/release/promise.js:691:18)
```

I tried to add catching to mysql dialect's stream function, but it didn't help... also code in mysql driver where error is throws did look a bit strange.

```js
Parser.prototype.write = function(buffer) {
  this.append(buffer);

  while (!this._paused) {
    if (!this._packetHeader) {
      if (this._bytesRemaining() < 4) {
        break;
      }

      this._packetHeader = new PacketHeader(
        this.parseUnsignedNumber(3),
        this.parseUnsignedNumber(1)
      );

      if (this._packetHeader.number !== this._nextPacketNumber) {
        var err = new Error(
          'Packets out of order. Got: ' + this._packetHeader.number + ' ' +
          'Expected: ' + this._nextPacketNumber
        );

        err.code  = 'PROTOCOL_PACKETS_OUT_OF_ORDER';
        err.fatal = true;

        this._onError(err);
      }

      this.incrementPacketNumber();
    }

    if (this._bytesRemaining() < this._packetHeader.length) {
      break;
    }

    this._packetEnd    = this._offset + this._packetHeader.length;
    this._packetOffset = this._offset;

    if (this._packetHeader.length === MAX_PACKET_LENGTH) {
      this._longPacketBuffers.push(this._buffer.slice(this._packetOffset, this._packetEnd));

      this._advanceToNextPacket();
      continue;
    }

    this._combineLongPacketBuffers();

    // Try...finally to ensure exception safety. Unfortunately this is costing
    // us up to ~10% performance in some benchmarks.
    var hadException = true;
    try {
      this._onPacket(this._packetHeader);
      hadException = false;
    } catch (err) {
      if (!err || typeof err.code !== 'string' || err.code.substr(0, 7) !== 'PARSER_') {
        throw err; // Rethrow non-MySQL errors THIS IS WHERE UNCATCHABLE ERROR IS THROWN
      }

      // Pass down parser errors
      this._onError(err);
      hadException = false;
    } finally {
      this._advanceToNextPacket();

      // If we had an exception, the parser while loop will be broken out
      // of after the finally block. So we need to make sure to re-enter it
      // to continue parsing any bytes that may already have been received.
      if (hadException) {
        process.nextTick(this.write.bind(this));
      }
    }
  }
};
```

Maybe you could open issue to mysql driver's github to check if they know how to catch that?

**Comment by id0Sch** [comment]
I also tracked it down to the mysql code, but when I used the knex promise syntax the `.on('error'...` works. so it kinda makes me wonder.
i'll try opening an issue for mysql as well and will let you know, thanks!

**Comment by id0Sch** [comment]
@elhigu i just created this:
``` javascript
const mysql = require('mysql');

var connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: 'root',
    database: 'xxx',
});

connection.connect();
connection.query('SELECT date from xxx.xxx') // there's no date column
    .on('error', (err) => {
        console.log('here');
    });
```
and the error is caught, so it must be something that knex is doing wrong.
thoughts?

**Comment by elhigu** [comment]
Maybe mysql needs to register that error handler for each query separately... currently `.on('error')`is registered only globally to stream:

https://github.com/tgriesser/knex/blob/master/src/dialects/mysql/index.js#L98

Test + fix for this situation would be great to have!

**Comment by rubengmurray** [comment]
Tested in `3.1.0`. `console.log(err, 'my err')` is now called

<img width="457" height="112" alt="Image" src="https://github.com/user-attachments/assets/094b425a-30a0-4d12-919e-9ee5675e510e" />

<img width="480" height="145" alt="Image" src="https://github.com/user-attachments/assets/e27b0545-668f-4db1-bea3-d6a261632826" />

**Comment by mercmobily** [comment]
This is resolved and the issue is now closed. @rubengmurray
