### ISSUE TITLE
raw query error binding

### ISSUE THREAD

**Issue by Maxim-Chugaev** [tgriesser/knex#1861]
```javascript
knex.raw('CREATE TABLE IF NOT EXISTS ? AS SELECT * FROM stats WITH NO DATA', ['somebinding'])
```

return error 
```javascript
error: syntax error at or near "$1"
```

but in query object i have 
``` javascript
sql: 'CREATE TABLE IF NOT EXISTS ? AS SELECT * FROM stats WITH NO DATA',
bindings: [ 'somebinding' ],
```
whats wrong?

**Comment by coockoo** [comment]
```js
console.log(knex.raw('CREATE TABLE IF NOT EXISTS ? AS SELECT * FROM stats WITH NO DATA', ['somebinding']).toString());
```
gives me this
```sql
CREATE TABLE IF NOT EXISTS 'somebinding' AS SELECT * FROM stats WITH NO DATA
```

I thing the problem is in quotes. `knex` parse them as string and bind to query with single quotes. (Expression must be without them)

**Comment by coockoo** [comment]
Ok, i found this
Try to use this

> Positional bindings ? are interpreted as values and ?? are interpreted as identifiers.

```js
knex.raw('CREATE TABLE IF NOT EXISTS ?? AS SELECT * FROM stats WITH NO DATA', ['somebinding'])
```

**Comment by elhigu** [comment]
@coockoo is right, in this case problem was only that you actually should have pass value as identifier with `??`

There are also some other places in postgresql syntax where value bindings cannot be used for example:

```js
knex.raw(`SELECT EXTRACT(MONTH FROM INTERVAL ?)`, ['2 years 3 months'])
  .then(res => console.log(res));

> Unhandled rejection error: SELECT EXTRACT(MONTH FROM INTERVAL $1) - syntax error at or near "$1"
    at Connection.parseE (/Users/mikaelle/Projects/Vincit/yessql/superoperator-backend/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/mikaelle/Projects/Vincit/yessql/superoperator-backend/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/mikaelle/Projects/Vincit/yessql/superoperator-backend/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)

```

In those cases you just have to write the query without bindings:

```js
knex.raw(`SELECT EXTRACT(MONTH FROM INTERVAL '2 years 3 months')`)
  .then(res => console.log(res));
```

and use validated input strings to prevent sql injection.

**Comment by Maxim-Chugaev** [comment]
sorry, i don't understand this behaviour. Its normal?
```javascript
knex.raw('ALTER TABLE IF EXISTS ?? ADD CONSTRAINT partition_check CHECK (created_at >= ? AND created_at < ?)', [tableName, currentDate, nextDate]);

 error: bind message supplies 2 parameters, but prepared statement "" requires 0
 at Connection.parseE (/Users/maksim/Documents/rotator/node_modules/pg/lib/connection.js:554:11)
at Connection.parseMessage (/Users/maksim/Documents/rotator/node_modules/pg/lib/connection.js:381:17)
at Socket.<anonymous> (/Users/maksim/Documents/rotator/node_modules/pg/lib/connection.js:117:22)
at emitOne (events.js:96:13)
 at Socket.emit (events.js:188:7)
 at readableAddChunk (_stream_readable.js:176:18)
 at Socket.Readable.push (_stream_readable.js:134:10)
 at TCP.onread (net.js:551:20)
```

**Comment by coockoo** [comment]
@Maxim-Chugaev
I guess not. Tried to reproduce on local machine and got the same result.
What's interesting is that `console.log(builder.toString());` gives normal output. Looks like a bug or I don't understand something neither.

**Comment by elhigu** [comment]
@coockoo @Maxim-Chugaev Sounds like exactly one of those cases (which I mentioned in comment above) where one cannot use value bindings because postgresql database (not about knex, and not even about node-pg driver) doesn't support using bindings there.

So this should work instead:

```js
knex.raw(`ALTER TABLE IF EXISTS ?? ADD CONSTRAINT partition_check CHECK (created_at >= '${currentDate.toISOString()}' AND created_at < '${nextDate.toISOString()}')`, [tableName]);

```

**Comment by Maxim-Chugaev** [comment]
@elhigu yes, I did just that. Many thanks!
