### ISSUE TITLE
knex with aws xray

### ISSUE THREAD

**Issue by nabilnathani10** [tgriesser/knex#1882]
aws xray sdk monkey patches the postgres module to capture postgress calls and capture metrics.

http://docs.aws.amazon.com/xray-sdk-for-nodejs/latest/reference/

I am trying to pass the aws sdk's monkey-patched postgres connection to knex using the .connection(dbConnection) feature as mentioned in the documentation. But it is not working. 

Will there be support for passing in your own db connection? OR will there be support for xray?

**Comment by RickDT** [comment]
Simply capturing Postgres within the context where you setup your knex object seems to work. See my code below and the X-Ray screen showing a few queries that are run in a Lambda function.

```
const knex = require("knex");
const AWSXRay = require("aws-xray-sdk");
const pg = AWSXRay.capturePostgres(require("pg"));

module.exports = () => {
  const connection = {
    host: process.env.PG_HOST,
    user: process.env.PG_USER,
    password: process.env.PG_PASSWORD,
    database: process.env.PG_DB
  };

  const db = knex({
    client: "pg",
    connection,
    pool: { min: 1, max: 1 }
  });

  return db;
};
```

<img width="868" alt="screen shot 2017-05-05 at 3 35 29 pm" src="https://cloud.githubusercontent.com/assets/179257/25761409/b2e209da-31a8-11e7-95fc-8afc32b287b3.png">

**Comment by justingshreve** [comment]
@RickDT I'm following your example to get knex working with x-ray, but running into:

```
Unhandled rejection Error: Failed to get the current sub/segment from the context.
    at Object.contextMissing (/home/project/node_modules/aws-xray-sdk-core/lib/context_utils.js:34:13)
    at Object.getSegment (/home/project/node_modules/aws-xray-sdk-core/lib/context_utils.js:96:45)
    at Object.resolveSegment (/home/project/node_modules/aws-xray-sdk-core/lib/context_utils.js:77:19)
    at Client.captureQuery [as query] (/home/project/node_modules/aws-xray-sdk-postgres/lib/postgres_p.js:31:26)
    at /home/project/node_modules/knex/lib/dialects/postgres/index.js:180:18
    at Client_PG.checkVersion (/home/project/node_modules/knex/lib/dialects/postgres/index.js:179:12)
    at /home/project/node_modules/knex/lib/dialects/postgres/index.js:156:25
    at Connection.<anonymous> (/home/project/node_modules/pg/lib/client.js:159:7)
    at Connection.g (events.js:291:16)
    at emitOne (events.js:101:20)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (/home/project/node_modules/pg/lib/connection.js:136:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread [as _originalOnread] (net.js:551:20)
    at TCP.onread (/home/project/node_modules/async-listener/glue.js:188:31)
```
Any thoughts? Also, in your example, doesn't look like you're passing the overridden `const pg = AWSXRay.capturePostgres(require("pg"))` into knex at all. Isn't that necessary? Thanks!

**Comment by RickDT** [comment]
@justingshreve based on your error, I'm guessing you get that when you run locally? If so, you'll need to set an ENV var on your local machine: `AWS_XRAY_CONTEXT_MISSING=LOG_ERROR`. Obviously, you don't want to set that when running in Lambda.

Passing the overridden pg into knex is not necessary in my experience. I believe Knex pulls from the local context. (I may be wrong, but I am getting pg traces in Xray as seen in my screenshot).

**Comment by justingshreve** [comment]
Yes, `AWS_XRAY_CONTEXT_MISSING=LOG_ERROR` fixed the error running locally. I wanted to at least see tests run smooth before deploying. Thanks!

**Comment by ferarnoled** [comment]
I'm still having trouble setting this up. Btw, I'm running this in an EC2 instance, not locally.

`Unhandled rejection Error: Failed to get the current sub/segment from the context.
    at Object.contextMissingRuntimeError [as contextMissing] (/home/ec2-user/outpatient/op-server-xray/node_modules/aws-xray-sdk-core/lib/context_utils.js:21:15)
    at Object.getSegment (/home/ec2-user/outpatient/op-server-xray/node_modules/aws-xray-sdk-core/lib/context_utils.js:92:45)
    at Object.resolveSegment (/home/ec2-user/outpatient/op-server-xray/node_modules/aws-xray-sdk-core/lib/context_utils.js:73:19)
    at Client.captureQuery [as query] (/home/ec2-user/outpatient/op-server-xray/node_modules/aws-xray-sdk-postgres/lib/postgres_p.js:31:26)
    at /home/ec2-user/outpatient/op-server-xray/node_modules/knex/lib/dialects/postgres/index.js:126:18
    at Promise._execute (/home/ec2-user/outpatient/op-server-xray/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/ec2-user/outpatient/op-server-xray/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/ec2-user/outpatient/op-server-xray/node_modules/bluebird/js/release/promise.js:79:10)
    at Client.checkVersion (/home/ec2-user/outpatient/op-server-xray/node_modules/knex/lib/dialects/postgres/index.js:125:12)
    at /home/ec2-user/outpatient/op-server-xray/node_modules/knex/lib/dialects/postgres/index.js:103:25
    at Connection.<anonymous> (/home/ec2-user/outpatient/op-server-xray/node_modules/pg/lib/client.js:158:7)
    at Connection.g (events.js:291:16)
    at emitOne (events.js:101:20)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (/home/ec2-user/outpatient/op-server-xray/node_modules/pg/lib/connection.js:121:12)
    at emitOne (events.js:96:13)`

_connection.js_
`const environment = process.env.NODE_ENV;
const config = require('./../../../knexfile.js')[environment];
const knex = require('knex')(config);

const AWSXRay = require('aws-xray-sdk');
let pg;

if (process.env.NODE_ENV !== 'development' && process.env.NODE_ENV !== 'test') {
  pg = AWSXRay.capturePostgres(require("pg"));
}

module.exports = knex;
`

For this to work is it required to open the segment somewhere else before this gets executed? I'm running out of ideas.

**Comment by marianzange** [comment]
I found that patching the `mysql` client with the X-Ray SDK led to major issues when using it with knex transactions. So I've started writing a custom adapter. I just hacked it together last night as a prototype, but feel free to check it out. Seemed to work so far for me and since I need it for a current project, I'll very likely get it into proper shape soon:

https://github.com/marianzange/knex-aws-xray

**Comment by cazzer** [comment]
I'm also having some issues getting @RickDT's suggestion working. My connection looks like this:
```js
import AWSXRay from 'aws-xray-sdk'
import knex from 'knex'
//...
const pg = AWSXRay.capturePostgres(require('pg'))

const db = knex({
  connection: DB_ENDPOINT,
  dialect: 'pg'
})
//...
```
But my requests are all timing out, and the traces show as pending:
![image](https://user-images.githubusercontent.com/2466842/31743573-70a942c8-b410-11e7-94b4-09020c0c9c81.png)
My Lambda is limited to 3 seconds, but increasing to 30 yields the same results.

**Comment by nakedible-p** [comment]
I am seeing the same error: `Cannot read property 'name' of undefined`. Looking at the XRay code and the Postgres client code it would seem that the XRay code is meant to work with a very old version of the Postgres client. It assumes that the `query` method returns the created `Query` object, where as the pg client that supports Promises will either return a straight up Promise, or nothing at all.

**Comment by sid88in** [comment]
hey guys! any update on this? I am facing the same problem.  I see this reply from AWS
https://forums.aws.amazon.com/thread.jspa?threadID=247556&tstart=0

**Comment by jsuna** [comment]
Hey Gang, FYI I've opened a PR against @marianzange 's solution that adds postgres support.. 
https://github.com/marianzange/knex-aws-xray/pull/2 we've been using a modified version that only handles postgres and it's been working great!

**Comment by felipefdl** [comment]
Any update? the solution from marianzange/knex-aws-xray not work for me.

**Comment by elhigu** [comment]
I don't think here is nothing that knex should do about this, maybe people working with marianzange/knex-aws-xray can help how to get it work. Closing.

**Comment by kibertoad** [comment]
@elhigu Well, `I am trying to pass the aws sdk's monkey-patched postgres connection to knex using the .connection(dbConnection) feature as mentioned in the documentation. But it is not working.` sounds like a potentially legitimate knex bug.

**Comment by elhigu** [comment]
Actually IIRC that `.connection` is not implemented at all nor it has been properly specified what it should even do... https://knexjs.org/#Builder-connection

So feature request for that would be the way to go and good specification what it should really do... for example if it should take same kind of object that acquireConnection() returns or what.

**Comment by kibertoad** [comment]
https://github.com/tgriesser/knex/issues/2804 -> will improve on it later
