### ISSUE TITLE
Error when attempting to create Sqlite3 db

### ISSUE THREAD

**Issue by oscarhou** [tgriesser/knex#1918]
I'm trying to use knex with ReactJs but am currently running into some problems just trying to create a table.

Code snippet:
```
    var knex = require('knex')({
            client: 'sqlite3',
            connection: { filename : "./testdb"},
            useNullAsDefault: true,
    //      debug:true
    });


knex.schema.createTable('users', function(table) {
        console.log("creating");
        table.increments('id').primary();
        table.string('username');
        table.string('password');
        table.timestamps();
})
.then(() => {})
.catch((error) => { console.log(error);});

var bookshelf = require('bookshelf')(knex);
export { knex, bookshelf }; `
```

Error output from the Chrome Console Tab:
```
TypeError: _this.driver.Database is not a constructor
    at http://localhost:3000/static/js/bundle.js:106754:17
    at Client_SQLite3.acquireRawConnection (http://localhost:3000/static/js/bundle.js:106753:13)
    at Object.create (http://localhost:3000/static/js/bundle.js:63023:17)
    at Pool._createResource (http://localhost:3000/static/js/bundle.js:81118:18)
    at Pool.dispense [as _dispense] (http://localhost:3000/static/js/bundle.js:81078:11)
    at Pool.acquire (http://localhost:3000/static/js/bundle.js:81200:9)
    at http://localhost:3000/static/js/bundle.js:63073:20
From previous event:
    at Client_SQLite3.acquireConnection (http://localhost:3000/static/js/bundle.js:63064:13)
    at http://localhost:3000/static/js/bundle.js:69280:31
    at http://localhost:3000/static/js/bundle.js:69278:36
    at Runner.ensureConnection (http://localhost:3000/static/js/bundle.js:69277:35)
    at Runner.run (http://localhost:3000/static/js/bundle.js:69127:43)
    at SchemaBuilder.Target.then (http://localhost:3000/static/js/bundle.js:62470:44)
    at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:51485:5)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:556:30)
    at fn (http://localhost:3000/static/js/bundle.js:87:20)
    at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:51377:24)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:556:30)
    at fn (http://localhost:3000/static/js/bundle.js:87:20)
    at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:32596:2)
From previous event:
    at http://localhost:3000/static/js/bundle.js:69278:36
From previous event:
    at Runner.ensureConnection (http://localhost:3000/static/js/bundle.js:69277:35)
    at Runner.run (http://localhost:3000/static/js/bundle.js:69127:43)
    at SchemaBuilder.Target.then (http://localhost:3000/static/js/bundle.js:62470:44)
    at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:51485:5)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:556:30)
    at fn (http://localhost:3000/static/js/bundle.js:87:20)
    at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:51377:24)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:556:30)
    at fn (http://localhost:3000/static/js/bundle.js:87:20)
    at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:32596:2)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:556:30)
    at fn (http://localhost:3000/static/js/bundle.js:87:20)
    at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:10825:13)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:556:30)
    at fn (http://localhost:3000/static/js/bundle.js:87:20)
    at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:591:19)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:556:30)
    at http://localhost:3000/static/js/bundle.js:579:37
    at http://localhost:3000/static/js/bundle.js:582:10
```

It doesn't seem like anything is missing, could it be an environmental issue?

**Comment by absolux** [comment]
@oscarhou 
It's obvious that the browser cannot use a SQL database

**Comment by oscarhou** [comment]
@absolux 
Thanks, I guess I had the wrong idea about SQLite3, I was using SQLite3 for initial prototyping purposes to avoid having to write an API to interface it.
