### ISSUE TITLE
Can't call knex

### ISSUE THREAD

**Issue by thestrayed** [tgriesser/knex#1924]
I already install knex globally but somehow, i can't call knex 
`ww:server win$ knex init`
`/usr/local/lib/node_modules/knex/bin/cli.js:91`
    `.option(`-x [${filetypes.join('|')}]`, 'Specify the knexfile extension (de`
            `^`
`SyntaxError: Unexpected token ILLEGAL`
    `at exports.runInThisContext (vm.js:73:16)`
    `at Module._compile (module.js:443:25)`
    `at Object.Module._extensions..js (module.js:478:10)`
    `at Module.load (module.js:355:32)`
    `at Function.Module._load (module.js:310:12)`
    `at Function.Module.runMain (module.js:501:10)`
    `at startup (node.js:129:16)`
    `at node.js:814:3`

**Comment by thestrayed** [comment]
update node version solved the problem (v0.12.5 -> v7.4.0)
