### ISSUE TITLE
Version of lodash in knex 0.12.7 in package.json is badly specified

### ISSUE THREAD

**Issue by wsieroci** [tgriesser/knex#1931]
Hi,

You have set version of `lodash` to `"lodash": "^4.6.0"` (in knex `0.12.7`). It is not working on my environment. The lowest version should be `4.17.4` (AFAIK). If not then I got exception that node cannot require `lodash/first`

Regards,
Wiktor

**Comment by elhigu** [comment]
Cannot reproduce

```
> require('lodash').VERSION
'4.6.1'
> require('lodash/first')
[Function: head]
>
```

**Comment by cjwatson** [comment]
Perhaps you have a different version under `node_modules/knex/node_modules/` or something?  The following commands reproduce the original problem in a clean directory:

    $ mkdir -p ~/knex/migrations
    $ cd ~/knex
    $ npm i lodash@4.6.0
    $ npm i knex sqlite3
    $ node_modules/.bin/knex init
    $ node_modules/.bin/knex migrate:latest

**Comment by jeromemacias** [comment]
I just had the same issue, upgrading lodash to latest version (4.17.4) fix the issue.

**Comment by elhigu** [comment]
@cjwatson nope, still can't reproduce

```
mikaelle$ npm init
mikaelle$ npm i lodash@4.6.0
mikaelle$ npm i knex sqlite3
mikaelle$ node_modules/.bin/knex init
mikaelle$ node_modules/.bin/knex migrate:latest
Using environment: development
Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
Already up to date
mikaelle$ node
> require('lodash').VERSION
'4.6.0'
> require('lodash/first')
[Function: head]
> 
```

**Comment by suhaig** [comment]
@elhigu I attached a small project to reproduce the issue. Just unzip, npm install and npm start. The output is:
```
lodash version: 4.6.0
module.js:471
    throw err;
    ^

Error: Cannot find module 'lodash/first'
```
If you delete the npm-shrinkwrap.json then npm will install lodash 4.17.4 (latest version) and knex will work just fine.
[knex-lodash-test.tar.gz](https://github.com/tgriesser/knex/files/850903/knex-lodash-test.tar.gz)

**Comment by elhigu** [comment]
@suhaig could you provide some more info about your platform OS, node version, etc... still cannot reproduce:

```shell
> knex-lodash-test@0.0.1 start /Users/mikaelle/Downloads/knex-lodash-test
> node knex-lodash-test.js

lodash version: 4.6.0
Mikaels-MacBook-Pro-2:knex-lodash-test mikaelle$ 
```

**Comment by suhaig** [comment]
@elhigu the "older" version of knex I'm using is 0.12.8 (as you can see from the package.json), but knex does not get to the point you mention, because of the lodash/first problem.
I globally installed the 4.17.4 version of lodash and now my test successfully loads the lodash/first module, but it still prints `lodash version: 4.6.0`. So maybe you have a globally installed lodash. Can you check that?

**Comment by suhaig** [comment]
@elhigu sorry I forgot the platform details:

- Xubuntu 16.10 64bit
- Node 6.10.0
- NPM 3.10.10

**Comment by elhigu** [comment]
@suhaig thanks, I was able to reproduce now!

**Comment by elhigu** [comment]
Looks like 4.12.0 was the first version, which did import that correctly. Is there any reason why version should be  >= 4.17?

**Comment by suhaig** [comment]
@elhigu nothing special about 4.17.4, it's just the latest version of lodash.

**Comment by fernandocanizo** [comment]
Hello, we found the same problem in **knex@0.14.1**, we use Archlinux and Ubuntu machines, the problem appears on the Ubuntus, not in the Archlinuxes.

I don't know how it can be related as we use `nvm` to manage our Nodejs version.

Platform details where it fails:

- Ubuntu 16.04.3 LTS
- Node v8.9.2
- npm 5.5.1

Stacktrace:

```
Error: Cannot find module 'lodash/first'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/www/maps/node_modules/knex/lib/schema/tablecompiler.js:25:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/www/maps/node_modules/knex/lib/client.js:69:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

Our solution was to `npm i --no-save lodash` (we don't use lodash in our project).

But it would be nice that knex just upgrade its dependencies.
