### ISSUE TITLE
Allow to opt-in .ts use

### ISSUE THREAD

**Issue by MichaelBuen** [tgriesser/knex#1945]
Our migration that is based on .ts and converted to .js is now failing on the latest 0.12.7:

```
(function (exports, require, module, __filename, __dirname) { import * as Knex from 'knex';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Migrator._validateMigrationStructure (/Users/jack/WebstormProjects/great-project/node_modules/knex/lib/migrate/index.js:342:21)
    at wrapper (/Users/jack/WebstormProjects/great-project/node_modules/knex/node_modules/lodash/_createBind.js:23:15)
    at arrayMap (/Users/jack/WebstormProjects/great-project/node_modules/knex/node_modules/lodash/_arrayMap.js:16:21)
    at map (/Users/jack/WebstormProjects/great-project/node_modules/knex/node_modules/lodash/map.js:50:10)
    at /Users/jack/WebstormProjects/great-project/node_modules/knex/lib/migrate/index.js:308:55

```

To fix the problem, the '.ts' need to be removed from `SUPPORTED_EXTENSIONS`of node_modules/knex/lib/migrate/index.js file:

`
var SUPPORTED_EXTENSIONS = (0, _freeze2.default)(['.co', '.coffee', '.eg', '.iced', '.js', '.litcoffee', '.ls', '.ts']);`

to this:

`
var SUPPORTED_EXTENSIONS = (0, _freeze2.default)(['.co', '.coffee', '.eg', '.iced', '.js', '.litcoffee', '.ls']);`

We will revert to 0.12.6 for the meantime.

Same problem as this: https://github.com/tgriesser/knex/pull/1769#issuecomment-280815901

**Comment by elhigu** [comment]
Duplicate https://github.com/tgriesser/knex/issues/1922
