### ISSUE TITLE
Concurrent migrations fail instead of waiting

### ISSUE THREAD

**Issue by itaysabato** [tgriesser/knex#1950]
This is in continuum to a comment I made [here](https://github.com/tgriesser/knex/issues/1217#issuecomment-284764072).

In the [docs](http://knexjs.org/#Notes-about-locks) it says:

> A lock system is there to prevent multiple processes from running the same migration batch in the same time. When a batch of migrations is about to be run, the migration system first tries to get a lock using a SELECT ... FOR UPDATE statement (preventing race conditions from happening). If it can get a lock, the migration batch will run. If it can't, it will wait until the lock is released.

But, in actuality, it is impossible for one process to wait while another is migrating. This can be seen by running two processes at the same time that start by calling `knex.migrate.latest()` - one will succeed and the other will fail with a lock error.

From what I could tell, this is caused by the code for [`_getLock()`](https://github.com/tgriesser/knex/blob/master/src/migrate/index.js#L174) which starts a transaction, selects the migration lock `FOR UPDATE`, sets it to true and commits the transaction before the calling code moves on to perform the migration. This way, any other process that tries to get the lock will fail.

If the transaction will end only after the whole migration, this should not happen.

These are knex logs for running two such processes against PostgreSQL:
```
  knex:client acquired connection from pool: __knexUid1 +1s
  knex:query select * from information_schema.tables where table_name = ? and table_schema = current_schema +3ms
  knex:bindings [ 'knex_migrations' ] +1ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=1 +32ms
  knex:client acquired connection from pool: __knexUid1 +1s
  knex:query select * from information_schema.tables where table_name = ? and table_schema = current_schema +2ms
  knex:bindings [ 'knex_migrations' ] +1ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=1 +4ms
  knex:client releasing connection to pool: __knexUid1 +300ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=2 +1ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=1 available=2 +1ms
  knex:client acquired connection from pool: __knexUid2 +0ms
  knex:query select * from information_schema.tables where table_name = ? and table_schema = current_schema +1ms
  knex:bindings [ 'knex_migrations_lock' ] +0ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=2 +285ms
  knex:client releasing connection to pool: __knexUid1 +56ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=3 +1ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=1 available=3 +1ms
  knex:client acquired connection from pool: __knexUid2 +0ms
  knex:query select * from information_schema.tables where table_name = ? and table_schema = current_schema +1ms
  knex:bindings [ 'knex_migrations_lock' ] +0ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=2 +93ms
  knex:client releasing connection to pool: __knexUid2 +256ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=3 +0ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=1 available=3 +2ms
  knex:client acquired connection from pool: __knexUid1 +1ms
  knex:query select * from "knex_migrations_lock" +5ms
  knex:bindings [] +0ms
  knex:client releasing connection to pool: __knexUid2 +358ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=3 +0ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=1 available=3 +0ms
  knex:client acquired connection from pool: __knexUid3 +1ms
  knex:query select * from "knex_migrations_lock" +3ms
  knex:bindings [] +0ms
  knex:client releasing connection to pool: __knexUid1 +162ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=3 +0ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=1 available=3 +1ms
  knex:client acquired connection from pool: __knexUid3 +0ms
  knex:query select "name" from "knex_migrations" order by "id" asc +1ms
  knex:bindings [] +0ms
  knex:client releasing connection to pool: __knexUid3 +211ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=3 +0ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=1 available=3 +1ms
  knex:client acquired connection from pool: __knexUid1 +0ms
  knex:query select "name" from "knex_migrations" order by "id" asc +0ms
  knex:bindings [] +0ms
  knex:client releasing connection to pool: __knexUid3 +267ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=3 +0ms
  knex:tx trx4: Starting top level transaction +1ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=1 available=3 +1ms
  knex:client acquired connection from pool: __knexUid2 +0ms
  knex:query BEGIN; +1ms
  knex:bindings undefined +0ms
  knex:client releasing connection to pool: __knexUid1 +171ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=3 +0ms
  knex:tx trx4: Starting top level transaction +2ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=1 available=3 +1ms
  knex:client acquired connection from pool: __knexUid2 +0ms
  knex:query BEGIN; +2ms
  knex:bindings undefined +0ms
  knex:query select * from "knex_migrations_lock" for update +170ms
  knex:bindings [] +0ms
  knex:query select * from "knex_migrations_lock" for update +174ms
  knex:bindings [] +0ms
  knex:query update "knex_migrations_lock" set "is_locked" = ? +173ms
  knex:bindings [ 1 ] +0ms
  knex:query COMMIT; +351ms
  knex:bindings undefined +0ms
  knex:tx trx4: releasing connection +169ms
  knex:client releasing connection to pool: __knexUid2 +0ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=3 +0ms
  knex:query ROLLBACK; +655ms
  knex:bindings undefined +0ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=1 available=3 +2ms
  knex:client acquired connection from pool: __knexUid1 +1ms
  knex:query select max("batch") as "max_batch" from "knex_migrations" +0ms
  knex:bindings [] +0ms
  knex:client releasing connection to pool: __knexUid1 +164ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=3 +0ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=1 available=3 +2ms
  knex:client acquired connection from pool: __knexUid3 +0ms
  knex:query update "knex_migrations_lock" set "is_locked" = ? +0ms
  knex:bindings [ 0 ] +0ms
  knex:tx trx4: releasing connection +174ms
  knex:client releasing connection to pool: __knexUid2 +1ms
  knex:pool INFO pool postgresql:pg:client0 - dispense() clients=0 available=3 +0ms
Knex:warning - Can't take lock to run migrations: Migration table is already locked
Knex:warning - If you are sure migrations are not running you can release the lock manually by deleting all the rows from migrations lock table: knex_migrations_lock
```

At which point an exception is thrown in process 2.

**Comment by elhigu** [comment]
Documentation doesn't seem to be up-to-date with the implementation. I'm not sure if I want to see that functionality being changed either (potentially blocking for ever instead of exit with error)... you can implement your own waiting around the `.latest()` as a work around for your usecase.

Issue should be added to documentation repo though for updating description of how locking works.

**Comment by itaysabato** [comment]
@elhigu in what scenario would it block forever?

Wouldn't blocking be confined to the duration of the migration done by the one holding the lock? It seems weird to me to have to implement another lock on top of one that is already in place...

**Comment by elhigu** [comment]
When there has been error in other migration attempt, for example process was killed because of out-of-memory and lock table is left dirty. There is an issues opened every now and then, when lock has not been cleaned for some reason.

No need to implement another lock. Just polling.

**Comment by elhigu** [comment]
IIRC they are done in separate transaction because, migrations can be run without transaction (few versions ago there was no implicit transaction initialized for migrations).

However that is actually really good idea to do the locking in the same implicit transaction if implicit transactions are used. That will make migration system more robust and in that case I wouldn't mind  that other processes are just waiting first to finish. If implicit transactions are not used, locking could stay the way it is now (otherwise we would need at least 2 db connections... one to take the the lock and other for running the migration).

I would gladly accept pull request fixing that.

**Comment by itaysabato** [comment]
I guess I'll give it a go then :)

**Comment by itaysabato** [comment]
I've implemented the change but I seem to be running into trouble with the integration tests - because there is a purposely faulty migration file in the migration folder the migration always fails. 

Previously, this meant that all the migrations before the bad one were committed in separate transactions and therefore their effects could be seen; but now, since they are all part of one transaction, no changes are committed by the failed migration.

I think this is the correct behavior and that the valid migrations should be tested separately from the invalid one but I am not sure how to fix this in the tests. Any ideas?

This is where I am failing (tested on Postgres):
```
    knex.migrate
      ✓ should create a new migration file with the create method
      ✓ should list the current migration state with the currentVersion method
      knex.migrate.status
Knex:warning - migrations failed with error: SELECT foo FROM unknown_table - relation "unknown_table" does not exist
        ✓ should create a migrations lock table
Knex:warning - migrations failed with error: SELECT foo FROM unknown_table - relation "unknown_table" does not exist
        1) should return 0 if code matches DB
        2) "after each" hook for "should return 0 if code matches DB"

  704 passing (1s)
  2 failing

  1) postgresql | pg knex.migrate knex.migrate.status should return 0 if code matches DB:

      AssertionError: expected -2 to equal 0
      + expected - actual

      --2
      +0
      
      at test/integration/migrate/index.js:76:39
  From previous event:
      at test/integration/migrate/index.js:75:84
  From previous event:
      at Context.<anonymous> (test/integration/migrate/index.js:74:10)
  From previous event:

  2) postgresql | pg knex.migrate knex.migrate.status "after each" hook for "should return 0 if code matches DB":
     Error: The migration directory is corrupt, the following files are missing: foobar, foobarbaz
      at validateMigrationList (lib/migrate/index.js:9:28643)
  From previous event:
      at lib/migrate/index.js:9:7469
  From previous event:
      at Migrator.rollback (lib/migrate/index.js:9:7270)
      at Context.<anonymous> (test/integration/migrate/index.js:44:29)
```

**Comment by itaysabato** [comment]
Never mind, I fixed the tests and added a couple more to test the parallel migrations.
If you have time, please review my PR: #1962

**Comment by elhigu** [comment]
I think this is now complete.

**Comment by itaysabato** [comment]
@elhigu indeed, but, when will it be released? :)

**Comment by elhigu** [comment]
soonish  :)
