### ISSUE TITLE
password authentication failed for user "[username]"

### ISSUE THREAD

**Issue by LucasMcL** [tgriesser/knex#1997]
I am trying to connect knex to a running postgres server and perform a simple migration.   I am getting the following error: 

     error: password authentication failed for user "Lucas"
    at Connection.parseE (/Users/Lucas/Workspace/8-Db-driven-applications/exercises/08-intro-to-ORMs/node_modules/pg/lib/connection.js:569:11)
    at Connection.parseMessage (/Users/Lucas/Workspace/8-Db-driven-applications/exercises/08-intro-to-ORMs/node_modules/pg/lib/connection.js:396:17)
    at Socket.<anonymous> (/Users/Lucas/Workspace/8-Db-driven-applications/exercises/08-intro-to-ORMs/node_modules/pg/lib/connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)

My settings object for the development environment looks like this:

  development: {
    client: 'postgresql',
    connection: {
      database: 'knex_practice'
    },
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'knex_migrations'
    }
  },

I've tried creating a test user with username test and password test which did not work.  In addition, I get this error even when the server is not running, or I pass a database name that doesn't exist.  It's like it fails before it even connects to the database.  Please help!

Running:
node 7.4.0
knex 0.12.9
pg 6.1.5
Mac OSX

**Comment by elhigu** [comment]
try...

```js
{
  client: 'pg'
  connection: 'postgres:///knex_practise'
}
```

...and learn to configure postgresql users. 

You can try using `psql postgres://<something here>` from command line to connect your database and when you figure out which connection string works for you you can use that in knex configuration too.

Anyways this is user error and pretty much general question how to connect postgresql db which has bunch of answers in stackoverflow.
