### ISSUE TITLE
Knex migrate and seed CLI commands throwing error

### ISSUE THREAD

**Issue by johnazre** [tgriesser/knex#2000]
```
Error: Cannot find module './dialects/[object KnexClient]/index.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Knex (/Users/johnarmbruster/Desktop/knexTodos/node_modules/knex/lib/index.js:55:15)
    at initKnex (/usr/local/lib/node_modules/knex/bin/cli.js:69:10)
    at Command.<anonymous> (/usr/local/lib/node_modules/knex/bin/cli.js:142:17)
    at Command.listener (/usr/local/lib/node_modules/knex/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/knex/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/knex/node_modules/commander/index.js:458:21)
    at Liftoff.invoke (/usr/local/lib/node_modules/knex/bin/cli.js:186:13)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/knex/node_modules/liftoff/index.js:193:16)
    at module.exports (/usr/local/lib/node_modules/knex/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/knex/node_modules/liftoff/index.js:185:9)
    at /usr/local/lib/node_modules/knex/node_modules/liftoff/index.js:159:9
    at /usr/local/lib/node_modules/knex/node_modules/v8flags/index.js:108:14
    at /usr/local/lib/node_modules/knex/node_modules/v8flags/index.js:36:12
    at /usr/local/lib/node_modules/knex/node_modules/v8flags/index.js:47:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Here is my knexfile: 
```
var environment = process.env.NODE_ENV || 'development';

var config = {
    development: {
        client: 'pg',
        connection: 'postgres://localhost/todos_test',
        migrations: {
            directory: __dirname + '/db/migrations',
          },
        seeds: {
            directory: __dirname + '/db/seeds',
          },
      },
    production: {
        client: 'pg',
        connection: process.env.DATABASE_URL,
        migrations: {
            directory: __dirname + '/db/migrations',
          },
        seeds: {
            directory: __dirname + '/db/seeds/production',
          },
      },
  };

  module.exports = require('knex')(config[environment]);
```

Operating System: Mac OS Sierra

It happens when I run any of the CLI commands, but my server works fine if I call the database with the API. Any ideas?

**Comment by johnazre** [comment]
I saw the other issue #1791, but I'm not sure exactly what they did to fix it. I just created another project to replicate the issue and was able to replicate it with this setup.

**Comment by elhigu** [comment]
You are returning knex instance from knexfile.js you should return configuration instead.

```js
module.exports = config;
```

os maybe (I'm not using knexfiles myself)

```js
module.exports = config[environment];
```
