### ISSUE TITLE
SQlite warning useNullAsDefault appears on select(columns) even if specified in configuration

### ISSUE THREAD

**Issue by dfranciosi** [tgriesser/knex#2008]
A message `Knex:warning - sqlite does not support inserting default values. Set the useNullAsDefault flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).`
appears when using knex with selected columns as would happen with `undefined` inserts.
e.g.
``` 
knex.select().from('table'); => OK
knex.select('column1', 'column2').from('table') => warning message
```

**Comment by elhigu** [comment]
can't reproduce:

```
knex = require('knex')({client: 'sqlite3});
> knex.select().from('table').toSQL();
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '4f885f59-d8ec-4dc3-b9a2-adc613e8958a',
  sql: 'select * from "table"' }
> knex.select('column1', 'column2').from('table').toSQL()
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '693d0247-d055-410c-938a-c9036c8ce718',
  sql: 'select "column1", "column2" from "table"' }
> knex('table').insert([{a: 1}, {b: 2}]).toSQL()
TypeError: `sqlite` does not support inserting default values. Specify values explicitly or use the `useNullAsDefault` config flag. (see docs http://knexjs.org/#Builder-insert).
    at /Users/mikaelle/Projects/Vincit/yessql/superoperator-backend/node_modules/knex/lib/dialects/sqlite3/query/compiler.js:90:44
    at arrayEach (/Users/mikaelle/Projects/Vincit/yessql/superoperator-backend/node_modules/knex/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/mikaelle/Projects/Vincit/yessql/superoperator-backend/node_modules/knex/node_modules/lodash/forEach.js:38:10)
    at /Users/mikaelle/Projects/Vincit/yessql/superoperator-backend/node_modules/knex/lib/dialects/sqlite3/query/compiler.js:89:28
    at arrayEach (/Users/mikaelle/Projects/Vincit/yessql/superoperator-backend/node_modules/knex/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/mikaelle/Projects/Vincit/yessql/superoperator-backend/node_modules/knex/node_modules/lodash/forEach.js:38:10)
    at QueryCompiler_SQLite3.insert (/Users/mikaelle/Projects/Vincit/yessql/superoperator-backend/node_modules/knex/lib/dialects/sqlite3/query/compiler.js:88:26)
    at QueryCompiler_SQLite3.toSQL (/Users/mikaelle/Projects/Vincit/yessql/superoperator-backend/node_modules/knex/lib/query/compiler.js:108:27)
    at Builder.toSQL (/Users/mikaelle/Projects/Vincit/yessql/superoperator-backend/node_modules/knex/lib/query/builder.js:111:44)
    at repl:1:40
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
> 
```

**Comment by mauroere** [comment]
Insert **useNullAsDefault: true** into knex connection file, and try again.

**Comment by elhigu** [comment]
@mauroere that is not the problem in this issue if you read it properly. Doing just select statement should never trigger that error.
