### ISSUE TITLE
Required configuration option 'client' is missing.

### ISSUE THREAD

**Issue by Ginden** [tgriesser/knex#2023]
Documentation states:

> You can even use knex without a connection, just for its query building features. 

Though running direct example from docs:

> const knex = require('knex')({});

Throws error:
```
> knex = require('knex')({})
Error: knex: Required configuration option 'client' is missing.
    at new Client (/home/ginden/.../node_modules/knex/lib/client.js:108:11)
    at Knex (/home/ginden/.../node_modules/knex/lib/index.js:60:34)
    at repl:1:23
```

**Comment by elhigu** [comment]
Docs are out of date: https://github.com/knex/documentation/issues/28

**Comment by stoplion** [comment]
same issue and my client is hard coded

**Comment by kibertoad** [comment]
@stoplion Can you please share your config?

**Comment by elhigu** [comment]
@stoplion not the same issue, in this was about wrong documentation. But yeah you have a problem in your config or how you read your config from knexfile.js because `const knex = require('knex')({client: 'pg'})` definitely works. I write that line at least few times a week, when verifying knex issues.

**Comment by Haisum92** [comment]
@Ginden , it raised due to two reasons at my side and so sharing for ease
_**Error: knex: Required configuration option 'client' is missing.**_

1. Wrong **environment name** in the knexfile.js.
    In my .env **NODE_ENV = development** and at **knexfile.js** there was no entry in it
    ```
     module.exports = {

  test: {
    client: config.DB_DIALECT,
    connection: {
      host      : process.env.DB_HOST,
      user      : process.env.DB_USERNAME,
      password  : process.env.DB_PASSWORD,
      database  : (process.env.DB_NAME == "test") ? process.env.DB_NAME_TEST : process.env.DB_NAME,
      timezone  : config.GLOBAL_TIME_ZONE
    },
    migrations: {
      tableName: migrationTable
    }
  },
  Local: {
    client: config.DB_DIALECT,
    connection: {
      host      : process.env.DB_HOST,
      user      : process.env.DB_USERNAME,
      password  : process.env.DB_PASSWORD,
      database  : (process.env.DB_NAME == "test") ? process.env.DB_NAME_TEST : process.env.DB_NAME,
      timezone  : config.GLOBAL_TIME_ZONE
    },
    migrations: {
      tableName: migrationTable
    }
  },
  
  staging: {
    client: config.DB_DIALECT,
    connection: {
      host      : process.env.DB_HOST,
      user      : process.env.DB_USERNAME,
      password  : process.env.DB_PASSWORD,
      database  : process.env.DB_NAME,
      timezone  : config.GLOBAL_TIME_ZONE
    },
    migrations: {
      tableName: migrationTable
    }
  },

  production: {
    client: config.DB_DIALECT,
    connection: {
      host      : process.env.DB_HOST,
      user      : process.env.DB_USERNAME,
      password  : process.env.DB_PASSWORD,
      database  : process.env.DB_NAME,
      timezone  : config.GLOBAL_TIME_ZONE
    },
    migrations: {
      tableName: migrationTable
    }
  }

};

```
 2. Wrong client name at configrations
         client: config.DB_DIALECT, // either key doesn't exits or wrong name at config file
