### ISSUE TITLE
Knex installation issue

### ISSUE THREAD

**Issue by arjunnayak0705** [tgriesser/knex#2043]
Installed Knex using `sudo npm install -g knex` 
When I run `knex` command I get following error
```
/usr/local/lib/node_modules/knex/bin/cli.js:91
    .option(`-x [${filetypes.join('|')}]`, 'Specify the knexfile extension (de
            ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Please help me

**Comment by arjunnayak0705** [comment]
Its because of node version I was using.
I was using 0.10.* and es6 syntax is not supported by this version of node.
I solved this by installing nvm and using latest version of node
