### ISSUE TITLE
MSSQL - TypeError: _this.driver.Connection is not a constructor

### ISSUE THREAD

**Issue by tmcdonnell87** [tgriesser/knex#2069]
Either there's something going on, or the error message isn't helpful. :-) 

My connection works with the base mssql, but not with Knex. Sample code to reproduce (run with babel-node):
```
import mssql from 'mssql';
import knex from 'knex';

require('dotenv').config();

const test = async () => {
  try {
    await mssql.connect(process.env.DATABASE_URL);
    const result = await mssql.query`select 1 as dbIsUp`;
    console.log(result.recordset);
    mssql.close();
  } catch (err) {
    console.log(err);
  }
};
test();

const db = knex({
  client: 'mssql',
  connection: process.env.DATABASE_URL,
  debug: true,
});

db.raw('select 1 as dbIsUp').then((values) => {
  // there is a valid connection in the pool
  console.log(values);
}).catch((err) => {
  console.log(err);
});
```

**Expected Result:**
Connects without errors, OR error message that helps troubleshoot issue
**Actual Result:**
```
  knex:pool INFO pool mssql:mssql:client0 - dispense() clients=1 available=0 +0ms
TypeError: _this.driver.Connection is not a constructor
    at /mnt/c/Users/Terry/Projects/gohealth/node_modules/knex/lib/dialects/mssql/index.js:135:24
    at Promise._execute (/mnt/c/Users/Terry/Projects/gohealth/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/mnt/c/Users/Terry/Projects/gohealth/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/mnt/c/Users/Terry/Projects/gohealth/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MSSQL.acquireRawConnection (/mnt/c/Users/Terry/Projects/gohealth/node_modules/knex/lib/dialects/mssql/index.js:134:12)
    at Object.create (/mnt/c/Users/Terry/Projects/gohealth/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (/mnt/c/Users/Terry/Projects/gohealth/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool._ensureMinimum (/mnt/c/Users/Terry/Projects/gohealth/node_modules/generic-pool/lib/generic-pool.js:408:12)
    at new Pool (/mnt/c/Users/Terry/Projects/gohealth/node_modules/generic-pool/lib/generic-pool.js:157:8)
    at Client_MSSQL.initializePool (/mnt/c/Users/Terry/Projects/gohealth/node_modules/knex/lib/client.js:269:17)
    at Client_MSSQL.Client (/mnt/c/Users/Terry/Projects/gohealth/node_modules/knex/lib/client.js:116:12)
    at new Client_MSSQL (/mnt/c/Users/Terry/Projects/gohealth/node_modules/knex/lib/dialects/mssql/index.js:93:20)
    at Knex (/mnt/c/Users/Terry/Projects/gohealth/node_modules/knex/lib/index.js:60:34)
    at Object.<anonymous> (/mnt/c/Users/Terry/Projects/gohealth/scratch.js:18:12)
    at Module._compile (module.js:571:32)
    at loader (/mnt/c/Users/Terry/Projects/gohealth/node_modules/babel-register/lib/node.js:144:5)
  knex:pool INFO pool mssql:mssql:client0 - dispense() clients=0 available=0 +54ms
  knex:pool INFO pool mssql:mssql:client0 - dispense() clients=0 available=0 +1ms
  knex:pool INFO pool mssql:mssql:client0 - dispense() clients=0 available=0 +0ms
[ { dbIsUp: 1 } ]
```

**Comment by Aides359** [comment]
Taking from http://stackoverflow.com/questions/43283552/node-js-knex-and-mssql-error-typeerror-this-driver-connection-is-not-a-cons, downgrading to `mssql@3.3` solves this issue.
However a proper fix would be needed.

**Comment by wubzz** [comment]
Closing in favor of #1999

Knex currently has no support for `node-mssql` 4.0.0. (PR Open #2029)

**Comment by calebeaires** [comment]
@wubzz - even if support were added, this error still persist!

https://github.com/tgriesser/knex/commit/17bf763cb13543f502668d2f74ae0ca1b2d67a28

**Comment by wubzz** [comment]
@calebeaires Well as far as I can tell #2029 hasn't been published. Or are you testing from master branch?

**Comment by calebeaires** [comment]
@wubzz still using 0.13.0. I thought this package were the last one!

**Comment by jordanhenderson** [comment]
Still getting this issue on 0.13.0.
Unhandled rejection TypeError: _this.driver.Connection is not a constructor
    at node_modules/knex/lib/dialects/mssql/index.js:135:24
 "dependencies": {
    "knex": "^0.13.0"
  },

**Comment by kabirbaidhya** [comment]
Is there any update on when this fix is going to be released and published to npm? Or when is the next release scheduled?

**Comment by elhigu** [comment]
There are no schedules, but I'll make the release before christmas. Maybe this month, maybe some other.

**Comment by kabirbaidhya** [comment]
Great. Thanks.

**Comment by johncade** [comment]
@elhigu any update on this? I believe `mssql v4` is needed in order to support `multi-subnet-failover`. This is a pretty big deal breaker for anyone needing failover support.

**Comment by elhigu** [comment]
Have you checked knex 0.14.4?

**Comment by RecursiveCTE** [comment]
Hello all,
I know i'm late to the party...
I'm receiving the same error others above are reporting.

```
message: "_this.driver.ConnectionPool is not a constructor"
stack: "TypeError: _this.driver.ConnectionPool is not a constructor
    at https://localhost:4321/dist/sqlconnector-webpart-web-part.js:41995:24
    at Client_MSSQL.acquireRawConnection (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:41994:12)
    at create (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:41375:23)
    at https://localhost:4321/dist/sqlconnector-webpart-web-part.js:93108:34
    at Object.tryPromise (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:93289:24)
    at https://localhost:4321/dist/sqlconnector-webpart-web-part.js:93108:17
    at new Promise (<anonymous>)
    at callbackOrPromise (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:93099:12)
    at Pool._create (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:93029:9)
    at Pool._doCreate (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:93001:36)
    at Pool._tryAcquireOrCreate (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:92952:18)
    at Pool.acquire (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:92878:14)
    at https://localhost:4321/dist/sqlconnector-webpart-web-part.js:41428:26
From previous event:
    at Client_MSSQL.acquireConnection (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:41427:34)
    at Runner.ensureConnection (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:52320:24)
    at Runner.run (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:52140:42)
    at Raw.Target.then (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:49474:43)
    at SqlHelperUtil../lib/webparts/sqlconnectorWebpart/environment/SqlHelper/SqlHelperUtil.js.SqlHelperUtil.ExecuteSqlQuery (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:543:46)
    at WebFormEventListeners.ConnectionWizardDataSubmit (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:661:37)
    at ObjectExplorerBuilder.ConnectionWizardDataSubmit (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:924:39)
    at HTMLButtonElement.<anonymous> (https://localhost:4321/dist/sqlconnector-webpart-web-part.js:805:119)"
__proto__: Error {constructor: , name: "TypeError", message: "", …}

```

Here is my package.json file:

```
{
  "name": "sqlconnector-webpart",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.9.1",
    "@microsoft/sp-lodash-subset": "1.9.1",
    "@microsoft/sp-office-ui-fabric-core": "1.9.1",
    "@microsoft/sp-webpart-base": "1.9.1",
    "@pnp/common": "^1.3.5",
    "@pnp/logging": "^1.3.5",
    "@pnp/odata": "^1.3.5",
    "@pnp/sp": "^1.3.5",
    "@types/es6-promise": "^3.3.0",
    "@types/webpack-env": "^1.14.0",
    "graceful-fs": "^4.2.2",
    "jquery": "^3.4.1",
    "tsc": "^1.20150623.0",
    "webpack": "^4.39.2"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-2.9": "^0.7.29",
    "@microsoft/sp-build-web": "1.9.1",
    "@microsoft/sp-module-interfaces": "1.9.1",
    "@microsoft/sp-tslint-rules": "1.9.1",
    "@microsoft/sp-webpart-workbench": "1.9.1",
    "@types/chai": "^4.2.0",
    "@types/gulp": "^4.0.6",
    "@types/knex": "^0.16.1",
    "@types/mocha": "^5.2.7",
    "@types/mssql": "^3.3.0",
    "ajv": "^6.10.2",
    "globalthis": "^1.0.0",
    "gulp": "^3.9.1",
    "knex": "^0.14.4",
    "mssql": "^3.3.0"
  }
}
```

I tried installing mssql@3.3
I also downgraded my knex version to 0.14.4 to see if that would help.
The newer version gives an error that says it's not compatible with mssql@3.3.

if there's anything else I can do or any advice you could offer me i'd be greatly appreciative.
Oh, and i'm a noob when it comes to typescript so if there is a workaround I may need some guidance/assistance implementing it.
 
Thank you for your time.
Great job with the library and docs by the way.

**Comment by elhigu** [comment]
latest knex (0.19.x) should work with latest mssql 3.x driver. mssql 4 is not yet supported.
