### ISSUE TITLE
Errors are incredibly annoying to trace to application

### ISSUE THREAD

**Issue by jpike88** [tgriesser/knex#2074]
The below error fires at some point while my application is running. Tracking it down in a pain... what's the best way to tackle this?

`Unhandled rejection Error: Undefined binding(s) detected when compiling SELECT query: select `u`.* from `user` as `u` inner join `user_clientGroup_map` as `ucgm` on `ucgm`.`userID` = `u`.`id` where `u`.`active` = ? and `ucgm`.`clientGroupID` = ? and `ucgm`.`active` = ? and `ucgm`.`isClient` = ?
    at QueryCompiler_MySQL.toSQL (/home/ec2-user/server/node_modules/knex/lib/query/compiler.js:131:13)
    at Builder.toSQL (/home/ec2-user/server/node_modules/knex/lib/query/builder.js:115:44)
    at /home/ec2-user/server/node_modules/knex/lib/runner.js:56:32
    at tryCatcher (/home/ec2-user/server/node_modules/bluebird/js/release/util.js:16:23)
    at /home/ec2-user/server/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/home/ec2-user/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ec2-user/server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ec2-user/server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ec2-user/server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ec2-user/server/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ec2-user/server/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/home/ec2-user/server/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/ec2-user/server/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/home/ec2-user/server/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/ec2-user/server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ec2-user/server/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ec2-user/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ec2-user/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ec2-user/server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)`

**Comment by minecrawler** [comment]
You should implement proper error management by wrapping anything which can throw. In JS, the standard-way to do so is to use try..catch blocks, however, personally, I prefer Result Monads (for example [result-js](https://www.npmjs.com/package/result-js)), because they are more clean and allow the V8 optimizer to actually optimize your code. Examples:

```js
function mightThrow() { throw new Error('uh oh!'); }

try {
  const value = mightThrow();
  // do sth. with value
}
catch(err) {
  // try to resolve the problem internally first
  // else log the error and inform the user. Please be specific at this point!
  console.error('An error occurred while trying to do sth.: ' + err.toString());
}
```

```js
const Result = require('result-js');
function mightThrow() { throw new Error('uh oh!'); }

const resultValue = Result.fromTry(mightThrow);

// In case you have an alternative value from the beginning
const value = resultValue.or('alternative value');

// In case you want to handle an error gracefully
if (resultValue.isErr()) {
  console.error('An error occurred while trying to do sth.: ' + resultValue.unwrapErr().toString());
}

// not recommended, bbut you can restore the default behavior, which might just throw
const value = resultValue.unwrap();

// do sth. with value
```

**Comment by wubzz** [comment]
Yup, missing a `.catch` handler. Finding the relevant code that builds the query and is lacking a handler surely shouldn't be a problem. If it is, then try this: http://bluebirdjs.com/docs/api/promise.longstacktraces.html

You then need to discover when/how/why any of those bindings would be `undefined` and prevent it from happening.
