### ISSUE TITLE
Call to knex.migrate.currentVersion causes an error

### ISSUE THREAD

**Issue by maxkoryukov** [tgriesser/knex#2111]
I use **knex.migrate** for DB-migrations , and after each migration I call `knex.migrate.currentVersion(migrationConfig)` to get the new version of DB. Passing a `migrationConfig` argument is possible, if the [documentation](http://knexjs.org/#Migrations-currentVersion) is correct.

But after updating knex to version `0.13.0` I get an error:

```
Unhandled rejection TypeError: Cannot read property 'hasTable' of undefined
    at Migrator._ensureTable (/home/user/projects/demo/node_modules/knex/lib/migrate/index.js:248:22)
    at Migrator._listCompleted (/home/user/projects/demo/node_modules/knex/lib/migrate/index.js:394:17)
    at Migrator.currentVersion (/home/user/projects/demo/node_modules/knex/lib/migrate/index.js:177:17)
    at mycli.knex.migrate.latest.then (/home/user/projects/demo/bin/cli.js:87:29)
    at tryCatcher (/home/user/projects/demo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/user/projects/demo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/user/projects/demo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/user/projects/demo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/user/projects/demo/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/user/projects/demo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/user/projects/demo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/user/projects/demo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

After short debugging, I found, that the bug is caused by changes in this file (and line): https://github.com/tgriesser/knex/blame/master/src/migrate/index.js#L261

Old code:

```js
  // Lists all migrations that have been completed for the current db, as an
  // array.
  _listCompleted() {
    const { tableName } = this.config
```

New version

```js
  // Lists all migrations that have been completed for the current db, as an
  // array.
  _listCompleted(trx = this.knex) {
    const { tableName } = this.config
```

In old version there was no params for methos `_listCompleted`, in new version - there is a `trx` param. Old version of code always used `this.knex`, and new version use passed `trx` param first.

I don't know, why you have added this param, but this patch is the reason of this bug.

**Comment by gsavin** [comment]
I think the trouble is more in the `currentVersion` function (cf. line 92), where the `config` object should not be passed as a parameter of `_listCompleted`.

**Comment by maxkoryukov** [comment]
@gsavin thanks, may be. I am not an expert in knex, and all my debug - is just a first glance..

**Comment by maxkoryukov** [comment]
Any news?

**Comment by b-gran** [comment]
If anyone is looking for a "user-space" workaround for this function while we wait for the fix to be merged, here's an implementation of `currentVersion` that doesn't require modifying the `knex` package or overriding any `node_modules` files:

```
// Implementation of migrate#currentVersion
const currentVersion_patched = (cfg, migrate) => {
  migrate.config = migrate.setConfig(cfg);
  return migrate._listCompleted().then(completed => {
    const val = Math.max(...completed.map(value => value.split('_')[0]));
    return val === undefined ? 'none' : val;
  });
};

// Usage:
const db = knex(config);
const version = await currentVersion_patched(config, db.migrate);

// Equivalent to:
const db = knex(config);
const version = await db.migrate.currentVersion(config);
```
