### ISSUE TITLE
Catch error on initial connection

### ISSUE THREAD

**Issue by wayne-nlt** [tgriesser/knex#2143]
Hi,
We have been writing a server that has an optional knex connection.
We would like to be able to ignore this connection if there is an error when connecting.
For example, an access denied message:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Access denied for user ''@'localhost' (using password: NO)
    at Packet.asError (/xxx/node_modules/mysql2/lib/packets/packet.js:497:13)
    at ClientHandshake.Command.execute (/xxx/node_modules/mysql2/lib/commands/command.js:25:22)
    at Connection.handlePacket (/xxx/node_modules/mysql2/lib/connection.js:310:28)
    at PacketParser.onPacket (/xxx/node_modules/mysql2/lib/connection.js:83:65)
    at PacketParser.executeStart (/xxx/node_modules/mysql2/lib/packet_parser.js:39:12)
    at Socket.<anonymous> (/xxx/node_modules/mysql2/lib/connection.js:95:31)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

We have tried a try catch block on the initial connection, adding an error handler to the instance, and also in the afterCreate callback, but none of this works.

This is an unhandled exception, and causes the app to crash, is there any way to catch this event?
Thanks!

**Comment by elhigu** [comment]
Some related discussion is found here https://github.com/tgriesser/knex/issues/407 there might be also some other issue discussing this, but I couldn't find it. It would be great to be able to properly catch all errors. 

It is not so straight forward as one could thing, since pool is the one who decides when it tries to create connection.

**Comment by elhigu** [comment]
This should not happen anymore since `tarn` pool  does never autostart and fill connections on pool creation. So connection error is not thrown until the first query is done.

**Comment by jerrychong25** [comment]
In my case, I use this line of code to catch knex connection error

`if (!knex.pool) throw new Error('Not connected')`

**Comment by elhigu** [comment]
@jerrychong25 that doesn't work. Pool instance is created even if it is never able to connect to the DB. IIRC that is removed only if knex.destroy() is called.
