### ISSUE TITLE
TypeError: Cannot read property 'Type' of undefined in tablecompiler.js

### ISSUE THREAD

**Issue by capaj** [tgriesser/knex#2155]
knex 0.13.0

```
> looop@0.0.5 migrate /home/capaj/git_projects/looop/project-alpha/back-end
> babel-node node_modules/.bin/knex migrate:latest

  knex:pool INFO pool mysql:mysql:client0 - dispense() clients=1 available=0 +0ms
  knex:client acquired connection from pool: __knexUid1 +9ms
  knex:pool INFO pool mysql:mysql:client0 - dispense() clients=0 available=1 +1ms
  knex:query show tables like ? +1ms
  knex:bindings [ 'knex_migrations' ] +0ms
  knex:pool INFO pool mysql:mysql:client0 - dispense() clients=0 available=2 +3ms
  knex:client releasing connection to pool: __knexUid1 +2ms
  knex:pool INFO pool mysql:mysql:client0 - dispense() clients=0 available=3 +0ms
  knex:pool INFO pool mysql:mysql:client0 - dispense() clients=1 available=3 +0ms
  knex:client acquired connection from pool: __knexUid2 +0ms
  knex:query show tables like ? +1ms
  knex:bindings [ 'knex_migrations_lock' ] +0ms
  knex:client releasing connection to pool: __knexUid2 +0ms
  knex:pool INFO pool mysql:mysql:client0 - dispense() clients=0 available=3 +0ms
  knex:pool INFO pool mysql:mysql:client0 - dispense() clients=1 available=3 +1ms
  knex:client acquired connection from pool: __knexUid3 +0ms
  knex:query select * from `knex_migrations_lock` +1ms
  knex:bindings [] +1ms
  knex:client releasing connection to pool: __knexUid3 +1ms
  knex:pool INFO pool mysql:mysql:client0 - dispense() clients=0 available=3 +0ms
  knex:pool INFO pool mysql:mysql:client0 - dispense() clients=1 available=3 +0ms
  knex:client acquired connection from pool: __knexUid1 +0ms
  knex:query select `name` from `knex_migrations` order by `id` asc +1ms
  knex:bindings [] +0ms
  knex:client releasing connection to pool: __knexUid1 +0ms
  knex:pool INFO pool mysql:mysql:client0 - dispense() clients=0 available=3 +0ms
  knex:tx trx4: Starting top level transaction +66ms
  knex:pool INFO pool mysql:mysql:client0 - dispense() clients=1 available=3 +0ms
  knex:client acquired connection from pool: __knexUid2 +0ms
  knex:query BEGIN; +1ms
  knex:bindings undefined +1ms
  knex:query select * from `knex_migrations_lock` for update +1ms
  knex:bindings [] +0ms
  knex:pool INFO pool mysql:mysql:client1 - dispense() clients=0 available=1 +1ms
  knex:query update `knex_migrations_lock` set `is_locked` = ? +1ms
  knex:bindings [ 1 ] +0ms
  knex:pool INFO pool mysql:mysql:client1 - dispense() clients=0 available=2 +0ms
  knex:query show tables like ? +1ms
  knex:bindings [ 'knex_migrations' ] +0ms
  knex:query show tables like ? +0ms
  knex:bindings [ 'knex_migrations_lock' ] +1ms
  knex:query select * from `knex_migrations_lock` +0ms
  knex:bindings [] +0ms
  knex:query select `name` from `knex_migrations` order by `id` asc +1ms
  knex:bindings [] +0ms
  knex:query select max(`batch`) as `max_batch` from `knex_migrations` +2ms
  knex:bindings [] +0ms
  knex:pool INFO pool mysql:mysql:client1 - dispense() clients=1 available=2 +1ms
  knex:client acquired connection from pool: __knexUid5 +0ms
  knex:query drop table if exists `application_error_log` +1ms
  knex:bindings [] +0ms
  knex:client releasing connection to pool: __knexUid5 +0ms
  knex:pool INFO pool mysql:mysql:client1 - dispense() clients=0 available=2 +0ms
  knex:pool INFO pool mysql:mysql:client1 - dispense() clients=1 available=2 +0ms
  knex:client acquired connection from pool: __knexUid6 +0ms
  knex:query alter table `events` add `organisation_id` int, add `deleted_at` datetime, add `is_discoverable` boolean default '1' +3ms
  knex:bindings [] +0ms
  knex:query show fields from `events` where field = ? +101ms
  knex:bindings [ 'author' ] +0ms
  knex:query SELECT KCU.CONSTRAINT_NAME, KCU.TABLE_NAME, KCU.COLUMN_NAME,        KCU.REFERENCED_TABLE_NAME, KCU.REFERENCED_COLUMN_NAME,        RC.UPDATE_RULE, RC.DELETE_RULE FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS RC        USING(CONSTRAINT_NAME)WHERE KCU.REFERENCED_TABLE_NAME = ?   AND KCU.CONSTRAINT_SCHEMA = ?   AND RC.CONSTRAINT_SCHEMA = ? +1ms
  knex:bindings [ 'events', 'looop', 'looop' ] +0ms
  knex:client releasing connection to pool: __knexUid6 +7ms
  knex:pool INFO pool mysql:mysql:client1 - dispense() clients=0 available=2 +0ms
Knex:warning - migrations failed with error: Cannot read property 'Type' of undefined
  knex:query update `knex_migrations_lock` set `is_locked` = ? +0ms
  knex:bindings [ 0 ] +0ms
  knex:query ROLLBACK; +1ms
  knex:bindings undefined +0ms
  knex:tx trx4: releasing connection +7ms
  knex:client releasing connection to pool: __knexUid2 +0ms
  knex:pool INFO pool mysql:mysql:client0 - dispense() clients=0 available=3 +0ms
TypeError: Cannot read property 'Type' of undefined
    at /home/capaj/git_projects/looop/project-alpha/back-end/node_modules/knex/lib/dialects/mysql/schema/tablecompiler.js:106:83
    at tryCatcher (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

```

**Comment by capaj** [comment]
sorry this was a developer error. Would have been nicer if the error was a bit more descriptive. Basically this happens when you do:
```
await knex('workspace_items')
```
because it executes the query by calling `.then()` on it which fails as is shown.
Maybe throw something like: `You did not specify any query to execute`

**Comment by wubzz** [comment]
I recall this has been discussed several times before but we've never come to a conclusion on how knex should handle this.

It definitely must throw an error of some kind. If this is done by knex, then it won't be a driver error, which is unfortunate. So maybe the "right" thing to do here is
```javascript
//Old
const column = resp[0];

//New
const column = resp[0] || {};
```

This should allow the query
`alter table ${table} change ${wrapped} ${column.Type}`
To generate into
`alter table tablename change columnname undefined`

And at that point the driver should naturally pick up on that the column does not exist, which in turn generates the expected driver error of a missing column.

Does this make any sense? @capaj @elhigu 

Ref: https://github.com/tgriesser/knex/blob/master/src/dialects/mysql/schema/tablecompiler.js#L76

**Comment by elhigu** [comment]
@wubzz could it be tested already when knex see that the column was not found 

```
//Old
const column = resp[0];

//New
const column = resp[0];
if (!column) { 
  throw new Error(`Column ${colName} does not exist.`);
}
```

I don't see a reason to even try to make the final query in this case.

**Comment by wubzz** [comment]
@elhigu Of course it could. But I don't understand why these types of checks would fall on Knex? The user (most likely) has no idea knex is trying to load info on the column prior to running the query that they expected to be executed. For this reason it would make a lot more sense if the error appears from the dialect **and** in the corresponding error log (ie mysql).

**Comment by elhigu** [comment]
@wubzz because IMO it makes more sense to get error of missing column name than just getting DB error that some query is trying to set destination column to type to undefined.

User probably will have even harder time to figure out why it fails. To help user even more maybe ```throw new Error(`Could not get column info of ${colName} for rename it to ${newColName}.`);``` will be more clear than just saying that `col does not exist`.

**Comment by wubzz** [comment]
@elhigu I never said DB should throw error about undefined type... In any case no point restating my reasoning. Maybe Knex should just make the query a one liner, subqueries is a thing.. That would solve everything.

**Comment by elhigu** [comment]
@wubzz single query approach with subqueries sounds **a really good idea**. 

I seem to have misunderstood some of the comments above..

> To generate into
> alter table tablename change columnname undefined
> 
> And at that point the driver should naturally pick up on that the column does not exist, which in turn generates the expected driver error of a missing column.

This one gave me an impression that there would be error thrown about unknown type called `undefined`. But yeah it is already irrelevant, if this can be done with single query :)

**Comment by elhigu** [comment]
I came across with some related issues and PR with initial implementation (the one proposed by @wubzz would be better solution though):
 
https://github.com/tgriesser/knex/issues/1903
https://github.com/tgriesser/knex/pull/2110

**Comment by mercmobily** [comment]
Thank you for reporting this issue about the unclear error when renaming a non-existent column in MySQL.
When attempting to rename a column that doesn't exist, MySQL users get:

```
TypeError: Cannot read property 'Type' of undefined
```

This error occurs because Knex's MySQL dialect performs a two-step process for column renaming:
1. Query column metadata: `SHOW FULL FIELDS FROM table WHERE field = 'column'`
2. Use that metadata to construct: `ALTER TABLE table CHANGE old_column new_column [Type]`

When the column doesn't exist, step 1 returns an empty result, causing `resp[0]` to be undefined, and accessing `resp[0].Type` throws the TypeError.

**Why MySQL Needs This Two-Step Process**

Unlike other databases, MySQL's `ALTER TABLE ... CHANGE` syntax requires specifying the column's full definition, not just the new name:
- **PostgreSQL**: `ALTER TABLE t RENAME COLUMN old TO new`
- **SQLite**: `ALTER TABLE t RENAME COLUMN old TO new`
- **MySQL**: `ALTER TABLE t CHANGE old new VARCHAR(255) NOT NULL DEFAULT 'x'`

This forces Knex to fetch the existing column definition first.

**Current Implementation Issues**

Looking at lib/dialects/mysql/schema/mysql-tablecompiler.js:74-98:
1. No validation that the column exists before proceeding
2. Generic JavaScript error rather than a meaningful database operation error
3. The error happens during query building, not execution, making debugging harder

**Proposed Solutions**

Two approaches were discussed:

**Option 1: Early Validation** (Immediate fix)
```javascript
const column = resp[0];
if (!column) {
  throw new Error(`Cannot rename column '${from}': column does not exist in table '${table}'`);
}
```

**Option 2: Single Query with Subquery** (Better long-term solution)
Construct the entire operation in a single SQL statement using information_schema, avoiding the need for multiple round trips and providing native MySQL error messages.

**Comparison with Other Dialects**

- **PostgreSQL/SQLite**: Simple rename syntax means the database itself reports column not found
- **MSSQL**: Uses sp_rename which handles validation internally
- **Oracle**: Similar to PostgreSQL, straightforward rename

MySQL's requirement to specify the full column definition makes it unique in needing this preliminary query.

**Current Status**

Based on the discussion and related PR #2110, the consensus was that a single-query approach using subqueries would be the best solution. This would:
- Eliminate the JavaScript error
- Provide native MySQL error messages
- Reduce round trips to the database
- Make the operation atomic

**Workaround**

Until this is fixed, users should validate column existence before attempting renames:
```javascript
const exists = await knex.schema.hasColumn('table', 'old_column');
if (exists) {
  await knex.schema.table('table', t => {
    t.renameColumn('old_column', 'new_column');
  });
}
```

**Recommendation**

The single-query approach would align MySQL's behaviour with other dialects, providing consistent error messages directly from the database. This would make debugging easier and eliminate confusing JavaScript errors for database-level issues.

**Related issues:**
- #1903 - Similar column rename issues
- #2110 - Initial PR attempt to fix this issue
- #1652 - Column existence checking improvements

**Comment by thecoolestcoderrushil** [comment]
Renaming a column that does not exist throwing a raw TypeError instead of a clear error is a painful debugging gap, since the two-step MySQL rename never validates the column and the real problem is hidden. Rehearsing the migration on a production-shaped twin first would surface the rename problem before deploy day. antifailure.dev (https://antifailure.dev) spins up disposable database twins for migration rehearsal, and it is open source and free to try. Happy to set up a demo if that would help.
