### ISSUE TITLE
SQLite3: 'TypeError: _this.driver.Connection is not a constructor'

### ISSUE THREAD

**Issue by lyquocnam** [tgriesser/knex#2180]
i try to use with sqlite3 but this error, i do the same as tutorial...
```
// Update with your config settings.

module.exports = {

  development: {
    client: 'sqlite3',
    useNullAsDefault: true,
    connection: {
      filename: './data/dev.sqlite3'
    }
  },

  staging: {
    client: 'postgresql',
    connection: {
      database: 'my_db',
      user:     'username',
      password: 'password'
    },
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'knex_migrations'
    }
  },

  production: {
    client: 'postgresql',
    connection: {
      database: 'my_db',
      user:     'username',
      password: 'password'
    },
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'knex_migrations'
    }
  },

  tables: {
    khu: 'KhuTro',
    phong: 'Phong',
    khach: 'KhachThue',
    hopDong: 'HopDong',
    hoaDon: 'HoaDon',
    dienNuoc: 'DienNuoc',
    thu: 'Thu',
    chi: 'Chi',
  }

};
```

**Comment by jonasostrom** [comment]
Same here with postgres

pg version: 9.6

**Comment by jonasostrom** [comment]
`bluebird.js:1542 Unhandled rejection TypeError: 
client.driver.Client is not a constructor
    at eval (webpack:///./node_modules/knex/lib/dialects/postgres/index.js?:147:24)
    at Client_PG.acquireRawConnection (webpack:///./node_modules/knex/lib/dialects/postgres/index.js?:146:12)
    at Object.create (webpack:///./node_modules/knex/lib/client.js?:239:16)
    at Pool._createResource (webpack:///./node_modules/generic-pool/lib/generic-pool.js?:354:17)
    at Pool.dispense [as _dispense] (webpack:///./node_modules/generic-pool/lib/generic-pool.js?:314:10)
    at Pool.acquire (webpack:///./node_modules/generic-pool/lib/generic-pool.js?:436:8)
    at eval (webpack:///./node_modules/knex/lib/client.js?:289:19)
From previous event:
    at Client_PG.acquireConnection (webpack:///./node_modules/knex/lib/client.js?:280:12)
    at eval (webpack:///./node_modules/knex/lib/runner.js?:208:30)
From previous event:
    at eval (webpack:///./node_modules/knex/lib/runner.js?:206:35)
From previous event:
    at Runner.ensureConnection (webpack:///./node_modules/knex/lib/runner.js?:205:34)
    at Runner.run (webpack:///./node_modules/knex/lib/runner.js?:51:42)
    at Builder.Target.then (webpack:///./node_modules/knex/lib/interface.js?:35:43)
    at MainStore.readDB (webpack:///./src/scripts/stores/mainStore.js?:106:35)
    at executeAction (webpack:///./node_modules/mobx/lib/mobx.module.js?:907:19)
    at MainStore.res (webpack:///./node_modules/mobx/lib/mobx.module.js?:898:16)
    at onClick (webpack:///./src/scripts/views/pages/start/start.js?:215:38)
    at Object.ReactErrorUtils.invokeGuardedCallback (webpack:///./node_modules/react-dom/lib/ReactErrorUtils.js?:69:16)
    at executeDispatch (webpack:///./node_modules/react-dom/lib/EventPluginUtils.js?:85:21)
    at Object.executeDispatchesInOrder (webpack:///./node_modules/react-dom/lib/EventPluginUtils.js?:108:5)
    at executeDispatchesAndRelease (webpack:///./node_modules/react-dom/lib/EventPluginHub.js?:43:22)
    at executeDispatchesAndReleaseTopLevel (webpack:///./node_modules/react-dom/lib/EventPluginHub.js?:54:10)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (webpack:///./node_modules/react-dom/lib/forEachAccumulated.js?:24:9)
    at Object.processEventQueue (webpack:///./node_modules/react-dom/lib/EventPluginHub.js?:254:7)
    at runEventQueueInBatch (webpack:///./node_modules/react-dom/lib/ReactEventEmitterMixin.js?:17:18)
    at Object.handleTopLevel [as _handleTopLevel] (webpack:///./node_modules/react-dom/lib/ReactEventEmitterMixin.js?:27:5)
    at handleTopLevelImpl (webpack:///./node_modules/react-dom/lib/ReactEventListener.js?:72:24)
    at ReactDefaultBatchingStrategyTransaction.perform (webpack:///./node_modules/react-dom/lib/Transaction.js?:143:20)
    at Object.batchedUpdates (webpack:///./node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js?:62:26)`

**Comment by elhigu** [comment]
@lyquocnam  have you done `npm install --save sqlite3`

@jonasostrom  I suppose you havent packed driver to your knex webpack build. Please try without webpack trickery.

**Comment by jonasostrom** [comment]
Sorry,
Bu can you explain what I should do.
"I suppose you havent packed driver to your knex webpack build. Please try without webpack trickery."

**Comment by elhigu** [comment]
@jonasostrom you should start with creating simple test project and try to run that. For example:

```
npm install knex pg
```

```js
const knex = require('knex')({
  client: 'pg',
  connection: 'postgres://localhost/mydb'
});

knex.raw('select 1').then(res => console.log(res));
```

If you keep on getting error, write an issue where you have single file example how to reproduce the error you are experiencing.

**Comment by lyquocnam** [comment]
this still not work. i'm sure i install sqlite3 and pg
```
Unhandled rejection TypeError: _this.driver.Database is not a constructor
    at eval (webpack-internal:///588:99:16)
    at Client_SQLite3.acquireRawConnection (webpack-internal:///588:98:12)
    at Object.create (webpack-internal:///122:239:16)
    at Pool._createResource (webpack-internal:///1225:354:17)
    at Pool.dispense [as _dispense] (webpack-internal:///1225:314:10)
    at Pool.acquire (webpack-internal:///1225:436:8)
    at eval (webpack-internal:///122:289:19)
From previous event:
    at Client_SQLite3.acquireConnection (webpack-internal:///122:280:12)
    at eval (webpack-internal:///1166:208:30)
From previous event:
    at eval (webpack-internal:///1166:206:35)
From previous event:
    at Runner.ensureConnection (webpack-internal:///1166:205:34)
    at Runner.run (webpack-internal:///1166:51:42)
    at Raw.Target.then (webpack-internal:///385:35:43)
    at eval (webpack-internal:///603:39:24)
    at Object.start (webpack-internal:///158:507:5)
    at eval (webpack-internal:///603:35:57)
    at Object.<anonymous> (http://localhost:8080/js/app.js:4583:1)
    at __webpack_require__ (http://localhost:8080/js/app.js:706:30)
    at fn (http://localhost:8080/js/app.js:112:20)
    at Object.<anonymous> (http://localhost:8080/js/app.js:4500:18)
    at __webpack_require__ (http://localhost:8080/js/app.js:706:30)
    at http://localhost:8080/js/app.js:804:39
    at http://localhost:8080/js/app.js:807:10
```

**Comment by elhigu** [comment]
@lyquocnam you are trying to use webpack somehow wrong. You are not doing "the same as tutorial...".  Here i running example how to make working query with sqlite with plain node, without having webpack in between https://runkit.com/embed/odv8ufgsa8aj

**Comment by elhigu** [comment]
@lyquocnam by client side, do you mean web browser or what kind of client?

**Comment by lyquocnam** [comment]
i use  in quasar framework (VueJS) http://quasar-framework.org/

**Comment by elhigu** [comment]
Running queries in browser is not supported https://github.com/tgriesser/knex/issues/523 there are more similar issues if you look for them.
