### ISSUE TITLE
Oracle connection issues

### ISSUE THREAD

**Issue by marcelotmagalhaes** [tgriesser/knex#2216]
Hello everyone. I'm trying to create an oracle connection, but is seriously lacking some support in the docs... I've tried the following:

./config/knex.js
`const knex = require('knex');

const conn = knex({
	client: 'oracle',
	connection: {
		host: process.env.ORACLE_HOST,
		user: process.env.ORACLE_USER,
		password: process.env.ORACLE_PASS,
		database: process.env.ORACLE_DB
	}
});

module.exports = conn;`

index.js
`const conn = require('./config/knex');

app.get('/api/send', sendRequest);

function sendRequest(req, res, next) {
	conn.raw('select 1 from dual').then(result => {
		res.send(result);
	});
}`

package.json
`"knex": "^0.13.0",
    "oracle": "^0.4.1",
    "oracledb": "^1.13.1",`

I only had the oracledb dependency before, but when I tried to run the project appeared an error saying that I had to install oracle too. So I installed it, now a warning appears when the project starts:
`This node-oracle driver is obsolete.  Oracle has a new driver: https://github.com/oracle/node-oracledb.
Please install the new driver with 'npm install oracledb', see https://github.com/oracle/node-oracledb/blob/master/INSTALL.md
If you absolutely need the old driver, use 'npm install oracle@0.3.9'
✓ App is running at http://localhost:5000 in development mode
  Press CTRL-C to stop
`

And when I access the endpoint, this error appears:
`Unhandled rejection TypeError: _this2.driver.connect is not a function
    at /Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/knex/lib/dialects/oracle/index.js:139:21
    at Promise._execute (/Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_Oracle.acquireRawConnection (/Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/knex/lib/dialects/oracle/index.js:138:12)
    at Object.create (/Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (/Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool.dispense [as _dispense] (/Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/generic-pool/lib/generic-pool.js:314:10)
    at Pool.acquire (/Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/generic-pool/lib/generic-pool.js:436:8)
    at /Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/knex/lib/client.js:289:19
    at Promise._execute (/Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_Oracle.acquireConnection (/Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/knex/lib/client.js:280:12)
    at /Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/knex/lib/runner.js:208:30
    at Promise._execute (/Users/marcelomagalhaes/Projects/Clientes/Internos/Comercial/server/node_modules/bluebird/js/release/debuggability.js:300:9)`

Can anyone point some tutorial or example on how to create a connection with oracle?

Just to clarify, the connection is fully working, I was using it with the raw oracledb driver before trying knex.

**Comment by marcelotmagalhaes** [comment]
Just a big gigantic enormous lack of atention from me...

`client: 'oracledb',`

This solved... 
Sorry for this...
