### ISSUE TITLE
Cannot add foreign key constraint when create tables

### ISSUE THREAD

**Issue by dxcqcv** [tgriesser/knex#2234]
OS: win7
sql: mysql 5.7
ORM: Objection.js
node.js version: 7.6.0

knex migrate js file is
```
exports.up = function(knex, Promise) {
  return knex.schema
    .createTable('attributes', function (table) {
      table.increments('id').primary().notNullable()
      table.integer('pid').notNullable()
      table.string('position').notNullable()
      table.string('value').notNullable()
      table.foreign('pid').references('id').inTable('projects').onDelete('CASCADE').onUpdate('RESTRICT')
    })
    .createTable('rules', function (table) {
      table.increments('id').primary().notNullable()
      table.integer('pid').notNullable()
      table.string('position').notNullable()
      table.text('value').notNullable()
      table.foreign('pid').references('id').inTable('projects').onDelete('CASCADE').onUpdate('RESTRICT')
    })
};

exports.down = function(knex, Promise) {
  return knex.schema
    .dropTableIfExists('attributes')
    .dropTableIfExists('rules')
};
```

error code:
```
$ knex --knexfile=./server/config/knexfile.js migrate:latest
Working directory changed to D:\dev\github\auto-activity\server\config
Knex:warning - migrations failed with error: alter table `attributes` add constraint `attributes_pid_foreign` foreign key (`pid`) references `projects` (`id`) on update RESTRICT on delete CASCADE - ER_CANNOT_ADD_FOREIGN: Cannot add foreign key constraint
Error: ER_CANNOT_ADD_FOREIGN: Cannot add foreign key constraint
    at Query.Sequence._packetToError (D:\dev\github\auto-activity\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (D:\dev\github\auto-activity\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\dev\github\auto-activity\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (D:\dev\github\auto-activity\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (D:\dev\github\auto-activity\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\dev\github\auto-activity\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
    --------------------
    at Protocol._enqueue (D:\dev\github\auto-activity\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at Connection.query (D:\dev\github\auto-activity\node_modules\mysql\lib\Connection.js:208:25)
    at D:\dev\github\auto-activity\node_modules\knex\lib\dialects\mysql\index.js:152:18
    at Promise._execute (D:\dev\github\auto-activity\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (D:\dev\github\auto-activity\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (D:\dev\github\auto-activity\node_modules\bluebird\js\release\promise.js:79:10)
    at Client_MySQL._query (D:\dev\github\auto-activity\node_modules\knex\lib\dialects\mysql\index.js:146:12)
    at Client_MySQL.query (D:\dev\github\auto-activity\node_modules\knex\lib\client.js:197:17)
    at D:\dev\github\auto-activity\node_modules\knex\lib\transaction.js:274:21
    at tryCatcher (D:\dev\github\auto-activity\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (D:\dev\github\auto-activity\node_modules\bluebird\js\release\method.js:39:29)
    at Client_MySQL.trxClient.query (D:\dev\github\auto-activity\node_modules\knex\lib\transaction.js:271:34)
    at Runner.<anonymous> (D:\dev\github\auto-activity\node_modules\knex\lib\runner.js:146:36)
    at Runner.tryCatcher (D:\dev\github\auto-activity\node_modules\bluebird\js\release\util.js:16:23)
    at Runner.query (D:\dev\github\auto-activity\node_modules\bluebird\js\release\method.js:15:34)
    at Runner.<anonymous> (D:\dev\github\auto-activity\node_modules\knex\lib\runner.js:193:19)
error Command failed with exit code 1.

```

**Comment by elhigu** [comment]
I usually create foreign keys like this:

```js
table.biginteger('otherTableId').unsigned().notNullable().references('id').inTable('OtherTable').onDelete('CASCADE').index();
```

Your error is thrown by mysql database when running query:

```
alter table `attributes` add constraint `attributes_pid_foreign` foreign key (`pid`) references `projects` (`id`) on update RESTRICT on delete CASCADE;
```

you can log in to your DB, check your schema how it looks like and try to run that query manually to be able to figure out what is wrong and why that query fails.

Maybe you need to add unsigned() to your pid column type, like this guy had to https://github.com/tgriesser/knex/issues/1059

**Comment by elhigu** [comment]
Anyways, this doesn't look like a knex builder bug so closing. We can continue discussion here though (I get email notifications from all the comments).

**Comment by dxcqcv** [comment]
solve the problem with to add unsigned() to my pid column type, thank you very much.

**Comment by GAumala** [comment]
I think it would be nice if knex had something like `.foreignIncrements([name])` which under the hood does the same as `.integer([name]).unsigned().notNullable()`. 

From reading the documentation, it is not obvious that `.increments()` sets these constraints. If the user needs to understand the `.increments()` implementation in order to reference it in another table, then it is a bad abstraction IMO. 

Would you guys approve such feature?

**Comment by elhigu** [comment]
@GAumala I wouldn't.  

1. `.integer([name]).unsigned().notNullable()` is a bit too opinionated, since `notNullable()` is not something one always likes to have for foreign keys, but index usually is, except for those who doesn't want that either.
2. For consistency one should add similar helper for bigincrements 
3. Name sounds kind of confusing since it doesn't create really incrementing column (I understand that is meant to be counter part for increments() column, but still). 

But even that all the 3 notes would be fixed I would hesitate to add another way to do the same thing, which is only slightly easier and could be resolved by better documentation. 

What I would like would be that someone would write these kind of small set of well designed helpers to some separate helper library, where you can easily use them between projects. 

Even better would be if that set would be well designed consistent set of helpers where for example primary key generation and foreign key references would have understandable names and defaults. 

That could be a higher level API for schema operations, when `knex` just implements lowest SQL level of the abstraction. I would love to see package like that, instead of making small patches to current schema API which really cant go very far from abstracting plain SQL 1:1 to its builder format.

If all the new stuff would be implemented directly to knex it would be end up as really bad and confusing API, since we really cannot drop the old schema functionality because there is so much migration code, which relays on current API.

Improvements to the documentation would be also great.

**Comment by GAumala** [comment]
Fair enough, I'll try to submit PRs to the documentation repo.
