### ISSUE TITLE
EACCES when using socket and requesting more eager expressions than min connections

### ISSUE THREAD

**Issue by amosyuen** [tgriesser/knex#2256]
I'm using objection v0.8.9 and knex 0.13.0 in a docker linux container on Windows.

When I make a request that has a more eager expressions than the default pool connections in knex, it gives me this error:
```
Error: connect EACCES /var/lib/mysql/mysql.sock
    at Object._errnoException (util.js:1019:11)
    at _exceptionWithHostPort (util.js:1041:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
From previous event:
    at Client_MySQL2.acquireRawConnection (/code/api/src/node_modules/knex/lib/dialects/mysql2/index.js:74:12)
    at Object.create (/code/api/src/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (/code/api/src/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool.dispense [as _dispense] (/code/api/src/node_modules/generic-pool/lib/generic-pool.js:314:10)
    at Pool.acquire (/code/api/src/node_modules/generic-pool/lib/generic-pool.js:436:8)
    at /code/api/src/node_modules/knex/lib/client.js:289:19
From previous event:
    at Client_MySQL2.acquireConnection (/code/api/src/node_modules/knex/lib/client.js:280:12)
    at /code/api/src/node_modules/knex/lib/runner.js:208:30
From previous event:
    at /code/api/src/node_modules/knex/lib/runner.js:206:35
From previous event:
    at Runner.ensureConnection (/code/api/src/node_modules/knex/lib/runner.js:205:34)
    at Runner.run (/code/api/src/node_modules/knex/lib/runner.js:51:42)
    at Builder.Target.then (/code/api/src/node_modules/knex/lib/interface.js:35:43)
    at Builder.Target.(anonymous function) [as bind] (/code/api/src/node_modules/knex/lib/interface.js:85:26)
    at Object.<anonymous> (/code/api/src/node_modules/objection/lib/queryBuilder/QueryBuilder.js:512:31)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at QueryBuilder.execute (/code/api/src/node_modules/objection/lib/queryBuilder/QueryBuilder.js:497:20)
    at QueryBuilder.then (/code/api/src/node_modules/objection/lib/queryBuilder/QueryBuilder.js:393:26)
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

+ I'm using the default WhereInEagerAlgorithm
+ I'm connecting to mysql using a socket. If I use a host and port instead, there is no problem.
+ By default the knex config has a connection pool with min connections of 2 and max of 10. So if I request more 2 eager relations, the query works fine. If I request more than 2 it throws the above error. If I increase the min connection pool to 3, then I can request up to 3 eager relations.

I posted this also in Objection https://github.com/Vincit/objection.js/issues/540, but they think it's likely a bug on knex / mysql level.

**Comment by elhigu** [comment]
Try to run your code with DEBUG=knex:* variable what is happening with queries and then try to reproduce this without objection.

If you do just like 50 parallel selects or short wait statements, are you getting the same error?

**Comment by amosyuen** [comment]
I was able to repro by just doing 3 parallel queries. Using `DEBUG=knex:*`, I get this output right before the rror:

```
Sat, 07 Oct 2017 20:47:16 GMT knex:pool INFO pool mysql:mysql2:client0 - dispense() clients=0 available=1
api_1  | Sat, 07 Oct 2017 20:47:16 GMT knex:pool INFO pool mysql:mysql2:client0 - dispense() clients=0 available=2
api_1  | Sat, 07 Oct 2017 20:47:22 GMT knex:pool INFO pool mysql:mysql2:client0 - dispense() clients=1 available=2
api_1  | Sat, 07 Oct 2017 20:47:22 GMT knex:client acquired connection from pool: __knexUid1
api_1  | Sat, 07 Oct 2017 20:47:22 GMT knex:pool INFO pool mysql:mysql2:client0 - dispense() clients=1 available=1
api_1  | Sat, 07 Oct 2017 20:47:22 GMT knex:client acquired connection from pool: __knexUid2
api_1  | Sat, 07 Oct 2017 20:47:22 GMT knex:pool INFO pool mysql:mysql2:client0 - dispense() clients=1 available=0
api_1  | Sat, 07 Oct 2017 20:47:22 GMT knex:query select * from `Home`
api_1  | Sat, 07 Oct 2017 20:47:22 GMT knex:bindings []
api_1  | Sat, 07 Oct 2017 20:47:22 GMT knex:query select * from `User`
api_1  | Sat, 07 Oct 2017 20:47:22 GMT knex:bindings []
api_1  | Sat, 07 Oct 2017 20:47:22 GMT knex:client releasing connection to pool: __knexUid2
api_1  | Sat, 07 Oct 2017 20:47:22 GMT knex:pool INFO pool mysql:mysql2:client0 - dispense() clients=0 available=1
api_1  | Sat, 07 Oct 2017 20:47:22 GMT knex:pool INFO pool mysql:mysql2:client0 - dispense() clients=0 available=1
```

**Comment by amosyuen** [comment]
I can try to create a single file repro. It's entirely possible this might be caused by something windows or docker specific.

**Comment by amosyuen** [comment]
Huh this is kind of mysterious. Using the same knexfile I don't run into the error when I do the exact some 3 parallel queries using a knex seed file. But I do when running the query from the webserver.

**Comment by amosyuen** [comment]
OK, I found the problem. I had copied some code that removes root privileges after starting the server so as to restrict the privileges by running.

```js
process.setegid('node');
process.seteuid('node');
```

Seems like root access is needed to open new connections on the socket. Removing those lines fixes the problem.
