### ISSUE TITLE
Failed migrations due to thrown errors should log which migration failed

### ISSUE THREAD

**Issue by davidfurlong** [tgriesser/knex#2269]
I currently receive an error such as: (but what I really need to know is which migration caused this error)

```
Using environment: production
       Knex:warning - migrations failed with error: alter table "job_applications" add constraint "job_applications_job_location_id_foreign" foreign key ("job_location_id") references "job_locations" ("id") - column "job_location_id" referenced in foreign key constraint does not exist
       error: column "job_location_id" referenced in foreign key constraint does not exist
       at Connection.parseE (/tmp/build_853109ad51913a5b81dfa39b4e299753/node_modules/pg/lib/connection.js:546:11)
       at Connection.parseMessage (/tmp/build_853109ad51913a5b81dfa39b4e299753/node_modules/pg/lib/connection.js:371:19)
       at TLSSocket.<anonymous> (/tmp/build_853109ad51913a5b81dfa39b4e299753/node_modules/pg/lib/connection.js:114:22)
       at emitOne (events.js:115:13)
       at TLSSocket.emit (events.js:210:7)
       at addChunk (_stream_readable.js:266:12)
       at readableAddChunk (_stream_readable.js:253:11)
       at TLSSocket.Readable.push (_stream_readable.js:211:10)
       at TLSWrap.onread (net.js:585:20)
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! deedmob-api@0.9.0 postinstall: `knex migrate:latest`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the deedmob-api@0.9.0 postinstall script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /app/.npm/_logs/2017-10-16T12_30_29_150Z-debug.log
```

**Comment by elhigu** [comment]
Wouldn't hurt to have this data.
