### ISSUE TITLE
Knex TimeoutError when acquiring a connection

### ISSUE THREAD

**Issue by calebeaires** [tgriesser/knex#2317]
After the upgrade to knex 1.14 an single select starts to show this error message, then it stops to make database calls.

When I downgrade to 1.13, this errors is fixed.

knex conection config

```js
            return knex({
                client: 'mysql2',
                connection: {
                    host: conn.host,
                    user: conn.user,
                    password: conn.password,
                    database: conn.database,
                    port: conn.port,
                    multipleStatements: true
                }
            });
```

**The error**
```bash
ee { TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /home/ubuntu/app-one/node_modules/knex/lib/client.js:334:13
    at tryCatcher (/home/ubuntu/app-one/node_modules/bluebird/js/release/util.js:16:23)
    at /home/ubuntu/app-one/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/home/ubuntu/app-one/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/app-one/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/app-one/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/app-one/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/app-one/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/ubuntu/app-one/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ubuntu/app-one/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ubuntu/app-one/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5) sql: undefined, bindings: undefined }
```

**Comment by elhigu** [comment]
Please add complete test case and add results from DEBUG=knex:*. I cannot reproduce this.

```
knex = require('knex')({ client: 'mysql2', connection: { host: 'localhost', user: 'root', database: 'knex_test', multipleStatements: true } })

> knex.select(1).then((res) => console.log(res))
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> [ { '1': 1 } ]
```
