### ISSUE TITLE
Migration Failing

### ISSUE THREAD

**Issue by bsloan334** [tgriesser/knex#2327]
I am trying to migrate with knex and my code keeps failing. I get the following error after using the command 'knex migrate:latest --env development': 
`Using environment: development
Knex:warning - migrations failed with error: Invalid migration: connection.js must have both an up and down function
Error: Invalid migration: connection.js must have both an up and down function
    at Migrator._validateMigrationStructure (/Users/bertsloan/Desktop/node-koa-api/node_modules/knex/lib/migrate/index.js:378:13)
    at wrapper (/Users/bertsloan/Desktop/node-koa-api/node_modules/lodash/_createBind.js:23:15)
    at arrayMap (/Users/bertsloan/Desktop/node-koa-api/node_modules/lodash/_arrayMap.js:16:21)
    at map (/Users/bertsloan/Desktop/node-koa-api/node_modules/lodash/map.js:50:10)
    at /Users/bertsloan/Desktop/node-koa-api/node_modules/knex/lib/migrate/index.js:342:55
    at tryCatcher (/Users/bertsloan/Desktop/node-koa-api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/bertsloan/Desktop/node-koa-api/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/bertsloan/Desktop/node-koa-api/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/bertsloan/Desktop/node-koa-api/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/bertsloan/Desktop/node-koa-api/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/bertsloan/Desktop/node-koa-api/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/bertsloan/Desktop/node-koa-api/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/bertsloan/Desktop/node-koa-api/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)`

I have a connection.js file containing this:
`const environment = process.env.NODE_ENV || 'development';
const config = require('../../../../knexfile.js')[environment];

module.exports = require('knex')(config);`

What does this error mean and how could I fix it?

**Comment by elhigu** [comment]
Your migration file or knex configuration is not correct. Migration system is trying to run `connection.js` as migration.

**Comment by rwbrockhoff** [comment]
I recently ran into this issue and was able to resolve it by turning my exports.up and exports.down into an async function. I was doing async work in my functions without using async/await or promises. This resolved the same comment I was getting while running tests.

`exports.down = async function (knex, Promise) {
    await knex.schema.dropTable("name_of_your_table");
};`
