### ISSUE TITLE
could not determine data type of parameter

### ISSUE THREAD

**Issue by eBaeza** [tgriesser/knex#2330]
I'm trying to binding :clng, :clng, :meters and :type into

```
WHERE
  s.state = 1 AND lat IS NOT NULL AND is_active
  AND ROUND(CAST(ST_Distance_Sphere(ST_Centroid(ST_SetSRID(ST_Point(lng, lat), 4326)),
  ST_GeomFromText('POINT(:clng :clng)', 4326)) AS numeric), 2) <= :meters
AND type = :type
```
but I get an error:

```
{ error: could not determine data type of parameter $1
    at Connection.parseE (/Users/edgarbaeza/rappi-proys/grability-api/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/Users/edgarbaeza/rappi-proys/grability-api/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/Users/edgarbaeza/rappi-proys/grability-api/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
From previous event:
    at Client_PG._query (/Users/edgarbaeza/rappi-proys/grability-api/node_modules/knex/lib/dialects/postgres/index.js:239:12)
    at Client_PG.query (/Users/edgarbaeza/rappi-proys/grability-api/node_modules/knex/lib/client.js:197:17)
    at Runner.<anonymous> (/Users/edgarbaeza/rappi-proys/grability-api/node_modules/knex/lib/runner.js:146:36)
From previous event:
    at /Users/edgarbaeza/rappi-proys/grability-api/node_modules/knex/lib/runner.js:65:21
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Runner.run (/Users/edgarbaeza/rappi-proys/grability-api/node_modules/knex/lib/runner.js:51:31)
    at Raw.Target.then (/Users/edgarbaeza/rappi-proys/grability-api/node_modules/knex/lib/interface.js:35:43)
  name: 'error',
  length: 104,
  severity: 'ERROR',
  code: '42P18',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1324',
  routine: 'exec_parse_message' }
```

My js code is
` DB.raw(queries.getNearStoreKeepersQuery, { clng, clat, meters, type })`

**Comment by elhigu** [comment]
You are not showing the whole query that is created and not bindings that are passed to the query.

DB is saying that inputted data in not good I suppose. Cannot reproduce this.

**Comment by eBaeza** [comment]
@elhigu the whole query is this

```
```

**Comment by elhigu** [comment]
It still doesnt say what data is passed in clng and clat parameters. 

Also query.toSQL().toNative() output would be useful.

**Comment by eBaeza** [comment]
@elhigu when I use .toNative() i get an error `TypeError: READ.raw(...).toSQL(...).toNative is not a function` I do not know if it's because it's just a .raw()

**Comment by elhigu** [comment]
hmm.. yeah, probably because of that (which is actually a bug). Well you can get the plain toSQL() output so that I can see what data is passed to query.

**Comment by eBaeza** [comment]
@elhigu this the toSQL output
`
{ method: 'raw',
  sql: 'SELECT \n  s.id, \n  s.id || \' - \' || s.first_name || \' \' || s.last_name AS label, \n  type,\n  transport_media_type, \n  s.updated_at, \n  payment_type, \n  first_name, \n  last_name, \n  profile_pic, \n  telephone,\n  lat, \n  lng, \n  COUNT(o.id) AS orders_in_progress,\n  CASE \n    WHEN array_agg(o.id) = \'{null}\' \n    THEN NULL ELSE array_agg(o.id) \n  END AS order_ids,\n  pos_terminal, \n  has_delivery_kit\nFROM storekeepers s\nLEFT JOIN orders o\nON COALESCE(o.deliveryboy_id, o.storekeeper_id) = s.id\n  AND o.state IN(\'in_progress\', \'in_store\', \'on_the_route\', \'arrive\')\nWHERE s.state = 1 \n  AND lat IS NOT NULL \n  AND is_active\n  AND ROUND(CAST(ST_Distance_Sphere(\nST_Centroid(ST_SetSRID(ST_Point(lng, lat), 4326)),\n    ST_GeomFromText(\'POINT(? ?)\', 4326)\n  ) AS numeric), 2) <= ?\nAND type = ?\nGROUP BY 1,2,3,4,5,6,7,8,9,10,11',
  bindings: [ -99.165225, 19.427277, 1000, 'rt' ],
  options: {},
  __knexQueryUid: '43880af5-7ea5-4133-af8a-ebc4c8eeeb08' }
`
