### ISSUE TITLE
bundling failed: Error: require() must have a single string literal argument

### ISSUE THREAD

**Issue by santosh-indpro** [tgriesser/knex#2349]
# Environment

Knex version:0.14.1

When using knex inot any import statment as "import knex from 'knex';" in any react -native view.
The packager is throwing below mentioned exception.

error: bundling failed: Error: require() must have a single string literal argument
    at pushDependency (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/react-native/node_modules/metro-bundler/src/JSTransformer/worker/extract-dependencies.js:39:13)
    at CallExpression (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/react-native/node_modules/metro-bundler/src/JSTransformer/worker/extract-dependencies.js:50:9)
    at NodePath._call (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/babel-traverse/lib/index.js:114:17)
error: bundling failed: Error: require() must have a single string literal argument
    at pushDependency (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/react-native/node_modules/metro-bundler/src/JSTransformer/worker/extract-dependencies.js:39:13)
    at CallExpression (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/react-native/node_modules/metro-bundler/src/JSTransformer/worker/extract-dependencies.js:50:9)
    at NodePath._call (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/santoshkumar/Documents/GitHub/dreams-react-native/node_modules/babel-traverse/lib/index.js:114:17)

**Comment by elhigu** [comment]
Should it be?

```
import * as knex from 'knex';
```

Anyways this doesn't look like knex bug. Closing.
