### ISSUE TITLE
Obscure error when unable to connect MSSQL database

### ISSUE THREAD

**Issue by lanttu** [tgriesser/knex#2359]
# Environment

Knex version: knex@0.14.2 (mssql@4.1.0)
Database + version: MSSQL 2017-CU2 (docker)
OS: macOS 10.12.6, nodejs 8.9.1

@Grimace1975

# Bug

Knex produces obscure error message when running migrations and connection to MSSQL database fails.
```
TypeError: (connection.tx_ || connection).request is not a function
    at /Users/adii/project/node_modules/knex/lib/dialects/mssql/index.js:213:48
    at Promise._execute (/Users/adii/project/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/adii/project/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/adii/project/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MSSQL._query (/Users/adii/project/node_modules/knex/lib/dialects/mssql/index.js:208:12)
    at Client_MSSQL.query (/Users/adii/project/node_modules/knex/lib/client.js:211:17)
    at Runner.<anonymous> (/Users/adii/project/node_modules/knex/lib/runner.js:149:36)
    at Runner.tryCatcher (/Users/adii/project/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/Users/adii/project/node_modules/bluebird/js/release/method.js:15:34)
    at Runner.queryArray (/Users/adii/project/node_modules/knex/lib/runner.js:199:40)
    at /Users/adii/project/node_modules/knex/lib/runner.js:59:23
    at tryCatcher (/Users/adii/project/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/adii/project/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Users/adii/project/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/adii/project/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/adii/project/node_modules/bluebird/js/release/promise.js:569:18)
```
```js
// knexfile
module.exports = {
  client: 'mssql',
  connection: 'mssql://username:pw@no-db-here/db'
};
```
```sh
./node_modules/.bin/knex migrate:latest
```

**Comment by elhigu** [comment]
Is that valid mssql connection string? https://www.connectionstrings.com/sql-server/ anyways better error message would be nice.

**Comment by lanttu** [comment]
Yes it is. Domain is just wrong and not responding.

**Comment by mathiasgmz** [comment]
Hello! could you explain how did you resolved? I have this inside the config/database.js

mssql: {
    client: 'mssql',
    connection: 'Server=DESARROLLO;Database=test;User_Id=test;Password=test*;'
  }
and is not working yet, could you help me please?

**Comment by elhigu** [comment]
I think this issue should be rephrased so that it would be feature request for supporting different connection string formats of the driver https://github.com/patriksimek/node-mssql/blob/master/README.md#general-same-for-all-drivers

**Comment by lanttu** [comment]
At least for me the issue wasn't unsupported connection string format. The problem was just that there were no SQL server listening the given address. That resulted an error which was hard to decipher.

**Comment by tmcdonnell87** [comment]
I get the same error when there is a firewall (or other similar) issue on otherwise valid connection string format. Minor point but I agree a nicer error would be great.

**Comment by brandonramirez** [comment]
I got this error too when I had the wrong port number configured.  I'd love to see better error handling.

**Comment by crumhorn** [comment]
I recently upgraded knex to 14.2 (14.0 worked) and am now getting exactly this on a "used to be valid" code and cannot for the life of me figure out what may be wrong. Has anyone managed a connection to mssql on 14.2? Basically my string is:

`let knex = require('knex')({
      client: 'mssql',
      connection: {
        host: '127.0.0.1',
        user: 'myuser',
        password: 'mypass',
        database: 'ourDB',
        charset: 'utf8',
        domain: 'companyDomain'
      },
      debug: true
    });
`
This throws the not a function error with nothing else to go on..

**Comment by crumhorn** [comment]
Just to reply to my own foolishness, apparently my port setting was non-default. According to the SQL startup log (in my case at: C:\Program Files\Microsoft SQL Server\MSSQL10.SQL2008\MSSQL\Log) I should've been on port 51439 rather than the default port. I also enabled TCP/IP connections for the server which were off (not sure if this matters, but in case someone else runs into issues it's worth a try).

Now it works :)

To debug this, I added a console.error(err) on line 137 in index.js under the knex mssql directory (so, knex\dialects\mssql\index.js:137) to print out the actual error that the server was giving me, and I had full login logging enabled on the server to ensure I could see if the problem was connection or login related. 

All in all, better error reporting would be awesome as it would help doing things like this :)

**Comment by rsflaherty** [comment]
I am seeing a similar error with oracledb.  When I give an invalid database name or mess the connection string up in some other way, I get an error saying "TypeError: connection.executeAsync is not a function" .  When I try the same thing with plain oracledb I get a more helpful error indicating that there is no database with that name ("Error: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor").

**Comment by levinmr** [comment]
@rsflaherty I am seeing the same problem.  If the oracle server refuses connection for any reason, that same error is returned.  I am having to keep debugging code around which uses node-oracledb directly to diagnose connection issues

**Comment by elhigu** [comment]
@levinmr Doesn't that error come only when connection problems are found through runnin migrations? If you create knex instance and try to make query, the normal error should be passed to the query rejection.

**Comment by levinmr** [comment]
@elhigu this seems to be a separate but similar issue.  Added #2455

**Comment by mercmobily** [comment]
Thank you for reporting this issue about obscure error messages when database connections fail. This is indeed a frustrating developer experience issue that affects multiple database drivers.

**Note: When implementing a fix for this issue, please also review #2455 which reports the same problem for Oracle. The solution may  be applicable to both database drivers, as they share the same root cause of inadequate error handling during connection acquisition.**


When a connection to MSSQL (or Oracle, as noted in related issues) fails, instead of getting a clear error message like "Connection refused" or "Host not found", users get cryptic errors like:

- MSSQL: `TypeError: (connection.tx_ || connection).request is not a function`
- Oracle: `TypeError: connection.executeAsync is not a function`

These errors occur because when the connection fails, the connection object isn't properly initialised, so when Knex tries to use it to execute queries, it's trying to call methods on an invalid object.

The issue arises in the connection acquisition flow:
1. Knex tries to get a connection from the pool
2. The connection attempt fails (wrong host, port, firewall, etc.)
3. Instead of a proper connection object, an error object or undefined is returned
4. Knex tries to use this invalid "connection" to execute queries
5. The attempt to call methods on the invalid object produces the cryptic error

Since this issue was reported in 2018, there have been some improvements to error handling in Knex:

- Commit e405d669 addressed passing connection errors directly to queries
- Commit 0ccd591b fixed connection error propagation when streaming
- The pool library was switched from generic-pool to tarn (#2450), which improved connection handling

However, the specific issue with obscure error messages for failed connections still persists in some scenarios, particularly during migration runs.

As several users discovered in the comments:
1. Enable better logging: Add error logging directly in the dialect's index.js file to see the actual error
2. Check common connection issues:
   - Verify the host is reachable
   - Confirm the port is correct (SQL Server doesn't always use 1433)
   - Ensure TCP/IP connections are enabled on the server
   - Check firewall settings
3. Test connection separately: Use the native driver directly to verify connection parameters before using Knex

The solution would involve:
1. Better error checking when acquiring connections from the pool
2. Proper validation of the connection object before attempting to use it
3. Preserving and propagating the original connection error message
4. Providing context about what operation was being attempted when the connection failed

This would require changes in the dialect-specific connection handling code to ensure that connection failures are caught early and reported clearly.

This affects developer productivity significantly, as connection issues are common during:
- Initial setup
- Environment changes
- Docker/container deployments
- Firewall configuration changes

Clear error messages would save developers hours of debugging time.

This remains a valid improvement request. The error handling should be enhanced to:

1. Catch connection failures immediately when they occur
2. Provide the actual error from the database driver
3. Include helpful context (what connection string was used, what operation was being attempted)
4. Suggest common fixes based on the error type

**Related issues:**

- #2455 - Error when unable to connect to Oracle database (exact same issue for Oracle)
- #2336 - Fixed passing connection errors directly to the query
- #2199 - Fix connection error propagation when streaming
- #2608 - ORACLEDB: Updated handling of connection errors for disposal
- #3611 - Dispose Oracle connection on connection error
- #2450 - Use tarn as pool (improved connection handling)
