### ISSUE TITLE
Unhandled rejection Error: pool is draining and cannot accept work

### ISSUE THREAD

**Issue by c0debreaker** [tgriesser/knex#2362]
My table is empty right now.

```js
const dbConfig = require('./knexfile.js')
const knex = require('knex')(dbConfig['development']);
knex.migrate.latest([dbConfig]);

knex.table('build_info')
.first()
.then((o)=>{console.log(o)})
.finally(()=>{
  knex.destroy();
})
```
Here is the complete details of the error
```
❯ node app2.js
undefined
Unhandled rejection Error: pool is draining and cannot accept work
   at Pool.acquire (/Users/c0debreaker/repos/experiment/exer4/node_modules/generic-pool/lib/Pool.js:400:35)
   at Client_MySQL.acquireConnection (/Users/c0debreaker/repos/experiment/exer4/node_modules/knex/lib/client.js:348:22)
   at Runner.ensureConnection (/Users/c0debreaker/repos/experiment/exer4/node_modules/knex/lib/runner.js:215:24)
   at Runner.run (/Users/c0debreaker/repos/experiment/exer4/node_modules/knex/lib/runner.js:47:42)
   at Builder.Target.then (/Users/c0debreaker/repos/experiment/exer4/node_modules/knex/lib/interface.js:35:43)
   at Builder.tryCatcher (/Users/c0debreaker/repos/experiment/exer4/node_modules/bluebird/js/release/util.js:16:23)
   at doThenable (/Users/c0debreaker/repos/experiment/exer4/node_modules/bluebird/js/release/thenables.js:63:38)
   at tryConvertToPromise (/Users/c0debreaker/repos/experiment/exer4/node_modules/bluebird/js/release/thenables.js:28:20)
   at Promise._resolveCallback (/Users/c0debreaker/repos/experiment/exer4/node_modules/bluebird/js/release/promise.js:431:24)
   at Promise._settlePromiseFromHandler (/Users/c0debreaker/repos/experiment/exer4/node_modules/bluebird/js/release/promise.js:524:17)
   at Promise._settlePromise (/Users/c0debreaker/repos/experiment/exer4/node_modules/bluebird/js/release/promise.js:569:18)
   at Promise._settlePromise0 (/Users/c0debreaker/repos/experiment/exer4/node_modules/bluebird/js/release/promise.js:614:10)
   at Promise._settlePromises (/Users/c0debreaker/repos/experiment/exer4/node_modules/bluebird/js/release/promise.js:693:18)
   at Async._drainQueue (/Users/c0debreaker/repos/experiment/exer4/node_modules/bluebird/js/release/async.js:133:16)
   at Async._drainQueues (/Users/c0debreaker/repos/experiment/exer4/node_modules/bluebird/js/release/async.js:143:10)
   at Immediate.Async.drainQueues (/Users/c0debreaker/repos/experiment/exer4/node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by elhigu** [comment]
I suppose that the problem here was that knex.migrate.latest() was not ready when the query was done and knex eventually destroyed.

**Comment by c0debreaker** [comment]
Yup, it was my promise written at the wrong place. :)
