### ISSUE TITLE
how can I create a char(8) column not varchar(8)

### ISSUE THREAD

**Issue by blackmatch** [tgriesser/knex#2365]
# Environment

Knex version: `0.13.0`
Database + version: `mysql5.7`
OS: `ubuntu16.04`

I want to create a char(8) column when I create a table using schema builder, but I always got the varchar(8) column.

I try:

```js
table.string('name', 8)
      .notNullable()
      .comment('the name');
```

> got a varchar(8) column.

```js
table.char('name', 8)
      .notNullable()
      .comment('the name');
```

> error occur like below:

```js
{ Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'undefined not null comment 'the name', `attendingCode` varchar(16) null comment ' at line 1
    at Query.Sequence._packetToError (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
    --------------------
    at Protocol._enqueue (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/mysql/lib/Connection.js:208:25)
    at /Users/blackmatch/Desktop/lilian/demo/knex/node_modules/knex/lib/dialects/mysql/index.js:152:18
    at Promise._execute (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/knex/lib/dialects/mysql/index.js:146:12)
    at Client_MySQL.query (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/knex/lib/client.js:197:17)
    at Runner.<anonymous> (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/knex/lib/runner.js:146:36)
    at Runner.tryCatcher (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/bluebird/js/release/method.js:15:34)
    at Runner.<anonymous> (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/knex/lib/runner.js:193:19)
    at Runner.tryCatcher (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/bluebird/js/release/reduce.js:157:18)
    at Object.gotAccum (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/Users/blackmatch/Desktop/lilian/demo/knex/node_modules/bluebird/js/release/util.js:16:23)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0 }
```

anyone can tell me how to create a char column with `knex.schema`?

**Comment by elhigu** [comment]
with `.specificType` http://knexjs.org/#Schema-specificType

**Comment by fluxsauce** [comment]
Does `specificType` support the length?

**Comment by elhigu** [comment]
it supports pretty much anything you give to it https://runkit.com/embed/3k33qe7kq7i0

**Comment by fluxsauce** [comment]
Ah, I didn't quite understand that from the docs. Here's an example specific to `CHAR`:

```
table.specificType('country', 'CHAR(2) DEFAULT NULL');
```

Thanks!

**Comment by elhigu** [comment]
Adding default value there is a nice touch 👍 I had never thought of that, might be useful some time :) Btw. is it necessary to explicitly tell default value if it is `NULL`?

**Comment by fluxsauce** [comment]
> is it necessary to explicitly tell default value if it is `NULL`?

Honestly, probably not. I'm migrating an existing schema and trying to leave it untouched. Cleanup pass will be next!

**Comment by blackmatch** [comment]
@elhigu Thank you very much! I create a 'char(8)' column like this:

```js
table.specificType('name', 'char(8)')
      .notNullable()
      .comment('the name');
```
