### ISSUE TITLE
Support for composite foreign keys?

### ISSUE THREAD

**Issue by fer22f** [tgriesser/knex#2397]
In the docs, it states that knex has support for composite foreign keys. However, when trying it, I was met with an error (yes, I am using MS SQL, but it seems irrelevant):
```
TypeError: Cannot read property 'sql' of undefined
    at TableCompiler_MSSQL.TableCompiler.alterTableForCreate (knex\lib\schema\tablecompiler.js:254:45)
    at TableCompiler_MSSQL.TableCompiler.create (knex\lib\schema\tablecompiler.js:93:10)
    at TableCompiler_MSSQL.TableCompiler.toSQL (knex\lib\schema\tablecompiler.js:73:20)
    at TableBuilder.toSQL (knex\lib\schema\tablebuilder.js:72:42)
    at SchemaCompiler_MSSQL.createTable (knex\lib\schema\compiler.js:62:23)
    at SchemaCompiler_MSSQL.toSQL (knex\lib\schema\compiler.js:51:26)
    at SchemaBuilder.toSQL (knex\lib\schema\builder.js:57:43)
```
Using the syntax the docs referenced:
```javascript
k.schema.createTable('account', t => {
  t.foreign(['bank', 'office']).references(['office.bank', 'office.office'])
  t.integer('bank')
  t.integer('office')
})
```
I started to dig into the code, and found no relevant tests for it [in postgres](https://github.com/tgriesser/knex/blob/7032dffe70e62543621c2393f26b7fccae1c985e/test/unit/schema/postgres.js), and the code only makes reference to the argument in singular, which leads me to think this is a documented feature, but not an implemented one. To make it work, I ended up writing it raw:
```javascript
  await k.raw('ALTER TABLE account ' +
    'ADD CONSTRAINT account_office_foreign ' + 
    'FOREIGN KEY (bank, office) REFERENCES office(bank, office)')
```
Which works, but it would be nice to write it alongside the column definitions.

**Comment by brandonramirez** [comment]
I get this exact same error when running the integration tests.

      1) mssql | mssql Schema createTable rejects setting foreign key where tableName is not typeof === string:
         TypeError: Cannot read property 'sql' of undefined
          at TableCompiler_MSSQL.TableCompiler.alterTableForCreate (lib/schema/tablecompiler.js:9:16687)
          at TableCompiler_MSSQL.TableCompiler.create (lib/schema/tablecompiler.js:9:5173)
          at TableCompiler_MSSQL.TableCompiler.toSQL (lib/schema/tablecompiler.js:9:4314)
          at TableBuilder.toSQL (lib/schema/tablebuilder.js:9:4031)
          at SchemaCompiler_MSSQL.createTable (lib/schema/compiler.js:9:2758)
          at SchemaCompiler_MSSQL.toSQL (lib/schema/compiler.js:9:2279)
          at SchemaBuilder.toSQL (lib/schema/builder.js:9:3010)
          at lib/runner.js:9:3009
      From previous event:
          at Runner.run (lib/runner.js:9:2625)
          at SchemaBuilder.Target.then (lib/interface.js:9:1687)

I observe this error when using both SQL Server 2008 and SQL Server 2017 for Linux (via Docker).

**Comment by brandonramirez** [comment]
It's interesting that in the case of the test, the error occurs in a test which specifically asserts that this error occurs.  I think it's a bug in the test that the exception is not properly caught.

**Comment by fer22f** [comment]
That specific test seems to test something else, which is the `inTable` method, which specifies where the table should be joined to. This brought me light into the `inTable` method however, I didn't see it before! Apparently this does work correctly:
```javascript
k.schema.createTable('account', t => {
  t.foreign(['bank', 'office']).references(['bank', 'office']).inTable('office')
  t.integer('bank')
  t.integer('office')
})
```
So the issue becomes:
* The `references(['table.column1', 'table.column2'])` form doesn't work, but `references(['column1', 'column2']).inTable('table')` does. If we choose to not allow the first form, we should document it properly.
* The tests are lacking in this aspect. I didn't see a single example of a composite foreign key and assumed it didn't actually work.
* That error is really weird looking, can we prevent it or make it more informative?

**Comment by mercmobily** [comment]
Thank you for reporting this issue about composite foreign keys. After an in-depth investigation of the codebase, I can now provide a complete picture of what's happening.

**This affects ALL databases, not just MSSQL.** While you encountered this error using MSSQL, the issue exists in the core Knex code and affects all database drivers (PostgreSQL, MySQL, SQLite, Oracle, etc.). The problem is in the shared `TableBuilder` class that all databases use.

You've uncovered a significant gap between what might be implied by the documentation and what's actually implemented. The dot notation syntax for composite foreign keys (`['office.bank', 'office.office']`) was **never implemented** in Knex for any database, despite what the documentation might have suggested.

Dot notation **does** work, but **only for single-column foreign keys**:
```javascript
// This works fine on ALL databases:
table.integer('user_id').references('users.id')
// Generates: REFERENCES "users" ("id")
```

This is properly tested across all database dialects in the test suite.

The implementation in `lib/schema/tablebuilder.js` (lines 90-114) reveals why composite dot notation fails:
1. When `references()` receives a string, it checks for dot notation and splits it
2. When `references()` receives an array, it skips the dot notation parsing entirely
3. The array is passed through unchanged, with strings like `'office.bank'` intact
4. Without `inTable` being set, the `foreign()` method in the base tablecompiler.js (line 97) silently returns without generating any SQL
5. When `alterTableForCreate` tries to access the SQL statement that should have been generated, it finds nothing, causing the "Cannot read property 'sql' of undefined" error

The precise error path is:
1. You call: `foreign(['bank', 'office']).references(['office.bank', 'office.office'])`
2. The array `['office.bank', 'office.office']` is stored as-is in `foreignData.references`
3. `foreignData.inTable` remains undefined (no parsing occurred)
4. In tablecompiler.js, the condition `if (foreignData.inTable && foreignData.references)` fails
5. No SQL is generated
6. `alterTableForCreate` crashes trying to access `this.sequence[0].sql` when sequence is empty

The documentation appears to have been ambiguous or misleading about this capability. The reality is:
- Single column with dot notation: `references('table.column')` - works on all databases
- Array with dot notation: `references(['table.col1', 'table.col2'])` - never worked on any database
- Array with inTable: `references(['col1', 'col2']).inTable('table')` - works on all databases

**What the Documentation Should Say**

The documentation for foreign keys should be explicit about the syntax differences. For single-column foreign keys, you have two syntax options:

1. Dot notation (shorthand):
   ```javascript
   table.integer('user_id').references('users.id');
   ```

2. Explicit table specification:
   ```javascript
   table.integer('user_id').references('id').inTable('users');
   ```

Both generate the same SQL.

For composite foreign keys, you MUST use the `inTable()` method:

```javascript
// CORRECT - This works:
table.foreign(['column1', 'column2'])
     .references(['ref_col1', 'ref_col2'])
     .inTable('referenced_table');

// INCORRECT - This will NOT work (despite what you might expect):
table.foreign(['column1', 'column2'])
     .references(['referenced_table.ref_col1', 'referenced_table.ref_col2']);
// Arrays with dot notation are not supported
```

Dot notation in the `references()` method only works with single string arguments, not with arrays. When dealing with composite foreign keys, always use `inTable()` to specify the referenced table.

Complete example:

```javascript
knex.schema.createTable('orders', function(table) {
  // Single-column foreign key (both syntaxes work)
  table.integer('user_id').references('users.id');
  // OR
  table.integer('customer_id').references('id').inTable('customers');
  
  // Composite foreign key (only inTable syntax works)
  table.integer('product_id');
  table.integer('warehouse_id');
  table.foreign(['product_id', 'warehouse_id'])
       .references(['id', 'location_id'])
       .inTable('inventory');
});
```

The lack of dot notation support for arrays is actually defensible:
1. Ambiguity: With arrays, it's unclear if all columns reference the same table or different tables
2. Consistency: The `inTable()` method makes the intent explicit
3. Validation: It's easier to validate that all columns reference the same table
4. Clarity: Separating table and column names improves readability

Database-specific notes:
- MSSQL: Shows the error you encountered
- PostgreSQL/MySQL/Oracle: Would show the same error
- SQLite: Has its own foreign key implementation but would still fail with dot notation arrays during table creation

Rather than implementing array dot notation support (which would be complex and potentially ambiguous), the documentation should be clarified as shown above to explicitly state:
- Dot notation works only for single-column foreign keys
- Composite foreign keys require the `inTable()` method
- This is by design, not a bug
- This applies to all database drivers

Your workaround using raw SQL was entirely appropriate given the confusion, but the `inTable()` approach is the intended solution across all databases.

**Related issues:**

- #5825 - Possibly outdated information about how to use composite foreign keys
- #2909 - renameColumn fails when composite foreign keys are present
- #4202 - SQLite drop composite foreign keys (shows correct inTable usage)
- #1933 - Missing docs: Composite foreign key
- #1179 - Multi-column foreign keys

**Exact duplicates:**

None found - this is the first issue to identify this specific dot notation limitation with composite foreign keys.
