### ISSUE TITLE
Knex `.stream` breaks with mssql

### ISSUE THREAD

**Issue by dhinklexo** [tgriesser/knex#2440]
# Environment

Knex version: 13.x AND 14.x
Database + version: Microsoft SQL Server 2012 (SP1) - 11.0.3349.0 (X64)
OS: DB is on Server 2008, script running on MacOS 10.12
Driver: `mssql` 3.x.x AND 4.x.x

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ Grimace1975 .
Rest of dialects doesn't need tags.
@Grimace1975 

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

When attempting to run a simple query `knex.select('*').from('my_table')` via stream, Node throws an error. Normally I'd expect a working stream.

2. Error message

```
TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:254:10)
    at WriteStream.Writable.write (_stream_writable.js:288:21)
    at PassThrough.ondata (...Streamer/node_modules/knex/node_modules/readable-stream/lib/_stream_readable.js:572:20)
    at emitOne (events.js:116:13)
    at PassThrough.emit (events.js:211:7)
    at readableAddChunk (...Streamer/node_modules/knex/node_modules/readable-stream/lib/_stream_readable.js:195:16)
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

```
const outputStream = fs.createWriteStream('./output');
const queryStream = knex.select('*').from('VendorReviews').pipe(outputStream);
```

I tried with knex 14.x and mssql 4.x, as well as knex 13.x and mssql 3.x. I have a simple non-streaming COUNT query running perfectly fine, so I seem to have a good connection and otherwise mssql is playing nicely. However it appears to not be streaming correctly.

**Comment by dvicklund** [comment]
Seeing a similar error with postgres, code as follows: 

```
var output = fs.createWriteStream('./nonsense.txt')  
var input = knex.select('*').from('products').pipe(output)
```

throws this error: 
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:254:10)
    at WriteStream.Writable.write (_stream_writable.js:288:21)
    at PassThrough.ondata (/project/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at emitOne (events.js:116:13)
    at PassThrough.emit (events.js:211:7)
    at addChunk (/project/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/project/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at PassThrough.Readable.push (/project/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at PassThrough.Transform.push (/project/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at PassThrough.afterTransform (/project/node_modules/readable-stream/lib/_stream_transform.js:91:10)
    at PassThrough._transform (/project/node_modules/readable-stream/lib/_stream_passthrough.js:46:3)
    at PassThrough.Transform._read (/project/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at PassThrough.Transform._write (/project/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/project/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/project/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at PassThrough.Writable.write (/project/node_modules/readable-stream/lib/_stream_writable.js:334:11)
```

I can use the promise-based interface just fine with the same query.

**Comment by elhigu** [comment]
@dvicklund please open separate Issue for postgresql problem.

**Comment by ricardograca** [comment]
The problem here is that Knex is just passing along whatever the dialect adapter returns with its stream implementation, and it seems that all dialects are passing an *object* into the writable stream's `write()` method. The issue is that streams created with `fs.createWritableStream()` expect either a *string* or a *buffer*.

You can add an intermediate transform stream that converts the input to a string, like:

```js
const { Transform } = require('stream')
const outputStream = fs.createWriteStream('./output')

const toJson = new Transform({
  transform(chunk, encoding, callback) {
    this.push(JSON.stringify(chunk))
    callback()
  }
})

knex.select('*').from('VendorReviews').pipe(toJson).pipe(outputStream)
```

However I think there is also a documentation issue here since it's not stated anywhere that Knex will return object data in this case and that any writable stream must be in object mode or have an intermediary transform stream to do the conversion beforehand.

**Comment by agarbund** [comment]
I know this question is 8 months old, but just faced the same issue and spent a few hours looking for a solution so just want to share it here in case anyone else will have the same problem.

What @ricardograca wrote is mostly correct, however, `Transform` stream also doesn't accept objects by default so the same error will be thrown. The solution is `objectMode: true` setting which causes any writable stream to accept any type of value, not only strings and buffers.

```javascript
const { Transform } = require('stream')
const outputStream = fs.createWriteStream('./output')

const toJson = new Transform({
  objectMode: true,
  transform(chunk, encoding, callback) {
    this.push(JSON.stringify(chunk))
    callback()
  }
})

knex.select('*').from('VendorReviews').pipe(toJson).pipe(outputStream)
```

**Comment by mercmobily** [comment]
Hello! Thank you for reporting this issue.

This issue has been resolved. The problem was that Knex's streaming interface was returning object streams (where each chunk is a JavaScript object representing a database row), but `fs.createWriteStream()` expects either string or buffer chunks, which caused the "Invalid non-string/buffer chunk" error you encountered.

The root cause was in lib/execution/runner.js, where the Transform stream created for handling query results was missing the `objectMode: true` configuration. Without this setting, the stream couldn't properly handle JavaScript objects being passed through it, even though that's exactly what database drivers return.

Community members @ricardograca and @agarbund correctly identified the problem and provided excellent workarounds. They suggested using an intermediate Transform stream with `objectMode: true` to convert objects to strings before writing to the file stream, which is exactly the right approach for working with object streams.

The permanent fix was implemented in PR #4178, which reorganised the codebase structure and added `objectMode: true` to the Transform stream configuration in lib/execution/runner.js:65. This change was merged on 28 December 2020 and released in version 0.95.0 on 3 March 2021.

With this fix in place, Knex now properly handles object streams internally. However, if you want to pipe query results to `fs.createWriteStream()`, you still need an intermediate transform stream to convert the objects to strings (typically JSON), since file write streams inherently expect string or buffer data, not JavaScript objects. The workaround provided by @agarbund remains the correct pattern:

```javascript
const { Transform } = require('stream')
const outputStream = fs.createWriteStream('./output')

const toJson = new Transform({
  objectMode: true,
  transform(chunk, encoding, callback) {
    this.push(JSON.stringify(chunk) + '\n')
    callback()
  }
})

knex.select('*').from('products').pipe(toJson).pipe(outputStream)
```

The error you experienced should no longer occur with modern versions of Knex, though you'll still need the intermediate transform stream for converting objects to the appropriate output format.


Related issues: #4329, #4453, #3544, #1836
