### ISSUE TITLE
Cannot find module 'sqlite3', config is set for mysql use

### ISSUE THREAD

**Issue by apisandipas** [tgriesser/knex#2441]
# Environment

Knex version: ^0.14.2
Bookshelf: ^0.12.1
Database + version: mysqld 5.7.16-0ubuntu0.16.04.1
OS: OSX

# Bug

My knex/bookshelf configuration is set up for Mysql usage. I have the mysql npm package installed. For some reason when I run a query it bugs out and tells me to install sqlite3 package.

Knex: run
$ npm install sqlite3 --save
Error: Cannot find module 'sqlite3'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Client._driver (/Users/bryan/Code/redux-blog/api/node_modules/knex/lib/dialects/sqlite3/index.js:65:12)
    at Client.initializeDriver (/Users/bryan/Code/redux-blog/api/node_modules/knex/lib/client.js:211:26)
    at Client (/Users/bryan/Code/redux-blog/api/node_modules/knex/lib/client.js:92:10)
    at Client_SQLite3 (/Users/bryan/Code/redux-blog/api/node_modules/knex/lib/dialects/sqlite3/index.js:51:23)
    at new Client (/Users/bryan/Code/redux-blog/api/node_modules/knex/lib/util/make-client.js:24:18)
    at new Knex (/Users/bryan/Code/redux-blog/api/node_modules/knex/lib/index.js:57:36)
    at Knex (/Users/bryan/Code/redux-blog/api/node_modules/knex/lib/index.js:43:12)
    at Child.builderFn [as _builder] (/Users/bryan/Code/redux-blog/api/node_modules/bookshelf/lib/bookshelf.js:317:17)
    at Object.query (/Users/bryan/Code/redux-blog/api/node_modules/bookshelf/lib/helpers.js:44:23)
    at Child.query (/Users/bryan/Code/redux-blog/api/node_modules/bookshelf/lib/model.js:1206:30)
    at Child.where (/Users/bryan/Code/redux-blog/api/node_modules/bookshelf/lib/model.js:1241:23)
    at Function.Model.(anonymous function).Collection.(anonymous function) [as where] (/Users/bryan/Code/redux-blog/api/node_modules/bookshelf/lib/bookshelf.js:336:28)
    at _callee2$ (/Users/bryan/Code/redux-blog/api/build/bundle.js:507:39)
    at tryCatch (/Users/bryan/Code/redux-blog/api/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/bryan/Code/redux-blog/api/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/bryan/Code/redux-blog/api/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/bryan/Code/redux-blog/api/build/bundle.js:446:191)
    at /Users/bryan/Code/redux-blog/api/build/bundle.js:446:437
    at new Promise (<anonymous>)
    at /Users/bryan/Code/redux-blog/api/build/bundle.js:446:99
    at show (/Users/bryan/Code/redux-blog/api/build/bundle.js:531:22)
    at Layer.handle [as handle_request] (/Users/bryan/Code/redux-blog/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/bryan/Code/redux-blog/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/bryan/Code/redux-blog/api/node_modules/express/lib/router/route.js:112:3)
[nodemon] app crashed - waiting for file changes before starting...

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

Am I doing something wrong?

**Comment by apisandipas** [comment]
Code can be found here: https://github.com/apisandipas/blog/tree/master/api

**Comment by KristerV** [comment]
so how did you fix it?

**Comment by jazoom** [comment]
Getting the same thing for client set to 'pg'. The appropriate NodeJS module is installed.

**Comment by jazoom** [comment]
For future travellers, there are 2 problems here that lead to this confusion:

1. Strange behaviour by the uninitialised `knex` object returned by `require('knex')`
2. Unclear documentation

I realised that while the documentation shows this as initialisation code:
```
var pg = require('knex')({
  client: 'pg',
  connection: process.env.PG_CONNECTION_STRING,
  searchPath: ['knex', 'public'],
});
```

it uses this later for operations code:
`knex('books').insert({title: 'Slaughterhouse Five'})`

If you copy those examples you will get this strange error about SQLite3. In this example what you would need to do is:

`pg('books').insert({title: 'Slaughterhouse Five'})`

On looking around the docs now that I have this figured out, I can see some hints of this, but it's very inconsistent.

**Comment by lilia-simeonova** [comment]
I had a similar issue and it was resolved by reinstalling knex.

**Comment by tslater** [comment]
I think this issue happens when you import Knex and do something like Knex('tablename').insert() on the imported knex directly instead of on the configured object.

**Comment by femartinez92** [comment]
In my case i was i was making the import like this:
const knex = require("knex/knex");
i fixed it by changing it to this: 
const knex = require("./knex/knex");  (Notice the ./ before knex)
Also this ws the file knex.js on folder knex
![image](https://user-images.githubusercontent.com/7012413/106795747-3bf4cc80-6639-11eb-8e83-a87a190fbc22.png)
