### ISSUE TITLE
Error when unable to connect to Oracle database

### ISSUE THREAD

**Issue by levinmr** [tgriesser/knex#2455]
# Environment

Knex version: 0.14.2
Database + version: Oracle 12c
OS: OSX 10.11.6, NodeJS 8.9.1

@atiertant 

# Bug

Knex produces a strange error message when I provide invalid connection configs

```
TypeError: connection.executeAsync is not a function
    at /Users/levinmr/code/zipscripts/tails/node_modules/knex/lib/dialects/oracledb/index.js:261:16
    at Promise._execute (/Users/levinmr/code/zipscripts/tails/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/levinmr/code/zipscripts/tails/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/levinmr/code/zipscripts/tails/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_Oracledb._query (/Users/levinmr/code/zipscripts/tails/node_modules/knex/lib/dialects/oracledb/index.js:253:10)
    at Client_Oracledb.query (/Users/levinmr/code/zipscripts/tails/node_modules/knex/lib/client.js:211:17)
    at Runner.<anonymous> (/Users/levinmr/code/zipscripts/tails/node_modules/knex/lib/runner.js:149:36)
    at Runner.tryCatcher (/Users/levinmr/code/zipscripts/tails/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/Users/levinmr/code/zipscripts/tails/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/levinmr/code/zipscripts/tails/node_modules/knex/lib/runner.js:61:21
    at tryCatcher (/Users/levinmr/code/zipscripts/tails/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/levinmr/code/zipscripts/tails/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Users/levinmr/code/zipscripts/tails/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/levinmr/code/zipscripts/tails/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/levinmr/code/zipscripts/tails/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/levinmr/code/zipscripts/tails/node_modules/bluebird/js/release/promise.js:614:10)
```

```javascript
// Test code

let knex = require('knex')({
  client: 'oracledb',
  connection: {
    user: 'user',
    password: 'password',
    host: 'host',
    port: 1521,
    database: 'database'
  }
});

knex
  .select('TABLE_NAME')
  .from('ALL_TABLES')
  .then(result => {
    console.log(result);
  },
  err => {
    console.log(err);
  }
);
```

**Comment by rsflaherty** [comment]
I am seeing this too and have not found a way to capture the root database connection error (caused by the invalid config) rather that the error listed in the issue.

**Comment by mercmobily** [comment]
Thank you for reporting this issue about obscure error messages when Oracle database connections fail. This is the Oracle-specific variant of the broader connection error handling issue affecting multiple database drivers.

**Note: When implementing a fix for this issue, please also review #2359 which reports the same problem for MSSQL. The solution may be applicable to both database drivers, as they share the same root cause of inadequate error handling during connection  acquisition.**

When connection to Oracle fails, you receive:
```
TypeError: connection.executeAsync is not a function
```

Instead of the actual error from the Oracle driver, which would be something like:
```
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor
```

This makes debugging connection issues unnecessarily difficult, as the real error (wrong database name, host unreachable, authentication failure, etc.) is hidden behind a TypeError.

The issue occurs because:
1. The connection attempt fails in the Oracle driver
2. Instead of a valid connection object, the pool returns an error or undefined
3. Knex attempts to call `executeAsync` on this invalid object
4. This produces the misleading TypeError instead of the actual connection error

Since this issue was reported, there have been some improvements to Oracle error handling in Knex:
- Commit #2608 updated handling of connection errors for disposal in OracleDB
- Commit #3611 added proper disposal of Oracle connections on connection error

However, the core issue of obscure error messages during initial connection failures persists, particularly when running queries (as opposed to migrations).

Whilst #2359 describes the same symptom for MSSQL (particularly during migrations), this issue specifically affects Oracle during regular query execution. Both stem from the same root cause: inadequate error handling when connection acquisition fails.

As you've discovered, the most effective workaround is to maintain debugging code that uses node-oracledb directly to test connections:

```javascript
const oracledb = require('oracledb');
// Test connection directly to get proper error messages
oracledb.getConnection({
  user: 'user',
  password: 'password',
  connectString: 'host:1521/database'
}).then(conn => {
  console.log('Connection successful');
  conn.close();
}).catch(err => {
  console.log('Actual error:', err.message);
});
```

The solution requires:
1. Catching connection errors at the point of acquisition
2. Properly validating the connection object before use
3. Preserving the original Oracle error message
4. Rejecting the query promise with the actual error, not a TypeError

This is marked as a "good first issue" because the fix is relatively straightforward - it's mainly about proper error handling and validation in the Oracle dialect's `_query` method.

In `lib/dialects/oracledb/index.js`, the `_query` method should validate that `connection` is actually a valid connection object before attempting to use it. If it's not, the original connection error should be propagated.

This significantly affects developer experience when:
- Setting up new Oracle connections
- Migrating between environments
- Dealing with TNS configuration issues
- Debugging authentication problems

This is a valid improvement request that would benefit from a community contribution. The fix is relatively simple but would save developers significant debugging time. Given it's marked as "good first issue" and "PR please", it's an excellent opportunity for a new contributor to improve Knex's error handling.

**Related issues:**

- #2359 - Obscure error when unable to connect MSSQL database (same issue, different driver)
- #2608 - ORACLEDB: Updated handling of connection errors for disposal
- #3611 - Dispose Oracle connection on connection error
- #2336 - Fixed passing connection errors directly to the query
