### ISSUE TITLE
Tests fail without specifying DB env variable

### ISSUE THREAD

**Issue by ricardograca** [tgriesser/knex#2540]
# Environment

Knex version: 0.14.4
Database + version: Not relevant, but the failing test is trying to use the `mysql2` client
OS: Ubuntu 16.04.4

# Bug

Trying to run the test suite locally right after a clean install produces the following error:

```
  #2321 dead connections are not evicted from pool

/home/ricardo/src/knex/test/tape/pool.js:105
  if (process.env.DB.indexOf('mysql2') >= 0) {
                    ^

TypeError: Cannot read property 'indexOf' of undefined
    at Test.<anonymous> (/home/ricardo/src/knex/test/tape/pool.js:105:21)
    at Test.bound [as _cb] (/home/ricardo/src/knex/node_modules/tape/lib/test.js:77:32)
    at Test.run (/home/ricardo/src/knex/node_modules/tape/lib/test.js:96:10)
    at Test.bound [as run] (/home/ricardo/src/knex/node_modules/tape/lib/test.js:77:32)
    at Immediate.next [as _onImmediate] (/home/ricardo/src/knex/node_modules/tape/lib/results.js:71:15)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
```

I can confirm that setting the mentioned environment variable to a valid value will make the test suite run correctly.

### Steps to reproduce

1. Clone the repo
2. `npm install`
3. `npm test`

### Expected results

The test suite runs fine.

### Actual results

There is an unexpected error about a missing environment variable.

**Comment by wubzz** [comment]
[Looks fixed, closing](https://github.com/tgriesser/knex/commit/c89119b68191b7bf772352f784f7c167e7fc7259)
