### ISSUE TITLE
Redshift woes

### ISSUE THREAD

**Issue by walshe** [tgriesser/knex#2545]
have had to switch from postgres to redshift, but redshift doesn't like one of my migration files:

using knex 0.14.3

```
var config = require('../../config')

exports.up = function (knex, Promise) {
  return knex.schema.withSchema(config.get('/db/schema/metrics')).table('homenetstats', function (t) {
    t.string('iLotId').nullable()
    t.string('iLotName').nullable()
    t.dateTime('marketUpdatedDate').nullable()

    t.index('iLotId')
    t.index('iLotName')
    t.index('marketUpdatedDate')
  })
}

exports.down = function (knex, Promise) {

}
```

Knex:warning - migration failed with error: alter table "dev_temp"."homenetstats" add column "iLotId" varchar(255) null, add column "iLotName" varchar(255) null, add column "marketUpdatedDate" timestamptz null - syntax error at or near ","
error: syntax error at or near ","
    at Connection.parseE (/Users/emmett/dev/vroom/aggregated-inv-svc/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/Users/emmett/dev/vroom/aggregated-inv-svc/node_modules/pg/lib/connection.js:370:19)
    at TLSSocket.<anonymous> (/Users/emmett/dev/vroom/aggregated-inv-svc/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:237:11)
    at TLSSocket.Readable.push (_stream_readable.js:195:10)
    at TLSWrap.onread (net.js:586:20)

**Comment by elhigu** [comment]
@acofer any ideas why this is happening?

**Comment by walshe** [comment]
in the end i split the above migration into 3 - one for each new column - that works

**Comment by acofer** [comment]
Redshift `ADD COLUMN` will only take one at a time. https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE.html
I might need to modify the sql generated to account for this.
