### ISSUE TITLE
npm run build fails when I import knex in my react app

### ISSUE THREAD

**Issue by ahmadalibaloch** [tgriesser/knex#2556]
# Environment

Knex version: 0.10.0+, i have tested with latest (0.14.0 down to 0.10.0)
Database + version: client=pg, just using queryBuilder I dont want all stuff
OS: Ubuntu 16.04

# Bug

```
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! superset@0.19.1 build: `NODE_ENV=production webpack --colors --progress`
npm ERR! Exit status 2
````

This problem doesn't occure on npm run dev, I dont know. When I run `npm run build` it fails with this error.
When I remove knex from package.json. Build succeeds.

**Comment by elhigu** [comment]
Nothing in bug report hints that this would be knex issue.

**Comment by ahmadalibaloch** [comment]
What the heck you closed it!!
This is the problem, that build fails when I import knex in any of my js files for using it. There is no clue where is the problem. This is how I am using it.

```
import knex from 'knex'; // if remove this build succeeds
import Promise from 'bluebird';
import $ from 'jquery';

class DatasourcesAPI {
  constructor() {
    this.baseDbUrl = '/teamplay/datasource_query/';
    this.dbLanguage = 'pg';
    this.queryBuilderNamespace = {};
  }
  getAPI() {
    return this.createKnexClient();
  }

  createKnexClient() {
    const knexClient = knex({ client: this.dbLanguage });
    const getBuilder = () => {
      const queryBuilder = knexClient.queryBuilder();
      queryBuilder.id = Math.random() * Math.random();
      const apiThis = this;
      queryBuilder.query = function () {
        return apiThis.runQuery(this);
      };
      this.queryBuilderNamespace[queryBuilder.id] = queryBuilder;
      return queryBuilder;
    };
    return {
      builder: () => getBuilder(),
    };
  }
  runQuery(queryBuilder) {
    const query = queryBuilder.toString();
    if (!query.length) {
      return Promise.reject('Query empty');
    }
    delete this.queryBuilderNamespace[queryBuilder.id]; // ready for GC
    return $.post(this.baseDbUrl, { sql: query });
  }
}

export default new DatasourcesAPI();
```

**Comment by elhigu** [comment]
Try search from internet how to use node libraries with webpack (on browser i suppose). There are also some other issues about how to use knex with webpack here which might be helpful.

ps. I hope you are aware that running queries generated by frontend like that is completely insecure.

**Comment by ahmadalibaloch** [comment]
I think knex is not a node only lib. I searched those issues but they are very specific. I switched to [squel](https://hiddentao.com/squel/) lib.


P.S. Well aware of your P.S message. :-)

**Comment by elhigu** [comment]
It is node only in a way that there is no official / documented way available how to use it on browser side.

**Comment by ahmadalibaloch** [comment]
Here is the log of npm run build fail:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ahmadali/.nvm/versions/node/v6.11.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v6.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle superset@0.19.1~prebuild: superset@0.19.1
6 info lifecycle superset@0.19.1~build: superset@0.19.1
7 verbose lifecycle superset@0.19.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle superset@0.19.1~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/media/ahmadali/Data/Workspace/IntechWW/superset/superset/assets/node_modules/.bin:/home/ahmadali/.local/bin/luna-studio:/home/ahmadali/.nvm/versions/node/v6.11.1/bin:/home/ahmadali/bin:/home/ahmadali/.local/bin:/home/ahmadali/.local/bin/luna-studio:/home/ahmadali/bin:/home/ahmadali/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
9 verbose lifecycle superset@0.19.1~build: CWD: /media/ahmadali/Data/Workspace/IntechWW/superset/superset/assets
10 silly lifecycle superset@0.19.1~build: Args: [ '-c', 'NODE_ENV=production webpack --colors --progress' ]
11 silly lifecycle superset@0.19.1~build: Returned: code: 2  signal: null
12 info lifecycle superset@0.19.1~build: Failed to exec build script
13 verbose stack Error: superset@0.19.1 build: `NODE_ENV=production webpack --colors --progress`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid superset@0.19.1
15 verbose cwd /media/ahmadali/Data/Workspace/IntechWW/superset/superset/assets
16 verbose Linux 4.10.0-42-generic
17 verbose argv "/home/ahmadali/.nvm/versions/node/v6.11.1/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v6.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error superset@0.19.1 build: `NODE_ENV=production webpack --colors --progress`
22 error Exit status 2
23 error Failed at the superset@0.19.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```
