### ISSUE TITLE
knex.migrate.rollback() throws unable to acquire connection

### ISSUE THREAD

**Issue by peskic93** [tgriesser/knex#2627]
Knex version: 0.14.2
Database + version: Postgres 10.2
OS: Linux Mint

Hi, I have problem using `knex.migrate.rollback();` in testing. I'm using mocha and chai and in after block I want to rollback and then destroy connection. All test pass and it works ok, until it finishes and has to be destroyed.

As I debugged my code I found out that rollback is not working as it should and it throws error:
```
     Error: Unable to acquire a connection
      at Client_PG.acquireConnection (node_modules/knex/lib/client.js:346:40)
      at Runner.ensureConnection (node_modules/knex/lib/runner.js:215:24)
      at Runner.run (node_modules/knex/lib/runner.js:47:42)
      at SchemaBuilder.Target.then (node_modules/knex/lib/interface.js:35:43)
      at Migrator._ensureTable (node_modules/knex/lib/migrate/index.js:252:39)
      at Migrator._listCompleted (node_modules/knex/lib/migrate/index.js:396:17)
      at Migrator._migrationData (node_modules/knex/lib/migrate/index.js:408:58)
      at node_modules/knex/lib/migrate/index.js:158:21
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Function.Promise.attempt.Promise.try (node_modules/bluebird/js/release/method.js:39:29)
      at Migrator.rollback (node_modules/knex/lib/migrate/index.js:156:34)
      at Context.after (tests/Users/users-dal.spec.js:1:6789)

```
I googled for this error and all I found is that this has to do with config data for connection to database. But again all of my tests works until it comes to rollback and when I checked my config for connection it looks properly. 

config object:
```
{ client: 'pg',
  connection: 
   { host: '127.0.0.1',
     database: 'dbname_test',
     user: 'dbuser',
     password: 'dbpassword' }
```

after block: 
```
  after(async () => {
    await knex.migrate.rollback(knexConfig);
    return await knex.destroy(knexConfig);
  });
```

**Comment by elhigu** [comment]
According to docs, you are passing invalid config object to rollback method http://knexjs.org/#Migrations-API

**Comment by peskic93** [comment]
The same command with the same config works when run from cli. 
According to docs I am passing basic configuration and it works when I call the same function from app, but doesn't work when called from testing environment, in after block.
