### ISSUE TITLE
Getting error in Raw-Binding

### ISSUE THREAD

**Issue by chdnitinsharma** [tgriesser/knex#2670]
# Environment

Knex version:
Database + version:
OS: Window 8 x64

Package Json:
knex: "^0.14.6",
mssql: "^4.1.0"

# Bug

[Kinex Raw-Binding Doc](https://knexjs.org/#Raw-Bindings)

Sample code:

```javascript

 let DbConnection = {
  client: "mssql",
  connection: {
      host: "HOST",
      user: "USER",
      password: "PASSWORD",
      database: "DB"
  },
  debug:true
};
 let knex= require('knex')(DbConnection);
 let spRes = knex.raw(
    'select * from TABLE_NAME where id in (?)', [3]
  );
  spRes.then((re)=>{
    console.log(re);
  }).catch(ee=>{
      console.log(ee);
      
  });
  let spRes1 = knex.raw(
    'select * from TABLE_NAME where id in (?)', [[2,3]]
  );
  spRes1.then((re)=>{
    console.log(re);
  }).catch(ee=>{
      console.log(ee);
      
  });
```
Getting error in this statement:
```javascript
  let spRes1 = knex.raw(
    'select * from TABLE_NAME where id in (?)', [[2,3]]
  );
```
```
{ RequestError: Conversion failed when converting the nvarchar value '2,3' to data type int.
    at handleError (D:\SampleProjects\knex\node_modules\mssql\lib\tedious.js:519:15)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Parser.<anonymous> (D:\SampleProjects\knex\node_modules\tedious\lib\connection.js:619:16)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.<anonymous> (D:\SampleProjects\knex\node_modules\tedious\lib\token\token-stream-parser.js:54:15)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at addChunk (D:\SampleProjects\knex\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (D:\SampleProjects\knex\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at Parser.Readable.push (D:\SampleProjects\knex\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at Parser.Transform.push (D:\SampleProjects\knex\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at doneParsing (D:\SampleProjects\knex\node_modules\tedious\lib\token\stream-parser.js:110:18)
    at D:\SampleProjects\knex\node_modules\tedious\lib\token\infoerror-token-parser.js:46:5
    at D:\SampleProjects\knex\node_modules\tedious\lib\token\infoerror-token-parser.js:13:19
  code: 'EREQUEST',
  number: 245,
  lineNumber: 1,
  state: 1,
  class: 16,
  serverName: 'DEVSRV\\SQLEXPRESS',
  procName: '',
  originalError:
   { Error: Conversion failed when converting the nvarchar value '2,3' to data type int.
    at handleError (D:\SampleProjects\knex\node_modules\mssql\lib\tedious.js:517:19)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Parser.<anonymous> (D:\SampleProjects\knex\node_modules\tedious\lib\connection.js:619:16)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.<anonymous> (D:\SampleProjects\knex\node_modules\tedious\lib\token\token-stream-parser.js:54:15)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at addChunk (D:\SampleProjects\knex\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (D:\SampleProjects\knex\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at Parser.Readable.push (D:\SampleProjects\knex\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at Parser.Transform.push (D:\SampleProjects\knex\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at doneParsing (D:\SampleProjects\knex\node_modules\tedious\lib\token\stream-parser.js:110:18)
    at D:\SampleProjects\knex\node_modules\tedious\lib\token\infoerror-token-parser.js:46:5
    at D:\SampleProjects\knex\node_modules\tedious\lib\token\infoerror-token-parser.js:13:19
     info:
      { number: 245,
        state: 1,
        class: 16,
        message: 'Conversion failed when converting the nvarchar value \'2,3\' to data type int.',
        serverName: 'DEVSRV\\SQLEXPRESS',
        procName: '',
        lineNumber: 1,
        name: 'ERROR',
        event: 'errorMessage' } },
  name: 'RequestError',
  precedingErrors: [] }
```

**Comment by elhigu** [comment]
Driver doesn't support passing an array as a parameter like that. Also this has been discussed few times before. Closing as not bug / duplicate.

**Comment by chdnitinsharma** [comment]
Thanks, I appreciate it. So can you please mention in doc. So that everyone do not try to execute array  raw query and not create new issue on Git.

> MSSQL Driver doesn't support passing an array as a parameter like that

[https://knexjs.org/#Raw-Bindings](https://knexjs.org/#Raw-Bindings)

> 
> Note that due to ambiguity, arrays must be passed as arguments within a containing array.
> 
> knex.raw('select * from users where id in (?)', [1, 2, 3]);
> // Error: Expected 3 bindings, saw 1
> 
> knex.raw('select * from users where id in (?)', [[1, 2, 3]])
> Outputs:
> select * from users where id in (1, 2, 3)

**Comment by elhigu** [comment]
yeah, that part of docs was fixed recently, I suppose it is not deployed to web yet. that works only by an accident when toString() is used (which should never be used for running queries)
