### ISSUE TITLE
Catch fatal errors

### ISSUE THREAD

**Issue by vjpr** [tgriesser/knex#2687]
Is there a way to catch fatal errors which crash my app without resulting to wrapping all queries in `catch`?

```
error: relation "user" does not exist
    at Connection.parseE (xxx/db/node_modules/.registry.npmjs.org/pg/7.4.1/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (xxxk/db/node_modules/.registry.npmjs.org/pg/7.4.1/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (xxx/db/node_modules/.registry.npmjs.org/pg/7.4.1/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

Then app crashes.

# Environment

Knex version: 0.15.0
Database + version: pg
OS: macOS

**Comment by vjpr** [comment]
This was occurring in a passport callback which somehow isn't covered by any of my app's error handlers. This is prob not a knex issue. Closing.
