### ISSUE TITLE
migration failed with error: Cannot read property 'knex' of undefined

### ISSUE THREAD

**Issue by layverns** [tgriesser/knex#2809]
# Environment

Knex version: 0.15.2
Database + version: MySQL Community Server 5.7.23 
OS: mac os high sierra

# Bug
1. when i run knex migrate:latest, I get an error. I have ran knex init and other command follow the official doc. 

The full error message is as follow:
```
migration file "20180916151215_migration_name.js" failed
migration failed with error: Cannot read property 'knex' of undefined
TypeError: Cannot read property 'knex' of undefined
    at warnPromise (/Users/lunhao/code/learn/lknex/node_modules/knex/lib/migrate/index.js:504:10)
    at Object.<anonymous> (/Users/lunhao/code/learn/lknex/node_modules/knex/lib/migrate/index.js:451:16)
    at Object.tryCatcher (/Users/lunhao/code/learn/lknex/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/lunhao/code/learn/lknex/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/lunhao/code/learn/lknex/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/lunhao/code/learn/lknex/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (/Users/lunhao/code/learn/lknex/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/lunhao/code/learn/lknex/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/lunhao/code/learn/lknex/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/lunhao/code/learn/lknex/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by wubzz** [comment]
Fixed in #2730

**Comment by base698** [comment]
What's the workaround?

**Comment by kibertoad** [comment]
@base698 simplest solution would be to use latest 0.16.0.next version, but you can also return promise explicitly.
