### ISSUE TITLE
Buggy syntax error reporting

### ISSUE THREAD

**Issue by nikitalpopov** [tgriesser/knex#2850]
# Environment

Knex version: 0.15.2
Database + version: PostgreSQL 10
OS: macOS 10.14

# Bug

1. I've made a little mistake while was creating database raw request:

```
database.raw(
    'SELECT DISTINCT ON(tiger_id) tiger_id, created_at, latitude, longitude, id' +
    'FROM images ' +                                     // missed space there ^
    'ORDER BY tiger_id, created_at DESC;'
)
```

2. But the error I get when I'm trying to run the query is misleading (while there is only syntax error, it says that column is not present):
```
error: column "tiger_id" does not exist
    at Connection.parseE (/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

3. The `images` table was created with the following knex migration, so column `tiger_id` is present:  
```
exports.up = function(knex, Promise) {
    return knex.schema.createTable('images', (table) => {
        table.increments();
        table.string('tiger_id').unsigned().index().references('tiger_id').inTable('tigers').onDelete('CASCADE');
        table.string('name').notNullable();
        table.string('type').notNullable();
        table.string('path').unique().notNullable();
        table.text('description');
        table.float('latitude').notNullable();
        table.float('longitude').notNullable();
        table.timestamp('created_at').defaultTo(knex.fn.now());
    });
};
```

**Comment by ricardograca** [comment]
What happens if you run the same incorrect query directly on the PostgreSQL server?

**Comment by nikitalpopov** [comment]
@ricardograca the same error. So I have to close this issue?

```
ERROR:  column "tiger_id" does not exist
LINE 1: SELECT DISTINCT ON("tiger_id") tiger_id, created_at, latitud...
                                       ^
SQL state: 42703
Character: 32
```

**Comment by kibertoad** [comment]
Yup, as it is not related to knex, we are just returning whatever driver does.

**Comment by ricardograca** [comment]
Yeah, Knex only passes along any errors from the database driver which itself only passes along errors from the database server.

**Comment by elhigu** [comment]
Working as expected. Invalid query throws an error.
