### ISSUE TITLE
Migrations directory problem

### ISSUE THREAD

**Issue by belaarany** [tgriesser/knex#2862]
# Environment
Knex version: 0.15.2
Database + version: MySQL - Server version: 5.7.23-0ubuntu0.18.04.1 (Ubuntu) 
OS: Ubuntu 18.04.1 LTS

# Bug
1. I have changed the migrations' path to a different one. Then I used the `knex migrate:make` command and it created the migration file to the desired folder as I expected. So it recognizes the `directory` property within the `migration` object.
\
Then I tried to run the `knex migration:latest` command and got and error (I am referencing the next section).
\
However when I don't use the `directory` property, it works very well.

2. The error message I got:
```bash
x@pc:~$ knex migrate:latest
Using environment: development
migration file "20181017135233_create_users_table.js" failed
migration failed with error: Cannot read property 'knex' of undefined
TypeError: Cannot read property 'knex' of undefined
    at warnPromise (/home/x/node_modules/knex/lib/migrate/index.js:423:10)
    at Object.<anonymous> (/home/x/node_modules/knex/lib/migrate/index.js:370:16)
    at Object.tryCatcher (/home/x/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/x/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/x/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/x/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (/home/x/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/home/x/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/x/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/x/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
x@pc:~$ 
```
3. The code I am trying to use I put below. I tried using `__dirname` as well anyways.
```js
require('dotenv').load();

module.exports = {

    development: {
        client: 'mysql',
        connection: {
            database: process.env.DB_CONNECT_DATABASE,
            user: process.env.DB_CONNECT_USER,
            password: process.env.DB_CONNECT_PASSWORD
        },
        pool: {
            min: 2,
            max: 10
        },
        migrations: {
            tableName: 'knex_migrations',
            directory: "./database/migrations"
        },
        seeds: {
          directory: "./database/seeds"
        }
    }

};
```
<br />
<hr />
<br />
As I can see in the documentation, Knex supports the `directory` property and as I mentioned it is working when I create the migration file but It is not able to execute the migration. Am I doing something wrong or is it a bug?

**Comment by wubzz** [comment]
This is most likely same as #2725 which is fixed in #2730 (not yet published)

**Comment by kibertoad** [comment]
It was published in 0.16.nexts, though, so please try updating to that and see if it helps (e. g. "0.16.0-next3")

**Comment by belaarany** [comment]
> This is most likely same as #2725 which is fixed in #2730 (not yet published)

In the meantime I figured out it is due to I tried to run "empty" migrations without Promise would have been returned. So it is the problem that I didn't return a Promise?

**Comment by kibertoad** [comment]
Yes, but you don't need to in a newer version.

**Comment by belaarany** [comment]
Thank you guys for the help!
