### ISSUE TITLE
TypeError: mixed.hasOwnProperty

### ISSUE THREAD

**Issue by mwilliammyers** [tgriesser/knex#2879]
# Environment

Knex version: `knex@0.15.2`, `pg@7.4.3`

Database + version: PostgreSQL 10.3 (Debian 10.3-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

OS: `Debian GNU/Linux 9 (stretch)`, `macOS 10.11.6`, and `Ubuntu 18.04.1 LTS (Bionic Beaver)`

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

   Not error out on checks for `undefined` properties on an object.

2. Error message

```
TypeError: mixed.hasOwnProperty is not a function:
      at Object.containsUndefined (./node_modules/knex/lib/helpers.js:40:17)
      at Object.containsUndefined (./node_modules/knex/lib/helpers.js:42:37)
      at Object.containsUndefined (./node_modules/knex/lib/helpers.js:42:37)
      at Object.containsUndefined (./node_modules/knex/lib/helpers.js:36:35)
      at Raw.toSQL (./node_modules/knex/lib/raw.js:135:17)
      at ./node_modules/knex/lib/runner.js:39:32
  From previous event:
      at Runner.run (./node_modules/knex/lib/runner.js:34:31)
      at Raw.Target.then (./node_modules/knex/lib/interface.js:20:43)
      at process._tickCallback (internal/process/next_tick.js:189:7)
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.
   
    I think trying to use anything that uses a `null` prototype, which does not inherit the base properties and methods of ordinary `Object` instances (see: hapijs/hapi#3280 for a similar issue) in bindings.

I have a PR ready to go that fixes this (its one line)...

**Comment by kibertoad** [comment]
@mwilliammyers Could you please add test to that fix as well?

**Comment by ivosabev** [comment]
What is the status of this, I am having the same issue?

**Comment by elhigu** [comment]
status is cannot reproduce. not enough details in issue to take any actions.
