### ISSUE TITLE
Knex issue with MySQL

### ISSUE THREAD

**Issue by iamluca** [tgriesser/knex#2901]
# Environment

Knex version: latest
Database + version: MySQL - latest
OS: Ubuntu 18.04

```
0|images  | Unhandled Rejection (Promise): Error: Undefined binding(s) detected when compiling FIRST query: select * from `users` where `token` = ? limit ?
0|images  |     at QueryCompiler_MySQL.toSQL (/lolisafe-master/node_modules/knex/lib/query/compiler.js:151:13)
0|images  |     at Builder.toSQL (/lolisafe-master/node_modules/knex/lib/query/builder.js:119:44)
0|images  |     at /lolisafe-master/node_modules/knex/lib/runner.js:52:32
0|images  |     at tryCatcher (/lolisafe-master/node_modules/bluebird/js/release/util.js:16:23)
0|images  |     at /lolisafe-master/node_modules/bluebird/js/release/using.js:185:26
0|images  |     at tryCatcher (/lolisafe-master/node_modules/bluebird/js/release/util.js:16:23)
0|images  |     at Promise._settlePromiseFromHandler (/lolisafe-master/node_modules/bluebird/js/release/promise.js:512:31)
0|images  |     at Promise._settlePromise (/lolisafe-master/node_modules/bluebird/js/release/promise.js:569:18)
0|images  |     at Promise._settlePromise0 (/lolisafe-master/node_modules/bluebird/js/release/promise.js:614:10)
0|images  |     at Promise._settlePromises (/lolisafe-master/node_modules/bluebird/js/release/promise.js:694:18)
0|images  |     at Promise._fulfill (/lolisafe-master/node_modules/bluebird/js/release/promise.js:638:18)
0|images  |     at PromiseArray._resolve (/lolisafe-master/node_modules/bluebird/js/release/promise_array.js:126:19)
0|images  |     at PromiseArray._promiseFulfilled (/lolisafe-master/node_modules/bluebird/js/release/promise_array.js:144:14)
0|images  |     at Promise._settlePromise (/lolisafe-master/node_modules/bluebird/js/release/promise.js:574:26)
0|images  |     at Promise._settlePromise0 (/lolisafe-master/node_modules/bluebird/js/release/promise.js:614:10)
0|images  |     at Promise._settlePromises (/lolisafe-master/node_modules/bluebird/js/release/promise.js:694:18)

```

**Comment by kibertoad** [comment]
@iamluca Can't be sure without looking at you code, but I think what is happening is that you are passing undefined value as a parameter which by default throws an error. This is an expected behaviour. See documentation:

```
If one prefers that undefined keys are replaced with NULL instead of DEFAULT one may give useNullAsDefault configuration parameter in knex config.

var knex = require('knex')({
  client: 'mysql',
  connection: {
    host : '127.0.0.1',
    user : 'your_database_user',
    password : 'your_database_password',
    database : 'myapp_test'
  },
  useNullAsDefault: true
});

knex('coords').insert([{x: 20}, {y: 30}, {x: 10, y: 20}])
// insert into `coords` (`x`, `y`) values (20, NULL), (NULL, 30), (10, 20)"
```

**Comment by kibertoad** [comment]
Actually, I think I'm wrong; this is only for not specified keys, undefined values are always incorrect. Again, documentation:
```
Important: Supplying knex with an undefined value to any of the where functions will cause knex to throw an error during sql compilation. This is both for yours and our sake. Knex cannot know what to do with undefined values in a where clause, and generally it would be a programmatic error to supply one to begin with. The error will throw a message containing the type of query and the compiled query-string. Example:

knex('accounts')
.where('login', undefined)
.select()
.toSQL()
Error:
Undefined binding(s) detected when compiling SELECT query: select * from `accounts` where `login` = ?
```

**Comment by iamluca** [comment]
Ok; let me pass this along to the dev team.

**Comment by iamluca** [comment]
@kibertoad I'll invite you to the discord & the github resp. I'll pay too.

**Comment by kibertoad** [comment]
@iamluca Problem looks extremely trivial and doesn't seem to be anywhere in the realm of something deserving to be paid for; if I can take a look at sources, I'm pretty sure it would be pretty easy to figure out what's going on; likely some parameter is not being passed.

**Comment by elhigu** [comment]
@iamluca please provide way to reproduce the issue as it is instructed in issue template. Closing this until bug report is complete and there is something that we can do about.
