### ISSUE TITLE
Parse Error when inserting records into tables in many-to-many relationship

### ISSUE THREAD

**Issue by hubitor** [tgriesser/knex#2922]
# Environment

Knex version: 0.15.2
Database + version: MariaDB 10.1.37
OS: Antergos (Arch Linux)

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
I have 2 tables (users, permissions) which are linked over a junction table (user_permission). I'm trying to insert a record into the tables with a raw query with Knex but I'm getting a SQL Parse Error.  The same queries:
```
START TRANSACTION;
INSERT INTO permissions(name) VALUES('Permission 1');
SET @last_permission_id = LAST_INSERT_ID();
SET @user_id = (SELECT id FROM users WHERE last_name LIKE '%Smith%');
INSERT INTO user_permission (user_id, permission_id) VALUES (@user_id, @last_permission_id);
COMMIT;
```
work fine when I test them in Adminer.

2. Error message

```
Unhandled rejection Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDBserver version for the right syntax to use near 'INSERT INTO permissions(name) VALUES('Something19');
SET @last_permission_id = L' at line 2
    at Query.Sequence._packetToError (/home/user/workspace/ExpressJS/test_project_02/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/user/workspace/ExpressJS/test_project_02/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/user/workspace/ExpressJS/test_project_02/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/home/user/workspace/ExpressJS/test_project_02/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/user/workspace/ExpressJS/test_project_02/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/user/workspace/ExpressJS/test_project_02/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/home/user/workspace/ExpressJS/test_project_02/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)
    --------------------
    at Protocol._enqueue (/home/user/workspace/ExpressJS/test_project_02/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/user/workspace/ExpressJS/test_project_02/node_modules/mysql/lib/Connection.js:200:25)
    at /home/user/workspace/ExpressJS/test_project_02/node_modules/knex/lib/dialects/mysql/index.js:154:18
    at Promise._execute (/home/user/workspace/ExpressJS/test_project_02/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/home/user/workspace/ExpressJS/test_project_02/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/user/workspace/ExpressJS/test_project_02/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/home/user/workspace/ExpressJS/test_project_02/node_modules/knex/lib/dialects/mysql/index.js:148:12)
    at Client_MySQL.query (/home/user/workspace/ExpressJS/test_project_02/node_modules/knex/lib/client.js:202:17)
    at Runner.<anonymous> (/home/user/workspace/ExpressJS/test_project_02/node_modules/knex/lib/runner.js:146:36)
    at Runner.tryCatcher (/home/user/workspace/ExpressJS/test_project_02/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/home/user/workspace/ExpressJS/test_project_02/node_modules/bluebird/js/release/method.js:15:34)
    at /home/user/workspace/ExpressJS/test_project_02/node_modules/knex/lib/runner.js:48:21
    at tryCatcher (/home/user/workspace/ExpressJS/test_project_02/node_modules/bluebird/js/release/util.js:16:23)
    at /home/user/workspace/ExpressJS/test_project_02/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/home/user/workspace/ExpressJS/test_project_02/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/user/workspace/ExpressJS/test_project_02/node_modules/bluebird/js/release/promise.js:512:31)
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

```
var myquery = `START TRANSACTION;
INSERT INTO permissions(name) VALUES('Permission 1');
SET @last_permission_id = LAST_INSERT_ID();
SET @user_id = (SELECT id FROM users WHERE last_name LIKE '%Smith%');
INSERT INTO user_permission (user_id, permission_id) VALUES (@user_id, @last_permission_id);
COMMIT;`

knex.raw(myquery).then(function (records) {
    console.log(JSON.parse(JSON.stringify(records[0])));
});
```

**Comment by elhigu** [comment]
Try to use mariadb driver directly to run that query and report back if it works there.  Nothing in this report suggests that there is a bug in knex causing this.
