### ISSUE TITLE
JSON type MySQL column insertion issue

### ISSUE THREAD

**Issue by JSEA** [tgriesser/knex#2928]
# Environment

Knex version: 0.15.2
Database + version: MySQL 5.7.24
OS: OS X El Capitan 10.11.6

 @smorey2 

# Bug

1. JSON column unable to handle an array that contains objects/object with multiple properties. Works as specified with an array with an object with a single property.

2. Error message:

```
Unhandled rejection Error: ER_INVALID_JSON_TEXT: Invalid JSON text: "Missing a comma or '}' after an object member." at position 75 in value for column 'products.images'.
    at Query.Sequence._packetToError (/Product-Details/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Product-Details/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Product-Details/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Product-Details/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Product-Details/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Product-Details/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Product-Details/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
    --------------------
    at Protocol._enqueue (/Product-Details/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Product-Details/node_modules/mysql/lib/Connection.js:200:25)
    at /Product-Details/node_modules/knex/lib/dialects/mysql/index.js:154:18
    at Promise._execute (/Product-Details/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/Product-Details/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Product-Details/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/Product-Details/node_modules/knex/lib/dialects/mysql/index.js:148:12)
    at Client_MySQL.query (/Product-Details/node_modules/knex/lib/client.js:202:17)
    at Runner.<anonymous> (/Product-Details/node_modules/knex/lib/runner.js:146:36)
    at Runner.tryCatcher (/Product-Details/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/Product-Details/node_modules/bluebird/js/release/method.js:15:34)
    at /Product-Details/node_modules/knex/lib/runner.js:48:21
    at tryCatcher (/Product-Details/node_modules/bluebird/js/release/util.js:16:23)
    at /Product-Details/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Product-Details/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Product-Details/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Product-Details/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Product-Details/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Product-Details/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Product-Details/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Product-Details/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Product-Details/node_modules/bluebird/js/release/promise_array.js:144:14)
```

# Issue discussion

I'm seeding a db with data from a CSV, one column contains an array of objects. For example purposes this is how one column in the DB appears:

```
_id, name, rating, reviewCount, itemNum, price, mainImage, images
1, Tasty Granite Fish, 1.8, 130,1, 239.00, 41-min.jpg, [{"image":"https://ss-ss-wwww-1.wwwwwwwww.www/rrrrr-ttttttttttt/1-min.jpg","color":"Plum"}]
2, Practical Metal Shoes, 1.1, 67,2, 467.00, 87-min.jpg, [{"image":"https://ss-ss-wwww-1.wwwwwwwww.www/rrrrr-ttttttttttt/2-min.jpg","color":"Grey"},{"image":"https://ss-ss-wwww-1.wwwwwwwww.www/rrrrr-ttttttttttt/86-min.jpg","color":"Cyan"}]
```
The issue I'm facing is the array containing the objects with multiple properties are being rejected as invalid JSON text. However when I I remove the second property within the object, the row is inserted without issue.

``` 
Using environment: development
  knex:client acquired connection from pool: __knexUid1 +0ms
  knex:query delete from `products` undefined +0ms
  knex:bindings [] undefined +0ms
  knex:client releasing connection to pool: __knexUid1 +12ms
  knex:client acquired connection from pool: __knexUid1 +55ms
  knex:query insert into `products` (`images`, `itemNum`, `mainImage`, `name`, `price`, `rating`, `reviewCount`, `_id`) values (?, ?, ?, ?, ?, ?, ?, ?) undefined +63ms
  knex:bindings [ ' [{"image":"https://ss-ss-wwww-1.wwwwwwwww.www/rrrrr-ttttttttttt/1-min.jpg"}]',
  knex:bindings   '1',
  knex:bindings   ' https://ss-ss-wwww-1.wwwwwwwww.www/rrrrr-ttttttttttt/41-min.jpg',
  knex:bindings   ' Tasty Granite Fish',
  knex:bindings   ' 239.00',
  knex:bindings   ' 1.8',
  knex:bindings   ' 130',
  knex:bindings   '1' ] undefined +62ms
  knex:client releasing connection to pool: __knexUid1 +15ms
  knex:client acquired connection from pool: __knexUid1 +1ms
  knex:query insert into `products` (`images`, `itemNum`, `mainImage`, `name`, `price`, `rating`, `reviewCount`, `_id`) values (?, ?, ?, ?, ?, ?, ?, ?) undefined +15ms
  knex:bindings [ ' [{"image":"https://ss-ss-wwww-1.wwwwwwwww.www/rrrrr-ttttttttttt/2-min.jpg"',
  knex:bindings   '2',
  knex:bindings   ' https://ss-ss-wwww-1.wwwwwwwww.www/rrrrr-ttttttttttt/87-min.jpg',
  knex:bindings   ' Practical Metal Shoes',
  knex:bindings   ' 467.00',
  knex:bindings   ' 1.1',
  knex:bindings   ' 67',
  knex:bindings   '2' ] undefined +15ms
  knex:client releasing connection to pool: __knexUid1 +5ms
```
Due to the size of the CSV file I'm attempting to use stream to insert the data.

```javascript
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('products').del()
    .then(function () {
      // Inserts seed entries
      return new Promise(function(resolve, reject) {
        fs.createReadStream('database/data.csv')
        .on('error', reject)
        .pipe(csv())
        .on('error', reject)
        .pipe(new Transform({
          objectMode: true,
          transform: function(chunk, _, callback) {
            knex('products').insert(chunk).then(function() {
              callback();
            });
          }, function (done) {
            resolve();
            done();
          }
        }))
        .on('error', reject);
      })
    });
};
```

Any insight on how to resolve this issue will be greatly appreciated.

**Comment by elhigu** [comment]
Print out chunks which you are trying to insert and reduce this testcase to be a single failing insert. From that it wil be easier for you to find out how to insert that single chunk correctly. 

Closing as knex usage issue.

**Comment by JSEA** [comment]
Thanks for the response.

Single test case has been done prior to reporting this issue. I am knew to JS and Knex so I could be missing something however.

The below object inserts with no issues
```
[{"image":"https://ss-ss-wwww-1.wwwwwwwww.www/rrrrr-ttttttttttt/1-min.jpg"}]
```

The below does not insert
```
[{"image":"https://ss-ss-wwww-1.wwwwwwwww.www/rrrrr-ttttttttttt/1-min.jpg","color":"Plum"}]
```

Instead the above inserts as the following (basically stopping after the first property and ignoring the second property.
```
[{"image":"https://s3-us-west-1.amazonaws.com/hrr34-trailblazer/1-min.jpg"
```

Resulting in the following error:
```
ER_INVALID_JSON_TEXT: Invalid JSON text: "Missing a comma or '}' after an object member.
```

**Note:** I had to stringily the object during the generation of the CSV as a result of it being returned as [object Object].

**Comment by elhigu** [comment]
So if I understood correctly this works:

knex(’table’).insert([{”image” : ”a”}])

And

knex(”table”).insert([{ “image” : “a”, “color”: “p”}]) 

does not?

**Comment by JSEA** [comment]
Yes, that is exactly what I'm facing.

**Comment by elhigu** [comment]
Ok... none of them are working correctly. Since you are passing an array to `.insert` knex will think that you are inserting multiple rows with for example columns `image` and `color` in this case.

There is nothing in your code, which hints at all that you have JSON type of column used somewhere... 😐

**Comment by elhigu** [comment]
So would be best to first try to add some correct data manually (by hard coding some queries with knex) to your table and that way you will also learn how to deal with inserting JSON data. You might need to use `JSON.stringify` before inserting javascript object to JSON column, but I don't know for sure how mysql driver behaves.

**Comment by JSEA** [comment]
Thanks for your response. My apologies, I did not include it initially, but the JSON type column was specified in the table creation.

```Javascript
exports.up = function(knex, Promise) {
  return knex.schema.createTable('products', function(t) {
    t.increments('_id').primary().unique();
    t.string('name').notNullable();
    t.integer('rating');
    t.integer('reviewCount');
    t.integer('itemNum').notNullable();
    t.integer('price').notNullable();
    t.string('mainImage');
    t.json('images');
  })
  .then(() => console.log('table created'))
  .catch((err) => {
    console.log(err);
    throw err
  })
  .finally(() => {
    knex.destroy();
  })
};

exports.down = function(knex, Promise) {
  return knex.schema.dropTable('products');
};
```

I will continue to study the issue to see what is the cause. I was thinking there may be something I overlooked.

**Comment by Travelinprod** [comment]
gg
