### ISSUE TITLE
MYSQL ECONNRESET

### ISSUE THREAD

**Issue by Jay427** [tgriesser/knex#2965]
# Environment

Knex version:"0.14.6"
Database + version: MYSQL Ver 15.1 Distrib 10.1.31-MariaDB, for Win32 (AMD64)
OS:Windows 10

# Bug

```
{ error:
   { Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
    --------------------
    at Protocol._enqueue (C:\GitLabProject\demo\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Connection.query (C:\GitLabProject\demo\node_modules\mysql\lib\Connection.js:208:25)
    at C:\GitLabProject\demo\node_modules\knex\lib\dialects\mysql\index.js:161:18
    at Promise._execute (C:\GitLabProject\demo\node_modules\bluebird\js\release\debuggability.js:303:9)
    at Promise._resolveFromExecutor (C:\GitLabProject\demo\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\GitLabProject\demo\node_modules\bluebird\js\release\promise.js:79:10)
    at Client_MySQL._query (C:\GitLabProject\demo\node_modules\knex\lib\dialects\mysql\index.js:155:12)
    at Client_MySQL.query (C:\GitLabProject\demo\node_modules\knex\lib\client.js:206:17)
    at Runner.<anonymous> (C:\GitLabProject\demo\node_modules\knex\lib\runner.js:155:36)
    at Runner.tryCatcher (C:\GitLabProject\demo\node_modules\bluebird\js\release\util.js:16:23)
    at Runner.query (C:\GitLabProject\demo\node_modules\bluebird\js\release\method.js:15:34)
    at C:\GitLabProject\demo\node_modules\knex\lib\runner.js:61:21
    at tryCatcher (C:\GitLabProject\demo\node_modules\bluebird\js\release\util.js:16:23)
    at C:\GitLabProject\demo\node_modules\bluebird\js\release\using.js:185:26
    at tryCatcher (C:\GitLabProject\demo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\GitLabProject\demo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\GitLabProject\demo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\GitLabProject\demo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\GitLabProject\demo\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\GitLabProject\demo\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (C:\GitLabProject\demo\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (C:\GitLabProject\demo\node_modules\bluebird\js\release\promise_array.js:144:14)
     code: 'ECONNRESET',
     errno: 'ECONNRESET',
     syscall: 'read',
     fatal: true },
  data: null }
```

# Knex connection Function
```
const knexConnection = async (connection){
   const knex = require('knex')({
	client: 'mysql',
	connection:connection ,
	pool: { min: 0, max: 7 },
   });
   return knex;
}
```

#Query Used
const connection = {
	host: 'localhost',
	user: 'root',
	password: 'root',
	database: 'test',
}
const knexTemp = await knexConnection(connection);
const tableData = [{'name' : jack},{'name' : 'marker'}];
const data = await knexTemp.insert(tableData).into('testtable');

#Question 
1. When try to connect temporary knex connection above query fire for more than 3000 records insert at time below error occurs.

**Comment by elhigu** [comment]
Please add complete minimal code for reproduction. Current one cannot just be copy pasted and ran against own DB. Closing until then.

**Comment by Jay427** [comment]
@elhigu 

[code.zip](https://github.com/tgriesser/knex/files/2698917/code.zip)

Check this zip file
-Create table with including schema
-Run code using this command node server.js

**Comment by elhigu** [comment]
Thanks... I read the code through. I would suspect you are running to maximum SQL statement length. Single SQL statement can be only 65kB with mysql and you are creating insert with 5000 rows which means that unless single row is less than 13 bytes, you will exceed that limit.

**Comment by elhigu** [comment]
You can use knex.batchInsert, lodash.chunk (for splitting your rows to insert to smaller batches)  or for example objection's graphInsert to work around that.

**Comment by Jay427** [comment]
@elhigu Thanks.
