### ISSUE TITLE
MSSQL's batchInsert : The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.

### ISSUE THREAD

**Issue by Gehbrial** [tgriesser/knex#2986]
# Environment

Knex version: 0.16.3
Database + version: SQL Server 13.0.4206.0
OS: Windows 10

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

@smorey2 

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Whenever I try to batch insert records, I quickly run into an issue with tedious because I bust the maximum of request parameters. It makes you have to estimate the number of records you can insert at a time and requires extra work that isn't required when using other libraries such as Sequelize.

2. Error message

```
Unhandled rejection RequestError: The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
    at handleError (/mnt/c/integration-pwa-v2/node_modules/mssql/lib/tedious.js:551:15)
    at Connection.emit (events.js:182:13)
    at Parser.tokenStreamParser.on.token (/mnt/c/integration-pwa-v2/node_modules/tedious/lib/connection.js:635:12)
    at Parser.emit (events.js:182:13)
    at Parser.parser.on.token (/mnt/c/integration-pwa-v2/node_modules/tedious/lib/token/token-stream-parser.js:27:14)
    at Parser.emit (events.js:182:13)
    at addChunk (/mnt/c/integration-pwa-v2/node_modules/readable-stream/lib/_stream_readable.js:296:12)
    at readableAddChunk (/mnt/c/integration-pwa-v2/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at Parser.Readable.push (/mnt/c/integration-pwa-v2/node_modules/readable-stream/lib/_stream_readable.js:239:10)
    at Parser.Transform.push (/mnt/c/integration-pwa-v2/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at doneParsing (/mnt/c/integration-pwa-v2/node_modules/tedious/lib/token/stream-parser.js:80:14)
    at token (/mnt/c/integration-pwa-v2/node_modules/tedious/lib/token/infoerror-token-parser.js:48:5)
    at call.lineNumber (/mnt/c/integration-pwa-v2/node_modules/tedious/lib/token/infoerror-token-parser.js:13:19)
    at awaitData (/mnt/c/integration-pwa-v2/node_modules/tedious/lib/token/stream-parser.js:185:7)
    at Parser.awaitData (/mnt/c/integration-pwa-v2/node_modules/tedious/lib/token/stream-parser.js:109:7)
    at Parser.readUInt32LE (/mnt/c/integration-pwa-v2/node_modules/tedious/lib/token/stream-parser.js:182:10)
    at parser.readBVarChar.procName (/mnt/c/integration-pwa-v2/node_modules/tedious/lib/token/infoerror-token-parser.js:12:90)
    at readBuffer.data (/mnt/c/integration-pwa-v2/node_modules/tedious/lib/token/stream-parser.js:322:9)
    at awaitData (/mnt/c/integration-pwa-v2/node_modules/tedious/lib/token/stream-parser.js:314:7)
    at Parser.awaitData (/mnt/c/integration-pwa-v2/node_modules/tedious/lib/token/stream-parser.js:109:7)
    at Parser.readBuffer (/mnt/c/integration-pwa-v2/node_modules/tedious/lib/token/stream-parser.js:311:10)
    at readUInt8.length (/mnt/c/integration-pwa-v2/node_modules/tedious/lib/token/stream-parser.js:321:12)
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

```
async function insertRecords(records) { // Records contains 2000 objects with 6 properties each
  return knex.transaction(async function(trx) {
    return trx("SOME_TABLE")
      .truncate()
      .then(() => {
        return trx.batchInsert("SOME_TABLE", records);
      });
  });

await insertRecords(records)
```

**Comment by elhigu** [comment]
Sounds like you need to use smaller chunk size. Docs say that "By default, the chunkSize is set to 1000."   in your case I suppose 100-200 would be better.

**Comment by vkuzel** [comment]
Note: in case you encountered this error because Ebean generates a query with too many parameters, you have to set [`lazyLoadBatchSize`](https://ebean.io/docs/query/background/nplus1#lazy-batch-size) and `queryBatchSize` on server config.

**Comment by KrisLau** [comment]
> Sounds like you need to use smaller chunk size. Docs say that "By default, the chunkSize is set to 1000." in your case I suppose 100-200 would be better.

@elhigu Is there a reason you suggested 100-200? The error said 2100 and online I saw that the limit was 1000 inserts which would be within the default chunkSize. The change you suggested worked for me I was just curious why haha
