### ISSUE TITLE
Why do I have to have a knexfile.js file to use the CLI to generate migrations?

### ISSUE THREAD

**Issue by toymachiner62** [tgriesser/knex#2987]
I don't want to use a `knexfile.js` file for my env configurations b/c I'm using helm/kubernetes and I inject my environment configs during build/deploy.

I tried creating a migration without having a `knexfile.js` file and it blows up with:

```sh
$ knex migrate:make create_organization
Using environment: development
path.js:39
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1091:7)
    at directories.map.directory (/Users/tomcaflisch/Sites/ciitizen/ciitizen-organization-service/node_modules/knex/lib/migrate/MigrationGenerator.js:82:28)
    at Array.map (<anonymous>)
    at MigrationGenerator._absoluteConfigDirs (/Users/tomcaflisch/Sites/ciitizen/ciitizen-organization-service/node_modules/knex/lib/migrate/MigrationGenerator.js:81:24)
    at MigrationGenerator._ensureFolder (/Users/tomcaflisch/Sites/ciitizen/ciitizen-organization-service/node_modules/knex/lib/migrate/MigrationGenerator.js:41:23)
    at MigrationGenerator.make (/Users/tomcaflisch/Sites/ciitizen/ciitizen-organization-service/node_modules/knex/lib/migrate/MigrationGenerator.js:35:17)
    at Migrator.make (/Users/tomcaflisch/Sites/ciitizen/ciitizen-organization-service/node_modules/knex/lib/migrate/Migrator.js:122:27)
    at Command.commander.command.description.option.action (/Users/tomcaflisch/.nvm/versions/node/v9.11.1/lib/node_modules/knex/bin/cli.js:179:10)
    at Command.listener (/Users/tomcaflisch/.nvm/versions/node/v9.11.1/lib/node_modules/knex/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:180:13)
    at Command.parseArgs (/Users/tomcaflisch/.nvm/versions/node/v9.11.1/lib/node_modules/knex/node_modules/commander/index.js:654:12)
    at Command.parse (/Users/tomcaflisch/.nvm/versions/node/v9.11.1/lib/node_modules/knex/node_modules/commander/index.js:474:21)
    at Liftoff.invoke (/Users/tomcaflisch/.nvm/versions/node/v9.11.1/lib/node_modules/knex/bin/cli.js:278:13)
    at Liftoff.execute (/Users/tomcaflisch/.nvm/versions/node/v9.11.1/lib/node_modules/knex/node_modules/liftoff/index.js:203:12)
    at module.exports (/Users/tomcaflisch/.nvm/versions/node/v9.11.1/lib/node_modules/knex/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/Users/tomcaflisch/.nvm/versions/node/v9.11.1/lib/node_modules/knex/node_modules/liftoff/index.js:195:5)
    at /Users/tomcaflisch/.nvm/versions/node/v9.11.1/lib/node_modules/knex/node_modules/liftoff/index.js:165:9
    at /Users/tomcaflisch/.nvm/versions/node/v9.11.1/lib/node_modules/knex/node_modules/v8flags/index.js:135:14
    at /Users/tomcaflisch/.nvm/versions/node/v9.11.1/lib/node_modules/knex/node_modules/v8flags/index.js:41:14
    at /Users/tomcaflisch/.nvm/versions/node/v9.11.1/lib/node_modules/knex/node_modules/v8flags/index.js:53:7
    at process._tickCallback (internal/process/next_tick.js:176:11)
```

Since using the CLI to generate migrations doesn't actually run any migrations, why is the `knexfile.js` necessary to generate migrations?

**Comment by kibertoad** [comment]
It is not necessary in 0.16.3
