### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by jpegram2** [tgriesser/knex#3117]
# Environment

Knex version: 0.16.3
Database + version: Any
OS: Linux

1. Using node 11.10.0 Knex is throwing an Unexpected token export error on line 3 of knex/lib/index.js
export default Knex

2. Error message

/Users/direwolf/Sites/node/api-node/node_modules/knex/lib/index.js:3
export default Knex;
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:698:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/direwolf/Sites/node/api-node/node_modules/knex/knex.js:25:18)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/direwolf/Sites/node/api-node/modules/devtest/controllers/mysql.controller.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at module.exports (/Users/direwolf/Sites/node/api-node/modules/devtest/routes/mysql.routes.js:8:17)
    at config.files.routes.forEach (/Users/direwolf/Sites/node/api-node/server/services/express.js:129:37)
server failed: unable to initialize Mongoose or ExpressJS
(node:32220) UnhandledPromiseRejectionWarning: Error: unable to initialize Mongoose or ExpressJS
    at Promise (/Users/direwolf/Sites/node/api-node/server/app.js:53:21)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:32220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:32220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by elhigu** [comment]
Are you using node <6 ?

**Comment by elhigu** [comment]
Please provide reproduction code for this. Can be reopened if can be verified.
