### ISSUE TITLE
New version 0.16.4 throws an error and breaks our CI

### ISSUE THREAD

**Issue by tavizon** [tgriesser/knex#3139]
# Environment

Knex version: 0.16.4
Database + version: Mysql v5.5.59
OS: circleCi

# Bug

1. Your 0.16.4 version auto updated from '0.16.3' and this caused our circleCi build process to throw an error and fail when attempting to run migrate:latest. Since this can cause this breaking issue, we feel this release should be re-released as '0.17.0'. This does not occur locally 

2. Error: You are using Node.js 6. Please consider upgrading to Node.js 8+ or add '@babel/polyfill' dependency to the project (knex will automatically load it).
    at Object.<anonymous> (/home/circleci/build/node_modules/knex/knex.js:22:11)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at initKnex (/home/circleci/build/node_modules/knex/bin/cli.js:94:16)
    at Command.commander.command.description.option.action (/home/circleci/build/node_modules/knex/bin/cli.js:191:17)
    at Command.listener (/home/circleci/build/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/home/circleci/build/node_modules/commander/index.js:651:12)
    at Command.parse (/home/circleci/build/node_modules/commander/index.js:474:21)
    at Liftoff.invoke (/home/circleci/build/node_modules/knex/bin/cli.js:280:13)
Exited with code 1
.

**Comment by kibertoad** [comment]
related #2955

**Comment by kibertoad** [comment]
@tavizon 0.16.5 was just released. Please let us know if it resolves the problem in a satisfatory way.

**Comment by tavizon** [comment]
Thank you for the quick response. As soon as the release is available I will update.

**Comment by kibertoad** [comment]
@tavizon What do you mean? It was released already.

**Comment by ricardograca** [comment]
It fixed the problem in my case.

**Comment by tavizon** [comment]
I am good now. I was seeing the changes to master but not the actual release.

Thank you again!

**Comment by elhigu** [comment]
@tavizon did you update your knex to 0.16.5?
