### ISSUE TITLE
Runtime async errors don't show full traceback, even with asyncStackTraces enabled

### ISSUE THREAD

**Issue by rclmenezes** [tgriesser/knex#3200]
Run the following with `NODE_ENV=development`:

```javascript
const knex = require("knex");

const db = knex({
  asyncStackTrace: true,
  client: "postgres",
  connection: {
    host: "localhost",
    user: "postgres",
    password: "postgres",
    database: "postgres",
  },
  debug: true,
});

const test = async () => {
  await db("users").where({ id: "asdf" });
};

test().finally(() => {
  db.destroy();
});
```

And you get the following error, without the original line that called the query:

```
(node:4274) UnhandledPromiseRejectionWarning: error: invalid input syntax for integer: "asdf"
    at Connection.parseE (/Users/rmenezes/code/seedfi/web/node_modules/pg/lib/connection.js:601:11)
    at Connection.parseMessage (/Users/rmenezes/code/seedfi/web/node_modules/pg/lib/connection.js:398:19)
    at Socket.<anonymous> (/Users/rmenezes/code/seedfi/web/node_modules/pg/lib/connection.js:120:22)
    at Socket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
From previous event:
    at Client_PG._query (/Users/rmenezes/code/seedfi/web/node_modules/knex/lib/dialects/postgres/index.js:245:12)
    at Client_PG.query (/Users/rmenezes/code/seedfi/web/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/Users/rmenezes/code/seedfi/web/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /Users/rmenezes/code/seedfi/web/node_modules/knex/lib/runner.js:47:21
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Runner.run (/Users/rmenezes/code/seedfi/web/node_modules/knex/lib/runner.js:33:30)
    at Builder.Target.then (/Users/rmenezes/code/seedfi/web/node_modules/knex/lib/interface.js:23:43)
(node:4274) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4274) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

While `asyncStackTrace` revealed the error in https://github.com/tgriesser/knex/issues/2500, it doesn't seem to work for runtime errors like mine.

**Comment by david1602** [comment]
Reading the commit that apparently fixes it, it checks for `asyncStackTraces`, not `asyncStackTrace`, meaning you are not using the right property.

https://github.com/tgriesser/knex/commit/e086427db01e116f042f50a2acaf1e65c6bd2edd#diff-ff9eb136561ea616d243650733d24677R19

However, it doesn't work for me either. I'm using version 0.16.3. Since the latest version is 0.17.0 and I don't feel comfortable updating a giant project since the last major change that kicked us suddenly did not allow undefined bindings anymore. The version discrepancy might by my problem though, the proper property name might be yours.

**Comment by rclmenezes** [comment]
Fixing the typo and moving to 0.17.0 fixed this! Thanks!

```
$ node ./src/bin/testStackTrace.js
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'asdf' ],
  __knexQueryUid: 'd5ed7a8e-2a5e-402b-8807-bd4fc576053e',
  sql: 'select * from "users" where "id" = ?'
}
(node:16694) UnhandledPromiseRejectionWarning: error: invalid input syntax for integer: "asdf"
    at createQueryBuilder (/Users/rmenezes/code/seedfi/web/node_modules/knex/lib/util/make-knex.js:297:26)
    at knex (/Users/rmenezes/code/seedfi/web/node_modules/knex/lib/util/make-knex.js:33:12)
    at test (/Users/rmenezes/code/seedfi/web/src/bin/testStackTrace.js:16:9)
    at Object.<anonymous> (/Users/rmenezes/code/seedfi/web/src/bin/testStackTrace.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:822:10)
    at internal/main/run_main_module.js:17:11
(node:16694) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16694) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kibertoad** [comment]
@david1602 My apologies for the inconvenience caused. Are you talking about https://github.com/tgriesser/knex/pull/3231 or some other issue?

**Comment by david1602** [comment]
@kibertoad it's a pretty old change, we went from like 0.13.x to 0.16.3 at some point, and undefined query bindings would fail, such as:

```javascript
const obj = {a: 1};

knex('table').where({col1: obj.a, col2: obj.b})
```

not really a problem since have fixed it in all places in our code now (which is a 200k+ sloc project), but we're very careful about updating our libs again in general

**Comment by kibertoad** [comment]
@david1602 0.17 is a much tamer uodate in this regard, only potentially breaking changes are in TypeScript bindings, so if you are not using TS, it is both safe and recommended upgrade.

**Comment by david1602** [comment]
@kibertoad thanks for the info, we're already considering it, especially for that stack update since that often causes issues when looking for failed queries
