### ISSUE TITLE
The famous : Timeout acquiring a connection. The pool is probably full error

### ISSUE THREAD

**Issue by davidroman0O** [tgriesser/knex#3310]
# Environment

Knex version: ^0.18.0
PG version: ^7.11.0
Database + version: PostgreSQL 11
OS: unknown, hosted on DigitalOcean with their managed database cluster BUT same issue on my local OSX

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I'm trying to reach a PostgreSQL 11 database on the managed database cluster of DigitalOcean.

When working in local, everything works in my app BUT when deployed OR executed in local with all the production parameters, I got the famous `Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`.

I got this error even on the deployed container on a k8s cluster, the managed k8s of DO.

I've saw a lot of us got this error. 

My connection look like this : 

```javascript

{ 
    client: 'pg', 
    connection: { 
        sslmode: 'require', 
        ssl: true, 
        user: 'doadmin', 
        password: '********', 
        port: '25060', 
        host: 'beta-*****-do-user-*****-0.db.ondigitalocean.com', 
        database: 'staging.migrations'
    }, 
    migrations: { directory: '/app/src/db/migrations/migrations' }, 
    seeds: { directory: '/app/src/db/seeds/migrations' }, 
    acquireConnectionTimeout: 10000, 
    pool: { 
        min: 1, 
        max: 1, 
        // I saw an issue here telling to set this property to false
        propagateCreateError: false, 
        idleTimeoutMillis: 10000, 
        createTimeoutMillis: 10000, 
        acquireTimeoutMillis: 10000
    }, 
    ssl: true
}


```

2. Error message

`Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

```javascript

{ TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
   at Bluebird.try.then.catch (/app/node_modules/knex/src/client.js:315:17)
   at tryCatcher (/app/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
   at /app/node_modules/knex/node_modules/bluebird/js/release/catch_filter.js:17:41
   at tryCatcher (/app/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
   at Promise._settlePromiseFromHandler (/app/node_modules/knex/node_modules/bluebird/js/release/promise.js:517:31)
   at Promise._settlePromise (/app/node_modules/knex/node_modules/bluebird/js/release/promise.js:574:18)
   at Promise._settlePromise0 (/app/node_modules/knex/node_modules/bluebird/js/release/promise.js:619:10)
   at Promise._settlePromises (/app/node_modules/knex/node_modules/bluebird/js/release/promise.js:695:18)
   at _drainQueueStep (/app/node_modules/knex/node_modules/bluebird/js/release/async.js:138:12)
   at _drainQueue (/app/node_modules/knex/node_modules/bluebird/js/release/async.js:131:9)
   at Async._drainQueues (/app/node_modules/knex/node_modules/bluebird/js/release/async.js:147:5)
   at Immediate.Async.drainQueues (/app/node_modules/knex/node_modules/bluebird/js/release/async.js:17:14)
   at runCallback (timers.js:810:20)
   at tryOnImmediate (timers.js:768:5)
   at processImmediate [as _immediateCallback] (timers.js:745:5)
 sql: 'CREATE DATABASE "staging.migrations"',
 bindings: undefined }

```

EDIT : I've test a connection with `psql` and it's working ! Sooo, I really don't know right now.

---

Hope someone had the same issue and could pointing me what I missed! 😄

**Comment by elhigu** [comment]
Cannot reproduce, you need to add code which triggers that exception. 

Anyways you are creating pool with size of 1 so if you are trying to do 2 parallel queries or transactions it will already be filled...

Also that is a strange error... does your user have rights to create new databases?

> // I saw an issue here telling to set this property to false
>   propagateCreateError: false, 

Please don't do that. It will cause just error loop until acquireConnectionTimeout in case of invalid connection parameters and if there are network problems etc. Knex is designed to work with that set to `true`. Also it might mask original error in this case.

Where have you seen that issue? I should go to comment there...

Can be reopened if complete reproduction is provided.

**Comment by davidroman0O** [comment]
Thx for the tips, I'll try and comment when it's working 😄

**Comment by nealoke** [comment]
@davidroman0O how did you fix this? :(

**Comment by briandamaged** [comment]
@nealoke : Try increasing the `pool.max` to something larger than 1.  (Ex: `max: 5`)

(There are various operations in `knex` that need to establish secondary connections.)

**Comment by kevincherryholme** [comment]
@davidroman0O Have you solved this?

**Comment by batadamnjanovic** [comment]
I solved this problem with these versions:
"knex": "^0.21.1",
"objection": "^2.1.3",
"pg": "^8.0.3",

**Comment by himharsh1997** [comment]
> I solved this problem with these versions:
> 
> ```
> "knex": "^0.21.1",
> "objection": "^2.1.3",
> "pg": "^8.0.3"
> ```

I have same version of knex and pg but still getting error

**Comment by arifulislamat** [comment]
**Having same issue**

### Error logs
```
Error starting botpress
SubError [TimeoutError]: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /snapshot/botpress8/node_modules/knex/lib/client.js:345:17
    at tryCatcher (/snapshot/botpress8/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at /snapshot/botpress8/node_modules/knex/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/snapshot/botpress8/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/snapshot/botpress8/node_modules/knex/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/snapshot/botpress8/node_modules/knex/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/snapshot/botpress8/node_modules/knex/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/snapshot/botpress8/node_modules/knex/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/snapshot/botpress8/node_modules/knex/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/snapshot/botpress8/node_modules/knex/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/snapshot/botpress8/node_modules/knex/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate._onImmediate (/snapshot/botpress8/node_modules/knex/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21) {
  sql: undefined,
  bindings: undefined
}
```

- PostgreSQL docker image: 11.2-alpine

### Note: PostgreSQL was deployed on Docker Swarm with three replicas.

**Comment by KrishnaPayyavula** [comment]
I have the same issue now.

What is the fix for this ?
