### ISSUE TITLE
Regression to transaction 

### ISSUE THREAD

**Issue by optii** [tgriesser/knex#3314]
# Environment

Knex version: 0.18.0
Database + version: postgres 10

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

This relates to #3309 and is an example of what is occurring. Here is the repro code, explanation is below.

```sql
create table "user"
(
	id serial not null,
	name varchar
);

alter table "user" owner to hapi;

create unique index user_name_uindex
	on "user" (name);


```
```javascript

const Knex = require('knex');

const pg = Knex({
    client     : 'pg',
    connection : {
        host     : '0.0.0.0',
        user     : '',
        password : '',
        database : ''
    }
});

const run = async () => {

    try {

        await pg.transaction(async (trx) => {

            await pg('user').transacting(trx).insert({ name : '1' });
            await pg('user').transacting(trx).insert({ name : '1' });
        });
    }
    catch (error) {

        console.log('caught the error', error);
    }
};

run();

```
When running this code in knex v0.17.x the duplicate error gets caught by the `catch`. In knex v0.18.x the error is caught in the `catch` but there is also an `UnhandledPromiseRejection` detailed below. Using `doNotRejectOnRollback : false` or `doNotRejectOnRollback : true` didn't change the outcome.

2. Error message

```
(node:24006) UnhandledPromiseRejectionWarning: error: duplicate key value violates unique constraint "user_name_uindex"
    at Connection.parseE (/tmp/knex-repro/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/tmp/knex-repro/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/tmp/knex-repro/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Client_PG._query (/tmp/knex-repro/node_modules/knex18/src/dialects/postgres/index.js:235:12)
    at Client_PG.query (/tmp/knex-repro/node_modules/knex18/src/client.js:158:17)
    at /tmp/knex-repro/node_modules/knex18/src/transaction.js:312:24
From previous event:
    at Client_PG.trxClient.query (/tmp/knex-repro/node_modules/knex18/src/transaction.js:307:12)
    at Runner.query (/tmp/knex-repro/node_modules/knex18/src/runner.js:136:36)
    at /tmp/knex-repro/node_modules/knex18/src/runner.js:40:23
From previous event:
    at Runner.run (/tmp/knex-repro/node_modules/knex18/src/runner.js:26:16)
    at Builder.Target.then (/tmp/knex-repro/node_modules/knex18/src/interface.js:14:43)
(node:24006) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24006) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If you need any further information or if the reproduction doesn't work let me know.

**Comment by kibertoad** [comment]
Thank you for the repro! I'm flying back from tech summit in Germany right now, will take a look at this first thing when I'm fully operation again :D

**Comment by ianwremmel** [comment]
Ran into this where I'm relying on the previous behavior to implement insertOrUpdate (admittedly, there's probably a better way to do this:

```typescript
let token: string;
try {
  [token] = await knex.transaction(async (trx) =>
    trx
      .insert({
        installationId,
        owner,
        repo,
        repoId,
      })
      .into('repo_tokens')
      .returning('token')
  );
} catch (err) {
  // 23505 is postgres's internal code for `unique_violation`. I don't see
  // a more readable way to interpret `err`, unfortunately.
  if (err.code !== '23505') {
    throw err;
  }
  ({token} = await knex.transaction(async (trx) =>
    trx
      .select('token')
      .from('repo_tokens')
      .where({
        installationId,
        repoId,
      })
      .first()
  ));
}
return token
```

**Comment by kibertoad** [comment]
@optii Could you please check 0.18.1 and report back if it resolves the issue completely for you?

**Comment by optii** [comment]
`0.18.1` seems to have resolved the issue denoted above, thanks for the quick fix on this ! :+1:

**Comment by kibertoad** [comment]
@vonagam is the real hero :D
