### ISSUE TITLE
.spread is not a function when seed:run

### ISSUE THREAD

**Issue by colmer** [tgriesser/knex#3365]
# Environment

Knex version: 19.0.0
Database + version: pg 7.11.0
OS: Ubuntu 18.04

# Bug

When I try run seeds by command ```knex seed:run```, I have error
Error message ```TypeError: initKnex(...).seed.run(...).spread is not a function```
It's break from version 0.18.0. I think ```.spread``` is [bluebird](http://bluebirdjs.com) legacy code.

**Comment by kibertoad** [comment]
Why was it closed?

**Comment by colmer** [comment]
Problem was in old global knex version. Global was 0.15 version, locally  in project was 0.19.0.

**Comment by mynameisedison** [comment]
So how did you update the global knex version?

**Comment by kibertoad** [comment]
@mynameisedison https://docs.npmjs.com/updating-packages-downloaded-from-the-registry

**Comment by Omid-Incarnation** [comment]
even I updated the package globally but still doesn't work for me :(
"knex": "^0.19.2"

**Comment by kibertoad** [comment]
@Omid-Incarnation Can you share the stacktrace of an error that you are getting? And are you sure you are not calling .spread in your code anywhere?

**Comment by Omid-Incarnation** [comment]
@kibertoad Thanks for replying.

$ knex seed:run

Using environment: development
C:\Users\Omid Incarnation\AppData\Roaming\npm\node_modules\knex\bin\cli.js:268
        .spread((log) => {
         ^

TypeError: initKnex(...).seed.run(...).spread is not a function
    at Command.commander.command.description.option.action (C:\Users\Omid Incarnation\AppData\Roaming\npm\node_modules\knex\bin\cli.js:268:10)
    at Command.listener (C:\Users\Omid Incarnation\AppData\Roaming\npm\node_modules\knex\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:189:13)
    at Command.parseArgs (C:\Users\Omid Incarnation\AppData\Roaming\npm\node_modules\knex\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\Omid Incarnation\AppData\Roaming\npm\node_modules\knex\node_modules\commander\index.js:474:21)
    at Liftoff.invoke (C:\Users\Omid Incarnation\AppData\Roaming\npm\node_modules\knex\bin\cli.js:280:13)
    at Liftoff.execute (C:\Users\Omid Incarnation\AppData\Roaming\npm\node_modules\knex\node_modules\liftoff\index.js:201:12)
    at module.exports (C:\Users\Omid Incarnation\AppData\Roaming\npm\node_modules\knex\node_modules\flagged-respawn\index.js:51:3)
    at Liftoff.<anonymous> (C:\Users\Omid Incarnation\AppData\Roaming\npm\node_modules\knex\node_modules\liftoff\index.js:191:5)
    at C:\Users\Omid Incarnation\AppData\Roaming\npm\node_modules\knex\node_modules\liftoff\index.js:149:9
    at C:\Users\Omid Incarnation\AppData\Roaming\npm\node_modules\knex\node_modules\v8flags\index.js:138:14
    at C:\Users\Omid Incarnation\AppData\Roaming\npm\node_modules\knex\node_modules\v8flags\index.js:41:14
    at C:\Users\Omid Incarnation\AppData\Roaming\npm\node_modules\knex\node_modules\v8flags\index.js:53:7
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by Omid-Incarnation** [comment]
I just fix the problem!

Although I updated Knex globally by this code " npm update -g knex " the Knex didn't update so I install it again like this "npm install knex -g".

now it is working ;)

**Comment by f3ltron** [comment]
you should update your docs and tell to use npx to use the local version of the project

**Comment by danielbucket** [comment]
I'm having a similar problem when running the script 'knex migrate:make'. I've asked the question and added details on StackOverflow. Nothing I've attempted or found has proven to be helpful. If anyone can help me solve this issue, I'd be very appreciative.

Here's a link to my post: https://stackoverflow.com/questions/65801414/knex-migration-error-spread-not-a-function
