### ISSUE TITLE
Does knex support Windows Authentication for MS SQL?

### ISSUE THREAD

**Issue by ericbiewener** [tgriesser/knex#3376]
I'm trying to connect to MS Sql using a config that looks like:

```js
{
    client: "mssql",
    connection: `Server=0.0.0.0,1433;Database=MyApp;User Id=MyApp;Password=my_password`,
}
```

But am receiving the error:

```The "config.server" property is required and must be of type string.```

It looks like the connection string is getting parsed into:

```js
{
  "client": "sqlite3",
  "connection": {
    "filename": "Server=0.0.0.0,1433;Database=Rise;User Id=RiseDev;Password=heady-carafe3-Roar;"
  }
}
```

Does knex support an MS SQL connection string? Based on the error I'm receiving and [this issue](https://github.com/tgriesser/knex/issues/2794) my sense is that the answer is no, but I wanted to be certain.

**Comment by elhigu** [comment]
passing connection string directly to connection probably tries to parse it with some generic parser that doesn't support MSSql connection strings. You need to pass it like: 

```
{
  client: 'mssql',
  connection : {
    // options from https://www.npmjs.com/package/mssql#general-same-for-all-drivers
  }
}
```

Would be good to make knex to support passing native connection string directly to the driver though.

**Comment by llwt** [comment]
[It looks like the underlying driver supports connection strings](https://github.com/tediousjs/node-mssql/tree/3072bd6f9d6d74ee83895e749c844d2cb04a990c#formats), but knex is blowing up for me asking for a port.

__Example:__
```js
const config = {
  client: "mssql",
  connection: `mssql://AppDev:${process.env.APP_DEV_PASSWORD}@0.0.0.0:1433/App`,
  asyncStackTraces: true,
  debug: false,
};
export const db = knex(config);
```
__Error__
```
TypeError: The "config.options.port" property must be of type number.
    at Function.get (/Users/vn0my18/src/store-services/rise/node_modules/knex/src/util/make-knex.js:186:28)
    at getSchemaBuilder (/Users/vn0my18/src/store-services/rise/node_modules/knex/src/migrate/table-creator.js:61:17)
    at ensureTable (/Users/vn0my18/src/store-services/rise/node_modules/knex/src/migrate/table-creator.js:11:10)
    at listCompleted (/Users/vn0my18/src/store-services/rise/node_modules/knex/src/migrate/migration-list-resolver.js:13:10)
    at Object.listAllAndCompleted (/Users/vn0my18/src/store-services/rise/node_modules/knex/src/migrate/migration-list-resolver.js:32:5)
    at Migrator.latest (/Users/vn0my18/src/store-services/rise/node_modules/knex/src/migrate/Migrator.js:66:8)
    at Command.commander.command.description.option.action (/Users/vn0my18/src/store-services/rise/node_modules/knex/bin/cli.js:219:18)
    at Command.listener (/Users/vn0my18/src/store-services/rise/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:198:13)
    at Command.parseArgs (/Users/vn0my18/src/store-services/rise/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/vn0my18/src/store-services/rise/node_modules/commander/index.js:474:21)
    at Liftoff.invoke (/Users/vn0my18/src/store-services/rise/node_modules/knex/bin/cli.js:354:13)
    at Liftoff.execute (/Users/vn0my18/src/store-services/rise/node_modules/liftoff/index.js:201:12)
```

Is there a way to ask `knex` to just pass it to the driver?

**Comment by llwt** [comment]
Validated that strings work using:

```js
const ConnectionString = require("mssql/lib/connectionstring");

export const dbConfig = {
    client: "mssql",
    connection: ConnectionString.resolve(`mssql://AppDev:${process.env.APP_DEV_PASSWORD}@0.0.0.0:1433/App`),
};
```

**Comment by elhigu** [comment]
Try with password that doesn't have any special chars... those might mess up the parser. From stack trace the error seems to be coming from knex...

**Comment by llwt** [comment]
The error ended up coming from some object merging logic we had in our `knexfile.js` that was only used for migrations.

That being said, being able to pass a connection string directly to the underlying driver would be nice.

I dug into the codebase and [it looks like knex parses the string even for drivers where a string is allowed](https://github.com/tgriesser/knex/blob/master/lib/util/parse-connection.js#L24).

If I were to open a PR for this do you think going the route that is implemented for postgres (linked above) would be the right move? Is there something in knex that needs the connection params to be a parsed object?

**Comment by FabianTe** [comment]
Maybe this page might interest some of you: https://www.connectionstrings.com/sql-server-2016/

**Comment by hrmartinez** [comment]
I was able to connect using msnodeqlv8 by making a new dialect based on [this example ](https://github.com/knex/knex/blob/master/CONTRIBUTING.md#i-would-like-to-add-support-for-new-dialect-to-knex-is-it-possible)

I just added the msnodesqlv8 module and used the following code, hopefully it helps someone out:

`require('mssql/msnodesqlv8');

let Knex = require("knex");

let Dialect = require(`knex/lib/dialects/mssql/index.js`);
Dialect.prototype._driver = () => require('mssql/msnodesqlv8');

let sql = Knex({
  client: Dialect,
  connection: {
    server: "<sql server>",
    port: 1433,
    database: "<database name>",
    driver: "msnodesqlv8",
    options: {
        trustedConnection: true
      }
  }
});
`

**Comment by mazmoiz** [comment]
> I was able to connect using msnodeqlv8 by making a new dialect based on [this example ](https://github.com/knex/knex/blob/master/CONTRIBUTING.md#i-would-like-to-add-support-for-new-dialect-to-knex-is-it-possible)
> 
> I just added the msnodesqlv8 module and used the following code, hopefully it helps someone out:
> 
> ```js
> require('mssql/msnodesqlv8');
> 
> let Knex = require("knex");
> 
> let Dialect = require(`knex/lib/dialects/mssql/index.js`);
> Dialect.prototype._driver = () => require('mssql/msnodesqlv8');
> 
> let sql = Knex({
>   client: Dialect,
>   connection: {
>     server: "<sql server>",
>     port: 1433,
>     database: "<database name>",
>     driver: "msnodesqlv8",
>     options: {
>         trustedConnection: true
>       }
>   }
> });
> ```

This did not work for me :(. 
It gives me "MSSQL - TypeError: _this.driver.Connection is not a constructor" error.

**Comment by mercmobily** [comment]
Hi everyone, I wanted to provide an important update on Windows Authentication support that may help many of you.

Windows Authentication is actually now possible with Knex using the existing tedious driver, without needing msnodesqlv8. Tedious has supported NTLM authentication since version 1.1.0 (released in 2014), and modern versions of the mssql package allow you to use it through the `authentication` configuration object.

You can configure Knex like this to use Windows Authentication with domain credentials:

```javascript
{
  client: 'mssql',
  connection: {
    server: 'myserver',
    database: 'mycooldatabase',
    authentication: {
      type: 'ntlm',
      options: {
        domain: 'mydomain',
        userName: 'myuser',
        password: 'mypassword'
      }
    }
  }
}
```

This approach works with current versions of Knex without needing any custom dialect or workarounds. The `authentication` object gets passed through to tedious, which handles NTLM authentication natively.

Regarding the original question about connection strings, whilst the underlying mssql driver supports connection strings, Knex's configuration parser currently requires an object format. You can work around this using the mssql ConnectionString utility as @llwt demonstrated in 2019, but the authentication object approach above is cleaner.

For msnodesqlv8 support, there's been an open pull request (#3806) since April 2020. However, it hasn't been merged because it lacks tests and documentation. The maintainers wanted to ensure any new driver passes the entire Knex test suite, which is challenging for Windows-specific functionality in CI/CD pipelines.

The main remaining use case for msnodesqlv8 would be true Windows integrated authentication where you don't need to provide credentials at all (using `trustedConnection: true`). The NTLM approach above still requires username and password, even though it uses domain authentication. If passwordless integrated authentication is specifically what you need, the custom dialect workaround from @hrmartinez might work, though several users reported "Driver.Connection is not a constructor" errors with that approach.

**Related Issues:**
- #4626 (duplicate, closed)
- #6013 (duplicate)
- #3806 (PR for msnodesqlv8 support, still open)
