### ISSUE TITLE
pool.afterCreate no longer supported?

### ISSUE THREAD

**Issue by richardgirges** [tgriesser/knex#3380]
# Environment

Knex version: 0.19.0
Database + version: PostgreSQL 10.5
OS: macOS Mojave 10.14.15

It appears the `afterCreate` hook inside of the `pool` configuration is no longer available, yet the documentation still lists it as a viable option: http://knexjs.org/#Installation-pooling-afterCreate

Based on reading the changelog and upgrade guide, I can see that there is some callout to using `tarn.js` to manage these types of hooks ourselves, but I'm not seeing any actionable information on how to actually do this.

1. It would be nice for the documentation to be updated when a breaking change like this is introduced.

2. I'm looking for guidance on the "tarn.js way" of doing the following (this is effectively the same example provided in the knex documentation) - see code below.

The issue I'm facing is that I can't seem to figure out how to override the pool configuration with my own tarn.js pool, since instantiating a tarn.js pool requires passing in the DB client somehow. (see here: https://github.com/vincit/tarn.js#usage)

```
const dbClient = Knex({
  client: 'pg',
  useNullAsDefault: true,
  connection: {
    host: config.get('dbHost'),
    user: config.get('dbUser'),
    password: config.get('dbPassword'),
    database: config.get('dbName'),
    timezone: 'UTC',
  },
  searchPath: ['public'],
  pool: {
    min: 2,
    afterCreate: (connection, callback) => {
        connection.query(`SET timezone to 'UTC'`, err =>
        callback(err, connection),
      );
    }
  },
});
```

Any help would be greatly appreciated, and as always, thank you for the stellar work on knex.

**Comment by elhigu** [comment]
You need to set it up after creating knex instance by setting event handlers to knex.client.pool.on(eventName, handler) tarn docs has details about the events that can be hooked. Sorry for not being able to help more on mobile.

**Comment by elhigu** [comment]
Oops... sorry. I thought you were talking about afterDestroy or something like that that was finally deprecated.

afterCreate should still work as before. If not then it is a bug. That callback is implemented in knex’s code.

**Comment by richardgirges** [comment]
Oh man, okay that makes more sense. I just realized the problem goes deeper on my side. It looks like `afterCreate` _is_ working, but not when I'm running in NODE_ENV=test. During our jest integration tests, that's the only time `afterCreate` fails. Here's the error output:

```
    Tarn: unsupported option opt.afterCreate

       7 | types.setTypeParser(1700, parseFloat);
       8 | 
    >  9 | const dbClient = Knex({
         |                  ^
      10 |   client: 'pg',
      11 |   useNullAsDefault: true,
      12 |   connection: {

      at new Pool (node_modules/tarn/lib/Pool.js:63:23)
      at Client_PG.initializePool (node_modules/knex/lib/client.js:299:17)
      at Client_PG.Client (node_modules/knex/lib/client.js:61:12)
      at new Client_PG (node_modules/knex/lib/dialects/postgres/index.js:15:10)
      at Knex (node_modules/knex/lib/knex.js:52:28)
      at Object.Knex (src/utils/dbClient.js:9:18)
      at Object.<anonymous> (src/services/__tests__/DBService.test.js:1:1)

Test Suites: 16 failed, 16 total
Tests:       0 total
Snapshots:   0 total
Time:        2.877s, estimated 27s
Ran all test suites.
Error: Tarn: unsupported option opt.afterCreate
    at new Pool (/repo/workclout/api-service/node_modules/tarn/lib/Pool.js:63:23)
    at Client_PG.initializePool (/repo/workclout/api-service/node_modules/knex/lib/client.js:299:17)
    at Client_PG.Client (/repo/workclout/api-service/node_modules/knex/lib/client.js:61:12)
    at new Client_PG (/repo/workclout/api-service/node_modules/knex/lib/dialects/postgres/index.js:15:10)
    at Knex (/repo/workclout/api-service/node_modules/knex/lib/knex.js:52:28)
    at Object.Knex (/repo/workclout/api-service/src/utils/dbClient.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/repo/workclout/api-service/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/repo/workclout/api-service/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/repo/workclout/api-service/jest/globalTeardown.js:1:18)
```

**Comment by kibertoad** [comment]
Can you check if there are no conflicting versions of knex being used? If you take a look at client. js:299, you'll see it is deleting afterCreate before passing further.

**Comment by richardgirges** [comment]
I just checked around in the code, package.json, and package-lock.json. The only version of knex that I'm finding is 0.19.1 - no other version of knex. If I downgrade to knex 18.4 and re-run the tests, everything works fine

**Comment by kibertoad** [comment]
@richardgirges Can you submit PR with failing test for this?

**Comment by elhigu** [comment]
I actually didn't find any real testcase which should have been broken if that callback is not executed anymore. Thats pretty bad bug if it is really broken.

**Comment by johncmunson** [comment]
I can confirm that these both work equally...
```js
pool: {
  afterCreate: (conn, cb) => {
    conn.run('PRAGMA foreign_keys = ON', cb)
  }
}
```
```js
const knex = Knex(knexConfig.development)
knex.client.pool.on('createSuccess', (eventId, resource) => {
  resource.run('PRAGMA foreign_keys = ON', () => {})
})
Model.knex(knex)
```

**Comment by elhigu** [comment]
Anyways test case for afterCreate should be added. That is why I have left this open.

**Comment by mrbarletta** [comment]
In my case, on PG 12.11 and knex 2.1 the afterCreate didn't work, thankfully the other option worked just fine

My example in case another googler ends up here
``` 
knex.client.pool.on('createSuccess', (eventId, resource) => {
  resource.query('('hasura.user', '{ "x-hasura-role": "admin",  "x-hasura-application": "cli.import_clients_contacts", "x-hasura-lxusername": "mrb"}', false)', () => {})
})
```

**Comment by ddtch** [comment]
1) I wonder why we don't have this is documentation on the knex. 
2) It is September 2022 with nestjs aftercreate not working (

**Comment by Shubha9519** [comment]
Facing another issue with the afterCreate.
I am using Sqlite3 with SqlCipher. 
I followed this : https://coolaj86.com/articles/building-sqlcipher-for-node-js-on-raspberry-pi-2/ 
in order to build sqlcipher from source.

It seems conn.run('PRAGMA KEY='myKey') not working. Can you please guide me on this? 

My Code:
` DbCon = knex({
      client: 'sqlite3',
      connection: {
        filename:
        './local_user.db'
      },
      pool: {
        afterCreate: (conn: IConnection, done: () => void) => {
          const key = 'OP+5G1_a23[1]2';
          conn.run(`PRAGMA KEY = '${key}';`, (err: Error) => {
            if (err) {
              console.log('PRAGMA KEY err', err);
            }
            done();
          });
        },
        min: 1,
        max: 1
      },
       useNullAsDefault: true
    });
`

**Comment by mercmobily** [comment]
Hi! Thanks for flagging this.   In practice, `pool.afterCreate` works when the callback resolves correctly; if it appears ineffective, the usual culprit is that the callback never resolves.

**Previous maintainers suggested adding a test for `afterCreate`; I will keep this issue open for coverage improvements.**

You can see the flow in lib/client.js:200–220 and 259–268. `getPoolSettings()` attaches `create: async () => { const connection = await this.acquireRawConnection(); if (poolConfig.afterCreate) await promisify(poolConfig.afterCreate)(connection); return connection; }`. Then `initializePool()` removes `afterCreate` from the Tarn config (lib/client.js:288–301) because it is handled by Knex, not by Tarn.

Working patterns:

```js
pool: {
  min: 0,
  max: 10,
  afterCreate: (conn, done) => {
    // perform per-connection setup here
    done(null, conn);
  }
}
```

or

```js
pool: {
  min: 0,
  max: 10,
  afterCreate: async (conn) => {
    // async initialisation; just return when finished
  }
}
```

If `afterCreate` never calls its callback/never resolves a promise, pool creation stalls and later queries look like they “hang”. I know it's been quite a while, but if you have a concrete case where a properly resolving `afterCreate` isn’t invoked, please share the client/dialect and I’ll dig into that code path.

Alternative (Tarn pool event): as several users noted, you can also hook Tarn pool events directly if you prefer that style or run into test environment quirks. For example:

```js
const knex = require('knex')(config);
knex.client.pool.on('createSuccess', (_eventId, conn) => {
  // per-connection init here, e.g. PRAGMAs for sqlite, SET for pg
});
```

Note: the "Tarn: unsupported option opt.afterCreate" error appears when `afterCreate` reaches Tarn because it was not stripped by Knex (e.g. due to version mismatch or a conflicting install). In supported versions, Knex deletes `afterCreate` before passing the config to Tarn and runs it itself.
