### ISSUE TITLE
Using trx as a transaction object does not work with sqlite

### ISSUE THREAD

**Issue by handmilkingsoftware** [tgriesser/knex#3443]
# Environment

Knex version:0.19.3
Database + version: sqlite3 4.1.0
OS: Ubuntu 18.040.3 LTS

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
When I run my tests, when it comes to an api update resource test, I have it as a transaction, after that is done (without problems) and before moving to the next test example (beforeeach) it runs a clean script which truncates al tables, it uses the previosly commited transaction done time ago under the repository.
It should not reused the previous transaction and actuallly not use any transaction at all as the clean database script does not make use of transactions

2. Error message
Error: Transaction query already complete, run with DEBUG=knex:tx for more info

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

https://runkit.com/embed/icmy44o5nt44

```
DEBUG=knex:query,knex:bindings,knex:tx node testindex.js 
sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
  knex:query create table `test` (`id` integer not null primary key autoincrement, `data` varchar(255)) undefined +0ms
  knex:bindings [] undefined +0ms
  knex:query insert into `test` (`data`) select ? as `data` union all select ? as `data` undefined +6ms
  knex:bindings [ 'foo', 'bar' ] undefined +7ms
  knex:tx trx2: Starting top level transaction +0ms
  knex:query BEGIN; trx2 +3ms
  knex:bindings undefined trx2 +2ms
  knex:query COMMIT; trx2 +2ms
  knex:bindings undefined trx2 +3ms
  knex:tx trx2: releasing connection +4ms
  knex:query delete from `test` trx2 +2ms
  knex:bindings [] trx2 +1ms
  knex:query delete from sqlite_sequence where name = 'test' trx2 +0ms
  knex:bindings undefined trx2 +0ms
```

The last queries, from `knex:query COMMIT; trx2 +2ms` should not reference trx2 as that transaction already ended, in this example I didn't get the error, but what happened here is that it stays like for 1 minute like that, until throws timeout, and the timeout says that is was not able to get a conection from the pool.

**Comment by elhigu** [comment]
Cannot reproduce this with attached code:

```
require('sqlite3');
const Knex = require('knex');

const knex = Knex({
  client: 'sqlite',
  connection: ':memory:',
});

(async function run() {
  await knex.schema.createTable('test', (t) => {
    t.increments('id').primary();
    t.string('data');
  });

  await knex('test').insert([{ data: 'foo' }, { data: 'bar' }]);

  const trx = await knex.transaction();

  trx('test')
    .where('id', 1)
    .update({ data: 'abc' });

  await trx.commit();

  await database('test').truncate();
})();
```

```
>   knex:client acquired connection from pool: __knexUid1 +0ms
  knex:query create table `test` (`id` integer not null primary key autoincrement, `data` varchar(255)) undefined +0ms
  knex:bindings [] undefined +0ms
  knex:client releasing connection to pool: __knexUid1 +6ms
  knex:client acquired connection from pool: __knexUid1 +2ms
  knex:query insert into `test` (`data`) select ? as `data` union all select ? as `data` undefined +4ms
  knex:bindings [ 'foo', 'bar' ] undefined +5ms
  knex:client releasing connection to pool: __knexUid1 +2ms
  knex:tx trx2: Starting top level transaction +0ms
  knex:client acquired connection from pool: __knexUid1 +1ms
  knex:query BEGIN; trx2 +3ms
  knex:bindings undefined trx2 +2ms
  knex:query ROLLBACK trx2 +3ms
  knex:bindings undefined trx2 +3ms
  knex:tx trx2: releasing connection +4ms
  knex:client releasing connection to pool: __knexUid1 +4ms
(node:90227) UnhandledPromiseRejectionWarning: TypeError: container is not a function
    at init.then.then.transactor (/Users/mikaelle/Projects/Vincit/knex-db-manager/node_modules/knex/lib/transaction.js:48:20)
    at bound (domain.js:395:14)
    at runBound (domain.js:408:12)
    at tryCatcher (/Users/mikaelle/Projects/Vincit/knex-db-manager/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mikaelle/Projects/Vincit/knex-db-manager/node_modules/knex/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/mikaelle/Projects/Vincit/knex-db-manager/node_modules/knex/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/mikaelle/Projects/Vincit/knex-db-manager/node_modules/knex/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/mikaelle/Projects/Vincit/knex-db-manager/node_modules/knex/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/mikaelle/Projects/Vincit/knex-db-manager/node_modules/knex/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/mikaelle/Projects/Vincit/knex-db-manager/node_modules/knex/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/mikaelle/Projects/Vincit/knex-db-manager/node_modules/knex/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/mikaelle/Projects/Vincit/knex-db-manager/node_modules/knex/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
(node:90227) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:90227) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Anyhow the problem might be actaully related only to debug output. Maybe when connection is returned to the pool, old transaction identifier is not cleared. 

Please add working reproduction code and run it with `DEBUG=knex:*` to see also connection ids and when connections are acquired / returned to the pool.

**Comment by rclayton-the-terrible** [comment]
This same thing just started happening to me with Postgres.  I have production code where we pass the transaction between separate db repository functions:

```typescript
const tx =  await knex.transaction()
await createUser(tx, userParams)
```
And now we are experiencing:

```
"name":"TypeError","message":"container is not a function","stack":"TypeError: container is not a function..."
```

Did the signature of `knex.transaction` change to require the transaction function?  If so, how do we pass transactions around?  Is the happening because of the `await`?

**Comment by rclayton-the-terrible** [comment]
OK - my issue was resolved by upgrading `knex`.

**Comment by rclayton-the-terrible** [comment]
Just kidding.  This is an issue with the latest version of `knex`.  I'm trying to see if I can find the underlying error.

**Comment by mercmobily** [comment]
Hi! Thanks for the logs and reproduction link. I FINALLY reproduced the behaviour locally with DEBUG logging.

This is a logging artefact, not a functional `trx` reuse. After a transaction commits, Knex returns its connection to the pool but does not clear `connection.__knexTxId`. If the same socket is reused for the next query, the logger still prints the old `trx` id (e.g. `trx2`) even though the query is no longer running inside a transaction.

Evidence (with help of AI):
- Repro script (SQLite): start a transaction, update, commit, then run `truncate` outside any `trx`. DEBUG shows `COMMIT; trx2`, followed by `delete from 
  test trx2` (the truncate), which confirms the stale id is attached to the pooled connection’s logging context. Functionally, queries after `commit()` run outside the transaction.
- Code path: transactions set `connection.__knexTxId = this.txid` on acquire (lib/execution/transaction.js:259–286) and release the connection on commit/rollback, but the tx id isn’t cleared before returning it to the pool. The logger reads `__knexTxId` in `enrichQueryObject` for display (lib/execution/internal/query-executioner.js:16–34).

What needs to happen: clear `connection.__knexTxId` when a transaction completes (commit/rollback) before releasing the connection back to the pool. That will make the DEBUG output accurate for subsequent non‑transactional queries on the same socket.

Workarounds/notes for you:
- There’s no need to change your code for correctness:  this does not indicate that the `trx` is being reused after commit.
- If you want to avoid confusing logs until the fix lands, you can enable a separate logger for transaction queries only or filter out `__knexTxId` labels in your log sink.
