### ISSUE TITLE
Error: Connection reset after several hours of idle time

### ISSUE THREAD

**Issue by bdahon** [tgriesser/knex#3447]
# Environment

Knex version: 0.19.0
Database + version: Mysql 5.1.73
OS: Debian

# Bug

After a few hours of idle time in the application, we get a lot of `read ECONNRESET`. I wouldn't mind having this issue, if it was either handled by knex or tarn, but the error bubbles up to our application. This is the stack we get:

```
 Error: read ECONNRESET
  at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
  at Protocol._enqueue (/usr/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
  at Connection.query (/usr/app/node_modules/mysql/lib/Connection.js:201:25)
  at /usr/app/node_modules/knex/lib/dialects/mysql/index.js:130:18
  at Promise._execute (/usr/app/node_modules/bluebird/js/release/debuggability.js:313:9)
  at Promise._resolveFromExecutor (/usr/app/node_modules/bluebird/js/release/promise.js:488:18)
  at new Promise (/usr/app/node_modules/bluebird/js/release/promise.js:79:10)
  at Client_MySQL._query (/usr/app/node_modules/knex/lib/dialects/mysql/index.js:124:12)
  at Client_MySQL.query (/usr/app/node_modules/knex/lib/client.js:158:17)
  at Runner.query (/usr/app/node_modules/knex/lib/runner.js:135:36)
  at /usr/app/node_modules/knex/lib/runner.js:39:23
  at tryCatcher (/usr/app/node_modules/bluebird/js/release/util.js:16:23)
  at /usr/app/node_modules/bluebird/js/release/using.js:185:26
  at tryCatcher (/usr/app/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/usr/app/node_modules/bluebird/js/release/promise.js:517:31)
  at Promise._settlePromise (/usr/app/node_modules/bluebird/js/release/promise.js:574:18)
  at Promise._settlePromise0 (/usr/app/node_modules/bluebird/js/release/promise.js:619:10)

```

I know there are already a few issues opened (https://github.com/tgriesser/knex/issues/3037 for instance), but as @elhigu sugggested, I opened a new issue. 

Apart from this issue, is there any plan for knex to support validating a request in order to keep a healthy pool ?

**Comment by elhigu** [comment]
Thanks for the report! Can you setup somehow mysql server parameters to get this error to manifest without having to wait hours? 

Usually each client overrides that validateConnection() method to check out for example if there has been some error events thrown from connection during the time it has been in the pool.

I'll check if that code of mysql makes sense.

**Comment by elhigu** [comment]
Looks somewhat valid: https://github.com/tgriesser/knex/blob/master/lib/dialects/mysql/index.js#L89

**Comment by bdahon** [comment]
I did some manual tests where I spawn a mysql instance, run a bunch of queries, restart the db. Restarting the db will should make all connections unusable, and i was expecting the bug to be reproduced. However it worked fine. I'll try to get more information.

**Comment by elhigu** [comment]
I have done stress testing where I use toxiproxy to disconnect connections in various phases... Those stress tests has been working fine after I ironed out all driver bugs found during the process.

**Comment by Guo-dalu** [comment]
I had the same "read ECONNRESET" problem recently when using knex. And I also find the `validateConnection` in client.js always returns true. But it seems that I can't simply override `validateConnection` method or `validate` method by passing config params to `pool`. I must fix it, and publish my own custom-knex npm package to get all things right. So, did I missing any simple way to override `validateConnection`?
Also, can I just use [https://github.com/tgriesser/knex/blob/master/lib/dialects/mysql/index.js#L89](https://github.com/tgriesser/knex/blob/master/lib/dialects/mysql/index.js#L89) to fix it instead of querying something like `select 1` manually ?

**Comment by elhigu** [comment]
Please try out if that mysql validiation code works when it is passed directly to pool. 

I'm pretty sure it will not, since it is the same code that is passed there as default for mysql. If validate connection would always return true, then @bdahon tests where he closes db and restarts it would not have worked either.

**Comment by elhigu** [comment]
if you add `select 1` to validation function it will work always correctly, but it will also cause an extra query to DB every time you get connection from pool (in worst case query amount sent by app will double).

**Comment by bdahon** [comment]
@elhigu I don't mind having this extra query sent to server. How can I add the validation query to validation function ? I may have missed something from the docs, but I didn't find any examples.

**Comment by Guo-dalu** [comment]
Thanks for timely reply! 
I believe you are right about whether the validation code works or not when it is passed directly to pool @elhigu. But it really doesn't seem like that in client.js, which is:
```javascript
// in client.js line 233 
  getPoolSettings(poolConfig) {
    poolConfig = defaults({}, poolConfig, this.poolDefaults());

    POOL_CONFIG_OPTIONS.forEach((option) => {
      if (option in poolConfig) {
        this.logger.warn(
          [
            `Pool config option "${option}" is no longer supported.`,
            `See https://github.com/Vincit/tarn.js for possible pool config options.`,
          ].join(' ')
        );
      }
    });

    const timeouts = [
      this.config.acquireConnectionTimeout || 60000,
      poolConfig.acquireTimeoutMillis,
    ].filter((timeout) => timeout !== undefined);

    // acquire connection timeout can be set on config or config.pool
    // choose the smallest, positive timeout setting and set on poolConfig
    poolConfig.acquireTimeoutMillis = Math.min(...timeouts);

    return Object.assign(poolConfig, {
      create: () => {
        return this.acquireRawConnection().then(async (connection) => {
          connection.__knexUid = uniqueId('__knexUid');

          if (poolConfig.afterCreate) {
            await Bluebird.promisify(poolConfig.afterCreate)(connection);
          }
          return connection;
        });
      },

      destroy: (connection) => {
        if (connection !== void 0) {
          return this.destroyRawConnection(connection);
        }
      },

      validate: (connection) => {
        if (connection.__knex__disposed) {
          this.logger.warn(`Connection Error: ${connection.__knex__disposed}`);
          return false;
        }

        return this.validateConnection(connection);
      },
    });
  },
```
So when using Object.assign, my custom poolConfig will be overrided by its own validate function. Then why the custom validation function in pool config can still works? I'm so confused.

**Comment by Guo-dalu** [comment]
@bdahon I've tried this in my project:
```js
import knex from 'knex'
import config from '../config'

const k = knex(config.db)


k.client.pool.validate = async (connection) => {
  // eslint-disable-next-line
  if (connection._fatalError) {
    return false
  }
  await k.select(1)
  return true
}

export default k
```
So I rewrote the validate function in knex.client.pool. But when I tried to throw an Error after `await k.select(1)` to simulate a query mistake, the result is that I can still get data from server though the server terminal did log the `too many connections` Error. I may miss something.  Any help? @elhigu

**Comment by SmallhillCZ** [comment]
We have a same problem with Postgre. When it drops connection after inactivity, error is returned instead of recreating the connection. Tried `propagateCreateError:false`, but did not help.

As for your custom validation function I have two questions:
1) When in the validate function, how calling k.query makes sure it is thesting the current connection and does not acquire some other connection in the pool?
2) In the tarn.js code there is no async function handling, so passing an async function will probably always resolve to boolean true and not reporting the connection status. Am I missing something here?

**Comment by elhigu** [comment]
`propagateCreateError:false` never do that with knex, it will not do anything good for anyone. Knex just start working wrong. Please also inform all sources which is suggesting that it is plainly wrong and does no good. I've been trying to shoot that tip down in many places, but it comes up again and again... 😭

Looks like you are right about tarn's validate function. I'll change tarn to support async validation. Makes sense to support it.

> I also agree, that validating the connection should not be done by executing another query before every connection acquisition. Instead I believe Knex should check for such errors after resolving the queryPromise (either https://github.com/tgriesser/knex/blob/master/lib/runner.js#L144 or https://github.com/tgriesser/knex/blob/master/lib/client.js#L158) and when connection reset by peer or similar happens, should try to destroy current connection, acquire new one and retry the query with the new connection.

I don't thing knex should make that kind of decisions, it should just pass error to client, who will know if query should be retried or not. For example if that happened during transaction that naive approach would fail massively. Knex should have as little smartness in these matters as possible to allow user to decide what to do when unexpected error happens.

Anyhow bug here is that is some cases connection validation doesn't work and would be good to find out why, which requires some way to reproduce the problem.

> It also means connection end event is not called by pg in https://github.com/tgriesser/knex/blob/master/lib/dialects/postgres/index.js#L117 after reset from inactivity, otherwise connection would be marked as invalid and filtered out by original Knex validate fucntion. At the time of the query pg probably doesn't yet know the connection errored.

I don't understand what you mean by this... currently when connection is closed when in pool the exception is recorded and next time when connection is to be fetched from pool it gets discarded and new connection is requested instead. Anyways this issue is not about any postgres problems, this happend with mysql.

**Comment by SmallhillCZ** [comment]
Thanks for the propagateCreateError info, didn't know about that. 

Yer, it is true about the retry, that would cause problems. The real problem is in the connection validation.

Concerning the last paragraph. I meant that if `pg` would send the `error` or `end` event, connection would be marked as bad and would be discarded in the next round. But what we are seeing is that the connection is not discarded and when used throws an error. This is happening independently on the propagateCreateError setting btw.

**Comment by elhigu** [comment]
> But what we are seeing is that the connection is not discarded and when used throws an error. This is happening independently on the propagateCreateError setting btw.

If error is happening for example during transaction or when query is not inside of pool, then error will be returned to the user as a response for the query. Connection errors might happen at any time so pool cannot protect you completely from those.

>  But what we are seeing is that the connection is not discarded and when used throws an error.

Please open postgres related bug report for that with reproduction info. If it is not reproducible there is nothing we can do. You can also add more debug prints to knex that you are running and see if you can catch when that error is set, but not recognized by validate callback.

**Comment by bdahon** [comment]
I tried again to  reproduce the error, but still without success. I tried to restart the database, kill connections, .... And the validation at the pool stage works fine. However we still have the isssue on all our environments. 

@elhigu Any idea on how to reproduce a ECONNRESET error ?

**Comment by elhigu** [comment]
I have tried to reproduce that in multiple different ways, closing / restarting database, killing connections with SQL queries, using toxiproxy to cut / slowdown connections in certain time or after sending some amount of bytes and running all that in stress test looping. Still I have no idea how to get this error... 

Where is your DB server running in production environment? Maybe trying to get _exactly_ same setup locally somehow could help to reproduce it. Figuring out how that database instance is configured and how it is connected to the world. 

One way I can think that this could happen would be for example if that DB server somehow starts sleeping when idle long enough and there would be a proxy server between client and DB which prevents driver from noticing that connection was actually broken between proxy and db server (would be strange proxy but I'm inclined to start thinking long shots here).

**Comment by bdahon** [comment]
We get that behaviour on all our cloud hosted instances. Our production instance is deployed on a VM without any sort of proxy. Our dev / test instances are running as docker containers on kubernetes, which are exposed to the outside world through a nginx reverse tcp proxy.

**Comment by elhigu** [comment]
> We get that behaviour on all our cloud hosted instances. Our production instance is deployed on a VM without any sort of proxy.

Is it cloud hosted just so that virtual machines are in the cloud or somekind of clound managed instances like RDS or google? If they are plain VMs you could try to launch those production VMs locally and see if they work the same that docker instances does. That could rule out differences in database configuration / version / build.

**Comment by bdahon** [comment]
We have a bit of  both, VMs we own, and cloud managed instances (Google Cloud SQL). We could not reproduce it locally.
We tried a suggested fix which was to set the pool minimum size to 0 (we had a greater value before), and the problem seems to be gone.

**Comment by manjufy** [comment]
I have been experiencing the same issue.
https://github.com/nodejs/help/issues/2494

**Comment by SmallhillCZ** [comment]
> We have a bit of both, VMs we own, and cloud managed instances (Google Cloud SQL). We could not reproduce it locally.
> We tried a suggested fix which was to set the pool minimum size to 0 (we had a greater value before), and the problem seems to be gone. We had a few days without issue.

Yes, it is more of a workaround. It forces Tarn to drop the connections if not used and create new ones when needed, so they don't have time to die. We solved this the same way as well.

I went through all of the Knex and Tarn code and there is no active detecting that connection died in either knex or tarn. Tarn relies on connection marking itself as dead and then it replaces it. Since it is a generic pool manager it is logical that it doesn't solve these things, it wouldn't know how to check the specific connection health. Knex reports the connection as dead when it errors out, but in this case it doesn't. The reality that it is dead is known only when it tries to send query. Knex could check the connection before query, but only by sending test queries like SELECT 1 to the database before each query which would be too much overhead.

I see this possible solutions: 
1) Knex would watch if query failed due to connection reasons and in this case it would replace the connection, and rerun the query.
2) pg.Pool seems stable in this way to me, I don't know why. It's an overhead to use two pool mangers, but it could work to provide pg.Pool instead of pg.Client. But it is a workaround again.
3) The node-postgres should detect the failure somehow and report it in a normal way, resulting in Knex marking connection as dead and Tarn recreating it when it is needed. Then it should be reported to node-postgres.

**Comment by bertho-zero** [comment]
Could it be due to the `propagateCreateError` option on this line (documented [here](https://github.com/vincit/tarn.js/)) ?

https://github.com/knex/knex/blob/02d94d96b004a023c5ae1a77109f897e334fb21a/lib/client.js#L241

>

**Comment by bertho-zero** [comment]
It seems that it has more to do with **TCP keepalive**.

If I completely reduce my timeout I get a different error, the ECONNRESET comes from tcp of node.

https://github.com/mysqljs/mysql/issues/1939

I see the TCP keepalive is disabled for my connection if I run this on the server:

```
sudo netstat -napo | grep '3306'
```

**Comment by bertho-zero** [comment]
I thought I found the solution by adding a `pool.afterCreate` option which does a `setKeepAlive` on every new connection to keep it alive:

```js
const knex = knexLib({
  client: 'mysql',
  connection: config.db,
  pool: {
    min: 2,
    max: 20,
    afterCreate(connection, done) {
      connection._socket.setKeepAlive(true, 20000);
      done(null, connection);
    }
  }
})
```

And I can see the difference with this command:

```
sudo tcpdump -ni wlp2s0 port 3306
```

But that didn't fix the problem, after a short break I still had ECONNRESET errors

---

I'm using ProxySQL and by doing this on each instance I see that the connections are kept alive:

```
$> mysql -h 127.0.0.1 -P6032 -uadmin -padmin
mysql> SET mysql-use_tcp_keepalive = 1;
mysql> SET mysql-tcp_keepalive_time = 20;
mysql> LOAD MYSQL VARIABLES TO RUNTIME;
mysql> SAVE MYSQL VARIABLES TO DISK;
mysql> PROXYSQL RESTART;
```

and with `netstat -napo | grep '1.2.3.4'` (replace `1.2.3.4` with my ip) I see that the keepalive is finally activated.

**Comment by elhigu** [comment]
@bertho-zero Is your queries returning that `ECONNRESET`  or are you only seeing it in your logs? This issue is about pool not noticing those broken connections when they are fetched from pool and that is causing that next query sent to the same connection fails.

 It is perfectly fine to have those errors in background if pool notices them before leasing the connection back to application.

**Comment by bertho-zero** [comment]
@elhigu It is the query which returns an ECONNRESET error.

**Comment by elhigu** [comment]
Would you be able to provide reproduction code for that which fails fast?  😮

**Comment by bertho-zero** [comment]
I notice that this does not happen with an environment where I do not enable SSL on ProxySQL.

To reproduce the problem I deploy a new Mysql Cluster environment on https://app.jpe.infomaniak.com/ and I activate SSL with my certificates, my connection works but the first request after about 15 minutes of inactivity returns an ECONNRESET.

Maybe I can send you the credentials + certificates somewhere?

**Comment by elhigu** [comment]
If you could provide docker configuration to reproduce the problem that would be the best 😅 

I would just like to investigate thoroughly (actually I would like that someone else would investigate) the returned connection before executing it (a broken connection returned by knex.client.acquireConnection() after 15 minutes of idling) to see if there are any signs of it being closed that are only missed by knex and to write afterCreate function to the config, which adds event handlers printing out connection's socket events etc. to see if there was actually some events sent from driver about broken connection.

**Comment by bertho-zero** [comment]
It would seem that the minimum pool at 0 corrects the problem, at least for now.

When I reset it to 2, I happen to have an error.

**Comment by elhigu** [comment]
Minimum pool doesn't fix it, but hides the problem, because connection is removed from pool before it is closed by the server.

**Comment by midas104** [comment]
I have the same issue
```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
    --------------------
    at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/app/node_modules/mysql/lib/Connection.js:198:25)
    at /app/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/app/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/app/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/app/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:310:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  fatal: true
```

we have strapi + percona 8.0 installed in k8s cluster
here is strapi issue related to this https://github.com/strapi/strapi/issues/13388

**Comment by terion-name** [comment]
Still an issue. 3 years already

**Comment by manjufy** [comment]
@terion-name It took me months to resolve this issue.

It may not be an issue with knex all together, its multitude of factors. Based on my investigation, its mostly an issue related to configuration and network connections.

Since issue could be arise from varies sources, do state your environment setup, the problem details and how are you using knex.

Here is how it solved for me if it helps : https://github.com/nodejs/help/issues/2494

**Comment by manjufy** [comment]
@terion-name Yes, It could be that knex reconnection is faulty.
However, what I think is that, with the default `pool: { min: 2, max: 10 }`, knext instructs mysql to open minium two connections. Now, at this point in time, two connections are opened in MySQL server. if there are not active connections given time, MySQL marks these connections stale, but knex wouldn't know if these connections are already stale. One way to keep these two connections not stale, is probably having some kind of heart beat setup every few seconds.

Reason that MySQL marks any connections which idle to stale, that depends on the MySQL configuration. One can keep the timeout setting longer, but which could also lead a performance issue. So its hard to make these pool connection alive if we need rely on both Node-Knex settings vs MySQL default settings.

Best approach is to keep the pool connection to `min: 0`, in that, only open up connections when we need to.

**Comment by mercmobily** [comment]
This is being tracked as part of a broader connection pooling meta issue at #6241.

The workaround that works reliably is to set your pool minimum to 0 and configure an appropriate idle timeout so connections are discarded before MySQL closes them:

```js
knex({
  client: 'mysql',
  connection: { ... },
  pool: {
    min: 0,
    max: 10,
    idleTimeoutMillis: 300000 // 5 minutes
  }
})
```

The `min: 0` is crucial - if you have a minimum pool size, idle connections won't be discarded even when they exceed the idle timeout.

The long-term fix would involve proper connection validation before use, but that comes with a performance cost (potentially doubling query count if done naively). For now, the pool configuration above is the recommended approach.

Related issues: #1072, #3523 (PostgreSQL variant)

**Comment by tgriesser** [comment]
@mercmobily maybe we should should just set the default `min` to 0?

**Comment by mercmobily** [comment]
@tgriesser The main reason I haven't done this is because I never actually got to understand the code that handles with the connections. Setting it to 0 _feels_ to me like a way to mask the problem, but I might well be monumentally wrong. But, it IS a solution, the docs SAY to set it to 0, so... yes.
Happy to make a PR, unless you want to... which would be epic really :D

**Comment by tgriesser** [comment]
The argument for having min > 0 is that you learn more quickly that the connection is invalid. However the story around detecting this isn't that great anyway, so maybe it's not worth it. There's also the benefit of skipping the cost of creating a connection at the time of query, but that's typically rather small.

The argument for having the default of min === 0 is:
- Not creating connections unnecessarily as a side-effect of creating a knex instance
- Not having connections hang around and lose connection with the DB, which is this issue

I'd say we should move to min = 0, but wait until a 4.0 release.

In addition to that it'd probably also be helpful to add an option to have knex retry queries on transient network errors on idempotent queries, which we could default to `false` and be opt-in, and then default to `true` going forward.

So let's say you have a pool with 3 connections:

  - `select * from "table_1" ...` (conn 1)
  - `select * from "table_2" ...` (conn 2 - stale)
  - `select * from "table_3" ... ` (conn 3)

What would happen currently is `conn 2` would fail with `ECONNRESET`. There's not a great way to retry. The connection would then go back to the pool and get destroyed (I'm pretty sure at least, looking through the mysql code it's difficult to follow the flow of the event emitters - will confirm this).

What we'd actually probably want is that if we detect it's a basic SELECT query and it's a network error, we'd just retry the query once with a different connection.
