### ISSUE TITLE
Datetime bug in query builder

### ISSUE THREAD

**Issue by chaffeqa** [tgriesser/knex#3461]
# Environment

Knex version: 0.18.3
Database + version: mysql  Ver 8.0.15 for osx10.14 on x86_64 (Homebrew)
OS: osx10.14

# Bug

Simple query involving `Date` object seems to fail to pass compilation, though `toString()` generates valid SQL

```typescript
knex("Entry").count("*").where("createdAt", ">", new Date(nowAt - oneMinute)).toSQL().toNative()
{
  sql: 'select count(*) from `Entry` where `createdAt` > ?',
  bindings: [ 2019-10-01T23:24:23.872Z ]
}
knex("Entry").count("*").where("createdAt", ">", new Date(nowAt - oneMinute)).toString()
'select count(*) from `Entry` where `createdAt` > "2019-10-01T23:24:23.872Z"'
await knex("Entry").count("*").where("createdAt", ">", new Date(nowAt - oneMinute)).debug()
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 2019-10-01T23:24:23.872Z ],
  __knexQueryUid: 'b24ffdbd-162c-4a0a-a35e-5fecb9cc2b3e',
  sql: 'select count(*) from `Entry` where `createdAt` > ?'
}
Thrown:
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
    at createQueryBuilder (/Users/quinnchaffee/code/cbs/fantasy-picks/node_modules/knex/src/util/make-knex.js:257:26)
    at DataLayerEmails.knex (/Users/quinnchaffee/code/cbs/fantasy-picks/node_modules/knex/src/util/make-knex.js:13:12)
    at repl:1:40
    at repl:2:4
    at Script.runInContext (vm.js:137:20)
    at REPLServer.defaultEval (repl.js:386:29)
    at bound (domain.js:420:14)
    at REPLServer.runBound [as eval] (domain.js:433:12)
    at REPLServer.onLine (repl.js:700:10)
    at REPLServer.emit (events.js:214:15)
    at REPLServer.EventEmitter.emit (domain.js:476:20)
    at REPLServer.Interface._onLine (readline.js:316:10) {
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1",
  originalStack: "Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1\n" +
    '    at Packet.asError (/Users/quinnchaffee/code/cbs/fantasy-picks/node_modules/mysql2/lib/packets/packet.js:708:17)\n' +
    '    at Query.execute (/Users/quinnchaffee/code/cbs/fantasy-picks/node_modules/mysql2/lib/commands/command.js:28:26)\n' +
    '    at Connection.handlePacket (/Users/quinnchaffee/code/cbs/fantasy-picks/node_modules/mysql2/lib/connection.js:408:32)\n' +
    '    at PacketParser.onPacket (/Users/quinnchaffee/code/cbs/fantasy-picks/node_modules/mysql2/lib/connection.js:70:12)\n' +
    '    at PacketParser.executeStart (/Users/quinnchaffee/code/cbs/fantasy-picks/node_modules/mysql2/lib/packet_parser.js:75:16)\n' +
    '    at Socket.<anonymous> (/Users/quinnchaffee/code/cbs/fantasy-picks/node_modules/mysql2/lib/connection.js:77:25)\n' +
    '    at Socket.emit (events.js:209:13)\n' +
    '    at Socket.EventEmitter.emit (domain.js:476:20)\n' +
    '    at addChunk (_stream_readable.js:305:12)\n' +
    '    at readableAddChunk (_stream_readable.js:286:11)\n' +
    '    at Socket.Readable.push (_stream_readable.js:220:10)\n' +
    '    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)\n' +
    'From previous event:\n' +
    '    at Client_MySQL2._query (/Users/quinnchaffee/code/cbs/fantasy-picks/node_modules/knex/src/dialects/mysql/index.js:125:12)\n' +
    '    at Client_MySQL2.query (/Users/quinnchaffee/code/cbs/fantasy-picks/node_modules/knex/src/client.js:158:17)\n' +
    '    at Runner.query (/Users/quinnchaffee/code/cbs/fantasy-picks/node_modules/knex/src/runner.js:136:36)\n' +
    '    at /Users/quinnchaffee/code/cbs/fantasy-picks/node_modules/knex/src/runner.js:40:23\n' +
    'From previous event:\n' +
    '    at Runner.run (/Users/quinnchaffee/code/cbs/fantasy-picks/node_modules/knex/src/runner.js:26:16)\n' +
    '    at Builder.Target.then (/Users/quinnchaffee/code/cbs/fantasy-picks/node_modules/knex/src/interface.js:14:43)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)'
}
```

**Comment by elhigu** [comment]
Yep, looks like a bug. Knex should not change Date() to string.

https://runkit.com/embed/ai9im80r6iin

**Comment by Fylipp** [comment]
@elhigu When querying an Oracle database the parameter value becomes `null`. This completely breaks the Oracle compatibility for me. Is this an issue that can be resolved swiftly? This is a complete deal-breaker for my use case.

**Comment by chaffeqa** [comment]
FYI after more debugging, i think its related to something babel is doing in transpiling... may be doing something that breaks detection of `Date` object?

**Comment by chaffeqa** [comment]
@Fylipp  I was able to get around it by doing:

```typescript
await knex("Entry").count("*").where("createdAt", ">", (new Date(nowAt - oneMinute)).toISOString())
```

**Comment by elhigu** [comment]
@chaffeqa  Yep... I never have used  date object in bindings either. I always pass dates as iso strings.

> @elhigu When querying an Oracle database the parameter value becomes null. This completely breaks the Oracle compatibility for me. Is this an issue that can be resolved swiftly? This is a complete deal-breaker for my use case.

Doesn't seem like null to me... https://runkit.com/embed/nbtrv0kj944a

**Comment by mercmobily** [comment]
Hello! Thanks for reporting this issue.

This issue has been resolved in later versions of Knex. As elhigu correctly noted in the discussion, Date objects should be passed directly to the database driver without being converted to strings by Knex.

I've tested the current version (3.1.0) with your exact use case, and Date objects are now properly handled. The bindings array correctly contains the Date object, which is then passed through to the MySQL driver for proper handling. The driver itself knows how to convert Date objects to the appropriate format for MySQL.

The root cause in version 0.18.3 was in the formatter's `wrap` function at `src/formatter.js`. When a Date object was passed as a parameter, the code would attempt to process it as a generic object (calling `parseObject`), which expected a key-value structure for aliases. This was clearly incorrect for Date objects.

Between version 0.18.3 and the current version, the formatter code was significantly refactored (particularly around commits #4213-#4219 in early 2020, and #4275 in February 2021). The parameter handling was moved out of the formatter and into the client, and the logic was corrected to properly handle Date objects by passing them directly to bindings without transformation.

As elhigu mentioned in his comment, the workaround for older versions was to convert Date objects to ISO strings manually using `.toISOString()` before passing them to Knex:

```typescript
await knex("Entry").count("*").where("createdAt", ">", (new Date(nowAt - oneMinute)).toISOString())
```

For anyone still experiencing issues with Date objects in more recent versions, this is most likely a driver-specific issue rather than a Knex issue. Different database drivers may handle Date objects differently, and some may require specific configuration. For example, the MSSQL driver has explicit type mapping for Date objects (see `lib/dialects/mssql/index.js:374-376`), whilst MySQL drivers typically handle Date objects natively.

This issue can be closed as resolved in current versions.


## Related Issues

- #5389 - Timestamp binding not working with JS Date (similar issue reported in 2022, may be driver-specific)
