### ISSUE TITLE
[Bug] Possible unhandled Error with timeout of 1 minute

### ISSUE THREAD

**Issue by sebgie** [tgriesser/knex#587]
I tried to test some error cases that could come up when using Ghost in production. One test case was to stop the database and see what happens. The good news is that bookshelf/knex reconnect to the database once it is restarted. The bad news is that I get a possibly unhandled error when I try to update a post using a `PUT` request. The request is then pending for one minute and Ghost can't handle the error as the promise is not rejected.

**Ghost Setup**
Ghost: https://github.com/TryGhost/Ghost/commit/89905a8e3cd4fbc2ec0f7ce93c8686c17497e475
Bookshelf: 0.7.9
Knex: 0.7.3
DB: MySql

```
Possibly unhandled Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
    at Protocol._enqueue (/home/vagrant/code/Ghost/node_modules/mysql/lib/protocol/Protocol.js:110:48)
    at Protocol.handshake (/home/vagrant/code/Ghost/node_modules/mysql/lib/protocol/Protocol.js:42:41)
    at Connection.connect (/home/vagrant/code/Ghost/node_modules/mysql/lib/Connection.js:98:18)
    at /home/vagrant/code/Ghost/node_modules/knex/lib/dialects/mysql/index.js:105:16
From previous event:
    at new Promise (/home/vagrant/code/Ghost/node_modules/bluebird/js/main/promise.js:84:37)
    at Client_MySQL.acquireRawConnection (/home/vagrant/code/Ghost/node_modules/knex/lib/dialects/mysql/index.js:104:10)
    at Object.create (/home/vagrant/code/Ghost/node_modules/knex/lib/pool.js:33:19)
    at Object.Pool.createResource (/home/vagrant/code/Ghost/node_modules/knex/node_modules/generic-pool-redux/pool.js:288:12)
    at Object.Pool.dispense (/home/vagrant/code/Ghost/node_modules/knex/node_modules/generic-pool-redux/pool.js:166:16)
    at Object.Pool.acquire (/home/vagrant/code/Ghost/node_modules/knex/node_modules/generic-pool-redux/pool.js:116:12)
    at Pool_MySQL.Pool.acquire (/home/vagrant/code/Ghost/node_modules/knex/lib/pool.js:55:22)
    at /home/vagrant/code/Ghost/node_modules/knex/lib/client.js:33:10
From previous event:
    at new Promise (/home/vagrant/code/Ghost/node_modules/bluebird/js/main/promise.js:84:37)
    at Client_MySQL.Client.acquireConnection (/home/vagrant/code/Ghost/node_modules/knex/lib/client.js:31:10)
    at Runner_MySQL.<anonymous> (/home/vagrant/code/Ghost/node_modules/knex/lib/runner.js:146:22)
From previous event:
    at Function.Promise$Bind [as bind] (/home/vagrant/code/Ghost/node_modules/bluebird/js/main/promise.js:274:9)
From previous event:
    at Object.finallyHandler (/home/vagrant/code/Ghost/node_modules/bluebird/js/main/finally.js:63:31)
From previous event:
    at Function.Promise$Bind [as bind] (/home/vagrant/code/Ghost/node_modules/bluebird/js/main/promise.js:274:9)
    at Runner_MySQL.<anonymous> (/home/vagrant/code/Ghost/node_modules/knex/lib/runner.js:29:18)
From previous event:
    at QueryBuilder_MySQL.Target.then (/home/vagrant/code/Ghost/node_modules/knex/lib/interface.js:27:27)
From previous event:
    at Function.Promise$Bind [as bind] (/home/vagrant/code/Ghost/node_modules/bluebird/js/main/promise.js:274:9)
    at _.extend.select (/home/vagrant/code/Ghost/node_modules/bookshelf/lib/sync.js:67:20)
    at _.extend.first (/home/vagrant/code/Ghost/node_modules/bookshelf/lib/sync.js:38:17)
```

**Comment by elhigu** [comment]
Closing in favor of #1833
