### ISSUE TITLE
Setting decimal column defaultTo to 0

### ISSUE THREAD

**Issue by demisx** [tgriesser/knex#673]
I am creating a decimal price column in my migration file like this:

```js
table.decimal('price', 19, 4).notNullable().defaultTo(0).index();
```

However, running migration, I always get this error:

```
 Command failed: error: null value in column "price" violates not-null constraint
```

What is the proper way to set the default on a decimal column to be 0? Thank you.

**Comment by bendrucker** [comment]
Can you turn debug on and grab the queries? Because I see no reason why this shouldn't work:

https://github.com/tgriesser/knex/blob/9777a1c3dea044666e3066b76935dd45ee8a6a84/lib/schema/columncompiler.js#L112-L128

**Comment by demisx** [comment]
This only happens when I have mixed inserts--some with price and some without. If I run them in isolation, then everything works as expected.

Here is an example of such mixed seed

```js
    {// Without price property 
     poster_type_id: 1, source_id: 1, status_id: 2, classified_id: 2, section_id: 1, 
      category_id: 2, details: { condition: "Used", make: "iPhone 5c", serial: 203980982377442 }, 
      location: { city: "Newport Beach", state: "CA" }, 
      title: "This is a disabled ad #1 title", description: "This is a disabled ad #1" },

    { 
     // With price property 
     poster_type_id: 1, source_id: 1, status_id: 2, classified_id: 2, section_id: 1, 
      category_id: 2, details: { condition: "Used", make: "iPhone 5c", serial: 203980982377442 },
      location: { city: "Newport Beach", state: "CA" }, 
      title: "This is a disabled ad #2 title", description: "This is a disabled ad #2", 
      price: 232.34 }
```

 that generates this error:

```bash
{ __cid: '__cid1',
  method: 'insert',
  options: undefined,
  bindings: 
   [ 2,
     2,
     'This is a disabled ad #1',
     { condition: 'Used', make: 'iPhone 5c', serial: 203980982377442 },
     { city: 'Newport Beach', state: 'CA' },
     1,
     undefined,
     1,
     1,
     2,
     'This is a disabled ad #1 title',
     2,
     2,
     'This is a disabled ad #2',
     { condition: 'Used', make: 'iPhone 5c', serial: 203980982377442 },
     { city: 'Newport Beach', state: 'CA' },
     1,
     232.34,
     1,
     1,
     2,
     'This is a disabled ad #2 title' ],
  sql: 'insert into "ads" ("category_id", "classified_id", "description", "details", "location", "poster_type_id", "price", "section_id", "source_id", "status_id", "title") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11), ($12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)',
  returning: undefined }

error: null value in column "price" violates not-null constraint
    at Connection.parseE (/Users/dmoore/projects/dimaslist/dimaslist-org-api/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/dmoore/projects/dimaslist/dimaslist-org-api/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/dmoore/projects/dimaslist/dimaslist-org-api/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

[08:17:04] 'dbseed:dev' errored after 603 ms
[08:17:04] Error: Command failed: error: null value in column "price" violates not-null constraint
    at Connection.parseE (/Users/dmoore/projects/dimaslist/dimaslist-org-api/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/dmoore/projects/dimaslist/dimaslist-org-api/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/dmoore/projects/dimaslist/dimaslist-org-api/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

**Comment by bendrucker** [comment]
Ah okay so this is not a migration issue. You're actually running into #662 here. For now you can just manually set the price to 0.
