### ISSUE TITLE
Knex attempts to end non-existent connection

### ISSUE THREAD

**Issue by joepie91** [tgriesser/knex#702]
Upon attempting to load a page in my Express application that uses the database, while the MySQL server was not running, the following error crashed my process (in addition to a "connection reset" error being caught by my error handling):

```
/home/sven/projects/fancyshelf/node_modules/knex/lib/pool.js:45
      connection.end();
                 ^
TypeError: Cannot call method 'end' of undefined
    at Object.destroy [as destroyHandler] (/home/sven/projects/fancyshelf/node_modules/knex/lib/pool.js:45:18)
    at Object.Pool.destroy (/home/sven/projects/fancyshelf/node_modules/knex/node_modules/generic-pool-redux/pool.js:238:12)
    at Object.Pool.removeIdle (/home/sven/projects/fancyshelf/node_modules/knex/node_modules/generic-pool-redux/pool.js:261:14)
    at null._onTimeout (/home/sven/projects/fancyshelf/node_modules/knex/node_modules/generic-pool-redux/pool.js:279:27)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

The method in question:

``` javascript
    destroy: function(connection) {
      if (pool.config.beforeDestroy) {
        return pool.config.beforeDestroy(connection, function() {
          connection.end();
        });
      }
      connection.end();
    }
```

Shouldn't it only attempt to 'end' a connection when there actually _is_ a connection to end? I'd imagine an `if(connection)` statement or something like that would be appropriate here.

**Comment by bendrucker** [comment]
Sounds like there is a better place to put that logic. Even though the connection fails there should at least be one.

**Comment by wubzz** [comment]
Closing since we no longer use `generic-pool-redux`
