### ISSUE TITLE
Allow table name as parameter

### ISSUE THREAD

**Issue by gchauvet** [tgriesser/knex#709]
Permit to use a tablename as a request parameter (in a raw request in my case).

**Comment by bendrucker** [comment]
No idea what this means

**Comment by gchauvet** [comment]
I use multiple temporary table with same structure, but not with same name.
ATM, I insert the tablename in the string like this : 

```javascript
var SQL_PRODUCT_TABLE =
    'CREATE TEMPORARY TABLE "%s" ' +
    '( ' +
    '  id serial NOT NULL, ' +
    '    CONSTRAINT pk_import_dilicom PRIMARY KEY (id), ' +
    '  "codeMouvement" char NOT NULL, ' +
') ON COMMIT DROP';

knex
.raw(util.format(SQL_PRODUCT_TABLE, "MyTableName"))
.exec(function (err) {
   cb(err);
});
````

instead of 
````javascript
var SQL_PRODUCT_TABLE =
    'CREATE TEMPORARY TABLE "$1" ' +
    '( ' +
    '  id serial NOT NULL, ' +
    '    CONSTRAINT pk_import_dilicom PRIMARY KEY (id), ' +
    '  "codeMouvement" char NOT NULL, ' +
') ON COMMIT DROP';

knex
.raw(SQL_PRODUCT_TABLE, ["MyTableName"])
.exec(function (err) {
   cb(err);
});
````

That returns me an error like this 
```
 { [error: bind message supplies 1 parameters, but prepared statement "" requires 0]
  name: 'error',
  length: 130,
  severity: 'ERROR',
  code: '08P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'postgres.c',
  line: '1500',
  routine: 'exec_bind_message' }
error: bind message supplies 1 parameters, but prepared statement "" requires 0
    at Connection.parseE (/[...]/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/[...]/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/[...]/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)
```

**Comment by tgriesser** [comment]
This would be nice to figure out, node-mysql uses the `??` in its parameterization to denote tables, will take a look into this as things in #696 start to take more shape.

**Comment by wubzz** [comment]
I'm going to close this as `??` mentioned by Tim above is actually implemented in Knex now as identifiers.
