### ISSUE TITLE
How to build a where clause with a call to a Postgres function

### ISSUE THREAD

**Issue by demisx** [tgriesser/knex#741]
Hi. I am trying to build this full-text search query:
```sql
select id, title from ads where ts_data @@ to_tsquery('iphone'); 
```
If I build the `where` clause as: 
```js
   scope = {
      where: function (qb) {
         qb.whereRaw('ts_data @@ to_tsquery(?)', [queryParams.q]); // queryParams.q === 'iphone'
      }
    };
```
The resulting query as seen in the log:
```js
{ __cid: '__cid2',
  method: 'select',
  options: undefined,
  bindings: [ 'iphone' ],
  sql: 'select count(*) from "ads" where ts_data @@ to_tsquery($1)) }
```

generates this error:
```js
Unhandled rejection TypeError: Cannot read property 'apply' of undefined
    at Object.module.exports.query (/Users/dmoore/projects/dimaslist/dimaslist-org-api/node_modules/bookshelf/lib/helpers.js:46:24)
    at _.extend.query (/Users/dmoore/projects/dimaslist/dimaslist-org-api/node_modules/bookshelf/lib/model.js:248:20)
    at Runner_PG.<anonymous> (/Users/dmoore/projects/dimaslist/dimaslist-org-api/app/components/base-model/base-model.js:272:16)
```

However, if I run this query in `psql`, then it works as expected:
```sql
select count(*) from "ads" where ts_data @@ to_tsquery('iphone');
 count 
-------
    20
(1 row)
```

What is the correct way to build a `where` clause that contains PostgreSQL function call with parameter (e.g. `to_tsquery(param)`)? Thank you.

**Comment by demisx** [comment]
Please disregard. The error was generated by another query.
