### ISSUE TITLE
Cannot find module './dialects/postgresql/index.js'

### ISSUE THREAD

**Issue by 58bits** [tgriesser/knex#806]
Hi,

Just re-starting a project that was put aside for about 6 month. All the dependencies, and Knex have been updated to the latest version. The app is running fine, and Knex is working.

However, when I try to run... 

`./node_modules/.bin/knex migrate:latest`

I receive the following error:

```
Error: Cannot find module './dialects/postgresql/index.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Knex (/Users/tony/Projects/StoryServer/Solutions/server/api/node_modules/knex/lib/index.js:21:26)
    at initKnex (/Users/tony/Projects/StoryServer/Solutions/server/api/node_modules/knex/lib/bin/cli.js:70:10)
    at Command.<anonymous> (/Users/tony/Projects/StoryServer/Solutions/server/api/node_modules/knex/lib/bin/cli.js:125:17)
    at Command.listener (/Users/tony/Projects/StoryServer/Solutions/server/api/node_modules/knex/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/Users/tony/Projects/StoryServer/Solutions/server/api/node_modules/knex/node_modules/commander/index.js:610:12)
    at Command.parse (/Users/tony/Projects/StoryServer/Solutions/server/api/node_modules/knex/node_modules/commander/index.js:458:21)
    at Liftoff.invoke (/Users/tony/Projects/StoryServer/Solutions/server/api/node_modules/knex/lib/bin/cli.js:177:13)
    at Liftoff.<anonymous> (/Users/tony/Projects/StoryServer/Solutions/server/api/node_modules/knex/node_modules/liftoff/index.js:181:16)
    at module.exports (/Users/tony/Projects/StoryServer/Solutions/server/api/node_modules/knex/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/Users/tony/Projects/StoryServer/Solutions/server/api/node_modules/knex/node_modules/liftoff/index.js:174:9)
    at /Users/tony/Projects/StoryServer/Solutions/server/api/node_modules/knex/node_modules/liftoff/index.js:148:9
    at /Users/tony/Projects/StoryServer/Solutions/server/api/node_modules/knex/node_modules/v8flags/index.js:79:12
    at /Users/tony/Projects/StoryServer/Solutions/server/api/node_modules/knex/node_modules/v8flags/index.js:35:7
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

Is this the way I should be running the binary for Knex migrations? I have a knexfile.js in the root of the project, which I believe is correctly configured for PG.

Thoughts or suggestions greatly appreciated.

**Comment by 58bits** [comment]
Found it - the dialect configuration options in knexfile.js have changed from 'postgresql' to just 'pg'.

**Comment by tgriesser** [comment]
Oh that's a bug though. I'll look to get that fixed

**Comment by 58bits** [comment]
Okay thanks Tim.

**Comment by capaj** [comment]
It changed again to `postgres`.
BTW @tgriesser   In the docs, there's still `pg` instead of `postgres`. Would be nice to update those.

**Comment by elhigu** [comment]
@capaj actually all `pg`, `postgres` and `postgresql` should work nowadays https://github.com/tgriesser/knex/blob/master/src/index.js#L11

**Comment by capaj** [comment]
No only `postgres` works for me. No other finds the dialect.

**Comment by elhigu** [comment]
@capaj works here: https://runkit.com/embed/ta4vad1nhhsv  

if you are getting that error from knex-db-manager I fixed that bug some time ago, I thought I released it also maybe week ago (though there the error should be different...).

**Comment by capaj** [comment]
@elhigu trying it out in a clean folder it works with all three of them. Thanks for your response! I probably had the older `knex-db-manager` installed.
