### ISSUE TITLE
Cannot Browserify

### ISSUE THREAD

**Issue by nolanlawson** [tgriesser/knex#809]
Environment:

```
$ browserify --version
10.0.0
$ node -v
v0.10.36
$ npm -v
2.7.0
$ uname -a
Darwin cinnabar.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64 i386 MacBookAir6,2 Darwin
```

Steps to repro:

```
hub clone tgriesser/knex
cd knex
npm install -g browserify
browserify .
```

You'll get an error:

```
Error: ENOENT, open 'lodash/utility/noop'
```

**Comment by reggi** [comment]
I think I'm running into the same issue here trying to compile browserify for node

```
Error: Cannot find module 'sqlite3' from '/Users/thomasreggi/Desktop/monorepo-reggi/packages/services/node_modules/knex/lib/dialects/sqlite3'
    at /Users/thomasreggi/Desktop/monorepo-reggi/packages/api/node_modules/resolve/lib/async.js:46:17
    at process (/Users/thomasreggi/Desktop/monorepo-reggi/packages/api/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/thomasreggi/Desktop/monorepo-reggi/packages/api/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/thomasreggi/Desktop/monorepo-reggi/packages/api/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/thomasreggi/Desktop/monorepo-reggi/packages/api/node_modules/resolve/lib/async.js:92:31)
    at /Users/thomasreggi/Desktop/monorepo-reggi/packages/api/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)
```

Here's my browserify script.

```
../../node_modules/.bin/browserify --node -s default -g browserify-aws-sdk -t babelify -o main.js index.js
```

**Comment by nolanlawson** [comment]
That's really weird. In principle that shouldn't happen because of this: https://github.com/tgriesser/knex/blob/e3ea261cd167277354737408fdd5426bbce65776/package.json#L98

**Comment by reggi** [comment]
@nolanlawson I think this is an issue with lerna :/

https://github.com/lerna/lerna/issues/212

**Comment by reggi** [comment]
@nolanlawson I had the `--node` flag set which ignores the `browser` prop.
