### ISSUE TITLE
Timed-out connection causes crash

### ISSUE THREAD

**Issue by mfhholmes** [tgriesser/knex#892]
Hey,

I'm using express-sessions, connect-session-knex, and mysql2 modules. Mysql database running on localhost on Ubuntu VM. Left the VM running overnight, first test of the day crashed the server with:

```
Unhandled rejection Error: select `sess` from `sessions` where `sid` = '35983279-598a-4e88-8f1e-d9276e3859c1' and CAST('2015-07-07T13:24:05.376Z' as DATETIME) <= expired - This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:297:12)
    at Connection.write (/vagrant/national/node_modules/mysql2/lib/connection.js:136:15)
    at Connection.writePacket (/vagrant/national/node_modules/mysql2/lib/connection.js:150:10)
    at Query.start (/vagrant/national/node_modules/mysql2/lib/commands/query.js:39:14)
    at Query.Command.execute (/vagrant/national/node_modules/mysql2/lib/commands/command.js:34:20)
    at Connection.handlePacket (/vagrant/national/node_modules/mysql2/lib/connection.js:310:28)
    at Connection.addCommand (/vagrant/national/node_modules/mysql2/lib/connection.js:326:10)
    at Connection.query (/vagrant/national/node_modules/mysql2/lib/connection.js:397:15)
    at /vagrant/national/node_modules/knex/lib/dialects/mysql/index.js:92:18
    at tryCatcher (/vagrant/national/node_modules/knex/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/vagrant/national/node_modules/knex/node_modules/bluebird/js/main/promise.js:462:31)
    at new Promise (/vagrant/national/node_modules/knex/node_modules/bluebird/js/main/promise.js:69:37)
    at Client._query (/vagrant/national/node_modules/knex/lib/dialects/mysql/index.js:88:12)
    at Client.query (/vagrant/national/node_modules/knex/lib/client.js:127:24)
    at Runner.<anonymous> (/vagrant/national/node_modules/knex/lib/runner.js:118:24)
    at Runner.tryCatcher (/vagrant/national/node_modules/knex/node_modules/bluebird/js/main/util.js:24:31)
```

Looks to me like the connection timed out, the websocket got closed by MySQL, and Knex didn't pick it up and reconnect. Hence this looks like a knex issue rather than an express-sessions issue - happy to post the issue there if I'm wrong ;)

This is my config:

```
//knex setup
var knex = Knex({
  client: 'mysql2',
  connection: {
    host: '127.0.0.1',
    user: 'user_national',
    password: 'not very secret',
    database: 'national'
  }
});
```

Any help appreciated :) Also, excellent library, keep up the good work :)

**Comment by elhigu** [comment]
Closing in favor of #1833
