### ISSUE TITLE
Node.js v4.0.0

### ISSUE THREAD

**Issue by blah238** [tgriesser/knex#970]
FYI Node.js v4.0.0 (the long-awaited convergence of the io.js fork back into node.js) [has been released](https://nodejs.org/en/blog/release/v4.0.0/). It would be good to get a CI build going for this release.

I've only tested it with `sqlite3`, for which you'll need the latest release (https://github.com/mapbox/node-sqlite3/releases/tag/v3.1.0), but all tests pass.

I was unable to get `mariasql` to build correctly, may be related to https://github.com/mscdex/node-mariasql/pull/101

If anyone else has any other experiences with Node v4.0.0 please share.

**Comment by b3njamin** [comment]
#977 Added node v4 to travis - currently failing.

**Comment by blah238** [comment]
@b3njamin thanks, I think the `mariasql` issue will be fixed soon (just need a new release): https://github.com/mscdex/node-mariasql/issues/103

**Comment by blah238** [comment]
Looks like the 0.2.0 version builds provided you update the Travis gcc/g++ version to 4.8, but it has some [breaking changes](https://github.com/mscdex/node-mariasql/wiki/Upgrading-v0.1.x-to-v0.2.x) we would need to fix: https://travis-ci.org/tgriesser/knex/builds/82623558

**Comment by slapers** [comment]
I have the following code which fails on 4.2 and works on iojs 3.0:

```javascript
  var knex = require('knex')({
      client: 'mysql',
      connection: {
          host     : '127.0.0.1',
          user     : 'root',
          password : '',
          database : 'mysql',
          charset  : 'utf8'
      }
  });
  
  
  knex.select()
      .table('user')
      .map(function(doc){
          console.log(doc.User + "@" + doc.Host);
      });
```



When running with node 4.2.0:

```shell
  ➜  node-mysql-debug  nvm use v4.2
  Now using node v4.2.0 (npm v2.14.7)
  
  ➜  node-mysql-debug  node test.js
  Knex:warning - Pool2 - Error: Pool was destroyed
  Knex:Error Pool2 - Error: Handshake inactivity timeout
  Knex:Error Pool2 - Error: Handshake inactivity timeout
  Unhandled rejection Error: Pool was destroyed
      at Pool._destroyPool (xxx/node-mysql-debug/node_modules/knex/node_modules/pool2/lib/pool.js:536:20)
      at Pool.<anonymous> (xxx/node-mysql-debug/node_modules/knex/node_modules/pool2/lib/pool.js:458:18)
      at Pool.<anonymous> (xxx/node-mysql-debug/node_modules/knex/node_modules/pool2/lib/pool.js:493:17)
      at tryCatcher (xxx/node-mysql-debug/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
      at Promise.errorAdapter (xxx/node-mysql-debug/node_modules/knex/node_modules/bluebird/js/main/nodeify.js:36:34)
      at Promise._settlePromiseAt (xxx/node-mysql-debug/node_modules/knex/node_modules/bluebird/js/main/promise.js:579:21)
      at Promise._settlePromises (xxx/node-mysql-debug/node_modules/knex/node_modules/bluebird/js/main/promise.js:697:14)
      at Async._drainQueue (xxx/node-mysql-debug/node_modules/knex/node_modules/bluebird/js/main/async.js:123:16)
      at Async._drainQueues (xxx/node-mysql-debug/node_modules/knex/node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues [as _onImmediate] (xxx/node-mysql-debug/node_modules/knex/node_modules/bluebird/js/main/async.js:15:14)
      at processImmediate [as _immediateCallback] (timers.js:368:17)
```


Same code with iojs: When running with iojs:

```shell
  ➜  node-mysql-debug  nvm use iojs
  Now using io.js v3.0.0 (npm v2.13.3)
  
  ➜  node-mysql-debug  node test.js
  root@localhost
  root@goblix.local
  root@127.0.0.1
  root@::1
  @localhost
  @goblix.local
  infinite@localhost
  infinite@%
  ^C
```

This is the package.json:

```javascript
  {
    "name": "node-mysql-debug",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "ISC",
    "dependencies": {
      "bookshelf": "^0.8.2",
      "knex": "^0.8.6",
      "mysql": "^2.9.0"
    }
  }
```

**Comment by blah238** [comment]
@slapers I haven't tried 4.2.x yet, but did you `rm -rf node_modules` and `npm install` between versions?

**Comment by slapers** [comment]
@blah238 yes, i did. made no difference. Also tried running iojs with npm packages installed from node 4.2 and iojs test kept working.

**Comment by blah238** [comment]
@slapers can you try out #1033?

**Comment by slapers** [comment]
@blah238 thanks for the update, did the following: (let me know if i did something wrong here :-) )

```
➜  node-mysql-debug  node -v
v4.2.0
```

The test code is in folder node-mysql-debug and had all npm packages already installed..so..
```
cd node-mysql-debug/node_modules
rm -rf knex
git clone https://github.com/tgriesser/knex.git knex
cd knex
git fetch origin pull/1033/head:testing-node4
git checkout testing-node4
npm install
```

Then running it from my node-mysql-debug folder:

```
➜  node-mysql-debug  node test.js 
Knex:warning - Pool2 - Error: Pool was destroyed
Knex:Error Pool2 - Error: Handshake inactivity timeout
Knex:Error Pool2 - Error: Handshake inactivity timeout
Unhandled rejection Error: Pool was destroyed
    at Pool._destroyPool (/xxxxx/node-mysql-debug/node_modules/knex/node_modules/pool2/lib/pool.js:536:20)
    at Pool.<anonymous> (/xxxxx/node-mysql-debug/node_modules/knex/node_modules/pool2/lib/pool.js:458:18)
    at Pool.<anonymous> (/xxxxx/node-mysql-debug/node_modules/knex/node_modules/pool2/lib/pool.js:493:17)
    at tryCatcher (/xxxxx/node-mysql-debug/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.errorAdapter (/xxxxx/node-mysql-debug/node_modules/knex/node_modules/bluebird/js/main/nodeify.js:36:34)
    at Promise._settlePromiseAt (/xxxxx/node-mysql-debug/node_modules/knex/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/xxxxx/node-mysql-debug/node_modules/knex/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/xxxxx/node-mysql-debug/node_modules/knex/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/xxxxx/node-mysql-debug/node_modules/knex/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/xxxxx/node-mysql-debug/node_modules/knex/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)

```

**Comment by blah238** [comment]
@slapers I am not able to reproduce it in Ubuntu, what OS are you on?

**Comment by slapers** [comment]
@blah238 i'm on OSX 10.10.5 at the moment. Will see if i can do some additional testing tomorrow. Might be an issue on my machine...

**Comment by blah238** [comment]
@slapers I went ahead and merged that PR so you should just be able to use the master branch to test now. If you are able to reproduce the issue on a clean OSX machine please open a new issue with the details. I don't have an OSX machine but maybe someone else on the team does.

**Comment by fahad19** [comment]
was having similar issues, but upgrading to latest Node v4.2.2 fixed it for me.

**Comment by tthyer** [comment]
I encountered  "handshake inactivity timeout" as well. Upgrading from 4.2.0 to [4.2.1](https://github.com/nodejs/node/blob/v5.10.0/CHANGELOG.md#2015-10-13-version-421-argon-lts-jasnell) fixed my issue.
